objects/AccountRoles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Roles</description>
    <fields>
        <fullName>LastRun__c</fullName>
        <description>Batch Class Last Run DateTime</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LastRun</label>
        <type>DateTime</type>
    </fields>
    <label>Account Roles</label>
</CustomObject>

objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage_and_Consultant11_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>LG Brokerage, LG Self Relationship</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <formula>Brokerage__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax ID</label>
        <type>Text</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NEW_BSNS_TERM_DT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NEW BSNS TERM DT</label>
        <type>Date</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tax_ID__c.object
<CustomObject>
    <description>KF(20140507) table added to allow for more than one TaxID per account, per instruction from CIP and National SME&apos;s</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax IDs</relationshipLabel>
        <relationshipName>Tax_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax ID</label>
    <nameField>
        <displayFormat>TID-{000000}</displayFormat>
        <label>Tax ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BrokerageToOppRollUpBatchTest.cls
@isTest
public class BrokerageToOppRollUpBatchTest {
    @testSetup
    static  void setupTestData(){
        Id RecordTypeIdAccount = Schema.SObjectType.Account.getRecordTypeInfosByName().get('LG Brokerage').getRecordTypeId();
        Id RecordTypeIdCR = Schema.SObjectType.ContactRelationship__c.getRecordTypeInfosByName().get('LG Brokerage Consultant Relationship').getRecordTypeId();
        Account acc1 = new Account();
        acc1.Name = 'testAcc1';
        acc1.RecordTypeId = RecordTypeIdAccount;
        acc1.Tax_ID__c = '123456789';
        insert acc1;
        Account acc2 = new Account();
        acc2.Name = 'testAcc2';
        insert acc2;
        Contact con1 = new contact();
        con1.AccountId = acc1.Id;
        con1.LastName = 'testCon';
        insert con1;
        ContactRelationship__c cr1 = new ContactRelationship__c();
        cr1.Account__c = acc1.Id;
        cr1.EndDate__c = system.today().addDays(2);
        cr1.NEW_BSNS_TERM_DT__c = system.today().addDays(2);
        cr1.RecordTypeId = RecordTypeIdCR;
        insert cr1;
        
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity opp1 = new Opportunity();
        opp1.Name = 'testOpp1';
        opp1.StageName = 'Initiated';
        opp1.CloseDate = system.today();
        opp1.AccountId = acc1.Id;
        oppList.add(opp1);
        Opportunity opp2 = new Opportunity();
        opp2.Name = 'testOpp2';
        opp2.StageName = 'Closed Won';
        opp2.CloseDate = system.today();
        opp2.AccountId = acc1.Id;
        oppList.add(opp2);
        insert oppList;
        
        Brokerage_and_Consultant1__c BC = new Brokerage_and_Consultant1__c();
        BC.Opportunity__c = opp1.Id;
        BC.Brokerage__c = acc1.Id;
        BC.Consultant__c = cr1.Id;
        insert BC;
        
        Brokerage_and_Consultant1__c BC1 = new Brokerage_and_Consultant1__c();
        BC1.Opportunity__c = opp1.Id;
        BC1.Brokerage__c = acc1.Id;
        BC1.Consultant__c = cr1.Id;
        insert BC1;
        Brokerage_and_Consultant1__c BC2 = new Brokerage_and_Consultant1__c();
        BC2.Opportunity__c = opp2.Id;
        BC2.Brokerage__c = acc1.Id;
        //BC2.Consultant__c = null;
        insert BC2;
        Delete BC2;
        AccountRoles__c roles = new AccountRoles__c();
        roles.Name = 'BrokerageOppReport';
        roles.LastRun__c = Datetime.now().addDays(-5);
        insert roles;
    }
    static testMethod void testMethodOppExec()
    {
        Test.startTest();
        BrokerageToOppRollUpBatch obj = new BrokerageToOppRollUpBatch();
        database.executeBatch(obj); 
        Test.StopTest();
    }
     static testMethod void testMethodOppExec1()
    {
        Test.startTest();
        BrokerageToOppRollUpBatch obj1 = new BrokerageToOppRollUpBatch();
        obj1.isError = true;
        database.executeBatch(obj1); 
        Test.StopTest();
    }
}