objects/Account_Preferences__c.object
<CustomObject>
    <description>This object was formerly called Group Preference and will be updated to Account Preference</description>
    <label>Account Preferences</label>
    <nameField>
        <displayFormat>ACTPREF-{0000}</displayFormat>
        <label>Account Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Billing_Arrangement_Local__c.object
<CustomObject>
    <description>Create a new object named &quot;Billing Arrangement (Local)&quot; as a part of US# PRDCRM-43936.</description>
    <label>Billing Arrangement (Local)</label>
    <nameField>
        <displayFormat>BARR-{000000}</displayFormat>
        <label>Billing Arrangement Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing Arrangement (Local)s</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Broker_Consultant_Commissions1__c.object
<CustomObject>
    <description>Clone of Broker/Consultant Commissions object</description>
    <label>Broker/Consultant Commissions</label>
    <nameField>
        <displayFormat>BCC# {00000}</displayFormat>
        <label>Broker/Consultant Commissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker/Consultant Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Brokerage_of_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is the Brokerage of Record for this Account</inlineHelpText>
        <label>BOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <formula>Brokerage__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax ID</label>
        <type>Text</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Eligibility__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Eligibility</relationshipLabel>
        <relationshipName>Eligibility</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Eligibility</relationshipLabel>
        <relationshipName>Eligibility</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Eligibility</label>
    <nameField>
        <displayFormat>ELIG-{00000}</displayFormat>
        <label>Eligibility Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Eligibility</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group_Plan_Design__c.object
<CustomObject>
    <fields>
        <fullName>CBP_Bill_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Populated via API response from Customer Master</inlineHelpText>
        <label>CBP Bill Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Product Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group Plan Design</label>
    <nameField>
        <displayFormat>GPD-{000000}</displayFormat>
        <label>GPD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Plan Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Internal_Broker__c.object
<CustomObject>
    <label>Agent</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Internal Rep Listing</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Invoices_Local__c.object
<CustomObject>
    <fields>
        <fullName>CBP_Bill_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Populated via API response from Customer Master</inlineHelpText>
        <label>CBP Bill Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Invoices (Local)</relationshipLabel>
        <relationshipName>Invoices_Local</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoices (Local)</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoices Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices (Local)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>LHOL_Q__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LHOL Q</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                    <default>true</default>
                    <label>New Business</label>
                </value>
                <value>
                    <fullName>Endorsement</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Status</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__Type__c</fullName>
        <formula>Text(Product2.vlocity_ins__Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItemRates__c.object
<CustomObject>
    <label>Quote Line Item Rates</label>
    <nameField>
        <displayFormat>QLIRATE-{00000000}</displayFormat>
        <label>Quote Line Item Rate Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Item Rates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Compensation__c.object
<CustomObject>
    <fields>
        <fullName>Product_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Line Of Business</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Sales Compensation</label>
    <nameField>
        <displayFormat>COMP-{00000000}</displayFormat>
        <label>Sales Compensation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Compensations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceProviderRelationship__c.object
<CustomObject>
    <label>Service Provider Relationship</label>
    <nameField>
        <displayFormat>SPR-{0000}</displayFormat>
        <label>Service Provider Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Provider Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_ID__c.object
<CustomObject>
    <description>KF(20140507) table added to allow for more than one TaxID per account, per instruction from CIP and National SME&apos;s</description>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax ID</label>
    <nameField>
        <displayFormat>TID-{000000}</displayFormat>
        <label>Tax ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMPartialJSONRequestTest.cls
@isTest
private class CMPartialJSONRequestTest {
    
    @testSetup
    static void createData()
    {
        Account acc=IntegrationTestDataUtilty.createAccount(true);
        acc.Account_Medical_Funding_Type__c = 'ASO';
        acc.Program_Selection_Details__c = 'No';
        update acc; 
        
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        Quote Qte = IntegrationTestDataUtilty.createQuote(oppty.Id, grp.id, true);
        Order ImplCase = IntegrationTestDataUtilty.createImplCase(qte.Id, acc.Id, false);
        ImplCase.Implementation_Effective_Date__c = system.today();
        ImplCase.Implementation_Status__c = 'Initiated';
        ImplCase.Implementation_Type__c = 'New Business';
        ImplCase.User_Group__c = 'Local New Business';
        ImplCase.Production_Date__c = system.today();
        ImplCase.OpportunityId = oppty.Id ;                   
        //ImplCase.LHOL_Q__c = 'true',
        insert ImplCase;   
        System.debug('Impl Case Opp Id:'+ ImplCase.OpportunityId);
        
        Product2 prod = IntegrationTestDataUtilty.createProduct('40QA', true);
        prod.Name = 'Health and Wellness - Live Health Online';
        prod.vlocity_ins__Type__c = 'Medical';
        prod.Product_Type__c = 'Medical';
        Database.update(prod);
        
        vlocity_ins__AttributeAssignment__c  spiderAttrb = IntegrationTestDataUtilty.createAttributeAssgnmnt(prod.Id,'Spider Network Id', 'Spider Test', true);
		vlocity_ins__AttributeAssignment__c  metalLevelAttrb = IntegrationTestDataUtilty.createAttributeAssgnmnt(prod.Id,'Metal Level Code', 'Metal Level Test', true);
        vlocity_ins__AttributeAssignment__c  exchangeIndAttrb = IntegrationTestDataUtilty.createAttributeAssgnmnt(prod.Id,'Exchange Indicator', 'Exchange Ind Test', true);
        vlocity_ins__AttributeAssignment__c  legalEntityAttrb = IntegrationTestDataUtilty.createAttributeAssgnmnt(prod.Id,'Legal Entity', 'Legal value Test', true);
        vlocity_ins__AttributeAssignment__c  cdhpAttrb = IntegrationTestDataUtilty.createAttributeAssgnmnt(prod.Id,'CDHP Product Type', 'CDHP Test', true);

           
        PricebookEntry pbe= IntegrationTestDataUtilty.createpricebookEntry(prod.Id, true);
        QuoteLineItem qlitest = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, true);
       
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.QuoteId = qte.id;
        Database.insert(qli);
        
        QuoteLineItemRates__c rate1= IntegrationTestDataUtilty.createQLIRates(qli.Id, '123567', true);
        QuoteLineItemRates__c rate2= IntegrationTestDataUtilty.createQLIRates(qli.Id, '462829', true);
        
        Group_Plan_Design__c grpPlanDesign1 = IntegrationTestDataUtilty.createGrpPlanDesign(grp.Id, qli.Id, 'Active', true);
        Group_Plan_Design__c grpPlanDesign2 = IntegrationTestDataUtilty.createGrpPlanDesign(grp.Id, qli.Id, 'Active', true);   
        
        Account brokerAccount = IntegrationTestDataUtilty.createAccount('Test BrokerAccount', 'Virginia', 'LG Brokerage', 'Local/Large Group', false);
        brokerAccount.Tax_ID__c ='123456789';
        Database.insert(brokerAccount);
        
        Contact con = IntegrationTestDataUtilty.createContact(brokerAccount.Id, 'General Contact', 'Consultant', true);
        System.debug('Broker Account Id: '+brokerAccount.Id);
        System.debug('Broker Contact Id: '+con.Id);
        ContactRelationShip__c conRel = IntegrationTestDataUtilty.createConRelationship(brokerAccount.Id, con.Id, 'LG Brokerage Consultant Relationship', 'Billing Contact',true);
        System.debug('Broker Contact RelationId: '+conRel.Id);
        System.debug('Account Id: '+acc.Id);
        Brokerage_and_Consultant1__c brokerConsultant1 = IntegrationTestDataUtilty.createBrokerConsultant1(acc.Id, oppty.Id, brokerAccount.Id, conRel.Id, 'Medical', false);
        brokerConsultant1.Brokerage_of_Record__c = true;
        Database.insert(brokerConsultant1);
        
        Broker_Consultant_Commissions1__c brokerConsCommission = IntegrationTestDataUtilty.createBrokerConsCommission1(brokerConsultant1.Id, conRel.Id, acc.Id, 'Medical', true);
    
        Sales_Compensation__c salesComp = IntegrationTestDataUtilty.createSalesCompensation(oppty.Id, 'Medical', true);
        System.debug('Sales Comp Id: '+salesComp.Id);
        Internal_Broker__c agent = IntegrationTestDataUtilty.createAgent(salesComp.Id, 'SR - Account Coordinator (SAR)', 'Medical','12345', true);
        System.debug('Agent Id: '+ agent.Id); 
        
        Contact contct = IntegrationTestDataUtilty.createContact(acc.Id, 'General Contact', 'Test Billing', true);
        System.debug('Contact Id: '+contct.Id);
        
       	ServiceProviderRelationship__c srvProv = IntegrationTestDataUtilty.createSrvcPrvdrRltnshp(acc.Id, contct.id, 'TPA', true);
        
        Account_Preferences__c grpPref = IntegrationTestDataUtilty.createGrpPreferences(acc.Id, true);
        
        Eligibility__c eligibility = IntegrationTestDataUtilty.createEligibility(ImplCase.Id, grp.Id, true);
      
        AccountTeamMember teamMem = new AccountTeamMember(AccountId = acc.Id, TeamMemberRole ='Account Manager', UserId= UserInfo.getUserId());
        insert teamMem;
        /*AccountTeamMember teamMem1 = new AccountTeamMember(AccountId = acc.Id, TeamMemberRole ='Account Executive', UserId= UserInfo.getUserId());
        insert teamMem1;
        AccountTeamMember teamMem2 = new AccountTeamMember(AccountId = acc.Id, TeamMemberRole ='Underwriter', UserId= UserInfo.getUserId());
        insert teamMem2; */
        Invoices_Local__c invoice = IntegrationTestDataUtilty.createInvoice(acc.Id, contct.Id, grp.Id, true);
        invoice.CBP_Bill_Group_ID__c ='12345';
        update invoice;
        Billing_Arrangement_Local__c billArrgmnt1 = IntegrationTestDataUtilty.createBillingArrangement(invoice.Id, 'Medical', true);
        Billing_Arrangement_Local__c billArrgmnt2 = IntegrationTestDataUtilty.createBillingArrangement(invoice.Id, 'Medical', true);
    }
    
    @isTest
    static void buildProductsCustInfo(){  
        List<Account> acc = [Select Id from Account LIMIT 1];
        List<Order> implCase = [Select Id from Order 
                                WHERE AccountId =: acc[0].Id
                                LIMIT 1];
       
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CMIntegrationCalloutMockTest());
        
        CMIntegrationUtility utility = new CMIntegrationUtility();  
        String  output = CMIntegrationService.submitCaseToCM(CMIntegrationService.prepareOrder(implCase[0].id), 'AddUpdate');
         
        //CMIntegrationRequest req = CMIntegrationService.buildCMPayload(CMIntegrationService.prepareOrder(implCase[0].id), CMIntegrationService.buildEventMetaData('Preview'));
        //CMIntegrationRequest req = CMIntegrationGroupLoad.buildCMPayload(CMIntegrationService.prepareOrder(implCase[0].id), CMIntegrationService.buildEventMetaData('Preview'));
       // CMIntegrationUtility.StatusDetails returnStatus = utility.sendCMReqInfo(req);
      //  CMIntegrationUtility.CMIntgrtnAPITokenDetails tokenDetails = utility.getAuthToken();
  
        Test.stopTest(); 
        System.assertEquals('SUCCESS', output, 'Response status codes not matched');
   
      /* System.assertEquals(1, prodList.size() , 'Return Product List Size is not matched');
         System.assertEquals(1, reps.size() , 'Return Reps List Size is not matched'); */
    }
    
    @isTest
    static void testUtilityMethod(){
        List<Account> acc = [Select Id from Account LIMIT 1];
        List<Order> implCase = [Select Id, Implementation_Record_ID__c
                                FROM Order
                                WHERE AccountId =: acc[0].Id
                                LIMIT 1];
       
        Test.startTest();
        
        Test.setMock(HttpCalloutMock.class, new CMIntegrationCalloutMockTest());
        
        CMIntegrationUtility utility = new CMIntegrationUtility();
        CMIntegrationRequest req = CMIntegrationGroupLoad.buildCMPayload(CMIntegrationService.prepareOrder(implCase[0].id), CMIntegrationService.buildEventMetaData('Preview', implCase[0].Implementation_Record_ID__c));
        CMIntegrationUtility.StatusDetails returnStatus = utility.sendCMReqInfo(req);
        CMIntegrationUtility.CMIntgrtnAPITokenDetails tokenDetails = utility.getAuthToken();
  
        Test.stopTest(); 
        System.assertEquals(200, returnStatus.statusCode, 'Response status codes not matched');
        System.assertEquals('salesforce-large-gro', tokendetails.application_name);
        System.assertEquals('1557336486513', tokendetails.issued_at);
        System.assertEquals('899', tokendetails.expires_in);
        system.assertEquals('dv2JGaEOEl6p40WTKd17', tokendetails.client_id);
        system.assertEquals('approved', tokendetails.status);
        system.assertEquals(true, tokendetails.isNewToken); 
        system.assertEquals(null, tokendetails.currentTime); 
    }
    
}