objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Impl_Revision__c.object
<CustomObject>
    <fields>
        <fullName>Implementation_Case_Id__c</fullName>
        <label>Implementation_Case</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Revisions</relationshipLabel>
        <relationshipName>Revisions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Revision_Record_Status__c</fullName>
        <label>Revision Record Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Initiated/In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending Response From Sales/AM</fullName>
                </value>
                <value>
                    <fullName>Ready for Implementations</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status_Capture__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Capture</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Revision</label>
    <nameField>
        <displayFormat>REV-{0000}</displayFormat>
        <label>Revision ID #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Revisions</pluralLabel>
    <recordTypes>
        <fullName>Revision</fullName>
        <active>true</active>
        <label>Revision</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SME_Approvals__c.object
<CustomObject>
    <fields>
        <fullName>Group_Size__c</fullName>
        <formula>TEXT(Implementation_Record_ID__r.Account.Group_Size__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Size</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>If_Other_List_Department__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>If Other, List Department</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_to_HPCC__c</fullName>
        <label>Impact To HPCC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Cannot Determine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>SME_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Production_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Production Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>SME_Department__c</fullName>
        <label>SME Department</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Act Wise CDH</fullName>
                </value>
                <value>
                    <fullName>Act Wise FSA</fullName>
                </value>
                <value>
                    <fullName>Anthem Flex Hour</fullName>
                </value>
                <value>
                    <fullName>Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>Benefit Booklets/Contracts</fullName>
                    <isActive>false</isActive>
                    <label>Benefit Booklets/Contracts</label>
                </value>
                <value>
                    <fullName>Blue Exchange (BX)</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>CCMU</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Claims Retro</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Coordinated Care Model</fullName>
                </value>
                <value>
                    <fullName>Coordination of Benefits</fullName>
                </value>
                <value>
                    <fullName>Data Interface Team (DIT)</fullName>
                </value>
                <value>
                    <fullName>DeCare</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>EAP</fullName>
                </value>
                <value>
                    <fullName>EBA</fullName>
                    <isActive>false</isActive>
                    <label>EBA</label>
                </value>
                <value>
                    <fullName>Enrollment and Billing (E/B)</fullName>
                </value>
                <value>
                    <fullName>Group Services</fullName>
                </value>
                <value>
                    <fullName>Health and Wellness Solutions</fullName>
                </value>
                <value>
                    <fullName>HealthEquity/WageWorks/FSA/COBRA</fullName>
                </value>
                <value>
                    <fullName>ID Cards</fullName>
                </value>
                <value>
                    <fullName>IHM</fullName>
                </value>
                <value>
                    <fullName>Implementations</fullName>
                </value>
                <value>
                    <fullName>Interplan</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JAA/NTS</fullName>
                </value>
                <value>
                    <fullName>Life and Disability</fullName>
                </value>
                <value>
                    <fullName>LITES CDH</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Castlight (EBA Only)</fullName>
                </value>
                <value>
                    <fullName>Approved with Deviations</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SME Approvals</label>
    <nameField>
        <displayFormat>SMEAPR-{000}</displayFormat>
        <label>SME Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SME Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/SMEDepartment__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Department Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Omni_Script_Help_Text__c</fullName>
        <description>Fields to house the help text to be displayed in the Omni Script on when to choose a specific SME department.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Omni Script Help Text</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMEDepartment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>SMEDepartment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SMEDepartment</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AP19_RevisionSMEApproval.cls
/**
@Author : Accenture Offshore Dev team
@name : AP19_RevisionSMEApproval
@Description :This class creates 'SME Revision Approval' records based on 'Manually-ENgaged' departments.
*/
global without sharing class AP19_RevisionSMEApproval implements vlocity_ins.VlocityOpenInterface2  {
     
    private static Map<String,Set<Object>> STAutoDepartmentFinal = new Map<String,Set<Object>>();
    private static final string CLASS_NAME=UtilConstants.CLASS_NAME;
    private static final String TEST_CLASS =UtilConstants.TEST_CLASS;
    private static String RevisionText ='REVISION ';
    
    /*Implementation of invokeMEthod from VlocityOpenInterface2 interface.*/
    global static Boolean invokeMethod(String methodName,Map<String,Object> inputMap,
                                        Map<String,Object> outMap,Map<String,Object> optns)
    {                              
                                     
            String  otherDptVal = '';               
            if(UtilConstants.SAVE_SME_DEPARTMENT.equalsIgnoreCase(methodName))
            {           
                 Map<String,String> deptJSONMap = new Map<String,String>{
                                                 UtilConstants.ST_AUTO_DEPARTMENT => UtilConstants.SI_AUTO_DEPARTMENT
                                                 ,UtilConstants.ST_MANUAL_DEPARTMENT => UtilConstants.SI_MANUAL_DEPARTMENT    
            };                        
                          
              Set<Object> finalizedDepts = new Set<Object>();                                                         
                System.debug('inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT)'+inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT));    
                
                
                
                if(inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT) != null)
                {
                 
                     Set<Object> manualDepts = new Set<Object>{inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT)}; 
                     
                     Map<String,Object> engageManualDeptMap = new Map<String,Object>();    
                        
                                
                          for(Object tempObj : manualDepts)               
                            engageManualDeptMap = (Map<String,Object>) tempObj;                     
                         
                                                                         
                         if(engageManualDeptMap.get(UtilConstants.SI_MANUAL_DEPARTMENT) != null)
                         {  
                        
                             List<Object> engageManualDeptMap2 = (List<Object>) engageManualDeptMap.get(UtilConstants.SI_MANUAL_DEPARTMENT);
                             for(Object tempEngage : engageManualDeptMap2)
                             {
                                 Map<String,Object> engageDeptMap = (Map<String,Object>) tempEngage; 
                                 
                                 if(engageDeptMap.get(UtilConstants.JSON_NAME_FIELD) != null) {
                                    if(engageDeptMap.get(UtilConstants.JSON_NAME_FIELD) == UtilConstants.OTHER)
                                     {                                        
                                        otherDptVal = string.valueof(engageDeptMap.get(UtilConstants.JSON_OTHER_DEPT));
                                     }                                  
                                     finalizedDepts.add(engageDeptMap.get(UtilConstants.JSON_NAME_FIELD));   
                                 }                            
                                 
                             } 
                                                           
                         }
                        
                    System.debug('finalizedDepts'+finalizedDepts);      
                    

                     if(finalizedDepts != null)
                     {                     
                         createSMEApprovals(inputMap,finalizedDepts,outMap,OtherDptVal);                            
                     }   
                
                     
                       
                 }                                  
            }    
            else if(UtilConstants.CREATE_SME_DEPARTMENT.equalsIgnoreCase(methodName))
            {            
                createSMEApprovalOutmap(inputMap, outMap, optns);    
            }                        
            else if(UtilConstants.GENERATE_SME_DEPARTMENT.equalsIgnoreCase(methodName))
            {            
                GenerateSMEApprovalOutmap(inputMap, outMap, optns);    
            }
        return true; 
    }
  
     /*
    Method Name: createSMEApprovalOutmap
    Method Signature:public static Set<String> createSMEApprovalOutmap(Map<String,Object> outMap,String departmentout,Map<String,String> SIAutoDepartmenttMap,
                             Set<Object> SIAutoDepartment,Map<String,Set<Object>> STAutoDepartment,Set<String> actualDept)
    Method Return Type: Set<String>
    Method Description: This method is called from return value method to autoengageDepartmentList and send it back to OmniScript
    */
    public static void createSMEApprovalOutmap(Map<String,Object> inputMap, Map<String,
                                   Object> outMap,Map<String,Object> optns)
    { 
        String contextId  =  String.valueOf(inputMap.get(UtilConstants.IMP_ID));
        System.debug('inputMap.get(UtilConstants.IMP_ID)'+inputMap.get(UtilConstants.IMP_ID));             
        Set<SME_Approvals__c> relatedSMEAprovals = new Set<SME_Approvals__c>([SELECT Id,SME_Department__c,If_Other_List_Department__c FROM SME_Approvals__c WHERE Implementation_Record_ID__c = :contextId 
            order by SME_Department__c  ]);  //  PRDCRM-24502 cmh  
        //---- extract 'Other' department ;  PRDCRM-24502 cmh ; PRDCRM-42480 , see the dept Benefit Booklets/Contracts in old IMPL
        String BeBoCo = 'Benefit Booklets/Contracts';
        Boolean isBeBoCO_existsInIMPL = false;
        Map<Id,SME_Approvals__c> relatedSMEAprovalsOtherMap = new Map<Id,SME_Approvals__c>(); 
        for(SME_Approvals__c o : relatedSMEAprovals){ 
            if(o.SME_Department__c == 'Other'){relatedSMEAprovalsOtherMap.put(o.id, o); }
            if(o.SME_Department__c == BeBoCo){isBeBoCO_existsInIMPL = true; }  // PRDCRM-42480
        }
        //--PRDCRM-42480
        Set<SMEDepartment__c> relatedSMEDepartment = new Set<SMEDepartment__c>([SELECT Department_Name__c,Omni_Script_Help_Text__c,Active__c FROM SMEDepartment__c order by Department_Name__c  ]);    
        Set<String> departmentSet = new Set<String>();
        // PRDCRM-42480                               
        Set<String> departmentSetNotActive = new Set<String>();    
        for (SMEDepartment__c o :relatedSMEDepartment) { if (!o.Active__c) departmentSetNotActive.add(o.Department_Name__c) ;  }   
                              
        Set<Object> SIManualDepartment=  new Set<Object>();
        Map<String,Set<Object>> STManualDepartment= new Map<String,Set<Object>>();        
        Integer cntOther = 0;
        
        
        for(SME_Approvals__c tempSMEApproval : relatedSMEAprovals)
        {
            if( relatedSMEAprovalsOtherMap.get(tempSMEApproval.Id) == NULL ) 
                departmentSet.add(tempSMEApproval.SME_Department__c);
        }
        
        
        //List<SMEDepartment__c> relatedDeptHelptext = [SELECT Department_Name__c,Omni_Script_Help_Text__c FROM SMEDepartment__c where  Department_Name__C IN :departmentSet];  
        Map<String,String> deptHelpTextMap = new Map<String,String>();
        for(SMEDepartment__c tempSMEDept : [SELECT Department_Name__c,Omni_Script_Help_Text__c FROM SMEDepartment__c where  Department_Name__C IN :departmentSet])
        {
            deptHelpTextMap.put(tempSMEDept.Department_Name__c,tempSMEDept.Omni_Script_Help_Text__c);
        }
        if(!relatedSMEAprovals.isEmpty())
        {            
            for(SME_Approvals__c tempSMEApproval : relatedSMEAprovals)
            {

                String helpText = ''; String deptNm = 'N/A';
                if(deptHelpTextMap.containsKey(tempSMEApproval.SME_Department__c)) {
                    helpText = String.valueOf(deptHelpTextMap.get(tempSMEApproval.SME_Department__c));
                    deptNm =   tempSMEApproval.SME_Department__c;}
                else if( relatedSMEAprovalsOtherMap.get(tempSMEApproval.Id) <> NULL ) {
                    helpText = tempSMEApproval.If_Other_List_Department__c ;
                    deptNm =   tempSMEApproval.SME_Department__c+'  ';}

                
                Map<String,String> SIManualDepartmentMap= new Map<String,String>();                                                                   
                try
                {
                    SIManualDepartmentMap.put(UtilConstants.JSON_NAME_FIELD,deptNm);
                    SIManualDepartmentMap.put(UtilConstants.HELP_TEXT,helpText);
                    SIManualDepartmentMap.put(UtilConstants.VLC_SELECTED,UtilConstants.TRUE_VAL );
                    SIManualDepartment.add(SIManualDepartmentMap);
                
                }                    
                catch(Exception excp)
                { 
                UTIL_LoggingService.logHandledException(excp, UtilConstants.ORGID, UtilConstants.APPNAME, 
                                                       CLASS_NAME, UtilConstants.CANCEL,TEST_CLASS,LoggingLevel.ERROR); 
                }                 
                          
             }                    
       }    
                  
        if(!relatedSMEDepartment.isEmpty()) 
        {
             for(SMEDepartment__c tempSMEApproval : relatedSMEDepartment)
             {
                 //--PRDCRM-42480 , if old beboco in IMPL, do not add Contracts dept in manully dept, cmh
                 Boolean okToAddDept = true;
                 okToAddDept = (isBeBoCO_existsInIMPL && tempSMEApproval.Department_Name__c == 'Contracts') ? false: true;
                 if(okToAddDept && !departmentSet.Contains(tempSMEApproval.Department_Name__c) && !departmentSetNotActive.Contains(tempSMEApproval.Department_Name__c))
                 {
                      Map<String,String> SIManualDepartmentMap= new Map<String,String>(); 
                      try
                      {
                        SIManualDepartmentMap.put(UtilConstants.JSON_NAME_FIELD,tempSMEApproval.Department_Name__c);
                        SIManualDepartmentMap.put(UtilConstants.VLC_SELECTED,UtilConstants.FALSE_VAL);
                        SIManualDepartmentMap.put(UtilConstants.HELP_TEXT,tempSMEApproval.Omni_Script_Help_Text__c);
                        SIManualDepartment.add(SIManualDepartmentMap);                                  
                                                                                         
                      }  
                      catch(Exception excp)
                      { 
                          UTIL_LoggingService.logHandledException(excp, UtilConstants.ORGID, UtilConstants.APPNAME, 
                                                                   CLASS_NAME, UtilConstants.CANCEL,TEST_CLASS,LoggingLevel.ERROR); 
                      }                          
                  
                  }
              }   
        }
        
        STManualDepartment.put(UtilConstants.SI_MANUAL_DEPARTMENT,SIManualDepartment); 
        outMap.put(UtilConstants.ST_MANUAL_DEPARTMENT, STManualDepartment );        
                 
     }
     
    public static void GenerateSMEApprovalOutmap(Map<String,Object> inputMap, Map<String,
                                   Object> outMap,Map<String,Object> optns)
    {       
        
        String contextId  =  String.valueOf(inputMap.get(UtilConstants.CONTEXT_ID)); 
        System.debug('===COntextId=='+contextId);  
        List<SME_Approvals__c> existingSMEDept = [SELECT SME_Department__c,id,Status__c  FROM SME_Approvals__c WHERE Implementation_Record_ID__c = :contextId];  
        List<SME_Approvals__c> existingSMEDeptNew = new List<SME_Approvals__c>();
        List<Order> impCase = [Select Id,Are_there_changes_to_Rates__c,Impact_To_HPCC__c,Account_Group_Size__c from Order where Id = :contextId limit 1];
        System.debug('===ImpCase==='+impCase);
       //Added 4 more new departmrnt labels 
        Set<String> departmentSet = new Set<String>{UtilConstants.DENTAL,UtilConstants.Vision,UtilConstants.ENROLLBILL,UtilConstants.MEDICAL_BENEFITS,UtilConstants.ID_CARDS,UtilConstants.BENEFIT_DEPT,UtilConstants.PHARMACY,UtilConstants.INTER_PLAN,UtilConstants.SBC,UtilConstants.Issue_Control,
        UtilConstants.UNDERWRITING_MEDICAL,UtilConstants.UNDERWRITING_LIFE ,UtilConstants.UNDERWRITING_DENTAL ,UtilConstants.UNDERWRITING_VISION };
        Set<Object> SIManualDepartment=  new Set<Object>();
        Map<String,Set<Object>> STManualDepartment= new Map<String,Set<Object>>();           
        Set<string> existingDeptSet = new Set<String>();
        if(existingSMEDept.size()>0)
        {
        for(SME_Approvals__c tempDept : existingSMEDept)
            existingDeptSet.add(tempDept.SME_Department__c);
        }   
        if(existingSMEDept.size()>0){
            for(SME_Approvals__c tempDept : existingSMEDept){
                tempDept.Status__c ='Initiated';
                existingSMEDeptNew.add(tempDept);                         
            }                      
            update  existingSMEDeptNew;            
        }
        
        for(String tempDept : departmentSet)
        {
            Map<String,String> SIManualDepartmentMap= new Map<String,String>();                                                                   
            try
            {
                if((tempDept == UtilConstants.ENROLLBILL && impCase[0].Are_there_changes_to_Rates__c == UtilConstants.YES))                         
                {  
                    SIManualDepartmentMap.put(UtilConstants.JSON_NAME_FIELD,tempDept);                            
                    SIManualDepartmentMap.put(UtilConstants.VLC_SELECTED,UtilConstants.TRUE_VAL);
                    SIManualDepartment.add(SIManualDepartmentMap);
                    
                }
                else if((tempDept == UtilConstants.MEDICAL_BENEFITS && impCase[0].Impact_To_HPCC__c == UtilConstants.YES))
                {
                    SIManualDepartmentMap.put(UtilConstants.JSON_NAME_FIELD,tempDept);                            
                    SIManualDepartmentMap.put(UtilConstants.VLC_SELECTED,UtilConstants.TRUE_VAL);
                    SIManualDepartment.add(SIManualDepartmentMap);
                }   
                else        
                {
                    SIManualDepartmentMap.put(UtilConstants.JSON_NAME_FIELD,tempDept);                            
                    SIManualDepartment.add(SIManualDepartmentMap);
                }                 
             }                    
             catch(Exception excp)
             { 
                 UTIL_LoggingService.logHandledException(excp, UtilConstants.ORGID, UtilConstants.APPNAME, 
                                                           CLASS_NAME, UtilConstants.CANCEL,TEST_CLASS,LoggingLevel.ERROR); 
             }
             System.debug(SIManualDepartment);
             STManualDepartment.put(UtilConstants.SI_MANUAL_DEPARTMENT,SIManualDepartment); 
             outMap.put(UtilConstants.ST_MANUAL_DEPARTMENT, STManualDepartment );                                    
        } 
    } 

 /*
    Method Name: createSMEApprovals
    Method Signature: public static void createSMEApprovals(Map<String,Object> inputMap, Set<Object> deptList, Map<String,Object> outMap)
    Method Return Type: void
    Method Description: This method is called from 'invoke' method.
    */
   public static void createSMEApprovals(Map<String,Object> inputMap, 
        Set<Object> deptList, Map<String,Object> outMap,String OtherDptVal)    
    {          
        String contextId; 
        //ID recrdtypeID = '';
        //String groupcheck;      
        Impl_Revision__c currentRevision;       
        if(String.valueOf(inputMap.get(UtilConstants.IMP_ID)) !=null)
        {
            contextId                =  String.valueOf(inputMap.get(UtilConstants.IMP_ID));
            currentRevision = [Select Id,Status_Capture__c,Revision_Record_Status__c from Impl_Revision__c where Implementation_Case_Id__c = :contextId AND Revision_Record_Status__c =: UtilConstants.APPROVED Order By lastModifiedDate DESC limit 1];
        }
        else
        {
            contextId                =  String.valueOf(inputMap.get(UtilConstants.CONTEXT_ID));
        }        
        String implementationType       =  String.valueOf(inputMap.get(UtilConstants.IMPLEMENTATION_TYPE));  
        String productEffectiveDate     =  String.valueOf(inputMap.get(UtilConstants.PRODUCT_EFFECTIVE_DATE));
        //String otherTextFromOmniscript     =  String.valueOf(inputMap.get(UtilConstants.OTHERTEXT));
        
        Order currentOrder              =  [Select Id,SME_Service_Operations__c,Account.Group_Size__c,Revision_Text__c,Revision_Sequence_UpdatingTrigger__c,No_Rev_Email__c from Order where Id = :contextId limit 1];  
        Integer currentOrderValue;                          
        /*groupcheck = currentOrder.Account_Group_Size__c;
        if(groupcheck== '51 - 99') {
            recrdtypeID = System.Label.Account_Group_Size_ID;
        }*/
        Set<String> existingSMEAPDepartmentsCheck = new Set<String>();
        for(Object settemp: deptList){
            existingSMEAPDepartmentsCheck.add(String.valueof(settemp));
        }
    
        System.debug('deptList'+deptList);
        
        if (!deptList.isEmpty())
        {        
            //Fetching Quote Line Items related to present Order.
            System.debug('contextId'+contextId);
            List<SME_Approvals__c> relatedSMEAprovals = [SELECT Id,SME_Department__c FROM SME_Approvals__c WHERE Implementation_Record_ID__c = :contextId];
            System.debug('relatedSMEAprovals'+relatedSMEAprovals);
            Set<String> existingSMEAPDepartments = new Set<String>(); //We store all the existeng 'SME Approval' records departments related to the Implementation Case.   
            Map<String,String> SIAutoDepartmenttMap= new Map<String,String>();
            Set<Object> SIAutoDepartment =  new Set<Object>();
            Map<String,Set<Object>> STAutoDepartment  = new Map<String,Set<Object>>();   
            
            if(!relatedSMEAprovals.isEmpty())
            {            
                for(SME_Approvals__c tempSMEApproval : relatedSMEAprovals)
                {
                    existingSMEAPDepartments.add(tempSMEApproval.SME_Department__c); 
                        
                     if(inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT) != null)
                      {
                     Set<Object> manualDepts = new Set<Object>{inputMap.get(UtilConstants.ST_MANUAL_DEPARTMENT)};   
                     Map<String,Object> engageManualDeptMap = new Map<String,Object>();       
                      for(Object tempObj : manualDepts)               
                        engageManualDeptMap = (Map<String,Object>) tempObj;     
                        
                         if(engageManualDeptMap.get(UtilConstants.SI_MANUAL_DEPARTMENT) != null)
                         {
                             List<Object> engageManualDeptMap2 = (List<Object>) engageManualDeptMap.get(UtilConstants.SI_MANUAL_DEPARTMENT);
                             for(Object tempEngage : engageManualDeptMap2)
                             {
                                 Map<String,Object> engageDeptMap = (Map<String,Object>) tempEngage;                                 
                                 if(engageDeptMap.get(UtilConstants.JSON_NAME_FIELD) != null && 
                                    engageDeptMap.get(UtilConstants.JSON_NAME_FIELD) == tempSMEApproval.SME_Department__c)
                                    {
                                       if(String.valueOf(inputMap.get(UtilConstants.IMP_ID)) !=null)
                                           tempSMEApproval.Status__c = UtilConstants.STAT_PENDING ;                                        
                                 
                                    }                                                                    
                             }    
                                             
                         } 
                        
                     }                                                             
                }                
            } 
            
           //comented as part of defect 23590  
           if(inputmap.containsKey('DRId_Impl_Revision__c')){
               ID revisionId = String.valueof(inputmap.get('DRId_Impl_Revision__c'));
               Impl_Revision__c  r = [select name from Impl_Revision__c where id =:revisionId];
               RevisionText  = RevisionText + r.name + '-';
               currentOrder.put('Latest_Revision_ID__c',r.id);
           }            
          // if(!existingSMEAPDepartments.containsAll(existingSMEAPDepartmentsCheck)){
                if(currentOrder.Revision_Sequence_UpdatingTrigger__c != null){  
                    currentOrderValue = Integer.valueof(currentOrder.Revision_Sequence_UpdatingTrigger__c);
                    currentOrderValue = currentOrderValue + 1;
                    currentOrder.put('Revision_Sequence_UpdatingTrigger__c',currentOrderValue);
                    currentOrder.put('Revision_Text__c',RevisionText);
                    currentOrder.put('Revision_Record_Link_For_Template__c',true);                    
                    currentOrder.put('No_Rev_Email__c',false);
                 }
                 else{
                    currentOrderValue = 1;  
                    currentOrder.put('Revision_Sequence_UpdatingTrigger__c',currentOrderValue); 
                    currentOrder.put('Revision_Text__c',RevisionText);
                    currentOrder.put('No_Rev_Email__c',false);  
                    currentOrder.put('Revision_Record_Link_For_Template__c',true);                
                 }
                
          //  } 
                    
            System.debug('deptList'+deptList);  
                
            for (Object deptname : deptList)                              
            {
                 String checkBoxDepartment;
                 // PRDCRM-39088 cmh
                 if(String.valueOf(deptname) == UtilConstants.PRICING_CONFIGURATION_MANAGEMENT_PCM)
                 {
                     checkBoxDepartment = UtilConstants.API_PRICING_CONFIGURATION_MANAGEMENT_PCM;
                 } else if(String.valueOf(deptname).trim() == 'Other') {
                     checkBoxDepartment = 'SME_Other__c';
                 } else
                 {
                     checkBoxDepartment = String.valueOf(deptname).replace(' - ','_');
                     checkBoxDepartment = 'SME_' + String.valueOf(checkBoxDepartment).replaceAll('[/ / /]','_') + '__c';
                     checkBoxDepartment = checkBoxDepartment.replaceAll('[/( )/]',''); 
                 }                 
                 currentOrder.put(checkBoxDepartment, true); 
                 currentOrder.put(UtilConstants.IMPLEMENTATION_STATUS , UtilConstants.IC_STATUS_PENDINGSMEREVIEW );
                                    
            } 
              
            List<SME_Approvals__c> sme_approvalList = new List<SME_Approvals__c>();
            for (Object deptname : deptList)
            {   


                 SME_Approvals__c sme_apprnew = new  SME_Approvals__c();
                 if(String.valueOf(deptname) == UtilConstants.OTHER + '  '){
                    continue;  // auto-selected-other ; cmh 
                 } else if(String.valueOf(deptname) == UtilConstants.OTHER) {
                     if (OtherDptVal == NULL || String.isEmpty(OtherDptVal)){ continue;}
                     sme_apprnew.If_Other_List_Department__c = OtherDptVal; //cmh q0817  UtilConstants.OTHER;
                     sme_apprnew.SME_Department__c = String.valueOf(deptname);              
                     
                 }  
                             
                 if(!existingSMEAPDepartments.Contains(String.valueOf(deptname)) &&  String.valueOf(deptname) != UtilConstants.IHM)                 
                     if(String.valueOf(deptname) != null)                                                                                                                                                                                                                                                                                                               
                         sme_apprnew.SME_Department__c = String.valueOf(deptname);                                                                                                                
                 
                 if(String.valueOf(deptname) == UtilConstants.IHM && !existingSMEAPDepartments.Contains(UtilConstants.IHMM))                              
                     sme_apprnew.SME_Department__c =  UtilConstants.IHMM;                        
                 
                 if(!String.isBlank(productEffectiveDate))
                 {
                     if (implementationType.equals(UtilConstants.NEW_BUSINESS) || implementationType.equals(UtilConstants.RENEWAL))                                   
                        sme_apprnew.Production_Date__c = Date.valueOf(productEffectiveDate);                                        
                 }
                 sme_apprnew.Implementation_Record_ID__c = contextId;
                 sme_approvalList.add(sme_apprnew);                 
              }
              

            
             System.debug('sme_approvalList'+sme_approvalList);
              if (sme_approvalList.size() >0)
              {
                  Savepoint sp = Database.setSavepoint();
                 
                  try
                  {
                     
                      Database.insert(sme_approvalList,false);                      
                      Database.update(relatedSMEAprovals,false);
                      
                      update currentOrder; 

                  }
                  catch(Exception e)
                  {       
                                                    
                      outMap.put(UtilConstants.ERROR, e.getMessage());
                      Database.rollback(sp);                        
                  }
              } 
                
            
        }
        
        else
        {
            if(String.valueOf(inputMap.get(UtilConstants.IMP_ID)) !=null)
             currentOrder.put(UtilConstants.IMPLEMENTATION_STATUS , currentRevision.Status_Capture__c);
             update currentOrder;
        }
        
    } 

}