objects/AccountRoles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Roles</description>
    <fields>
        <fullName>LastRun__c</fullName>
        <description>Batch Class Last Run DateTime</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LastRun</label>
        <type>DateTime</type>
    </fields>
    <label>Account Roles</label>
</CustomObject>

objects/Funding__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Funding</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <recordTypes>
        <fullName>Funding</fullName>
        <active>true</active>
        <label>Funding</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Situs State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT( Opportunity.Account.Anthem_Entity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <formula>TEXT(Opportunity.Account.Situs_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Situs State</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>51 - 99</fullName>
                </value>
                <value>
                    <fullName>100 - 249</fullName>
                </value>
                <value>
                    <fullName>250 - 499</fullName>
                </value>
                <value>
                    <fullName>500 - 999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Quote.Opportunity.Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SIC__c.object
<CustomObject>
    <label>SIC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Industry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SICs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/QLIToAccountRollUpBatchLGTest.cls
/**************************************************************************************
Apex Class Name:  QLIToAccountRollUpBatchLGTest
Version     : 1.0 
Created Date    : 13 June 2019
* @Author: Legato Vikings Team
Function    : Test class for QLIToAccountRollUpBatchLG
*************************************************************************************/
@isTest
public class QLIToAccountRollUpBatchLGTest extends staticVariableClass {
    
    @testSetup
    static  void setupTestData(){
        AccountRoles__c roles = new AccountRoles__c();
        roles.Name = 'QLIToAccountRollUpBatchLG';        
        DateTime dt = DateTime.newInstance(2012,2,3,13,20,30);
        roles.LastRun__c = dt;
        insert roles;
        
    }
    
    static testMethod void testMethodBatchAccountUpdate() 
    {
        SIC__c Sic = new SIC__c(
            Name = staticVariableClass.SIC
        );
        Insert SIC;
        List<account>accList=new List<account>();      
        for(integer i=0;i<11;i++){
         Account acc =new Account(
            RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('LG Prospect').getRecordTypeId(),
            Name = 'VKLegosACN'+i,
            Account_s_Suppress_Auto_Renewal__c = false,
            Anthem_Entity__c = staticVariableClass.Entity,
            Region__c= staticVariableClass.Region,
            Branding__c =staticVariableClass.UniCare,
            SIC__c = SIC.Id,
            Group_Size__c =staticVariableClass.size,
            Total_Employees__c =staticVariableClass.emp,
            HQ_State__c =staticVariableClass.AK,
            Situs_State__c = staticVariableClass.California,
            Mailing_Address_Same_as_Physical_Address__c = true,
            BillingStreet = 'Land Marks'+i,
            BillingPostalCode = '560036',
            BillingCity = 'Manglores'+i,
            BillingCountry = 'India',
            BillingState = 'Karnataka',
            Physical_County__c = 'Banglore' 
            );
          accList.add(acc);
        }   
      
        insert accList;
        
        List<Opportunity> lstOpp= new List<Opportunity>();
        
        for(integer i=0;i<11;i++){
            Opportunity newOpp = new Opportunity(
                name=  (String.valueOf(system.today().year() + 1) + ' New Business Local-' +  accList[i].Name),
                StageName = staticVariableClass.ClosedWon,
                AccountID = accList[i].id,
                CloseDate = ((system.TODAY())-9),                   
                recordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('New Business Local').getRecordTypeId()                                    
            );
            lstOpp.add(newOpp);
        }   
        Database.insert(lstOpp);
        
        Group__c grp=ANA_UTIL01_TestMethods.createGroup(accList[0].id,false);
        Database.insert(grp);
        
        List<Quote> qteList=ANA_UTIL01_TestMethods.createQuotes(11,false,lstOpp[0].Id);
        for(integer i=0;i<11;i++){
        qteList[i].GroupNumber__c=grp.id;
        qteList[i].Opportunityid=lstOpp[i].Id;
        }
        
        Database.insert(qteList);
        
        Product2 prod=ANA_UTIL01_TestMethods.createProduct(false);
        prod.Family = 'Medical';
        prod.LOB__c= 'Medical';        
        prod.name='Anthem Health PPO Medical';
        Database.insert(prod);
        
        PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false,prod.id);
        Database.insert(pbe);
        
        List<QuoteLineItem> qliList=new List<QuoteLineItem>();       
        List<QuoteLineItem> qliList5=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[4].id,pbe.id);  // where all the QLI's will be in N/A Status 
        List<QuoteLineItem> qliList1=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[0].id,pbe.id);
        List<QuoteLineItem> qliList2=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[1].id,pbe.id);
        List<QuoteLineItem> qliList3=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[2].id,pbe.id);
        
        List<QuoteLineItem> qliList4=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[3].id,pbe.id);   //IN Progress+Mixed         
        List<QuoteLineItem> qliList6=ANA_UTIL01_TestMethods.createQuoteLineItems(4,false,qteList[5].id,pbe.id);   //IN Progress+FI     
        List<QuoteLineItem> qliList10=ANA_UTIL01_TestMethods.createQuoteLineItems(1,false,qteList[9].id,pbe.id);   //IN Progress+ASO
        
        List<QuoteLineItem> qliList7=ANA_UTIL01_TestMethods.createQuoteLineItems(2,false,qteList[6].id,pbe.id); //Lost+Mixed
        List<QuoteLineItem> qliList8=ANA_UTIL01_TestMethods.createQuoteLineItems(2,false,qteList[7].id,pbe.id);   //Lost+ASO        
        List<QuoteLineItem> qliList9=ANA_UTIL01_TestMethods.createQuoteLineItems(2,false,qteList[8].id,pbe.id);   //Lost+FI  

        List<QuoteLineItem> qliList11=ANA_UTIL01_TestMethods.createQuoteLineItems(2,false,qteList[10].id,pbe.id); // Covers Deleted  //Lost+FI          
        
           
         qliList5[0].Funding__c='N/A';       
         qliList5[1].Funding__c='N/A';      
         qliList5[2].Funding__c='N/A';        
         qliList5[3].Funding__c='N/A';
         
         qliList1[0].Funding__c='ASO';        // Sold+Mixed Funding
         qliList1[1].Funding__c='FI';       
         qliList1[2].Funding__c='ASO';        
         qliList1[3].Funding__c='ASO';
         qliList1[0].ProductStage__c='IGAP Sold'; 
         qliList1[1].ProductStage__c='Sold';
         qliList1[2].ProductStage__c='Renewed'; 
         qliList1[3].ProductStage__c='Sold'; 
            
            
         qliList2[0].Funding__c='ASO';     // Sold+ASO Funding    
         qliList2[1].Funding__c='ASO';          
         qliList2[2].Funding__c='ASO';        
         qliList2[3].Funding__c='ASO';         
         qliList2[0].ProductStage__c='Sold'; 
         qliList2[1].ProductStage__c='Sold';
         qliList2[2].ProductStage__c='Sold'; 
         qliList2[3].ProductStage__c='Sold'; 
         
         qliList3[0].Funding__c='FI';         // Sold+FI Funding
         qliList3[1].Funding__c='FI';         
         qliList3[2].Funding__c='FI';      
         qliList3[3].Funding__c='FI';       
         qliList3[0].ProductStage__c='Sold'; 
         qliList3[1].ProductStage__c='Sold';
         qliList3[2].ProductStage__c='Sold'; 
         qliList3[3].ProductStage__c='Sold'; 
            
         qliList4[0].Funding__c='ASO';       // In Progress+Mixed Funding  
         qliList4[1].Funding__c='ASO/FI';          
         qliList4[2].Funding__c='FI';        
         qliList4[3].Funding__c='ASO';         
         qliList4[0].ProductStage__c='In Progress'; 
         qliList4[1].ProductStage__c='IGAP In Progress';
         qliList4[2].ProductStage__c='In Progress'; 
         qliList4[3].ProductStage__c='In Progress'; 
        
         qliList6[0].Funding__c='FI';       // In Progress+FI Funding  
         qliList6[1].Funding__c='FI';          
         qliList6[2].Funding__c='FI';        
         qliList6[3].Funding__c='N/A';         
         qliList6[0].ProductStage__c='In Progress'; 
         qliList6[1].ProductStage__c='IGAP In Progress';
         qliList6[2].ProductStage__c='In Progress'; 
         qliList6[3].ProductStage__c='In Progress'; 
         
         qliList10[0].Funding__c='ASO';    // In Progress+ASO Funding        
         qliList10[0].ProductStage__c='In Progress';
         
        
         qliList7[0].Funding__c='ASO';       // Lost+Mixed Funding  
         qliList7[1].Funding__c='ASO/FI';
         qliList7[0].ProductStage__c='Lost'; 
         qliList7[1].ProductStage__c='IGAP Lost';
         
         qliList8[0].Funding__c='ASO';       // Lost+ASO  
         qliList8[1].Funding__c='ASO';
         qliList8[0].ProductStage__c='Lost'; 
         qliList8[1].ProductStage__c='IGAP Lost';
         
         qliList9[0].Funding__c='FI';       // Lost+FI  
         qliList9[1].Funding__c='FI'; 
         qliList9[0].ProductStage__c='Lost'; 
         qliList9[1].ProductStage__c='IGAP Lost';
    
         qliList11[0].Funding__c='N/A';       // will be deleted 
         qliList11[1].Funding__c='FI'; 
         qliList11[0].ProductStage__c='In Progress'; 
         qliList11[1].ProductStage__c='IGAP Lost';
         
         qliList.addall(qliList1);
         qliList.addall(qliList2);
         qliList.addall(qliList3);
         qliList.addall(qliList4);
         qliList.addall(qliList5);
         qliList.addall(qliList6);
         qliList.addall(qliList7);
         qliList.addall(qliList8);
         qliList.addall(qliList9);
         qliList.addall(qliList10);
         qliList.addall(qliList11);
         
         Database.insert(qliList);
         delete qliList11;
        
         Test.startTest();
           QLIToAccountRollUpBatchLG obj = new QLIToAccountRollUpBatchLG();
           DataBase.executeBatch(obj,200); 
         Test.stopTest();
    }
    
    
}