objects/AccountRoles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Roles</description>
    <fields>
        <fullName>LastRun__c</fullName>
        <description>Batch Class Last Run DateTime</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LastRun</label>
        <type>DateTime</type>
    </fields>
    <label>Account Roles</label>
</CustomObject>

objects/Funding__c.object
<CustomObject>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Members__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscribers__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Competitor2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor2</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items (Competitor2)</relationshipLabel>
        <relationshipName>Quote_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitor3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor3</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items (Competitor3)</relationshipLabel>
        <relationshipName>Quote_Line_Items2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <label>Financing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Services Only</fullName>
                </value>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Fee / % of Savings</fullName>
                </value>
                <value>
                    <fullName>JAA (Jointly Administered Arrangement)</fullName>
                </value>
                <value>
                    <fullName>Minimum Premium</fullName>
                </value>
                <value>
                    <fullName>Modified Cost Plus</fullName>
                </value>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>Percent of Savings</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Cost Plus Alternate Funded</fullName>
                </value>
                <value>
                    <fullName>FI - Deposit Premium</fullName>
                </value>
                <value>
                    <fullName>FI - Refund Agreement</fullName>
                </value>
                <value>
                    <fullName>Fully Insured</fullName>
                </value>
                <value>
                    <fullName>Non-Refunding</fullName>
                </value>
                <value>
                    <fullName>Refunding</fullName>
                </value>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>MCS Network Rental</fullName>
                </value>
                <value>
                    <fullName>Contingent Premium</fullName>
                </value>
                <value>
                    <fullName>JIA (Jointly Integrated Arrangement)</fullName>
                </value>
                <value>
                    <fullName>ABF (Anthem Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>EBF (Empire Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>ASC (Administrative Service Contract)</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
                <value>
                    <fullName>Level Funded/Fully Insured</fullName>
                </value>
                <value>
                    <fullName>JAA (Full Service) - ANA Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Quote.OpportunityId</formula>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <formula>TEXT(Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLOB__c</fullName>
        <formula>IF(
NOT(ISBLANK(TEXT(Product2.LOB__c))),
TEXT(Product2.LOB__c),
LEFT( TEXT(Product2.LOB_Org__c),LEN(TEXT(Product2.LOB_Org__c))-2 )
)</formula>
        <label>ProductLOB</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Family_Local__c</fullName>
        <formula>TEXT(Product2.Product_Family__c)</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscribers__c</fullName>
        <inlineHelpText>Enter the number of Subscribers for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QLIToOpportunityRollUpBatch.cls
/*
* Purpose: Rolls up field values to respective Opportunity records
* Version: 1.0
* 
* JIRA NUMBER    DATE           DEVELOPER    DESCRIPTION 
* ===========    ===========    =========    =======================================================
*PRDCRM-33940    06-June-2019    Sharath KN   Created batch class
*History 
1) PRDCRM-37695 : Adding logic to rollup members and subscribers from QLI to Opportunity : Ravideep(Vikings)
2) PRDCRM-40695 : Adding logic to rollup members and subscribers from Medical only QLI's to Opportunity : Ravideep(Vikings)
3) PRDCRM-44200 : Added filter criteria for the changes made as part of PRDCRM-40695 : Sharath KN(Vikings)
*/

global class QLIToOpportunityRollUpBatch implements Database.Batchable<sObject>{
    String headerStr = 'Opportunity Id,Error \n';
    global String oppStr = headerStr;
    global Boolean isError = false;
    global String Query = 'SELECT Id, OpportunityId__c FROM QuoteLineItem WHERE lastmodifieddate >: lastRun OR Product2.lastmodifieddate >: lastRun ORDER By OpportunityId__c ASC nulls last ALL RoWS';
    global AccountRoles__c roles = AccountRoles__c.getValues('OppReport');//Custom setting that stores the batch last run datetime
    DateTime lastRun = roles.LastRun__c; // Holds the date when this batch was run last time
    DateTime jobStartTime = DateTime.now();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<QuoteLineItem> QLIList){
        Set<Id> oppIds = new Set<Id>(); // Set that holds unique opportunity IDs
        
        //generate list of unique Opportunity IDs
        for(QuoteLineItem thisQLI : QLIList){
            if(thisQLI.OpportunityId__c != null)
                oppIds.add(thisQLI.OpportunityId__c);
        }
        Set<Id> finalOppIds = new Set<Id>();
        Set<Id> nonDeletedQLIOppIds = new Set<Id>(); // stores OppIds for which atleast one QLI exists
        Map<String,Set<String>> masterFieldMap = new Map<String,Set<String>>();
        Map<String,decimal> masterNumberFieldMap = new Map<String,decimal>();
        for(QuoteLineItem thisQLI : [SELECT Id, Funding__c, Financing__c, OpportunityId__c,quote.opportunity.IsDeleted, ProductLOB__c, Product_Family_Local__c, ProductStage__c, Competitor__c, Competitor__r.Name, Competitor2__c, Competitor2__r.Name, Competitor3__c, Competitor3__r.Name,Subscribers__c,Members__c,ProductCategory__c FROM QuoteLineItem WHERE quote.opportunity.Id IN: oppIds]){
            nonDeletedQLIOppIds.add(thisQLI.OpportunityId__c);
            if(thisQLI.quote.opportunity.IsDeleted == false){
                finalOppIds.add(thisQLI.OpportunityId__c);
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Funding__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Funding__c', new Set<String>());
                    if(!String.isBlank(thisQLI.Funding__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Funding__c').add(thisQLI.Funding__c);
                }
                else {
                    if(!String.isBlank(thisQLI.Funding__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Funding__c').add(thisQLI.Funding__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Financing_Rollup__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Financing_Rollup__c', new Set<String>());
                    if(!String.isBlank(thisQLI.Financing__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Financing_Rollup__c').add(thisQLI.Financing__c);
                }
                else {
                    if(!String.isBlank(thisQLI.Financing__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Financing_Rollup__c').add(thisQLI.Financing__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Product_Families__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Product_Families__c', new Set<String>());
                    if(!String.isBlank(thisQLI.Product_Family_Local__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Product_Families__c').add(thisQLI.Product_Family_Local__c);
                }
                else {
                    if(!String.isBlank(thisQLI.Product_Family_Local__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Product_Families__c').add(thisQLI.Product_Family_Local__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Lines_of_Business__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Lines_of_Business__c', new Set<String>());
                    if(!String.isBlank(thisQLI.ProductLOB__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Lines_of_Business__c').add(thisQLI.ProductLOB__c);
                }
                else {
                    if(!String.isBlank(thisQLI.ProductLOB__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Lines_of_Business__c').add(thisQLI.ProductLOB__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Sold_Lines_of_Business__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Sold_Lines_of_Business__c', new Set<String>());
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase('sold') || thisQLI.ProductStage__c.containsIgnoreCase('renew'))){
                        if(!String.isBlank(thisQLI.ProductLOB__c))
                            masterFieldMap.get(thisQLI.OpportunityId__c + 'Sold_Lines_of_Business__c').add(thisQLI.ProductLOB__c);
                    }
                }
                else {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase('sold') || thisQLI.ProductStage__c.containsIgnoreCase('renew')))
                        if(!String.isBlank(thisQLI.ProductLOB__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Sold_Lines_of_Business__c').add(thisQLI.ProductLOB__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Sold_Product_Families__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Sold_Product_Families__c', new Set<String>());
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase('sold') || thisQLI.ProductStage__c.containsIgnoreCase('renew'))){
                        if(!String.isBlank(thisQLI.Product_Family_Local__c))
                            masterFieldMap.get(thisQLI.OpportunityId__c + 'Sold_Product_Families__c').add(thisQLI.Product_Family_Local__c);
                    }
                }
                else {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase('sold') || thisQLI.ProductStage__c.containsIgnoreCase('renew')))
                        if(!String.isBlank(thisQLI.Product_Family_Local__c))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Sold_Product_Families__c').add(thisQLI.Product_Family_Local__c);
                }
                if (!masterFieldMap.containsKey(thisQLI.OpportunityId__c + 'Competitors__c')) {
                    masterFieldMap.put(thisQLI.OpportunityId__c + 'Competitors__c', new Set<String>());
                    if(!String.isBlank(thisQLI.Competitor__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor__r.Name);
                    if(!String.isBlank(thisQLI.Competitor2__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor2__r.Name);
                    if(!String.isBlank(thisQLI.Competitor3__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor3__r.Name);
                }
                else {
                    if(!String.isBlank(thisQLI.Competitor__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor__r.Name);
                    if(!String.isBlank(thisQLI.Competitor2__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor2__r.Name);
                    if(!String.isBlank(thisQLI.Competitor3__r.Name))
                        masterFieldMap.get(thisQLI.OpportunityId__c + 'Competitors__c').add(thisQLI.Competitor3__r.Name);
                }
                // PRDCRM-37695 : Adding logic to rollup members and subscribers from QLI to Opportunity : Ravideep(Vikings)
                if (!masterNumberFieldMap.containsKey(thisQLI.OpportunityId__c + staticVariableClass.SubscribersRollup)) {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew))){
                        if(thisQLI.Subscribers__c != null){
                            system.debug('thisQLI.Subscribers__c 1 ' + thisQLI.Subscribers__c);
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.SubscribersRollup,thisQLI.Subscribers__c);
                        }
                    }
                }
                else {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew))){
                        if(thisQLI.Subscribers__c != null){
                            system.debug('thisQLI.Subscribers__c 2 ' + thisQLI.Subscribers__c);
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.SubscribersRollup,masterNumberFieldMap.get(thisQLI.OpportunityId__c + staticVariableClass.SubscribersRollup)+thisQLI.Subscribers__c);
                        }
                    }
                }

                if(!masterNumberFieldMap.containsKey(thisQLI.OpportunityId__c + staticVariableClass.MembersRollup )) {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew))){
                        if(thisQLI.Members__c != null){
                            system.debug('thisQLI.Members__c 1 ' + thisQLI.Members__c);
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.MembersRollup , thisQLI.Members__c);
                        }
                    }
                }
                else{
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew))){
                        if(thisQLI.Members__c != null){
                            system.debug('thisQLI.Members__c 2 ' + thisQLI.Members__c);
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.MembersRollup ,masterNumberFieldMap.get(thisQLI.OpportunityId__c + staticVariableClass.MembersRollup )+thisQLI.Members__c);
                        }
                    }
                }
                //PRDCRM-40695 : Adding logic to rollup members and subscribers from Medical only QLI's to Opportunity : Ravideep(Vikings)
                //PRDCRM-44200 : Added filter criteria to consider only 'Product' type categories : Sharath KN(Vikings)
                if(!masterNumberFieldMap.containsKey(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalSubscribers)) {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (!String.isBlank(thisQLI.ProductCategory__c)) && thisQLI.ProductCategory__c.containsIgnoreCase(staticVariableClass.PRODUCT_CATEGORY) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew)) && (!String.isBlank(thisQLI.ProductLOB__c)) && (thisQLI.ProductLOB__c.equalsIgnoreCase(staticVariableClass.Medical))){
                        if(thisQLI.Subscribers__c != null){
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalSubscribers,thisQLI.Subscribers__c);
                        }
                    }
                }
                else {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (!String.isBlank(thisQLI.ProductCategory__c)) && thisQLI.ProductCategory__c.containsIgnoreCase(staticVariableClass.PRODUCT_CATEGORY) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew)) && (!String.isBlank(thisQLI.ProductLOB__c)) && (thisQLI.ProductLOB__c.equalsIgnoreCase(staticVariableClass.Medical))){
                        if(thisQLI.Subscribers__c != null){
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalSubscribers,masterNumberFieldMap.get(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalSubscribers)+thisQLI.Subscribers__c);
                        }
                    }
                }
                if(!masterNumberFieldMap.containsKey(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalMembers)) {
                   if((!String.isBlank(thisQLI.ProductStage__c)) && (!String.isBlank(thisQLI.ProductCategory__c)) && thisQLI.ProductCategory__c.containsIgnoreCase(staticVariableClass.PRODUCT_CATEGORY) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew)) && (!String.isBlank(thisQLI.ProductLOB__c)) && (thisQLI.ProductLOB__c.equalsIgnoreCase(staticVariableClass.Medical))){
                        if(thisQLI.Members__c != null){
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalMembers, thisQLI.Members__c);
                        }
                    }
                }
                else {
                    if((!String.isBlank(thisQLI.ProductStage__c)) && (!String.isBlank(thisQLI.ProductCategory__c)) && thisQLI.ProductCategory__c.containsIgnoreCase(staticVariableClass.PRODUCT_CATEGORY) && (thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Sold) || thisQLI.ProductStage__c.containsIgnoreCase(staticVariableClass.Renew)) && (!String.isBlank(thisQLI.ProductLOB__c)) && (thisQLI.ProductLOB__c.equalsIgnoreCase(staticVariableClass.Medical))){
                        if(thisQLI.Members__c != null){
                            masterNumberFieldMap.put(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalMembers,masterNumberFieldMap.get(thisQLI.OpportunityId__c + staticVariableClass.TotalMedicalMembers)+thisQLI.Members__c);
                        }
                    }
                }
                
            }
        }
        system.debug('Master Field Map ======' + masterFieldMap);
        system.debug('Master Number Field Map ======' + masterNumberFieldMap);
        List<opportunity> oppsToBeUpdated = new List<opportunity>();
        List<String> oppFields = new List<String>{'Funding__c','Lines_of_Business__c','Financing_Rollup__c','Product_Families__c','Sold_Lines_of_Business__c','Sold_Product_Families__c','Competitors__c',staticVariableClass.SubscribersRollup,staticVariableClass.MembersRollup,staticVariableClass.TotalMedicalSubscribers,staticVariableClass.TotalMedicalMembers};
            for(String thisOppId : finalOppIds){
                Opportunity thisOpp = new Opportunity();
                thisOpp.Id = thisOppId;
                for(String thisField : oppFields){
                    if (!masterNumberFieldMap.isEmpty() && masterNumberFieldMap.get(thisOppId.substring(0, 15) + thisField) != null){
                        thisOpp.put(thisField,masterNumberFieldMap.get(thisOppId.substring(0, 15) + thisField)) ;
                    }
                    else {
                        if ((masterFieldMap.get(thisOppId.substring(0, 15) + thisField)) != null && !(masterFieldMap.get(thisOppId.substring(0, 15) + thisField)).isEmpty()) {
                            Set<String> fieldValues = masterFieldMap.get(thisOppId.substring(0, 15) + thisField);
                            List<string> fieldValuesList = new List<String>(fieldValues);
                            fieldValuesList.sort();
                            String str = String.join(fieldValuesList, ';');
                            thisOpp.put(thisField, (str.length() > 255 ? str.substring(0, 254) : str));
                        }else{
                            thisOpp.put(thisField, null);
                        }
                    }
                    
                }
                oppsToBeUpdated.add(thisOpp);
            }
        oppIds.removeAll(nonDeletedQLIOppIds);        
        if(oppIds.size() > 0){
            Set<Id> nonDelOpps = new Set<Id>();
            for(Opportunity thisOpp :[SELECT id FROM Opportunity WHERE Id IN: oppIds AND isDeleted = false] ){
                nonDelOpps.add(thisOpp.id);
            }
            if(nonDelOpps.size() > 0)
                for(Id thisOppId : nonDelOpps){
                    Opportunity thisOpp = new Opportunity(Id = thisOppId,Funding__c = null,Financing_Rollup__c = null,Competitors__c = null,Lines_of_Business__c = null,Product_Families__c = null,Sold_Lines_of_Business__c = null,Sold_Product_Families__c = null,Subscribers_Rollup__c= null,Members_Rollup__c = null,Total_Medical_Subscribers__c = null,Total_Medical_Members__c = null);
                    oppsToBeUpdated.add(thisOpp);
                }
        }
        
        if(oppsToBeUpdated.size() > 0){
            Database.SaveResult[] sR =  Database.update(oppsToBeUpdated,false);
            for(Integer i=0;i<oppsToBeUpdated.size();i++){
                If(!sR[i].isSuccess()){
                    isError = true;string errorMsg = '';
                    for(Database.Error error : sR[i].getErrors()){
                        errorMsg += ' ' + error.getMessage();
                    }
                    oppStr += oppsToBeUpdated[i].Id + ',' +  errorMsg + '\n';
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        AsyncApexJob batchStatus = [Select Id, NumberOfErrors, Status, ExtendedStatus from AsyncApexJob where Id =:BC.getJobId()];
        if(isError == true || batchStatus.NumberOfErrors > 0){ Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
            Blob csvBlob = Blob.valueOf(oppStr);string csvname= 'Opportunity Errors.csv';csvAttc.setFileName(csvname);csvAttc.setBody(csvBlob);
            Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();String subject ='QLIToOpportunityRollUpBatch :'+batchStatus.Status;
            email.setSubject(subject);email.setToAddresses(new list<string>{System.label.Admin_Email});email.setPlainTextBody('QLIToOpportunityRollUpBatch has errors in Org - '+ UserInfo.getOrganizationId());
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});Messaging.SendEmailResult [] emailResult = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }else{
            roles.LastRun__c =jobStartTime;
            update roles;
        }
    }
}