objects/Account.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HCR__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>IF( ISBLANK(Group__r.Id ), &apos;&apos;, HYPERLINK(Group__r.Id, Group__r.Name))</formula>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>HCRs</relationshipLabel>
        <relationshipName>HCRs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCR</label>
    <nameField>
        <displayFormat>HCR-{0000}</displayFormat>
        <label>General HCR Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCRs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/HCR_Plan_Grids__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCR_Status__c</fullName>
        <label>HCR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Grandfathered</fullName>
                    <default>true</default>
                    <label>Non-Grandfathered</label>
                </value>
                <value>
                    <fullName>Grandfathered</fullName>
                </value>
                <value>
                    <fullName>Grandfathered - Zero Enrollment</fullName>
                </value>
                <value>
                    <fullName>Exempt</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>HCR</label>
        <referenceTo>HCR__c</referenceTo>
        <relationshipLabel>HCR Plan Grids</relationshipLabel>
        <relationshipName>HCR_Plan_Grids</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>HCR Plan Grids</label>
    <nameField>
        <displayFormat>HCRPG-{000}</displayFormat>
        <label>HCR Plan Grid Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HCR Plan Grids</pluralLabel>
    <recordTypes>
        <fullName>Grandfathered</fullName>
        <active>true</active>
        <label>Grandfathered</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AP20_HcrPlanGridInserts_Test.cls
/**
@Author : Accenture Offshore Dev team
@name : AP20_HcrPlanGridInserts_Test
@CreateDate :4/9/2018
@Description :This class is used for the test coverage of AP20_HcrPlanGridInserts .
*/

@isTest
 
private class AP20_HcrPlanGridInserts_Test {

static testMethod void HcrPlanGridInsertsTest(){

  List<Account> accList= new List<Account>();
        Account acc = new Account (Name='newaccount',Anthem_Entity__c ='National Accounts',Brand__c ='Uni care',Group_Size__c ='0 - 50',HQ_State__c = 'ak',Total_Employees__c =20);
        Account acc1 = new Account (Name='newaccount1',Anthem_Entity__c ='National Accounts',Brand__c ='Uni care',Group_Size__c ='0 - 50',HQ_State__c = 'ak',Total_Employees__c =20);
        accList.add(acc);
        accList.add(acc1);
    insert accList;
 
  
  Group__c testGroup = new Group__c(Name='tet41',Account__c=accList[0].id);
  insert testGroup;
 
  HCR__c hcr1 = new HCR__c();
  hcr1.Group__c=testGroup.id; 
  insert hcr1;
  system.debug('&&hcr1'+hcr1.id);
  
  
  System.debug([Select Id,Group_Number__c from HCR__c where Id = :hcr1.Id]);
  
  HCR__c hcrRecord = [Select Id,Group_Number__c from HCR__c where Id = :hcr1.Id limit 1];
  id RecTypeId =Schema.SObjectType.HCR_Plan_Grids__c.getRecordTypeInfosByName().get('Grandfathered').getRecordTypeId();
  HCR_Plan_Grids__c hp1 = new HCR_Plan_Grids__c( Active__c='Yes',HCR__c=hcr1.id,HCR_Status__c='Grandfathered',RecordTypeID=RecTypeId);
  insert hp1;
  
  HCR__c hcr2 = new HCR__c(); 
  hcr2.Group__c=testGroup.id;
  insert hcr2;
  system.debug('&&hcr2'+hcr2.id);
   
  HCR_Plan_Grids__c hp2 = new HCR_Plan_Grids__c( Active__c='Yes',HCR__c=hcr2.id,HCR_Status__c='Grandfathered');
  insert hp2;
   
  HCR__c hcr3 = new HCR__c();
  hcr3.Group__c=testGroup.id;
  
  insert hcr3;
   
   
   list<String> grpnames = new list<String>();
   grpnames.add(testGroup.Name);
   
  
  String s = String.valueOf(hcrRecord.Group_Number__c);
  System.debug(s);
  AP20_HcrPlanGridInserts.processBuilderInput pbi = new AP20_HcrPlanGridInserts.processBuilderInput();
  pbi.hcrId =hcr3.id;
  pbi.groupName= testGroup.Id;
  
  
  list<AP20_HcrPlanGridInserts.processBuilderInput> innerList = new list<AP20_HcrPlanGridInserts.processBuilderInput>();
  innerList.add(pbi);
  Test.startTest(); 
  AP20_HcrPlanGridInserts.clonePlanGrids(innerList); 
  Test.stopTest(); 

 }
 
 
}