objects/AccountRoles__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Account Roles</description>
    <fields>
        <fullName>LastRun__c</fullName>
        <description>Batch Class Last Run DateTime</description>
        <encryptionScheme>None</encryptionScheme>
        <label>LastRun</label>
        <type>DateTime</type>
    </fields>
    <label>Account Roles</label>
</CustomObject>

objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>BrokName__c</fullName>
        <formula>Brokerage__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BrokName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>LG Brokerage, LG Self Relationship</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BrokerageToOppRollUpBatch.cls
/*
* Purpose: Rolls up field values to respective Opportunity records
* Version: 1.0
* 
* JIRA NUMBER    DATE           DEVELOPER    DESCRIPTION 
* ===========    ===========    =========    =======================================================
*PRDCRM-36244    22-June-2019    Sharath KN   Created batch class
*/
global class BrokerageToOppRollUpBatch implements Database.Batchable<sObject> , Database.Stateful{
    String headerStr = 'Opportunity Id,Error \n';
    global String oppStr = headerStr;
    global Boolean isError = false;
    global String Query = 'SELECT Id, Opportunity__r.Id FROM Brokerage_and_Consultant1__c WHERE lastmodifieddate >: lastRun '
        +'OR Brokerage__r.lastmodifieddate >: lastRun OR Consultant__r.lastmodifieddate >: lastRun OR Consultant__r.Contact__r.lastmodifieddate >: lastRun' 
        +' ORDER By Opportunity__r.Id ASC nulls last ALL RoWS';
    global AccountRoles__c roles = AccountRoles__c.getValues('BrokerageOppReport');//Custom setting that stores the batch last run datetime
    DateTime lastRun = roles.LastRun__c; // Holds the date when this batch was run last time
    DateTime jobStartTime = DateTime.now();
    
    global Database.QueryLocator start(Database.BatchableContext BC){
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Brokerage_and_Consultant1__c> BCList){
        Set<Id> oppIds = new Set<Id>(); // Set that holds unique opportunity IDs
        
        //generate list of unique Opportunity IDs
        for(Brokerage_and_Consultant1__c thisBC : BCList){
            if(thisBC.Opportunity__r.Id != null)
                oppIds.add(thisBC.Opportunity__r.Id);
        }
        Set<Id> finalOppIds = new Set<Id>();
        Set<Id> nonDeletedQLIOppIds = new Set<Id>(); // stores OppIds for which atleast one QLI exists
        Map<String,Set<String>> masterFieldMap = new Map<String,Set<String>>();
        for(Brokerage_and_Consultant1__c thisOpp : [SELECT Id,opportunity__r.IsDeleted, Opportunity__r.Id, Brokerage__c, BrokName__c, Consultant__r.Contact__r.FirstName, Consultant__r.Contact__r.LastName, Consultant__c FROM Brokerage_and_Consultant1__c WHERE Opportunity__r.Id IN: oppIds]){
            nonDeletedQLIOppIds.add(thisOpp.Opportunity__r.Id);
            if(thisOpp.opportunity__r.IsDeleted == false){
                finalOppIds.add(thisOpp.Opportunity__r.Id);
                if (!masterFieldMap.containsKey(thisOpp.Opportunity__r.Id + 'All_Opportunity_Brokerages__c')) {
                    masterFieldMap.put(thisOpp.Opportunity__r.Id + 'All_Opportunity_Brokerages__c', new Set<String>());
                    if(!String.isBlank(thisOpp.Brokerage__c))masterFieldMap.get(thisOpp.Opportunity__r.Id + 'All_Opportunity_Brokerages__c').add(thisOpp.BrokName__c);
                }
                else {
                    if(!String.isBlank(thisOpp.Brokerage__c))
                        masterFieldMap.get(thisOpp.Opportunity__r.Id + 'All_Opportunity_Brokerages__c').add(thisOpp.BrokName__c);
                }
                if (!masterFieldMap.containsKey(thisOpp.Opportunity__r.Id + 'Opportunity_Brokers__c')) {
                    masterFieldMap.put(thisOpp.Opportunity__r.Id + 'Opportunity_Brokers__c', new Set<String>());
                    if(!String.isBlank(thisOpp.Consultant__c))
                    {
                        String fName = (thisOpp.Consultant__r.Contact__r.FirstName != null) ? thisOpp.Consultant__r.Contact__r.FirstName : '';
                        String LName = (thisOpp.Consultant__r.Contact__r.LastName != null) ? thisOpp.Consultant__r.Contact__r.LastName : '';
                        masterFieldMap.get(thisOpp.Opportunity__r.Id + 'Opportunity_Brokers__c').add(fName + ' ' + LName);
                    }
                }
                else {
                    if(!String.isBlank(thisOpp.Consultant__c))
                    {
                        String fName = (thisOpp.Consultant__r.Contact__r.FirstName != null) ? thisOpp.Consultant__r.Contact__r.FirstName : '';
                        String LName = (thisOpp.Consultant__r.Contact__r.LastName != null) ? thisOpp.Consultant__r.Contact__r.LastName : '';
                        masterFieldMap.get(thisOpp.Opportunity__r.Id + 'Opportunity_Brokers__c').add(fName + ' ' + LName);
                    }
                }
            }
        }
        List<opportunity> oppsToBeUpdated = new List<opportunity>();
        List<String> oppFields = new List<String>{'All_Opportunity_Brokerages__c','Opportunity_Brokers__c'};
            for(String thisOppId : finalOppIds){
                Opportunity thisOpp = new Opportunity();
                thisOpp.Id = thisOppId;
                for(String thisField : oppFields){
                    if ((masterFieldMap.get(thisOppId + thisField)) != null && !(masterFieldMap.get(thisOppId + thisField)).isEmpty()) {
                        Set<String> fieldValues = masterFieldMap.get(thisOppId + thisField);
                        fieldValues.remove(' ');
                        List<string> fieldValuesList = new List<String>(fieldValues);
                        fieldValuesList.sort();
                        String str = String.join(fieldValuesList, ';');
                        thisOpp.put(thisField, (str.length() > 255 ? str.substring(0, 254) : str));
                    }else{
                        thisOpp.put(thisField,'');
                    }
                }
                oppsToBeUpdated.add(thisOpp);
            }
        oppIds.removeAll(nonDeletedQLIOppIds);        
        if(oppIds.size() > 0){
            Set<Id> nonDelOpps = new Set<Id>();
            for(Opportunity thisOpp :[SELECT id FROM Opportunity WHERE Id IN: oppIds AND isDeleted = false] ){
                nonDelOpps.add(thisOpp.id);
            }
            if(nonDelOpps.size() > 0)
            for(Id thisOppId : oppIds){
                Opportunity thisOpp = new Opportunity(Id = thisOppId,All_Opportunity_Brokerages__c = '',Opportunity_Brokers__c = '');
                oppsToBeUpdated.add(thisOpp);
            }
        }
        
        if(oppsToBeUpdated.size() > 0){
            Database.SaveResult[] sR =  Database.update(oppsToBeUpdated,false);
            for(Integer i=0;i<oppsToBeUpdated.size();i++){
                If(!sR[i].isSuccess()){isError = true;
                    string errorMsg = '';
                    for(Database.Error error : sR[i].getErrors()){
                        errorMsg += ' ' + error.getMessage();
                    }
                    oppStr += oppsToBeUpdated[i].Id + ',' +  errorMsg + '\n';
                }
            }
        }
    }
    
    global void finish(Database.BatchableContext BC){
        AsyncApexJob batchStatus = [Select Id, NumberOfErrors, Status, ExtendedStatus from AsyncApexJob where Id =:BC.getJobId()];
        if(isError == true || batchStatus.NumberOfErrors > 0){ Messaging.EmailFileAttachment csvAttc = new Messaging.EmailFileAttachment();
            Blob csvBlob = Blob.valueOf(oppStr);string csvname= 'Opportunity Errors.csv';csvAttc.setFileName(csvname);
            csvAttc.setBody(csvBlob);Messaging.SingleEmailMessage email =new Messaging.SingleEmailMessage();String subject ='BrokerageToOppRollUpBatch :'+batchStatus.Status;
            email.setSubject(subject);email.setToAddresses(new list<string>{System.label.Admin_Email});email.setPlainTextBody('BrokerageToOppRollUpBatch has errors in Org - '+ UserInfo.getOrganizationId());
            email.setFileAttachments(new Messaging.EmailFileAttachment[]{csvAttc});Messaging.SendEmailResult [] emailResult = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        }else{
            roles.LastRun__c =jobStartTime;
            update roles;
        }
    }
}