objects/AlternateNetwork__c.object
<CustomObject>
    <fields>
        <fullName>QuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipName>Alternate_Networks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Term Date</label>
        <type>Date</type>
    </fields>
    <label>Advantage Network</label>
    <nameField>
        <displayFormat>AdvNet-{00000}</displayFormat>
        <label>Advantage Network Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Advantage Networks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductSelectionDetail__c.object
<CustomObject>
    <fields>
        <fullName>QuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Product Selection Details</relationshipLabel>
        <relationshipName>Product_Selection_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TermDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Term Date</label>
        <type>Date</type>
    </fields>
    <label>Product Selection Detail</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Selection Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Selection Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>AlternateNetwork__c</fullName>
        <inlineHelpText>If Yes, please complete the Adv Net table</inlineHelpText>
        <label>Advantage Network</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>1GD - AZ Blue PPO</fullName>
                </value>
                <value>
                    <fullName>1GG - CA Select PPO</fullName>
                </value>
                <value>
                    <fullName>1GE - DC/MD/Northern VA BlueChoice</fullName>
                </value>
                <value>
                    <fullName>1GQ - FL NetworkBlue</fullName>
                </value>
                <value>
                    <fullName>1GO - GA Blue Open Access POS </fullName>
                </value>
                <value>
                    <fullName>1GU - GA EPO Alt Net </fullName>
                </value>
                <value>
                    <fullName>1GI - MN Accord </fullName>
                </value>
                <value>
                    <fullName>1GM - MO Blue Preferred POS </fullName>
                </value>
                <value>
                    <fullName>1GR - Preferred- Care Blue PPO (BCBS Kansas City) </fullName>
                </value>
                <value>
                    <fullName>1GN - MO Blue Access Choice </fullName>
                </value>
                <value>
                    <fullName>1GY - NH Bluechoice Open Access POS </fullName>
                </value>
                <value>
                    <fullName>1GS - NJ Horizon Managed Care Network </fullName>
                </value>
                <value>
                    <fullName>1GJ - NY Empire POS </fullName>
                </value>
                <value>
                    <fullName>1GT - TN Network S </fullName>
                </value>
                <value>
                    <fullName>1GP - WI Blue Preferred POS </fullName>
                </value>
                <value>
                    <fullName>1G2 - WI Blue Priority </fullName>
                </value>
                <value>
                    <fullName>1GZ - MN Blue Performance Enhanced </fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HasAHG__c</fullName>
        <formula>Quote.Opportunity.HasAHG__c</formula>
        <label>Has Approved Product Line</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Quote.OpportunityId</formula>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentQuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to self.</description>
        <label>Parent Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0%</fullName>
                </value>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>35%</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>45%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>55%</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>65%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
                <value>
                    <fullName>80%</fullName>
                </value>
                <value>
                    <fullName>85%</fullName>
                </value>
                <value>
                    <fullName>90%</fullName>
                </value>
                <value>
                    <fullName>95%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductLineApprovalStatus__c</fullName>
        <description>This field indicates the approval status of the Product Line. It is applicable for National Accounts only for the Anthem Health Guide and Integrated Health Model products.</description>
        <label>Product Line Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not started</fullName>
                    <default>true</default>
                    <label>Not started</label>
                </value>
                <value>
                    <fullName>Submitted for Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProgramLines__c</fullName>
        <label>ProgramLines</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Advocacy</fullName>
                </value>
                <value>
                    <fullName>Account/Sales Team</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy/Client Went Out of Business</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Product Options</fullName>
                </value>
                <value>
                    <fullName>Billing Issues</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Broker of Record Change</fullName>
                </value>
                <value>
                    <fullName>Cede</fullName>
                </value>
                <value>
                    <fullName>Claim Issues</fullName>
                </value>
                <value>
                    <fullName>Client Withdrew/No Further Inquiry</fullName>
                </value>
                <value>
                    <fullName>Clinical Value</fullName>
                </value>
                <value>
                    <fullName>COVID19</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Digital and Consumer Engagement</fullName>
                </value>
                <value>
                    <fullName>Discount Value</fullName>
                </value>
                <value>
                    <fullName>Does Not Meet Requirements</fullName>
                </value>
                <value>
                    <fullName>Employee Customer Service</fullName>
                </value>
                <value>
                    <fullName>Exchange – Moving To/From</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation/ New Participant</fullName>
                </value>
                <value>
                    <fullName>Fees</fullName>
                </value>
                <value>
                    <fullName>Financial/Discount Value</fullName>
                </value>
                <value>
                    <fullName>Funding Type Change</fullName>
                </value>
                <value>
                    <fullName>Group Number Change</fullName>
                </value>
                <value>
                    <fullName>Guarantees</fullName>
                </value>
                <value>
                    <fullName>Incomplete Data</fullName>
                </value>
                <value>
                    <fullName>Inconvenient to Change Carriers</fullName>
                </value>
                <value>
                    <fullName>IT Security</fullName>
                </value>
                <value>
                    <fullName>Medical Products - CDHP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TECH_OSIsMultiSelect__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Field required to differentiate between a single product select or multiple product select</description>
        <label>TECH_OSIsMultiSelect</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TermDate__c</fullName>
        <description>JT(20140306)The termination date for this Quote Line.</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Enter the Termination Date for this Product IF Terming.</inlineHelpText>
        <label>Term Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ANA_AP06_QLI_Process_ChildCount.cls
/*
@Author : Accenture Offshore Dev team
@name : ANA_AP06_QLI_Process_ChildCount
@CreateDate : 30-05-2017
@Description : This class process the child QuoteLineItems and updates the Program Lines field of QLI.
*/
public with sharing class ANA_AP06_QLI_Process_ChildCount {    
    private Static final string CLASS_NAME = 'ANA_AP06_QLI_Process_ChildCount';
    private Static final string PARENTQUOTELINEITEM = 'ParentQuoteLineItem__c';
    private Static final string CHILDCOUNT = 'childCount';
    private Static final string FIXED = 'Fixed';
    private static final String EMPTY=''; 
    private static final String IHM='Integrated Health Model';
    private static final String AHG='Other-Anthem Health Guide';
    private static final String SFA='Submitted For Approval';
    private static final String APRD='Approved';
    private static final String NSTD='Not started';
    private static final String RJTD='Rejected';
    private Set<Id> qliParentIdSet;
    private Set<Id> parentQliSet;
    private Set<Id> optyIdSet;
    private map<Id,QuoteLineItem> parentProdMap;    
    private map<Id,QuoteLineItem> liUpdateMap;
    private List<AggregateResult> agrrList;
    private List<AggregateResult> countList;
    private List<QuoteLineItem> childList;
    private List<Opportunity> OptyUpdateList;
    private List<ProductSelectionDetail__c> childSelections;
    private List<AlternateNetwork__c> childNetworks;
    private List<PricebookEntry> priceBooks;
    private List<Opportunity> optyList;
    private QuoteLineItem lineItem;
    private set<Id> optyHasAHGSet;
   
    
    private static final String SELECT_QLI_PARENT = 'SELECT count(id) childCount,ParentQuoteLineItem__c FROM \n'+
                                                    'QuoteLineItem WHERE ParentQuoteLineItem__c in :idSet1 \n'+
                                                    'GROUP BY ParentQuoteLineItem__c LIMIT 1000';
    private static final String SELECT_QLI_CHILD = 'SELECT ID FROM QuoteLineItem\n'+
                                                   'WHERE ParentQuoteLineItem__c in :idSet2 LIMIT 1000';
    private static final String SELECT_PRODUCT_CHILD = 'SELECT ID FROM ProductSelectionDetail__c\n'+
                                                       'WHERE QuoteLineItem__c in :idSet3 LIMIT 1000';                                             
    private static final String SELECT_NETWORK_CHILD = 'SELECT ID FROM AlternateNetwork__c\n'+
                                                        'WHERE QuoteLineItem__c in :idSet4 LIMIT 1000';
    private static final String SELECT_CHILD_PRODUCT = 'SELECT vlocity_ins__ChildProductId__c,vlocity_ins__ParentProductId__c\n'+
                                                        'FROM vlocity_ins__ProductChildItem__c\n'+
                                                        'WHERE vlocity_ins__ParentProductId__c in :idSet5 LIMIT 1000';
    private static final String SELECT_PRICE_BOOKID = 'SELECT ID,Product2Id FROM PricebookEntry\n'+
                                                   'WHERE Product2Id in :idSet5 LIMIT 1000';
    private static final String SELECT_PRODUCTS = 'select id,Bundle__c from Product2\n'+
                                                  'where id In:idSet6 LIMIT 1000';   
    private static final String SELECT_AHGPRODS_COUNT='SELECT OpportunityId__c,HasAHG__c FROM QuoteLineItem WHERE \n'+
                                                '(Product2.Name=:AHG OR Product2.Name=:IHM)\n'+
                                                ' AND (ProductLineApprovalStatus__c=:SFA OR ProductLineApprovalStatus__c=:APRD) AND Quote.OpportunityId in :optyIdSet2';
                                                
   
    /**************************************************************************************************/
    /*This method is used to capture parent QLI and process the count of child QLI for each parent QLI.*/
    public void processChildCount (List<QuoteLineItem> newList,map<Id,QuoteLineItem> oldMap,List<QuoteLineItem> oldList,string triggerName){          
        qliParentIdSet = new Set<Id>();
        liUpdateMap = new map<Id,QuoteLineItem>();        
        try{
            /*create*/
            if((oldList == null) && (oldMap == null)){
                for(QuoteLineItem newQLI:newList){
                        if((newQLI.ParentQuoteLineItem__c != null)){
                        qliParentIdSet.add(newQLI.ParentQuoteLineItem__c);
                            
                    }
                }
            }
            /*delete*/
            else if((newlist == null)){
                for(QuoteLineItem oldQLI:oldList){
                    if((oldQLI.ParentQuoteLineItem__c != null)){                
                        qliParentIdSet.add(oldQLI.ParentQuoteLineItem__c);
                    }
                }
            }
            /*update*/
            else{
               for(QuoteLineItem newQLI:newList){
                        if(newQLI.ParentQuoteLineItem__c != null ){                     
                        qliParentIdSet.add(newQLI.ParentQuoteLineItem__c);
                    }
                }
            }          
            if(!qliParentIdSet.isEmpty()){
                persistLineItems();
            }
            
        }       
        catch(Exception excp){
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
        }
    }
    /**************************************************************************************************/
    /*This method captures all the deleted parent QLI's.*/
    public void deleteChildQLI(List<QuoteLineItem> newList,map<Id,QuoteLineItem> oldMap,List<QuoteLineItem> oldList,string triggerName){
        parentQliSet = new Set<Id>();
        try{
        /*delete*/
           if((newlist == null)){
                for(QuoteLineItem oldQLI:oldList){
                    if((oldQLI.ParentQuoteLineItem__c == null)){                
                        parentQliSet.add(oldQLI.Id);
                    }
                }
            }
            
            if(!parentQliSet.isEmpty()){
                deleteLineItems();
                deleteProductSelections();
                deleteAlternateNetworks();
            }
          }
        catch(Exception excp){
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
        }
    }
    /**************************************************************************************************/
    /*This method is used to capture parent QLI and process the count of child QLI for each parent QLI.*/
    public void insertChildQLI(List<QuoteLineItem> newList,map<Id,QuoteLineItem> oldMap,List<QuoteLineItem> oldList,string triggerName){
        parentProdMap = new map<Id,QuoteLineItem>();
        set<id> setqliids=new set<Id>();
        map<id,Product2> mapprod = new map<id,Product2>();
        try{
        /*Create*/
          if((oldList == null) && (oldMap == null)){
             for(QuoteLineItem newQLI:newList){
                 setqliids.add(newQLI.Product2id);
             }
             if(!setqliids.isEmpty()){
                 ANA_UTIL07_AccessProductDataUtil.idSet6 = setqliids;
                 for(product2 pid:ANA_UTIL07_AccessProductDataUtil.queryProds(SELECT_PRODUCTS)){
                     mapprod.put(pid.id,pid);
                 }
             }
              for(QuoteLineItem newQLI:newList){
                  if(newQLI.TECH_OSIsMultiSelect__c && (String.isBlank(newQLI.ParentQuoteLineItem__c)) && !mapprod.isEmpty() && mapprod.containskey(newQLI.Product2id) && FIXED.equalsIgnoreCase(mapprod.get(newQLI.Product2id).Bundle__c)){
                         parentProdMap.put(newQLI.Product2Id,newQLI);
                  }
              }
          }
         if(!parentProdMap.isEmpty()){
              insertLineItems();
           }
        }
       catch(Exception excp){
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
      }
    }
    /**************************************************************************************************/
    /*This method updates the ProgamLines__c field of parent QLI with the count of its child.*/
    private void persistLineItems(){        
        ANA_UTIL02_AccessQLIDataUtil.idSet1 = qliParentIdSet;
        agrrList = ANA_UTIL02_AccessQLIDataUtil.callAggregateQuery(SELECT_QLI_PARENT);     
        for(AggregateResult result :agrrList){
            lineItem = new QuoteLineItem(Id=(Id)result.get(PARENTQUOTELINEITEM));
            lineItem.ProgramLines__c = (Integer)result.get(CHILDCOUNT);
            liUpdateMap.put(lineItem.Id,lineItem);
        }
           if(liUpdateMap.size() < qliParentIdSet.size()){
            for(Id pId: qliParentIdSet){
                if(liUpdateMap.get(pId) == null){
                    lineItem = new QuoteLineItem(Id = pId);
                    lineItem.ProgramLines__c = 0;
                    liUpdateMap.put(lineItem.Id,lineItem);
                }         
            }
        }        
        if(!liUpdateMap.isEmpty()) {
            ANA_UTIL02_AccessQLIDataUtil.updateQuoteLineItems(liUpdateMap.values());
        }
    }
    /**************************************************************************************************/
    /*This method deletes the child QLI's for which parent QLI's are deleted.*/ 
         private void deleteLineItems(){
             ANA_UTIL02_AccessQLIDataUtil.idSet2 = parentQliSet;
             childList = ANA_UTIL02_AccessQLIDataUtil.queryQuoteLineItems(SELECT_QLI_CHILD);             
              if(!childList.isEmpty()){                
              ANA_UTIL02_AccessQLIDataUtil.deleteQuoteLineItems(childList);
                        } 
         }
         /**************************************************************************************************/
    /*This method deletes the child Product Selections records for which parent QLI's are deleted.*/ 
         private void deleteProductSelections(){
             ANA_UTIL10_AccessProductSelectionUtil.idSet3 = parentQliSet;
             childSelections = ANA_UTIL10_AccessProductSelectionUtil.queryProductSelections(SELECT_PRODUCT_CHILD);  
              if(!childSelections.isEmpty()){                
              ANA_UTIL10_AccessProductSelectionUtil.deleteSelections(childSelections);
                        } 
         }
    /**************************************************************************************************/
    /*This method deletes the child Alternate Network records for which parent QLI's are deleted.*/      
         private void deleteAlternateNetworks(){
             ANA_UTIL11_AccessAlternateNetworkUtil.idSet4 = parentQliSet;
             childNetworks = ANA_UTIL11_AccessAlternateNetworkUtil.queryAlternateNetworks(SELECT_NETWORK_CHILD);  
              if(!childNetworks.isEmpty()){                
              ANA_UTIL11_AccessAlternateNetworkUtil.deleteNetworks(childNetworks);
                        } 
         }
    /**************************************************************************************************/
    /*This method inserts the child QuoteLineItem records for which parent QLI's are updated with TECH_OSIsMultiSelect field.*/  
     private void insertLineItems(){
        map<Id,List<Id>> parentChildPrdMap = new map<Id,List<Id>>();
        QuoteLineItem qli;
        List<QuoteLineItem> childProdList = new List<QuoteLineItem>();
        set<Id> childProdSet = new set<Id>();
        
        ANA_UTIL07_AccessProductDataUtil.idSet5 = parentProdMap.keyset();
        for(vlocity_ins__ProductChildItem__c pci: ANA_UTIL07_AccessProductDataUtil.queryProdItems(SELECT_CHILD_PRODUCT)){
            if(!parentChildPrdMap.containsKey(pci.vlocity_ins__ParentProductId__c)){
                parentChildPrdMap.put(pci.vlocity_ins__ParentProductId__c,new List<Id>{pci.vlocity_ins__ChildProductId__c});
                childProdSet.add(pci.vlocity_ins__ChildProductId__c);
            }               
            else{
                parentChildPrdMap.get(pci.vlocity_ins__ParentProductId__c).add(pci.vlocity_ins__ChildProductId__c);
                childProdSet.add(pci.vlocity_ins__ChildProductId__c);
            }               
        }       
        if(!childProdSet.isEmpty()){
            ANA_UTIL07_AccessProductDataUtil.idSet5 = childProdSet;
            map<Id,Id> prdPriceBookMap = ANA_UTIL07_AccessProductDataUtil.queryPriceBookEntry(SELECT_PRICE_BOOKID);
            for(Id ParentPrdId:parentChildPrdMap.keyset()){
                for(Id childPrdId:parentChildPrdMap.get(ParentPrdId)){
                    qli = new QuoteLineItem();
                    qli.PricebookEntryId = prdPriceBookMap.get(childPrdId);
                    qli.Product2Id = childPrdId;
                    qli.ParentQuoteLineItem__c = parentProdMap.get(ParentPrdId).Id;
                    qli.QuoteId = parentProdMap.get(ParentPrdId).QuoteId;
                    qli.ProductStage__c = parentProdMap.get(ParentPrdId).ProductStage__c;
                    qli.Reason__c = parentProdMap.get(ParentPrdId).Reason__c;
                    qli.Probability__c = parentProdMap.get(ParentPrdId).Probability__c;
                    qli.TermDate__c = parentProdMap.get(ParentPrdId).TermDate__c;
                    qli.OppType__c = parentProdMap.get(ParentPrdId).OppType__c;
                    qli.Quantity = parentProdMap.get(ParentPrdId).Quantity;
                    qli.UnitPrice = parentProdMap.get(ParentPrdId).UnitPrice;
                    childProdList.add(qli);
                }
                
            }
        }
        
    if(!childProdList.isEmpty()){
        ANA_UTIL02_AccessQLIDataUtil.insertQuoteLineItems(childProdList);  
    }            
  }
  
  /**************************************************************************************************/
    /*This method updates flag on Opportunity for AHG and IHM products when qli is deleted.*/
    public void updateFlagForDelete (List<QuoteLineItem> oldQliLst,string triggerName){
        optyIdSet=new Set<Id>();        
        optyHasAHGSet = new set<Id>();
        childList = new List<QuoteLineItem>();
        OptyUpdateList=new List<Opportunity>();
        try{
            for(QuoteLineItem oldQli:oldQliLst){
                if((AHG.equalsIgnoreCase(oldQli.ProductName__c) || IHM.equalsIgnoreCase(oldQli.ProductName__c)) && 
                  (SFA.equalsIgnoreCase(oldQli.ProductLineApprovalStatus__c) || APRD.equalsIgnoreCase(oldQli.ProductLineApprovalStatus__c))){
                    optyIdSet.add(oldQli.OpportunityId__c);
                  }
            }                
            if(!optyIdSet.isEmpty()){                    
                getOptysToUpdate();                                       
                if(!OptyUpdateList.isEmpty()){
                    database.update(OptyUpdateList);
                }
            }
        }
        catch(Exception excp){
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
      }
    }
    
  /************************************************************************************************************/    
  /*This method updates flag on Opportunity for AHG and IHM products*/
   public void updateFlagOnOpty(List<QuoteLineItem> newQliLst,string triggerName){    
        optyIdSet=new Set<Id>();        
        optyHasAHGSet = new set<Id>();
        childList = new List<QuoteLineItem>();
        OptyUpdateList=new List<Opportunity>();
        try{ 
            optyUpdateList=new List<Opportunity>();            
            for(QuoteLineItem newQli:newQliLst){
                if((AHG.equalsIgnoreCase(newQli.ProductName__c) || IHM.equalsIgnoreCase(newQli.ProductName__c)) && 
                (SFA.equalsIgnoreCase(newQli.ProductLineApprovalStatus__c) || APRD.equalsIgnoreCase(newQli.ProductLineApprovalStatus__c)) && (!newQli.HasAHG__c)){ 
                    OptyUpdateList.add(new Opportunity(Id=newQli.OpportunityId__c,HasAHG__c=true)); 
                }
                else if ((AHG.equalsIgnoreCase(newQli.ProductName__c) || IHM.equalsIgnoreCase(newQli.ProductName__c)) && 
                (NSTD.equalsIgnoreCase(newQli.ProductLineApprovalStatus__c) || RJTD.equalsIgnoreCase(newQli.ProductLineApprovalStatus__c))){                                 
                    optyIdSet.add(newQli.OpportunityId__c);
                }
            }            
            if(!optyIdSet.isEmpty()){
                    getOptysToUpdate();
            }
            if(!OptyUpdateList.isEmpty()){
                database.update(OptyUpdateList);
            }
        }
        catch(Exception excp){
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
        }
    }

    /************************************************************************************************************/
    /*This is a Helper method to update flag on Opportunity for AHG and IHM products*/
    public void getOptysToUpdate(){
        ANA_UTIL02_AccessQLIDataUtil.optyIdSet2=optyIdSet;
        ANA_UTIL02_AccessQLIDataUtil.AHG=AHG;
        ANA_UTIL02_AccessQLIDataUtil.IHM=IHM;
        ANA_UTIL02_AccessQLIDataUtil.SFA=SFA;
        ANA_UTIL02_AccessQLIDataUtil.APRD=APRD;     
        childList=ANA_UTIL02_AccessQLIDataUtil.queryQuoteLineItems(SELECT_AHGPRODS_COUNT);                    
        for(QuoteLineItem qliRec: childList){
            optyHasAHGSet.add(qliRec.OpportunityId__c);
        }                                      
        for(Id optyId: optyIdSet){                      
            if(!optyHasAHGSet.contains(optyId)){
                OptyUpdateList.add(new Opportunity(Id=optyId,HasAHG__c=false));                         
            }                
        }       
    }   
    
    /**************************************************************************************************/
    /*This method captures all the deleted ActWise Companion for HRA/HSA */
    public void deleteQLIActwiseCompanionProduct(List<QuoteLineItem> newList,map<Id,QuoteLineItem> oldMap,List<QuoteLineItem> oldList,string triggerName){
        /*System.debug('--- deleteQLIActwiseCompanionProduct oldMap='+oldMap);
        try {
            if(oldMap != null && oldMap.size() > 0) {
                Set<Id> quoteIdSet = new Set<Id>();
                for(QuoteLineItem qli:oldMap.values()) {
                    quoteIdSet.add(qli.QuoteId);
                } 
             delete [Select Id From QuoteLineItem where QuoteId in :quoteIdSet And (ActWise_ParentQuoteLineItem__r.ParentQuoteLineItem__c in :oldMap.keySet() OR ActWise_ParentQuoteLineItem__c in :oldMap.keySet()) And ActWiseChildQuote__c = null];
            //delete [Select Id From QuoteLineItem where QuoteId in :quoteIdSet And (ActWise_ParentQuoteLineItem__r.ActWiseChildQuote__c in :oldMap.keySet() OR ActWise_ParentQuoteLineItem__c in :oldMap.keySet()) And ActWiseChildQuote__c = null];
             }
            
        } catch(Exception excp){
            System.debug('--- deleteQLIActwiseCompanionProduct Exception'+excp);
            
            UTIL_LoggingService.logHandledException(excp, ANA_UTIL03_Constants.ORGID, ANA_UTIL03_Constants.APPNAME, 
            CLASS_NAME, ANA_UTIL03_Constants.CANCEL,triggerName,LoggingLevel.ERROR);
        }*/ 
        //commented this method for 43998
        
    }    
}