objects/Application_Document_Config__c.object
<CustomObject>
    <fields>
        <fullName>Additional_Checks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Additional Checks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ERISA_Qualified__c</fullName>
        <label>ERISA Qualified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ERISA</fullName>
                </value>
                <value>
                    <fullName>Non-ERISA</fullName>
                </value>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_Of_Business__c</fullName>
        <label>Product Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ABA</fullName>
                </value>
                <value>
                    <fullName>Accident</fullName>
                </value>
                <value>
                    <fullName>AIM</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin</fullName>
                </value>
                <value>
                    <fullName>Commercial Act Wise</fullName>
                </value>
                <value>
                    <fullName>Commercial AIM</fullName>
                </value>
                <value>
                    <fullName>Commercial Blue Distinction</fullName>
                </value>
                <value>
                    <fullName>Commercial Buy-Ups</fullName>
                </value>
                <value>
                    <fullName>Commercial Clinical</fullName>
                </value>
                <value>
                    <fullName>Commercial Engage</fullName>
                </value>
                <value>
                    <fullName>Commercial Subrogation</fullName>
                </value>
                <value>
                    <fullName>CONEXIS</fullName>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disability</fullName>
                </value>
                <value>
                    <fullName>EAP</fullName>
                </value>
                <value>
                    <fullName>Expatriate</fullName>
                </value>
                <value>
                    <fullName>FSA</fullName>
                    <label>FSA (Non-ActWise)</label>
                </value>
                <value>
                    <fullName>Group Companion</fullName>
                </value>
                <value>
                    <fullName>Health and Wellness</fullName>
                </value>
                <value>
                    <fullName>Hospital Indemnity</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Medicare</fullName>
                </value>
                <value>
                    <fullName>Network based</fullName>
                </value>
                <value>
                    <fullName>Non-Blue Health and Wellness</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Category__c</fullName>
        <label>Product Category</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Product</fullName>
                </value>
                <value>
                    <fullName>Plan</fullName>
                    <isActive>false</isActive>
                    <label>Plan</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Stage__c</fullName>
        <label>Product Stage</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Document Config</label>
    <nameField>
        <displayFormat>DC-{0}</displayFormat>
        <label>Document Config Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents Config</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Line_of_Business__c</fullName>
        <label>Line of Business1</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Involvement_Type__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Aggregate Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disability</fullName>
                </value>
                <value>
                    <fullName>Disease Management</fullName>
                </value>
                <value>
                    <fullName>EAP</fullName>
                </value>
                <value>
                    <fullName>FSA</fullName>
                </value>
                <value>
                    <fullName>Group Retiree</fullName>
                </value>
                <value>
                    <fullName>Group Retiree Solutions (GRS)</fullName>
                </value>
                <value>
                    <fullName>Labor</fullName>
                </value>
                <value>
                    <fullName>Life</fullName>
                </value>
                <value>
                    <fullName>LTD</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Medical Management</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>Spec/Agg Stop Loss</fullName>
                </value>
                <value>
                    <fullName>Specialty</fullName>
                </value>
                <value>
                    <fullName>Specific Stop Loss</fullName>
                </value>
                <value>
                    <fullName>STD</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Voluntary Disability</fullName>
                </value>
                <value>
                    <fullName>Voluntary Life</fullName>
                </value>
                <value>
                    <fullName>Worksite Wellness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <formula>TEXT(Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LGA_CreateDCChecks.cls
/***********************************************************************
@class Name   : LGA_CreateDCChecks
@date Created : 08/19/2019 (MM/DD/YYYY)
@created By   : Accenture Offshore
@description  : This class is used called from LGA_CreateDocumentChecklist
@change History : 08/27/2019 (As a Part of PRDCRM-41239, PRDCRM-40178, PRDCRM-41195, PRDCRM-41197, PRDCRM-40609, PRDCRM-41841 & PRDCRM-40610 )
**************************************************************************/
public with sharing class LGA_CreateDCChecks {
    
    /****************************************************************************************************
@method Name : createDocumentsforImplCase
@description : checkLOB This method checks the criteria for LOB.
@param : This method accepts Application_Document_Config__c & List of QuoteLineItem as parameters.
@return : This method returns a Boolean Values.
******************************************************************************************************/
    public Boolean checkLOB(Application_Document_Config__c docConfig, List<QuoteLineItem> qliList){
        Boolean checkLOB = LGA_Constants.CHECKLOB;
        Try{
            List<String> docConfigLOBList = new List<String>();
            if(String.isNotBlank(docConfig.Line_Of_Business__c)){
                for(String lob: docConfig.Line_Of_Business__c.split(';')){
                    docConfigLOBList.add(lob.toLowerCase());
                }
            }
            if(!docConfigLOBList.isEmpty() && String.isNotBlank(docConfig.Product_Category__c) 
               && String.isNotBlank(docConfig.Product_Stage__c) ){ 
                   for(QuoteLineItem qli: qliList){
                       system.debug('@@@condition55555' + docConfigLOBList.contains(qli.Product2.Product_Type__c.toLowerCase()));
                       if((String.isNotBlank(qli.ProductStage__c)) 
                          && (String.isNotBlank(qli.ProductCategory__c))
                          && qli.ProductCategory__c == docConfig.Product_Category__c 
                          && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                          && docConfigLOBList.contains(qli.Product2.Product_Type__c.toLowerCase())){
                              checkLOB=true;
                          }
                   }
               } 
           
        }
        Catch(Exception ex){
            System.debug('****The following exception has occurred: '+ex.getMessage());
        }
        return checkLOB;
    }
    
    /****************************************************************************************************
@method Name : additionalChecks
@description : checkLOB This method checks Other Criteria for Document Check List Creation.
@param : This method accepts Application_Document_Config__c & List of QuoteLineItem as parameters.
@return : This method returns a Boolean Values.
******************************************************************************************************/    
    public Boolean additionalChecks(Application_Document_Config__c docConfig, List<QuoteLineItem> qliList, Order ord){
        Boolean additionalCheck = LGA_Constants.CHECKLOB;
        Try{
            if (docConfig.Additional_Checks__c){
                if(String.isNotBlank(docConfig.ERISA_Qualified__c) 
                   && (docConfig.ERISA_Qualified__c == ord.Account.Is_this_Group_subject_to_ERISA__c)){
                       for(QuoteLineItem qli: qliList){
                           if((String.isNotBlank(qli.ProductStage__c)) 
                              && (String.isNotBlank(qli.ProductCategory__c))
                              && qli.ProductCategory__c == docConfig.Product_Category__c 
                              && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                             ){
                                 additionalCheck = True;
                             }
                       }
                       
                   }
                else if(String.isNotBlank(docConfig.Funding__c) && String.isBlank(docConfig.Financing__c) ){  //
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                           && qli.ProductCategory__c == docConfig.Product_Category__c){
                               if(docConfig.Funding__c == qli.Funding__c){ 
                                   additionalCheck = True;
                               }  
                           }
                    }
                }
                else if(String.isNotBlank(docConfig.Product_Family__c) && String.isBlank(docConfig.Financing__c) ){ //
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c ))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                               if(docConfig.Product_Family__c == qli.Product2.Product_Family__c ){
                                   additionalCheck = True;
                               }  
                           }
                    }
                }
                else if(String.isNotBlank(docConfig.Pooled_Non_Pooled__c)){
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                               if(docConfig.Pooled_Non_Pooled__c == ord.Account.Pooled_Non_Pooled__c ){
                                   additionalCheck = True;
                               }  
                           }
                    }
                } 
                else if(String.isNotBlank(docConfig.CEP_Indicator__c)){
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                               if(docConfig.CEP_Indicator__c == qli.CEP_Indicator__c ){
                                   additionalCheck = True;
                               }  
                           }
                    }
                }  
                else if(docConfig.Employee_Assistance_Program__c){
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                               if(docConfig.Employee_Assistance_Program__c == ord.Quote.Employee_Assistance_Program__c){
                                   additionalCheck = True;
                               }  
                           }
                    }
                }
                else if(String.isNotBlank(docConfig.Product_Name__c)){
                    List<String> prdNames = New List<String>();
                    if(docConfig.Product_Name__c.indexOf(',') > 0){
                        for(String str : docConfig.Product_Name__c.split(',')){
                            prdNames.add(str);
                        }
                    } else{
                        prdNames.add(docConfig.Product_Name__c); 
                    }
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                               for(String str : prdNames){
                                   if(qli.product2.Name.Contains(str)){
                                       additionalCheck = True;
                                   }
                               }
                               
                           }
                    }
                }
                else if( String.isNotBlank(docConfig.Financing__c) && String.isBlank(docConfig.Funding__c) 
                        && String.isBlank(docConfig.Product_Family__c) ){ //
                            for(QuoteLineItem qli: qliList){
                                if((String.isNotBlank(qli.ProductStage__c)) 
                                   && (String.isNotBlank(qli.ProductCategory__c))
                                   && qli.ProductCategory__c == docConfig.Product_Category__c 
                                   && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                                   && docConfig.Financing__c.contains(qli.Financing__c) 
                                  ){
                                       additionalCheck = True; 
                                   }
                            }
                        } 
                else if( String.isNotBlank(docConfig.Financing__c) && String.isNotBlank(docConfig.Product_Family__c) ){ //
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                           && docConfig.Financing__c.contains(qli.Financing__c) 
                           && docConfig.Product_Family__c == qli.Product2.Product_Family__c ){
                               additionalCheck = True; 
                           }
                    }
                } 
                else if(String.isNotBlank(docConfig.Financing__c) && String.isNotBlank(docConfig.Funding__c) ){ // 
                    for(QuoteLineItem qli: qliList){
                        if((String.isNotBlank(qli.ProductStage__c)) 
                           && (String.isNotBlank(qli.ProductCategory__c))
                           && qli.ProductCategory__c == docConfig.Product_Category__c 
                           && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                           && docConfig.Financing__c.contains(qli.Financing__c) 
                           && docConfig.Funding__c == qli.Funding__c ){
                               additionalCheck = True; 
                           }
                    }
                } 
            }
        }
        Catch(Exception ex){
            System.debug('****The following exception has occurred: '+ex.getMessage());
        }
        return additionalCheck;
    }
    
    
    /****************************************************************************************************
@method Name : dcNameExtension
@description : checkLOB This method checks Other Criteria for Document Check List Creation.
@param : This method accepts Application_Document_Config__c & List of QuoteLineItem as parameters.
@return : This method returns a Boolean Values.
******************************************************************************************************/    
    public List<String> dcNameExtension(Application_Document_Config__c docConfig, List<QuoteLineItem> qliList, Order ord){
        List<String> dcNameExtension = new List<String>();
        Try{
            if ((docConfig.Files_Parameter__c == LGA_Constants.LOB) 
                && (String.isNotBlank(docConfig.Line_Of_Business__c))){
                    List<String> docConfigLOBList = new List<String>();
                    for(String lob: docConfig.Line_Of_Business__c.split(';')){
                        docConfigLOBList.add(lob.toLowerCase());
                    }
                    if(!docConfigLOBList.isEmpty() && String.isNotBlank(docConfig.Product_Category__c) 
                       && String.isNotBlank(docConfig.Product_Stage__c)){
                           for(QuoteLineItem qli: qliList){
                              if((String.isNotBlank(qli.ProductStage__c)) 
                                  && (String.isNotBlank(qli.ProductCategory__c))
                                  && qli.ProductCategory__c == docConfig.Product_Category__c 
                                  && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                                  && docConfigLOBList.contains(qli.Product2.Product_Type__c.toLowerCase()) ) {
                                      dcNameExtension.add(qli.Product2.Product_Type__c.toUpperCase()) ;                              
                                  }
                           }
                       }
                }
            else if(docConfig.Files_Parameter__c == LGA_Constants.QLI  && String.isNotBlank(docConfig.Line_Of_Business__c)){
               List<String> docConfigLOBList = new List<String>();
                for(String dcLOB: docConfig.Line_Of_Business__c.split(';')){
                    docConfigLOBList.add(dcLOB.toLowerCase());
                }
                if(!docConfigLOBList.isEmpty() && String.isNotBlank(docConfig.Product_Category__c) 
                   && String.isNotBlank(docConfig.Product_Stage__c)){
                       for(QuoteLineItem qli: qliList){
                          
                           if((String.isNotBlank(qli.ProductStage__c)) 
                              && (String.isNotBlank(qli.ProductCategory__c))
                              && qli.ProductCategory__c == docConfig.Product_Category__c 
                              && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                              && docConfigLOBList.contains(qli.Product2.Product_Type__c.toLowerCase()) ) {
                                  if(qli.Product2.Name != Null ){
                                      dcNameExtension.add(qli.Product2.Name.toUpperCase()) ;
                                  }
                                  else if(qli.Product2.Name == Null ){
                                      dcNameExtension.add(' ') ;  
                                  }
                              }
                       }
                   }
            }
            else if(docConfig.Files_Parameter__c == LGA_Constants.QLI && String.isBlank(docConfig.Line_Of_Business__c)){
                for(QuoteLineItem qli: qliList){

                    if((String.isNotBlank(qli.ProductStage__c)) 
                       && (String.isNotBlank(qli.ProductCategory__c))
                       && qli.ProductCategory__c == docConfig.Product_Category__c 
                       && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                      ){
                          dcNameExtension.add(qli.Product2.Name.toUpperCase());
                      }
                }
            }
        }
        Catch(Exception ex){
            System.debug('****The following exception has occurred: '+ex.getMessage());
        }
        return dcNameExtension;
    }
    
    
    /****************************************************************************************************
@method Name : checkNoOfDC
@description : checkNoOfDC This method gives the # of Document Checklist to be created for the  Implementation Case.
@param : This method accepts Application_Document_Config__c, Boolean & List of QuoteLineItem as parameters.
@return : This method returns a Integer.
******************************************************************************************************/
    public Integer checkNoOfDC(Application_Document_Config__c docConfig, Boolean checkLOB,List<QuoteLineItem> qliList){
        Integer counter = LGA_Constants.COUNTER ;
        Try{
            
            if(String.isNotBlank(docConfig.Files_Parameter__c)){
                if(checkLOB){
                    if(docConfig.Files_Parameter__c == LGA_Constants.ICR){
                        counter = 1;
                    }
                    
                    // Modified the code as a part of (PRDCRM-41239, PRDCRM-40178, PRDCRM-41195, PRDCRM-41197, PRDCRM-40609, PRDCRM-41841 & PRDCRM-40610)
                    else if(docConfig.Files_Parameter__c == LGA_Constants.LOB && String.isNotBlank(docConfig.Line_Of_Business__c)){
                        //for each LOB 
                        List<String> docConfigLOBList = new List<String>();
                        Map<String,List<QuoteLineItem>> qliLOBMap = new Map<String,List<QuoteLineItem>>();
                        List<QuoteLineItem> qliList2;
                        if(String.isNotBlank(docConfig.Line_Of_Business__c)){
                            for(String dcLOB: docConfig.Line_Of_Business__c.split(';')){
                                docConfigLOBList.add(dcLOB.toLowerCase());
                            }
                        }
                        for(QuoteLineItem qli: qliList){
                            if(qliLOBMap.containskey(qli.Product2.Product_Type__c.toLowerCase())){
                                qliLOBMap.get(qli.Product2.Product_Type__c.toLowerCase()).add(qli);
                            }
                            else{
                                //List<QuoteLineItem> qliList2 = new List<QuoteLineItem>();
                                qliList2 = new List<QuoteLineItem>();
                                qliList2.add(qli);
                                qliLOBMap.put(qli.Product2.Product_Type__c.toLowerCase(),qliList2);
                            }
                        }
                        
                        if(!docConfigLOBList.isEmpty() && String.isNotBlank(docConfig.Product_Category__c) 
                           && String.isNotBlank(docConfig.Product_Stage__c)){
                               for(String lobString: docConfigLOBList){
                                   if(qliLOBMap.KeySet().contains(lobString) && !qliLOBMap.get(lobString).isEmpty()){
                                       Boolean increaseCount = False;
                                       for(QuoteLineItem qliRec : qliLOBMap.get(lobString)){
                                           if((String.isNotBlank(qliRec.ProductStage__c)) 
                                              && (qliRec.ProductCategory__c != Null || qliRec.ProductCategory__c != '')
                                              && qliRec.ProductCategory__c == docConfig.Product_Category__c 
                                              // && qliRec.ProductStage__c == docConfig.Product_Stage__c
                                              && docConfigLOBList.contains(qliRec.Product2.Product_Type__c.toLowerCase())){
                                                  increaseCount = True;
                                              }
                                       }
                                       If(increaseCount){
                                           counter++ ;
                                       }
                                       
                                   }
                               }
                               
                           }
                        //counter = Integer.valueOf(docConfig.Expected_No_of_Files__c)*counter;
                        counter = 1*counter;
                        system.debug('@@@counter2' + counter);               
                    }
                    
                    // Modified the code as a part of (PRDCRM-41239, PRDCRM-40178, PRDCRM-41195, PRDCRM-41197, PRDCRM-40609, PRDCRM-41841 & PRDCRM-40610) 
                    //Try OR Product Or QLI
                    else if(docConfig.Files_Parameter__c == LGA_Constants.QLI && String.isNotBlank(docConfig.Line_Of_Business__c)){
                        //will be updated once we get the requirements
                        List<String> docConfigLOBList = new List<String>();
                        //if(String.isNotBlank(docConfig.Line_Of_Business__c)){
                        for(String dcLOB: docConfig.Line_Of_Business__c.split(';')){
                            docConfigLOBList.add(dcLOB.toLowerCase());
                        }
                        //}
                        if(!docConfigLOBList.isEmpty() && String.isNotBlank(docConfig.Product_Category__c) 
                           && docConfig.Product_Stage__c != Null){
                               for(QuoteLineItem qli: qliList){
                                   if((String.isNotBlank(qli.ProductStage__c)) 
                                      && (String.isNotBlank(qli.ProductCategory__c))
                                      && qli.ProductCategory__c == docConfig.Product_Category__c 
                                      && docConfig.Product_Stage__c.contains(qli.ProductStage__c )
                                      && docConfigLOBList.contains(qli.Product2.Product_Type__c.toLowerCase())){
                                          counter++ ;
                                      }
                               }
                           }
                        counter = 1*counter;
                        system.debug('@@@counter3' + counter);   
                    }
                    
                    // Modified the code as a part of (PRDCRM-41239, PRDCRM-40178, PRDCRM-41195, PRDCRM-41197, PRDCRM-40609, PRDCRM-41841 & PRDCRM-40610)
                    else if(docConfig.Files_Parameter__c == LGA_Constants.QLI && String.isBlank(docConfig.Line_Of_Business__c)){
                        //will be updated once we get the requirements
                        
                        for(QuoteLineItem qli: qliList){
                            if((String.isNotBlank(qli.ProductStage__c)) 
                               && (String.isNotBlank(qli.ProductCategory__c) )
                               && qli.ProductCategory__c == docConfig.Product_Category__c 
                               && docConfig.Product_Stage__c.contains(qli.ProductStage__c )){
                                   counter++ ;
                               }
                        }
                        //counter = Integer.valueOf(docConfig.Expected_No_of_Files__c)*counter;
                        counter = 1*counter;
                    }
                    
                }
            }
          
        }
        Catch(Exception ex){
            System.debug('****The following exception has occurred: '+ex.getMessage());
        }
        return counter;
    }
    
}