objects/Benefit__c.object
<CustomObject>
    <fields>
        <fullName>Competitor_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Competitor Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Benefits</relationshipLabel>
        <relationshipName>Benefits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Benefit</label>
    <nameField>
        <displayFormat>B-{0000}</displayFormat>
        <label>Benefit Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Benefits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Benefit_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Benefit_Api_Name__c</fullName>
        <label>Benefit Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Datatype__c</fullName>
        <label>Benefit Datatype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Benefit_Recordtype__c</fullName>
        <label>Benefit Recordtype</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Section_Name__c</fullName>
        <label>Section Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Benefit Setting</label>
    <pluralLabel>Benefit Settings</pluralLabel>
</CustomObject>

objects/ExceptionLog__c.object
<CustomObject>
    <description>To track all exceptions occuring</description>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCP - {0000}</displayFormat>
        <label>Exception Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vision_Benefit_Creation__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to enable/disable vision benefit functionality</description>
    <fields>
        <fullName>Allow_Vision_Benefit_Creation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow Vision Benefit Creation</label>
        <type>Checkbox</type>
    </fields>
    <label>Vision Benefit Creation</label>
</CustomObject>

classes/LGCompetitorBenefitDetails.cls
/*
*******************************************************************************************
* Name:          LGCompetitorBenefitDetails
* Author:        Deloitte offshore
* ModifiedBy:    Deloitte offshore
* CreatedDate:   02/24/2020
* Used By:       
*******************************************************************************************
* Description:Wrapper Class for forming the wrapper data and metadata as wrapperlist

*******************************************************************************************
* Changes By:Deloitte Offshore
* Date:02/26/2020
*******************************************************************************************
*/
public with sharing class LGCompetitorBenefitDetails {
    /*
_________________________________________________________________________________________

*@description: This method will be used to get the benefit records for opportunity
_______________________________________________________________________________________

*@params: sOppId,sPlanType,sObjectApiName - holds the opportunity Id,plan type and object name - String
____________________________________________________________________________________

*@return: WrapperBenfit
_________________________________________________________________________________________
*/
    @AuraEnabled
    public static BenefitWrapper getBenefitRecords(String sOppId,String sPlanType,String sObjectApiName){
        //For Preparing the List of wrapper
        List<BenefitDataForPicklistWrapper> listOfWrapper = new List<BenefitDataForPicklistWrapper>();
        Boolean isVisionAllowed=false;
        Map<String, Benefit_Setting__mdt> mapSecNameVsLabel = new  Map<String, Benefit_Setting__mdt>();
        try{
            Vision_Benefit_Creation__c objCustomSetting = Vision_Benefit_Creation__c.getOrgDefaults();
            isVisionAllowed= objCustomSetting.Allow_Vision_Benefit_Creation__c;
            String sCommaSepratedFields = LGSObjectSchemaUtility.getFieldsList(sObjectApiName);
            //queries benefit records with all the fields for passed opportunity record
            String query = 'SELECT ' + sCommaSepratedFields + ' FROM ' + sObjectApiName + ' WHERE Opportunity__c =: sOppId AND recordtype.name= :sPlanType WITH SECURITY_ENFORCED';
            List<Benefit__c> listBenefitRec = Database.query(query);
            //checking whether the list is empty or not
            if(!listBenefitRec.isEmpty()){
                for(Benefit__c objBen :listBenefitRec ){
                        listOfWrapper.add(new BenefitDataForPicklistWrapper(objBen.Competitor_Name__c + ' ' + objBen.Plan_Name__c ,JSON.serialize(objBen))); 
                }
                for(Benefit_Setting__mdt objBenefitMetadata : [SELECT Id, MasterLabel, Section_Name__c, Benefit_Datatype__c,Benefit_Api_Name__c FROM Benefit_Setting__mdt where Benefit_Recordtype__c=:sPlanType]){
                    mapSecNameVsLabel.put(objBenefitMetadata.Section_Name__c + objBenefitMetadata.MasterLabel,objBenefitMetadata);      
                }
            } 
        }
        catch(Exception ex){  
            //Logging exception in ExceptionLog__c object
            UTIL_LoggingService.logHandledException(ex, UserInfo.getOrganizationId(),staticVariableClass.NLP_APP_NAME,staticVariableClass.LG_COMPETITOR_BENEFIT_DETAILS,staticVariableClass.GET_BENEFIT_RECORDS_METHOD, null, LoggingLevel.ERROR);  
        }
        //retuning the wrapperbenefit with label,name as liftOfWrapper and metadata                            
        return new BenefitWrapper(listOfWrapper,mapSecNameVsLabel,isVisionAllowed);
    } 
}