objects/Broker_Consultant_Commissions__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Broker/Consultant Commissions</relationshipLabel>
        <relationshipName>Broker_Consultant_Commissions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Broker/Consultant Commissions</label>
    <nameField>
        <displayFormat>BCC# {00000}</displayFormat>
        <label>Broker/Consultant Commissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker/Consultant Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Brokerage_and_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Brokerage</value>
            </filterItems>
            <filterItems>
                <field>Account.BROKCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Accounts</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Consultant Contact</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.Account__r.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ANA_AP17_Create_BC_Commissions_Test.cls
/**
@Author : Accenture Offshore Dev team
@name : ANA_AP17_Create_BC_Commissions_Test 
@CreateDate :23-08-2017
@Description : This class is test class for ANA_AP17_Create_BC_Commissions class. 
checks for positive and negative scenarios.
*/
@isTest
private class ANA_AP17_Create_BC_Commissions_Test {
	private static final string NATIONALAMPROFILE='National Sales';
    /*This method is for Positive test scenario.*/
    private static testmethod void testPositive()
    {
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1];       
        User user=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        system.runAs(user)
        {
            Account brAcc=ANA_UTIL01_TestMethods.createAccount(false);
            brAcc.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('Account','Brokerage');
            database.insert(brAcc);
            Contact con=ANA_UTIL01_TestMethods.createContact(true,brAcc.Id);        
            ContactRelationship__c cRel=ANA_UTIL01_TestMethods.createContactRelationship(false);
            cRel.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('ContactRelationship__c','Consultant Contact');
            cRel.Account__c=brAcc.Id;
			cRel.Contact__c=con.Id;
            database.insert(cRel);        
            Brokerage_and_Consultant__c bcon= ANA_UTIL01_TestMethods.createBrokerageAndConsultant(false);
            bcon.Consultant__c=cRel.id;
            bcon.Brokerage__c=brAcc.Id;
            bcon.Account__c=brAcc.id;        
            database.insert(bcon);
            Broker_Consultant_Commissions__c bccom=new Broker_Consultant_Commissions__c();
            ANA_AP17_Create_BC_Commissions.createSelectOptions(brAcc.id);
            ANA_AP17_Create_BC_Commissions.searchDB('Brokerage_and_Consultant__c','Name','Id',1,'Name','0','SearchByName','BrokerConsult',brAcc.id);
            ANA_AP17_Create_BC_Commissions.searchDB('Brokerage_and_Consultant__c','Name','Id',1,'Id',bcon.id,'SearchById','BrokerConsult',brAcc.id);
            ANA_AP17_Create_BC_Commissions.searchDB('Brokerage_and_Consultant__c','Name','Id',1,'Name',brAcc.name,'SearchByName','',brAcc.id);
            ANA_AP17_Create_BC_Commissions.searchDB('Brokerage_and_Consultant__c','Name','Id',1,'Id',brAcc.id,'SearchById','',brAcc.id);
            ANA_AP17_Create_BC_Commissions.saveBRRecord(brAcc.id,bcon.id,bccom);
            ANA_AP17_Create_BC_Commissions.getPickListValues();
        }
    }
    /*This method is for Negative test scenario.*/
     private static testmethod void testNegative()
    {
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1];       
        User user=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        system.runAs(user)
        {
            ANA_AP17_Create_BC_Commissions.createSelectOptions(null);
            Account brAcc=ANA_UTIL01_TestMethods.createAccount(false);
            brAcc.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('Account','Brokerage');
            database.insert(brAcc);                                 
            Brokerage_and_Consultant__c bcon= ANA_UTIL01_TestMethods.createBrokerageAndConsultant(false);
            bcon.Brokerage__c=brAcc.Id;
            bcon.Account__c=brAcc.id;        
            database.insert(bcon);
            ANA_AP17_Create_BC_Commissions.saveBRRecord(brAcc.id,bcon.id,null);

        }
    }
}