objects/Broker_Consultant_Commissions__c.object
<CustomObject>
    <fields>
        <fullName>BCContactRealtionshipID__c</fullName>
        <formula>BrokerageAndConsultant__r.Consultant__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BCContactRealtionshipID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Relationship__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Consultant</label>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Broker/Consultant Commissions</relationshipLabel>
        <relationshipName>Broker_Consultant_Commissions_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Broker/Consultant Commissions</label>
    <nameField>
        <displayFormat>BCC# {00000}</displayFormat>
        <label>Broker/Consultant Commissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker/Consultant Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ANA_BCCommnissionTrigger_Handler.cls
/*@author        :Accenture 
@date           27/09/2017
@name           ANA_BrokerConCommnissionTrigger_Handler
@description    Populates consultant lookup on BBrokerage consultant commission record.  
*/
public with sharing class ANA_BCCommnissionTrigger_Handler
{ 
/*This method updates consultant lookup of brokerage consultant commission with consultant of corressponding brokerage and consultant.*/
    public static void afterCreate(List<Broker_Consultant_Commissions__c>  BCCList){
        for(Broker_Consultant_Commissions__c bcc : BCCList){
            if(bcc.BCContactRealtionshipID__c != null) {
              bcc.Contact_Relationship__c = ID.ValueOf(bcc.BCContactRealtionshipID__c);
            }
        }
    }
}