objects/Broker_Consultant_Commissions1__c.object
<CustomObject>
    <description>Clone of Broker/Consultant Commissions object</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Broker_Consultant_Commissions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrokerageAndConsultant__c</fullName>
        <inlineHelpText>Do not make any consultant changes using this field. Please click Cancel and select the appropriate consultant from the drop-down.</inlineHelpText>
        <label>Brokerage/Consultant</label>
        <referenceTo>Brokerage_and_Consultant1__c</referenceTo>
        <relationshipLabel>Broker/Consultant Commissions</relationshipLabel>
        <relationshipName>Broker_Consultant_Commissions1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brokerage_Commission_Split__c</fullName>
        <label>Brokerage Commission Split %</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Broker_Consultant_Commissions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Broker/Consultant Commissions</label>
    <nameField>
        <displayFormat>BCC# {00000}</displayFormat>
        <label>Broker/Consultant Commissions Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Broker/Consultant Commissions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage_and_Consultant11_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>BrokerageAndConsultant__c</fullName>
        <label>Brokerage/Consultant</label>
        <summaryForeignKey>Broker_Consultant_Commissions1__c.BrokerageAndConsultant__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>LG Brokerage, LG Self Relationship</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <formula>Brokerage__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax ID</label>
        <type>Text</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SIC__c.object
<CustomObject>
    <label>SIC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Industry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SICs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Tax_ID__c.object
<CustomObject>
    <description>KF(20140507) table added to allow for more than one TaxID per account, per instruction from CIP and National SME&apos;s</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax IDs</relationshipLabel>
        <relationshipName>Tax_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax ID</label>
    <nameField>
        <displayFormat>TID-{000000}</displayFormat>
        <label>Tax ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/BrokerageCommissionCloneController_Test.cls
/*@author       Ravideep(Vikings)
@date           06/06/2019
@name           BrokerageCommissionCloneController_Test
@description    Test class for BrokerageCommissionCloneController
*/
@isTest
public class BrokerageCommissionCloneController_Test {
 static testMethod void testMethod1(){
        
        SIC__c Sic = new SIC__c(Name = staticVariableClass.SIC);
        Insert SIC;
        
        Test.startTest();
        Account acc =new Account(RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('LG Prospect').getRecordTypeId(),Name = staticVariableClass.AccountName,Account_s_Suppress_Auto_Renewal__c = false,Anthem_Entity__c = staticVariableClass.Entity,Region__c= staticVariableClass.Region,Branding__c =staticVariableClass.UniCare,SIC__c = SIC.Id,Group_Size__c =staticVariableClass.size,Total_Employees__c =staticVariableClass.emp,HQ_State__c =staticVariableClass.AK,Situs_State__c = staticVariableClass.California,Mailing_Address_Same_as_Physical_Address__c = true,BillingStreet = 'Land Mark',BillingPostalCode = '636111',BillingCity = 'Banglore',BillingCountry = 'India',BillingState = 'Karnataka',Physical_County__c = 'Banglore');
        insert acc;
        
        Account brAcc =new Account(RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('LG Brokerage').getRecordTypeId(),Name = staticVariableClass.AccountName + '1',Account_s_Suppress_Auto_Renewal__c = false,Anthem_Entity__c = staticVariableClass.Entity,Region__c= staticVariableClass.Region,Branding__c =staticVariableClass.UniCare,SIC__c = SIC.Id,Group_Size__c =staticVariableClass.size,Total_Employees__c =staticVariableClass.emp,HQ_State__c =staticVariableClass.AK,Situs_State__c = staticVariableClass.California,Mailing_Address_Same_as_Physical_Address__c = true,BillingStreet = 'Test',BillingPostalCode = '1232',BillingCity = 'Test',BillingCountry = 'Test',BillingState = 'Test',Physical_County__c = 'Test',Tax_ID__c = '123456789');
        insert brAcc;
        
        
        Opportunity newOpp = new Opportunity(name=  (String.valueOf(system.today().year() + 1) + ' New Business Local-' + acc.Name),StageName = staticVariableClass.ClosedWon,AccountID = acc.id,CloseDate = ((system.TODAY())-95),recordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('New Business Local').getRecordTypeId());
        insert newOpp;
    
        
        Contact con=ANA_UTIL01_TestMethods.createContact(true,brAcc.Id);        
        ContactRelationship__c cRel=ANA_UTIL01_TestMethods.createContactRelationship(false);
        cRel.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('ContactRelationship__c','LG Brokerage Consultant Relationship');
        cRel.Account__c=brAcc.Id;
        cRel.Contact__c=con.Id;
        database.insert(cRel);        
        Brokerage_and_Consultant1__c bcon= new Brokerage_and_Consultant1__c();
        bcon.Consultant__c=cRel.id;
        bcon.Brokerage__c=brAcc.Id;
        bcon.Account__c=brAcc.id;        
        database.insert(bcon);
        Broker_Consultant_Commissions1__c bccom=new Broker_Consultant_Commissions1__c(Brokerage_Commission_Split__c = 30,Opportunity__c = newOpp.id,BrokerageAndConsultant__c = bcon.id,Account__c = brAcc.id);
        BrokerageCommissionCloneController.insertClonedRecord(bccom);
        BrokerageCommissionCloneController.getBrokerageCommissionSplitTotal(newOpp.id,25);   
        Test.stopTest();
    }
    
    }