objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage_and_Consultant11_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brokerage_of_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is the Brokerage of Record for this Account</inlineHelpText>
        <label>BOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant_of_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Consultant of Record for the Account</inlineHelpText>
        <label>COR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <formula>Brokerage__r.Tax_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Tax ID</label>
        <type>Text</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_Code_ASF__c</fullName>
        <formula>IF( ISBLANK(  vlocity_ins__ContractCode__c ) , Product2.Contract_Code__c  , vlocity_ins__ContractCode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Custom Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>51 - 99</fullName>
                </value>
                <value>
                    <fullName>100 - 249</fullName>
                </value>
                <value>
                    <fullName>250 - 499</fullName>
                </value>
                <value>
                    <fullName>500 - 999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IC_ProductStage__c</fullName>
        <formula>IF(ISPICKVAL(ProductStage__c, &quot;Sold&quot;) || ISPICKVAL(ProductStage__c, &quot;IGAP Sold&quot;) || ISPICKVAL(ProductStage__c, &quot;Renewed&quot;), &quot;Sold&quot;, 
IF(ISPICKVAL(ProductStage__c, &quot;Lost&quot;) || ISPICKVAL(ProductStage__c, &quot;IGAP Lost&quot;) || ISPICKVAL(ProductStage__c, &quot;Dead&quot;) || ISPICKVAL(ProductStage__c, &quot;IGAP Dead&quot;) || ISPICKVAL(ProductStage__c, &quot;Termed&quot;), &quot;Lost&quot;, &quot;NA&quot;))</formula>
        <label>IC Product Stage</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <formula>TEXT(Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLOB__c</fullName>
        <formula>IF(
NOT(ISBLANK(TEXT(Product2.LOB__c))),
TEXT(Product2.LOB__c),
LEFT( TEXT(Product2.LOB_Org__c),LEN(TEXT(Product2.LOB_Org__c))-2 )
)</formula>
        <label>ProductLOB</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Product2.Name</formula>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Family_Local__c</fullName>
        <formula>TEXT(Product2.Product_Family__c)</formula>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State_Abbrev__c</fullName>
        <formula>Quote.Opportunity.Account.Situs_State_Abbrev__c</formula>
        <label>Situs_State_Abbrev</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tax_ID__c.object
<CustomObject>
    <description>KF(20140507) table added to allow for more than one TaxID per account, per instruction from CIP and National SME&apos;s</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax IDs</relationshipLabel>
        <relationshipName>Tax_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax ID</label>
    <nameField>
        <displayFormat>TID-{000000}</displayFormat>
        <label>Tax ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/APIApplication.cls
/*
 * Class Name: APIApplication
 * Current Version: 1.0
 * Created Date: October 2019
 * Author: Archima
 * Description: This class exposes a REST interface for retrieving an Application.
 * Below is the URL path pattern used to call the service.
 * 
 * GET /application/{applicationNumber}
 */
@RestResource(urlMapping='/application/*')
global with sharing class APIApplication {

    public static final STRING ROLE_ACCOUNT_MANAGER = 'Account Manager';
    public static final STRING ROLE_ACCOUNT_EXECUTIVE = 'Account Executive';


    @HttpGet
    global static Application getApplication() {
        String orderNumber = RestContext.request.requestURI.substring(RestContext.request.requestURI.lastIndexOf('/') + 1);
        return getApplication(orderNumber);
    }

    public static Application getApplication(String orderNumber) {
        Application application;

        if (String.isNotBlank(orderNumber)) {
            List<Order> orders = [
                SELECT
                    Account.Anthem_Entity__c,
                    Account.BillingCity,
                    Account.BillingPostalCode,
                    Account.BillingState,
                    Account.BillingStreet,
                    Account.Group_Size__c,
                    Account.SIC__r.Industry_Name__c,
                    Account.SIC__r.SIC_Code__c,
                    Account.Situs_State_Abbrev__c,
                    AccountLegalName__c,
                    LG_Broker_Portal_Case_Status__c,
                    Implementation_Type__c,
                    Opportunity.CloseDate,
                    Opportunity.Date_Signed_Paperwork_Rec_d__c,
                    OrderNumber,
                    QuoteId
                FROM
                    Order
                WHERE
                    OrderNumber = :orderNumber
            ];

            if (orders.size() > 0) {
                OpportunityTeamMember accountManager;
                OpportunityTeamMember accountExecutive;

                List<OpportunityTeamMember> opportunityTeamMembers = [
                    SELECT
                        TeamMemberRole,
                        User.FirstName,
                        User.LastName
                    FROM
                        OpportunityTeamMember
                    WHERE
                        OpportunityId = :orders[0].OpportunityId
                    AND
                        TeamMemberRole IN (:ROLE_ACCOUNT_MANAGER, :ROLE_ACCOUNT_EXECUTIVE)
                ];

                for (OpportunityTeamMember opportunityTeamMember : opportunityTeamMembers) {
                    if (opportunityTeamMember.TeamMemberRole == ROLE_ACCOUNT_MANAGER) {
                        accountManager = opportunityTeamMember;
                    } else if (opportunityTeamMember.TeamMemberRole == ROLE_ACCOUNT_EXECUTIVE) {
                        accountExecutive = opportunityTeamMember;
                    }
                }

                List<Brokerage_and_Consultant1__c> brokerageConsultants = [
                    SELECT
                        Brokerage_of_Record__c,
                        Consultant_of_Record__c,
                        Consultant__r.Account__r.ENCRYPTID__c,
                        Consultant__r.Account__r.Name,
                        Consultant__r.Contact__r.ENCRYPTID__c,
                        Consultant__r.Contact__r.FirstName,
                        Consultant__r.Contact__r.LastName
                    FROM
                        Brokerage_and_Consultant1__c
                    WHERE
                        Opportunity__c = :orders[0].OpportunityId
                    AND
                        (
                            Brokerage_of_Record__c = true
                            OR
                            Consultant_of_Record__c = true
                        )
                ];

                List<QuoteLineItem> quoteLineItems = [
                    SELECT
                        Contract_Code_ASF__c,
                        ProductName__c,
                        ProductLOB__c,
                        Product_Family_Local__c
                    FROM
                        QuoteLineItem
                    WHERE
                        QuoteId = :orders[0].QuoteId
                    AND
                        ProductCategory__c = 'Product'
                    AND
                        IC_ProductStage__c = 'Sold'
                ];

                Contact primaryContact;

                List<Contact> contacts = [
                    SELECT
                        Email,
                        Fax,
                        Name,
                        FirstName,
                        LastName,
                        Phone
                    FROM
                        Contact
                    WHERE
                        AccountId = :orders[0].AccountId
                    AND
                        IsActive1__c = true
                    AND
                        Primary_Contact__c = true
                    LIMIT 1
                ];

                if (contacts.size() > 0) {
                    primaryContact = contacts[0];
                }

                String taxId;

                // Get the last modified Tax ID record for the Account.
                List<Tax_ID__c> taxIds = [SELECT Tax_ID__c FROM Tax_ID__c WHERE Account__c = :orders[0].AccountId ORDER BY LastModifiedDate DESC LIMIT 1];

                if (taxIds.size() > 0) {
                    taxId = taxIds[0].Tax_ID__c;
                }

                application = new Application(orders[0], accountManager, accountExecutive, brokerageConsultants, quoteLineItems, primaryContact, taxId);
            } else {
                // No record found.
                RestContext.response.statusCode = 404;
            }
        } else {
            // Invalid request.
            RestContext.response.statusCode = 400;
        }

        return application;
    }


    global class Application {

        global String accountManagerId {get; set;}
        global String accountManagerName {get; set;}
        global List<Agent> agents {get; set;}
        global String appCreationDate {get; set;}
        global String applicationId {get; set;}
        global String applicationType {get; set;}
        global String appSource {get; set;}
        global CompanyInformation companyInformation {get; set;}
        global String ein {get; set;}
        global String marketSegment {get; set;}
        global String name {get; set;}
        global List<Plan> plans {get; set;}
        global String requestEffectiveDate {get; set;}
        global String salesRepId {get; set;}
        global String salesRepName {get; set;}
        global String sicCode {get; set;}
        global String size {get; set;}
        global String state {get; set;}
        global String status {get; set;}


        global Application() {
        }

        global Application(Order order, OpportunityTeamMember accountManager, OpportunityTeamMember accountExecutive, List<Brokerage_and_Consultant1__c> brokerageConsultants, List<QuoteLineItem> quoteLineItems, Contact primaryContact, String taxId) {
            if (accountManager != null) {
                accountManagerId = accountManager.UserId;
                accountManagerName = formatName(accountManager.User.FirstName, accountManager.User.LastName);
            }

            agents = new List<Agent>();

            for (Brokerage_and_Consultant1__c brokerageConsultant : brokerageConsultants) {
                Agent agent = new Agent();

                if (brokerageConsultant.Brokerage_of_Record__c == true) {
                    agent.paidAgentName = brokerageConsultant.Consultant__r.Account__r.Name;
                    agent.paidAgentTin = brokerageConsultant.Consultant__r.Account__r.ENCRYPTID__c;
                }

                if (brokerageConsultant.Consultant_of_Record__c == true) {
                    agent.writingAgentName = formatName(brokerageConsultant.Consultant__r.Contact__r.FirstName, brokerageConsultant.Consultant__r.Contact__r.LastName);
                    agent.writingAgentTin = brokerageConsultant.Consultant__r.Contact__r.ENCRYPTID__c;
                }

                agents.add(agent);
            }

            appCreationDate = formatDate(order.Opportunity.Date_Signed_Paperwork_Rec_d__c, 'yyyy-MM-dd');
            applicationId = order.OrderNumber;
            applicationType = order.Implementation_Type__c;

            companyInformation = new CompanyInformation();
            companyInformation.addresses = new List<Address>();
            companyInformation.addresses.add(new Address());
            companyInformation.addresses[0].city = order.Account.BillingCity;
            companyInformation.addresses[0].state = order.Account.BillingState;
            companyInformation.addresses[0].streetAddress = order.Account.BillingStreet;
            companyInformation.addresses[0].type = 'Company';
            companyInformation.addresses[0].zip = order.Account.BillingPostalCode;

            if (primaryContact != null) {
                companyInformation.contactDetails = new ContactDetails ();
                companyInformation.contactDetails.contactEmailAddress = primaryContact.Email;
                companyInformation.contactDetails.contactName = formatName(primaryContact.FirstName, primaryContact.LastName);
                companyInformation.contactDetails.faxNumber = primaryContact.Fax;
                companyInformation.contactDetails.primaryPhone = primaryContact.Phone;
            }

            ein = taxId;
            marketSegment = order.Account.Anthem_Entity__c;
            name = order.AccountLegalName__c;

            plans = new List<Plan>();

            for (QuoteLineItem quoteLineItem : quoteLineItems) {
                Plan plan = new Plan();
                plan.planType = quoteLineItem.Product_Family_Local__c;
                plan.productType = quoteLineItem.ProductLOB__c;
                plans.add(plan);
            }
            
            requestEffectiveDate = formatDate(order.Opportunity.CloseDate, 'yyyy-MM-dd');

            if (accountExecutive != null) {
                salesRepId = accountExecutive.UserId;
                salesRepName = formatName(accountExecutive.User.FirstName, accountExecutive.User.LastName);
            }

            sicCode = order.Account.SIC__r.SIC_Code__c + ',' + order.Account.SIC__r.Industry_Name__c;
            size = order.Account.Group_Size__c;
            state = order.Account.Situs_State_Abbrev__c;
            status = order.LG_Broker_Portal_Case_Status__c;
        }

    }

    public static String formatName(String firstName, String lastName) {
        String name;

        if (String.isNotBlank(firstName) && String.isNotBlank(lastName)) {
            name = lastName + ', ' + firstName;
        } else if (String.isNotBlank(firstName)) {
            name = firstName;
        } else if (String.isNotBlank(lastName)) {
            name = lastName;
        }

        return name;
    }

    public static String formatDate(Date d, String format) {
        return (d == null ? null : DateTime.newInstance(d.year(), d.month(), d.day()).format(format));
    }


    global class Plan {

        global String contractCode {get; set;}
        global String planName {get; set;}
        global String planType {get; set;}
        global String productType {get; set;}

    }

    global class Agent {

        global String paidAgentName {get; set;}
        global String paidAgentTin {get; set;}
        global String parentAgentName {get; set;}
        global String parentAgentTin {get; set;}
        global String writingAgentName {get; set;}
        global String writingAgentTin {get; set;}

    }

    global class CompanyInformation {

        global List<Address> addresses {get; set;}
        global ContactDetails contactDetails {get; set;}

    }

    global class Address {

        global String city {get; set;}
        global String state {get; set;}
        global String streetAddress {get; set;}
        global String type {get; set;}
        global String zip {get; set;}

    }

    global class ContactDetails {

        global String contactEmailAddress {get; set;}
        global String contactName {get; set;}
        global String faxNumber {get; set;}
        global String primaryPhone {get; set;}

    }

}