objects/Brokerage_and_Consultant__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Brokerage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Brokerage</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Brokerage</value>
            </filterItems>
            <filterItems>
                <field>Account.BROKCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customer Accounts</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Line of Business (not the total Opportunity)</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subscribers__c</fullName>
        <inlineHelpText>Enter the number of Subscribers for this particular Line of Business (not the total Opportunity)</inlineHelpText>
        <label>Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT( Opportunity.Account.Anthem_Entity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subscribers__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__EffectiveDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Probability__c</fullName>
        <label>Probability</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>0%</fullName>
                </value>
                <value>
                    <fullName>5%</fullName>
                </value>
                <value>
                    <fullName>10%</fullName>
                </value>
                <value>
                    <fullName>15%</fullName>
                </value>
                <value>
                    <fullName>20%</fullName>
                </value>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>30%</fullName>
                </value>
                <value>
                    <fullName>35%</fullName>
                </value>
                <value>
                    <fullName>40%</fullName>
                </value>
                <value>
                    <fullName>45%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>55%</fullName>
                </value>
                <value>
                    <fullName>60%</fullName>
                </value>
                <value>
                    <fullName>65%</fullName>
                </value>
                <value>
                    <fullName>70%</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
                <value>
                    <fullName>80%</fullName>
                </value>
                <value>
                    <fullName>85%</fullName>
                </value>
                <value>
                    <fullName>90%</fullName>
                </value>
                <value>
                    <fullName>95%</fullName>
                </value>
                <value>
                    <fullName>100%</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Advocacy</fullName>
                </value>
                <value>
                    <fullName>Account/Sales Team</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy/Client Went Out of Business</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Product Options</fullName>
                </value>
                <value>
                    <fullName>Billing Issues</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Broker of Record Change</fullName>
                </value>
                <value>
                    <fullName>Cede</fullName>
                </value>
                <value>
                    <fullName>Claim Issues</fullName>
                </value>
                <value>
                    <fullName>Client Withdrew/No Further Inquiry</fullName>
                </value>
                <value>
                    <fullName>Clinical Value</fullName>
                </value>
                <value>
                    <fullName>COVID19</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Digital and Consumer Engagement</fullName>
                </value>
                <value>
                    <fullName>Discount Value</fullName>
                </value>
                <value>
                    <fullName>Does Not Meet Requirements</fullName>
                </value>
                <value>
                    <fullName>Employee Customer Service</fullName>
                </value>
                <value>
                    <fullName>Exchange – Moving To/From</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation/ New Participant</fullName>
                </value>
                <value>
                    <fullName>Fees</fullName>
                </value>
                <value>
                    <fullName>Financial/Discount Value</fullName>
                </value>
                <value>
                    <fullName>Funding Type Change</fullName>
                </value>
                <value>
                    <fullName>Group Number Change</fullName>
                </value>
                <value>
                    <fullName>Guarantees</fullName>
                </value>
                <value>
                    <fullName>Incomplete Data</fullName>
                </value>
                <value>
                    <fullName>Inconvenient to Change Carriers</fullName>
                </value>
                <value>
                    <fullName>IT Security</fullName>
                </value>
                <value>
                    <fullName>Medical Products - CDHP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Quote.Opportunity.Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscribers__c</fullName>
        <inlineHelpText>Enter the number of Subscribers for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Subscribers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QLIUpdateUtilityTest.cls
@isTest
public class QLIUpdateUtilityTest {
    @testSetup static void setup() {
        Id i=[SELECT DeveloperName, Id, SobjectType, IsActive FROM RecordType where SobjectType='Account' and DeveloperName='Brokerage'].Id;
        Account parentacc =new Account();
        parentacc.recordtypeid=i;
        parentacc.Name = 'test2';
        parentacc.Anthem_Entity__c = 'Local/Large Group';
        insert parentacc;
        
        Account acc1 = new Account(Name = 'test1',
                                   Region__c = 'West',
                                   Anthem_Entity__c = 'Local/Large Group',
                                   parentid=parentacc.id,NASCO_Contracting_Situs_State__c='60 CO',WGS_Contracting_Situs_State__c='CA California');
        
        insert acc1;
        
        system.assert(acc1.id!=null);
        
        Group__c g=new Group__c();
        g.name='test group';
        g.Account__c=acc1.id;
        insert g;
        system.assert(g.id!=null);
        Id recid=[SELECT DeveloperName, Id, SobjectType, IsActive FROM RecordType where SobjectType='Account' and DeveloperName='ServiceProvider'].Id;
        
        Account acc2 = new Account(Name = 'testcompetitor',
                                   Region__c = 'West',
                                   Anthem_Entity__c = 'Local/Large Group',
                                   recordtypeid=recid,Competitor__c=true,NASCO_Contracting_Situs_State__c='60 CO',WGS_Contracting_Situs_State__c='CA California');
        
        insert acc2;
        
        
        Brokerage_and_Consultant__c brokcons=new Brokerage_and_Consultant__c(Account__c=acc1.id,Brokerage__c=parentacc.id);
        insert brokcons;
        
        Opportunity opp1 = new Opportunity(Name = 'test opp',
                                           AccountId = acc1.id,
                                           StageName = 'Initiated',closedate=date.newInstance(2020, 01, 01));
        
        insert opp1;
        
        Product2 prod = new Product2(Category__c = 'Product', Name = 'Castlight - Buy Up Products',vlocity_ins__SubType__c='Other',
                                     IsActive = true,LOB__c='Medical',productActive__c = true);
        insert prod;
        
        Product2 parentProd1 = new Product2(Category__c = 'Product', Name = 'Castlight - Buy Up Products',vlocity_ins__SubType__c='Other',
                                            IsActive = true,LOB__c='Medical',productActive__c = true);
        insert parentProd1;
        
        Product2 prod1 = new Product2(Name = 'Castlight - Buy Up Products',vlocity_ins__SubType__c='Other',
                                      IsActive = true,LOB__c='Medical',vlocity_ins__ProductSpecId__c=prod.Id,
                                      Contract_code__c='3MU2',vlocity_ins__EffectiveDate__c = Date.today(),productActive__c = true);
        insert prod1;
        
        Product2 prod2 = new Product2(Name = 'Castlight - Buy Up Products',vlocity_ins__SubType__c='Other',
                                      IsActive = true,LOB__c='Medical',vlocity_ins__ProductSpecId__c=prod.Id,
                                      Contract_code__c='3MU3',vlocity_ins__EffectiveDate__c = Date.today(),productActive__c = true);
        insert prod2;
        Product2 prod3 = new Product2(Name = 'Castlight - Buy Up Products',vlocity_ins__SubType__c='Other',
                                      IsActive = true,LOB__c='Medical',vlocity_ins__ProductSpecId__c=parentProd1.Id,
                                      Contract_code__c='3MU6',vlocity_ins__EffectiveDate__c = Date.today(),productActive__c = true);
        insert prod3;
        
        
        system.assert(prod.id!=null);
        Id pricebookId = Test.getStandardPricebookId();
        
        
        PricebookEntry standardPrice = new PricebookEntry( Pricebook2Id = pricebookId, 
                                                          Product2Id = prod.Id,
                                                          UnitPrice = 10000, IsActive = true);
        
        insert standardPrice;
        
        PricebookEntry standardPrice1 = new PricebookEntry( Pricebook2Id = pricebookId, 
                                                           Product2Id = prod1.Id,
                                                           UnitPrice = 20000, IsActive = true);
        insert  standardPrice1;
        PricebookEntry standardPrice2 = new PricebookEntry( Pricebook2Id = pricebookId, 
                                                           Product2Id = prod2.Id,
                                                           UnitPrice = 20000, IsActive = true);
        insert  standardPrice2;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        
        insert customPB;
        
        PricebookEntry pbe = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = prod.Id,
                                                UnitPrice = 12000, IsActive = true);
        
        insert pbe;
        PricebookEntry pbe1 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = parentProd1.Id,
                                                 UnitPrice = 12000, IsActive = true);
        
        insert pbe1;
        PricebookEntry pbe2 = new PricebookEntry(Pricebook2Id = pricebookId, Product2Id = prod3.Id,
                                                 UnitPrice = 12000, IsActive = true);
        
        insert pbe2;

        Quote q1 = new Quote(Name = 'test Quote',
                             Pricebook2Id = pricebookId,
                             OpportunityId = opp1.Id,GroupNumber__c=g.id);
        
        insert q1;
        
        /* PricebookEntry pbeforQuote = new PricebookEntry(Pricebook2Id = customPB.Id, Product2Id = q1.Id,
        UnitPrice = 12000, IsActive = true);
        
        insert pbeforQuote;*/
        
        system.assert(q1.id!=null);
        
        QuoteLineItem qli2 = new QuoteLineItem(Subscribers__c = 12, 
                                               Reason__c='Funding Type Change',
                                               Probability__c='15%',
                                               ProductStage__c='In Progress',
                                               Members__c = 10,
                                               QuoteId = q1.Id,
                                               Product2Id = prod1.Id,
                                               PricebookEntryId = standardPrice.Id,
                                               Quantity = 10,
                                               Unitprice = 10.00,Competitor__c=acc2.id,vlocity_ins__ContractCode__c='3MU2');
        insert qli2;
        
        QuoteLineItem qli1 = new QuoteLineItem(Subscribers__c = 13, 
                                               Reason__c='Funding Type Change',
                                               Probability__c='15%',
                                               ProductStage__c='In Progress',
                                               Members__c = 10,
                                               QuoteId = q1.Id,
                                               Product2Id = prod1.Id,
                                               PricebookEntryId = standardPrice.Id,
                                               Quantity = 10,
                                               ParentQuoteLineItem__c = qli2.id,
                                               Unitprice = 10.00,Competitor__c=acc2.id,vlocity_ins__ContractCode__c='3MU2');
        
        insert qli1;
        
        QuoteLineItem qli3 = new QuoteLineItem(Subscribers__c = 9, 
                                               Reason__c='Funding Type Change',
                                               Probability__c='15%',
                                               ProductStage__c='In Progress',
                                               Members__c = 10,
                                               QuoteId = q1.Id,
                                               Product2Id = prod2.Id,
                                               PricebookEntryId = standardPrice.Id,
                                               Quantity = 10,
                                               ParentQuoteLineItem__c = qli2.id,
                                               Unitprice = 10.00,Competitor__c=acc2.id,vlocity_ins__ContractCode__c='3MU3');
        
        insert qli3;
        QuoteLineItem qli4 = new QuoteLineItem(Subscribers__c = 10, 
                                               Reason__c='Funding Type Change',
                                               Probability__c='15%',
                                               ProductStage__c='In Progress',
                                               Members__c = 10,
                                               QuoteId = q1.Id,
                                               Product2Id = prod2.Id,
                                               PricebookEntryId = standardPrice.Id,
                                               Quantity = 10,
                                               SFDCLegacyID__c = 'TEMPID',
                                               Unitprice = 10.00,Competitor__c=acc2.id,vlocity_ins__ContractCode__c='3MU3',
                                               ParentQuoteLineItem__c = qli2.id);
        
        insert qli4;
        QuoteLineItem parentQLI = new QuoteLineItem(Subscribers__c = 6, 
                                                    Reason__c='Funding Type Change',
                                                    Probability__c='15%',
                                                    ProductStage__c='In Progress',
                                                    Members__c = 10,
                                                    QuoteId = q1.Id,
                                                    Product2Id = prod.Id,
                                                    PricebookEntryId = standardPrice.Id,
                                                    Quantity = 10,
                                                    SFDCLegacyID__c = 'TEMPID',
                                                    Unitprice = 10.00,Competitor__c=acc2.id);
        
        insert parentQLI;
        
        QuoteLineItem qli5 = new QuoteLineItem(Subscribers__c = 14, 
                                               Reason__c='Funding Type Change',
                                               Probability__c='15%',
                                               ProductStage__c='In Progress',
                                               Members__c = 10,
                                               QuoteId = q1.Id,
                                               Product2Id = prod2.Id,
                                               PricebookEntryId = standardPrice.Id,
                                               Quantity = 10,
                                               SFDCLegacyID__c = 'TEMPID',
                                               Unitprice = 10.00,Competitor__c=acc2.id,
                                               parentQuoteLineItem__C= parentQLI.id,vlocity_ins__ContractCode__c='3MU2');
        
        insert qli5;
        system.assert(qli1.id!=null); 
        
        QuoteLineItemRates__c rates = new QuoteLineItemRates__c (QuoteLineItem__c=qli5.id);
        insert rates;
        system.assert(rates.id!=null); 
        IntegrationTestDataUtilty.loadCustomSettings();
    }
     @isTest
    static void updateLegacyQLIProductWithParentQLITest()
    {
         QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where ParentQuoteLineItem__c!= null and Subscribers__c = 9 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU2');
        system.assert(QLIStatus.StatusCode=='SUCCESS'); 
           
    }
     @isTest
    static  void updateLegacyQLIProductWithoutParentQLITest()
    {
         QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 10 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU2');
        system.assert(QLIStatus.StatusCode=='SUCCESS'); 
           
    }
     @isTest
    static  void updateLegacyQLIProductWithoutProdTest()
    {
         QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 10 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'Test');
        system.assert(QLIStatus.StatusCode=='ERROR'); 
        system.assert(QLIStatus.StatusMessage.contains('No active product found with contract code')); 
           
    }
     @isTest
    static  void updateLegacyQLIProductWithoutQLITest()
    {
        QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 10 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct('0QL54000000AivVGbd','3MU2');
        system.assert(QLIStatus.StatusCode=='ERROR'); 
        system.assert(QLIStatus.StatusMessage.contains('No QuotelineItem record found with QLI Id')); 
           
    }
     @isTest
    static  void updateLegacyQLIProductWithChildQLITest()
    {
         QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 12 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU2');
        system.assert(QLIStatus.StatusCode=='ERROR'); 
        system.assert(QLIStatus.StatusMessage.contains('Child record exists for given QLI Id')); 
           												
    }
     @isTest
    static  void updateLegacyQLIProductWithLinkedContCodeTest()
    {
         QuoteLineItem qliRec = [select id,QuoteId,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 13 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU2');
        system.assert(QLIStatus.StatusCode=='ERROR'); 
        system.assert(QLIStatus.StatusMessage.contains('Quote Line record is already linked to contract code')); 
           
    }
    
    @isTest
    static void testUpdateQliForProdSelection()
    {
         QuoteLineItem qliRec = [select id,QuoteId,vlocity_ins__ContractCode__c,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 14 LIMIT 1];
         List<QuoteLineItem> qliList = new List<QuoteLineItem>();
         qliList.add(qliRec);
         ANA_UTIL01_TestMethods.createPSDRecord(qliList,true);
          List<ProductSelectionDetail__c> prodSelectionQliList = [SELECT id,QuoteLineItem__c 
                                                                FROM ProductSelectionDetail__c
                                                               WHERE QuoteLineItem__c=:qliRec.Id LIMIT 1];
        System.debug('Prod Selection size details: '+prodSelectionQliList.size()+ prodSelectionQliList[0].QuoteLineItem__c);
        System.debug('QLI Actual Id Old :'+ qliRec.Id);
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU2');
        system.assert(QLIStatus.StatusCode=='SUCCESS'); 
    }
    
    @isTest
	static void testUpdateQliForRates()
    {
        QuoteLineItem qliRec = [select id,QuoteId,vlocity_ins__ContractCode__c,Contract_code__c,ParentQuoteLineItem__c from QuoteLineItem where Subscribers__c = 10 LIMIT 1];
        QLIUpdateUtility qliutil = new QLIUpdateUtility();
        QLIUpdateUtility.QLIUpdateStatus QLIStatus = qliutil.updateQLIProduct(qliRec.Id,'3MU6');
        system.assert(QLIStatus.StatusCode=='SUCCESS'); 
    }
}