objects/Brokerage_and_Consultant1__c.object
<CustomObject>
    <description>Brokerage and Consultant object for Opportunity</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Brokerage_and_Consultant11_del</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Brokerage_of_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>This is the Brokerage of Record for this Account</inlineHelpText>
        <label>BOR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Consultant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Consultant must be a Contact on the selected Brokerage.</inlineHelpText>
        <label>Consultant</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1 AND (2 OR 4) AND 3</booleanFilter>
            <errorMessage>Please select an Active Consultant from the specified Brokerage Account.</errorMessage>
            <filterItems>
                <field>ContactRelationship__c.Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Brokerage__c</valueField>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.CONTCANCEL__c</field>
                <operation>equals</operation>
                <value>Active</value>
            </filterItems>
            <filterItems>
                <field>ContactRelationship__c.RecordType.DeveloperName</field>
                <operation>equals</operation>
                <value>LG_Brokerage_Consultant_Relationship</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>API User</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>ContactRelationship__c</referenceTo>
        <relationshipLabel>Brokerage and Consultant</relationshipLabel>
        <relationshipName>Brokerage_and_Consultant1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Consultant_of_Record__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Consultant of Record for the Account</inlineHelpText>
        <label>COR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Brokerage_and_Consultant11</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Brokerage and Consultant</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Brokerage and Consultant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ApplicationEventAction.cls
/*
 * Class Name: ApplicationEventAction
 * Current Version: 1.0
 * Created Date: October 2019
 * Author: Archima
 * Description: This class has an invocable method that is used by a process
 * to publish LG Application platform events.
 */
public with sharing class ApplicationEventAction {

    @InvocableMethod(label='Create Application Events')
    public static void createApplicationEvents(List<Id> orderIds) {
        List<Order> orders = [
            SELECT
                OpportunityId,
                OrderNumber,
                LG_Broker_Portal_Case_Status__c,
                LG_Broker_Portal_Status_Date__c,
                LG_Broker_Portal_Status_Event_Type__c,
                Account.Situs_State_Abbrev__c
            FROM
                Order
            WHERE
                Id IN :orderIds
        ];

        Set<Id> opportunityIds = new Set<Id>();

        for (Order order : orders) {
            opportunityIds.add(order.OpportunityId);
        }

        List<Brokerage_and_Consultant1__c> brokerageConsultants = [
            SELECT
                Opportunity__c,
                Brokerage_of_Record__c,
                Consultant_of_Record__c,
                Consultant__r.Account__r.ENCRYPTID__c,
                Consultant__r.Contact__r.ENCRYPTID__c
            FROM
                Brokerage_and_Consultant1__c
            WHERE
                Opportunity__c IN :opportunityIds
            AND
                (
                    Brokerage_of_Record__c = true
                    OR
                    Consultant_of_Record__c = true
                )
        ];

        Map<Id, Brokerage_and_Consultant1__c> opportunityBrokerageConsultants = new Map<Id, Brokerage_and_Consultant1__c>();
        Map<Id, Brokerage_and_Consultant1__c> opportunityWritingConsultants = new Map<Id, Brokerage_and_Consultant1__c>();

        for (Brokerage_and_Consultant1__c brokerageConsultant : brokerageConsultants) {
            if (brokerageConsultant.Brokerage_of_Record__c == true) {
                opportunityBrokerageConsultants.put(brokerageConsultant.Opportunity__c, brokerageConsultant);
            }

            if (brokerageConsultant.Consultant_of_Record__c == true) {
                opportunityWritingConsultants.put(brokerageConsultant.Opportunity__c, brokerageConsultant);
            }
        }

        for (Order order : orders) {
            Brokerage_and_Consultant1__c brokerageConsultant = opportunityBrokerageConsultants.get(order.OpportunityId);
            Brokerage_and_Consultant1__c writingConsultant = opportunityWritingConsultants.get(order.OpportunityId);

            AnthemAPI.EventRequest eventRequest = new AnthemAPI.EventRequest();
            eventRequest.eventName = order.LG_Broker_Portal_Status_Event_Type__c;
            eventRequest.eventCorrelation = new AnthemAPI.EventCorrelation();
            eventRequest.eventCorrelation.correlationId = order.OrderNumber;
            eventRequest.eventCorrelation.vendorAppId = order.OrderNumber;
            eventRequest.eventData = new AnthemAPI.EventData();
            eventRequest.eventData.lineOfBusiness = 'LG';
            eventRequest.eventData.agentTins = new List<AnthemAPI.AgentTin>();
            eventRequest.eventData.agentTins.add(new AnthemAPI.AgentTin());
            eventRequest.eventData.agentTins[0].payeeTin = (brokerageConsultant == null ? null : brokerageConsultant.Consultant__r.Account__r.ENCRYPTID__c);
            eventRequest.eventData.agentTins[0].writingTin = (writingConsultant == null ? null : writingConsultant.Consultant__r.Contact__r.ENCRYPTID__c);
            eventRequest.eventData.state = order.Account.Situs_State_Abbrev__c;
            eventRequest.eventData.summary = order.LG_Broker_Portal_Case_Status__c;
            eventRequest.timeStamp = APIApplication.formatDate(order.LG_Broker_Portal_Status_Date__c, 'MM-dd-yyyy');

            AnthemAPI.postEvent(JSON.serialize(eventRequest));
        }

    }

}