objects/Castlight_Opportunity__c.object
<CustomObject>
    <description>Object to store opportunity data received from Castlight</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Castlight Opportunities</relationshipLabel>
        <relationshipName>Castlight_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CSLT_Account_Owner__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT Account Owner</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSLT_Acnt_Owner_Email__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT Account Owner Email</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSLT_OE_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT OE End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSLT_OE_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT OE Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSLT_OE_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT OE Type</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSLT_Opp_Close_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT Opp Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CSLT_Opportunity_Id__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <externalId>true</externalId>
        <label>CSLT Opportunity Id</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CSLT_Opportunity_Stage__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>CSLT Opportunity Stage</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Castlight Opportunities</relationshipLabel>
        <relationshipName>Castlight_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SF_Org_Name__c</fullName>
        <description>Anthem Salesforce org name for data sent to Castlight (Com1/Com2)</description>
        <encryptionScheme>None</encryptionScheme>
        <label>SF Org Name</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <label>Castlight Opportunity</label>
    <nameField>
        <displayFormat>CSLTOpp-{0000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Castlight Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Engage_Scoping_And_Engage_Standard__c.object
<CustomObject>
    <fields>
        <fullName>Castlight_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Castlight Opportunity</label>
        <referenceTo>Castlight_Opportunity__c</referenceTo>
        <relationshipLabel>Engage Scoping And Engage Standard</relationshipLabel>
        <relationshipName>Engage_Scoping_And_Engage_Standard</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Form Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Engage Scoping And Engage Standard</label>
    <nameField>
        <displayFormat>ENGS-{000}</displayFormat>
        <label>Engage Scoping And Engage Standard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Engage Scoping And Engage Standard</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CastLightStatusUpdateService.cls
@RestResource(urlMapping = '/CSLTStatusUpdate/*')
global class CastLightStatusUpdateService{
 
    @HttpPost
    global static void doPost() {
        
        CastLightRequestResponse data;
        //ResponseWrapper res = new ResponseWrapper();
        RestResponse res = RestContext.response;
        try {
            Organization org = [select id, issandbox, instancename from organization];
            data = (CastLightRequestResponse) JSON.deserialize(RestContext.request.requestBody.toString(), CastLightRequestResponse.class);
            system.debug('Req body--->'+RestContext.request.requestBody.toString());
            system.debug('deserializedstring--->' + data);
            
            system.debug('fetched---' + data.Accounts);
            
            List < Castlight_Opportunity__c > castlightoppfullist= new List < Castlight_Opportunity__c > ();
            List<Engage_Scoping_And_Engage_Standard__c> engageformlist=new List<Engage_Scoping_And_Engage_Standard__c>();
            set<Id> engagestandardscopingformid=new set<Id>();
            Map<Id,string> engageformid=new Map<Id,string>();
            
            Castlight_Opportunity__c o;
            for(CastLightRequestResponse.Account eachacc: data.Accounts)
            {
                
                for(CastLightRequestResponse.Opportunity eachopp: eachacc.Opportunities)
                {
                    
                    o = new Castlight_Opportunity__c();
                    o.CSLT_Account_Owner__c = eachacc.CSLT_AccountOwnerName;
                    system.debug('Account Owner Name:' + eachacc.CSLT_AccountOwnerName);
                    o.CSLT_Acnt_Owner_Email__c = eachacc.CSLT_AccountOwnerEmail;
                    system.debug('Account Owner Email:' + eachacc.CSLT_AccountOwnerEmail);
                    if(eachacc.CSLT_Open_Enrollment_End_Date!=null)
                    {
                    o.CSLT_OE_End_Date__c = Date.valueof(eachacc.CSLT_Open_Enrollment_End_Date);
                     system.debug('Account open enrollment end date:' + eachacc.CSLT_Open_Enrollment_End_Date);
                    }
                    if(eachacc.CSLT_Open_Enrollment_Start_Date!=null)
                    {
                    o.CSLT_OE_Start_Date__c = Date.valueof(eachacc.CSLT_Open_Enrollment_Start_Date);
                    system.debug('Account start enrollment:' + eachacc.CSLT_Open_Enrollment_Start_Date);
                    }
                    o.CSLT_OE_Type__c = eachacc.CSLT_Open_Enrollment_Type;
                    system.debug('Account enrollment type:' + eachacc.CSLT_Open_Enrollment_Type);
                    o.AccountId__c = eachacc.AccountID;
                    system.debug('Anthem Account Id:' + eachacc.AccountID);
                    o.SF_Org_Name__c = eachacc.AnthemORGID;
                    system.debug('Anthem SF Org Id:' + eachacc.AnthemORGID);
                    if(eachopp.CSLT_CloseDate!=null)
                    {
                    o.CSLT_Opp_Close_Date__c = Date.valueof(eachopp.CSLT_CloseDate);
                    system.debug('Opportunity CSLT_CloseDate:' + eachopp.CSLT_CloseDate);
                    }
                    o.CSLT_Opportunity_Stage__c = eachopp.CSLT_StageName;
                    system.debug('Opportunity stagename:' + eachopp.CSLT_StageName);
                    o.CSLT_Opportunity_Id__c = eachopp.CSLT_OpportunityID;
                    system.debug('Opportunity id from CSLT:' + eachopp.CSLT_OpportunityID);
                    o.OpportunityId__c = eachopp.OpportunityID;
                    system.debug('Anthem Opportunity Id:' + eachopp.OpportunityID);
                    castlightoppfullist.add(o);
                    if(eachopp.ScopingForms!=null)
                    {
                    for(CastLightRequestResponse.ScopingForm eachscopform:eachopp.ScopingForms)
                    {
                        if(eachscopform.CSLTFormStatus!=null && eachscopform.CSLTFormStatus!='')
                        {
                            engagestandardscopingformid.add(eachscopform.AnthemRecordID);
                            engageformid.put(eachscopform.AnthemRecordID,eachscopform.CSLTFormStatus);
                            
                        }
                    }
                    }
                    if(eachopp.StandardForms!=null)
                    {
                        for(CastLightRequestResponse.StandardForm  eachstandardform:eachopp.StandardForms)
                    {
                        if(eachstandardform.CSLTFormStatus!=null && eachstandardform.CSLTFormStatus!='')
                        {
                            engagestandardscopingformid.add(eachstandardform.AnthemRecordID);
                            engageformid.put(eachstandardform.AnthemRecordID,eachstandardform.CSLTFormStatus);
                            
                        }
                    }
                    }
                    
                }
                
                
            }
            system.debug('castlightoppfullist:'+castlightoppfullist);
            system.debug('engagestandardscopingformid:'+engagestandardscopingformid);
            
            if (!castlightoppfullist.isempty() || castlightoppfullist.size() > 0) {
                upsert castlightoppfullist CSLT_Opportunity_Id__c;
            }
            if(engagestandardscopingformid.size() >0)
            {
            for(Engage_Scoping_And_Engage_Standard__c eachform: [select id,Form_Status__c from Engage_Scoping_And_Engage_Standard__c where id in :engagestandardscopingformid])
            {
                eachform.Form_Status__c=engageformid.get(eachform.id);
                engageformlist.add(eachform);
                
            }
            if(!engageformlist.isempty() || engageformlist.size() > 0)
            {
                update engageformlist;
            }
                
            }
            res.statusCode = 200;
            res.responseBody = Blob.valueOf('Opportunity status processed successfully');
            //added for SIT testing purpose
            if(org.IsSandbox){
            	CastLightProcessBatchStatus.CSLTToAnthProcessStatusEmail(RestContext.request.requestBody.toString(), 'Success');
            }

        }
        Catch(Exception ex) {
            res.statusCode = 500;
            res.responseBody = Blob.valueOf(String.valueOf(ex) + '\n\n' + ex.getStackTraceString());
            
            CastLightProcessBatchStatus.CSLTToAnthProcessStatusEmail(RestContext.request.requestBody.toString(), String.valueOf(ex) + '\n\n' + ex.getStackTraceString());
          
        }
        
        //return res;
    }
}