objects/Compensation_Estimator_Goal__c.object
<CustomObject>
    <description>Stores values for the goals used in the Sales Compensation Estimator (Calculator).  Goals are typically used to calculate percent attainment across lines of business.  Goals are only applicable for new business, but not renewals</description>
    <fields>
        <fullName>Refresh__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Refresh YTD Sold And Prorated Goal</label>
        <type>Checkbox</type>
    </fields>
    <label>Compensation Estimator Goal</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Unique ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Compensation Estimator Goals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CompensationEstimatorGoalTriggerHandler.cls
/*
@Author : Suman Manjunatha(Avengers)
@CreateDate : 5th March 2020
@description : Handler for Compensation Estimator Goal Object - Created for PRDCRM-53813
*/
public with sharing class CompensationEstimatorGoalTriggerHandler {
    /*
    @description :Method is invoked on before insert event
    @name :onBeforeInsert
    @param :trigger.new
    */
    public static void onBeforeInsert(List<Compensation_Estimator_Goal__c> newCEG){
        CompensationEstimatorGoalActions.updateYTDMembersAndPremium(newCEG);
    }
    /*
    @description :Method is invoked on before update event
    @name :onBeforeUpdate
    @param :trigger.oldMap,trigger.new
    */
    public static void onBeforeUpdate(Map<Id,Compensation_Estimator_Goal__c> oldValMap,List<Compensation_Estimator_Goal__c> newVals){
        List<Compensation_Estimator_Goal__c> newCegList = new List<Compensation_Estimator_Goal__c>();
        for(Compensation_Estimator_Goal__c ceg:newVals){
            if((ceg.Refresh__c!=oldValMap.get(ceg.Id).Refresh__c) && ceg.Refresh__c==true){
                newCegList.add(ceg);
            }
        }
        CompensationEstimatorGoalActions.updateYTDMembersAndPremium(newCegList);
    }
}