objects/ContactRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <inlineHelpText>To select more than one contact type, hold the control (ctrl) key and select the values.</inlineHelpText>
        <label>Contact Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Anthem Account Service Rep</fullName>
                </value>
                <value>
                    <fullName>Anthem Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Anthem Secondary Executive Sponsor</fullName>
                </value>
                <value>
                    <fullName>Benefits</fullName>
                </value>
                <value>
                    <fullName>Board Member</fullName>
                </value>
                <value>
                    <fullName>Billing Contact</fullName>
                </value>
                <value>
                    <fullName>CFO</fullName>
                </value>
                <value>
                    <fullName>CHRO</fullName>
                </value>
                <value>
                    <fullName>Consultant</fullName>
                </value>
                <value>
                    <fullName>COO</fullName>
                </value>
                <value>
                    <fullName>Decision Maker</fullName>
                </value>
                <value>
                    <fullName>Finance/CFO</fullName>
                </value>
                <value>
                    <fullName>Group Administrator</fullName>
                </value>
                <value>
                    <fullName>HIPAA Privacy Officer</fullName>
                </value>
                <value>
                    <fullName>HIPAA Rep</fullName>
                </value>
                <value>
                    <fullName>HR Mgr/Dir</fullName>
                </value>
                <value>
                    <fullName>Human Resources</fullName>
                </value>
                <value>
                    <fullName>MEU Contact</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Pathways to Health</fullName>
                </value>
                <value>
                    <fullName>President/CEO</fullName>
                </value>
                <value>
                    <fullName>Reference</fullName>
                </value>
                <value>
                    <fullName>Region Dir</fullName>
                </value>
                <value>
                    <fullName>Third Party Admin</fullName>
                </value>
                <value>
                    <fullName>TPA Account Manager</fullName>
                </value>
                <value>
                    <fullName>TPA Claims Analyst</fullName>
                </value>
                <value>
                    <fullName>TPA Client Liaison</fullName>
                </value>
                <value>
                    <fullName>Vice President</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Account To Contact Relationships</relationshipLabel>
        <relationshipName>Contact_Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NEW_BSNS_TERM_DT__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>NEW BSNS TERM DT</label>
        <type>Date</type>
    </fields>
    <label>Contact Relationship</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LHOL_Q__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>LHOL Q</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CMIntegrationServiceTestDataFactory.cls
public class CMIntegrationServiceTestDataFactory {
    public static void prepareTestData() {

        // Create common test accounts
		Account acc=IntegrationTestDataUtilty.createAccount(true); 
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        
        Quote Qte = new Quote();
		Qte.Name = 'Test Quote';
        Qte.OpportunityId = oppty.Id;
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        Qte.Pricebook2Id = customPB.id;
        Qte.GroupNumber__c = grp.id;
        
        insert Qte;
        Order ImplCase = new Order(Implementation_Effective_Date__c = system.today(),
                             Implementation_Status__c = 'Initiated',
                             Implementation_Type__c = 'New Business',
                             User_Group__c = 'Local New Business',
                             Production_Date__c = system.today(),
                             EffectiveDate = system.today(),
                             Status = 'Draft',
                             //LHOL_Q__c = 'true',
                             AccountId = Acc.Id,
                             QuoteId = Qte.Id,
                             OpportunityId = oppty.Id);
        
        insert ImplCase;

        Contact con1 = new contact();
        con1.AccountId = acc.Id;
        con1.LastName = 'testCon';
        insert con1;
        
        ContactRelationship__c cr1 = new ContactRelationship__c();
        cr1.Account__c = acc.Id;
        cr1.Contact__c = con1.id;
        cr1.EndDate__c = system.today().addDays(2);
        cr1.NEW_BSNS_TERM_DT__c = system.today().addDays(2);
        cr1.Contact_Type__c = 'Group Administrator';
        insert cr1;
        
	}
}