objects/ContentVersion.object
<CustomObject>
    <fields>
        <fullName>CaseId__c</fullName>
        <description>This field is created as part of 2433 to stamp the case Id from while the unzipped file is pushed to salesforce from JAVA.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>CaseId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Request Tracking ID</label>
        <referenceTo>Request_Tracking__c</referenceTo>
        <relationshipLabel>Content Versions</relationshipLabel>
        <relationshipName>Content_Versions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_Tracking_Name__c</fullName>
        <formula>Request_Tracking_ID__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request Tracking Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Status_Details__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Status Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Response Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

objects/NLP_Status_Code_Mapping__mdt.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NLP Status Code Mapping</label>
    <pluralLabel>&apos;NLP Status Code Mappings</pluralLabel>
</CustomObject>

objects/object__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>object</label>
    <nameField>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>objects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Request_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>CaseID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CaseID</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Request Tracking</relationshipLabel>
        <relationshipName>Request_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RequestID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Request Tracking</label>
    <nameField>
        <displayFormat>RT-{0000}</displayFormat>
        <label>Request Tracking Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Request Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/NLPFileStatusViewerController.cls
/*
********************************************************************************************
* Name          NLPFileStatusViewerController
* Author        Ethan Park
* ModifiedBy    Ethan Park
* CreatedDate   03/11/2020
* UsedBy        nLPFileStatusViewer to retrieve NLP file processing status
*********************************************************************************************
*/
public with sharing class NLPFileStatusViewerController {
    @TestVisible
    private static final String GENERIC_ERROR_STATUS_CODE = 'E2ENLP.500.0';
    @TestVisible
    private static final String STATUS_CODE_200 = '200';
    @TestVisible
    private static final String STATUS_CODE_200_IN_PROGRESS = '200In Progress';
    private static final String STATUS_CODE_200_SUCCESS = '200Success';
    private static final String STATUS_ERROR = 'Error';
    private static final String STATUS_OBJECT_CONTENT_VERSION = 'Content Version Object';
    private static final String STATUS_OBJECT_REQUEST_TRACKING = 'Request Tracking Object';
    
    /*
    * @This method is called from nLPFileStatusViewer and used to get NLP file processing status
    * @Name: getNLPFileStatus
    * @Created Date: 03/11/2020
    * @Author: Ethan Park
    * @Description Jira user story PRCDM2-1508
    */
    @AuraEnabled(cacheable = true)
    public static List<ContentVersion> getNLPFileStatus(Id recordId)
    {
        try {
            List<EmailMessage> listEmailMessages = [Select Id From EmailMessage Where ParentId =:recordId ];
            Set<Id> emailMessageIds = new Set<Id>();
            for(EmailMessage emailobj :listEmailMessages){
                emailMessageIds.add(emailobj.Id);
            }            
            List<ContentDocumentLink> contentDocumentLinks = [
                SELECT Id, LinkedEntityId, ContentDocumentId, ContentDocument.Title
                FROM ContentDocumentLink
                WHERE ( LinkedEntityId =: recordId OR LinkedEntityId IN :emailMessageIds ) AND IsDeleted = FALSE
            ];
            Set<Id> contentDocumentIds = new Set<Id>();
            for(ContentDocumentLink item :contentDocumentLinks) {
                contentDocumentIds.add(item.ContentDocumentId);
            }

            List<ContentVersion> contentVersions = [
                SELECT Id, ContentDocumentId, ContentDocument.Title, Error_Message__c, CreatedDate,
                    Response_Status__c, Response_Status_Details__c, Request_Tracking_ID__c,
                    Request_Tracking_Name__c, ContentModifiedDate
                FROM ContentVersion
                WHERE ContentDocumentId IN :contentDocumentIds
                    AND IsDeleted = FALSE
                    AND IsLatest = TRUE
                ORDER BY ContentModifiedDate DESC
            ];

            List<Request_Tracking__c> requestTrackings = [
                SELECT Id, CaseID__c, Status__c, RequestID__c
                FROM Request_Tracking__c
                WHERE CaseID__c = :recordId
            ];
            Map<String, Request_Tracking__c> requestTrackingByRequestId
                = new Map<String, Request_Tracking__c>();
            for(Request_Tracking__c item :requestTrackings) {
                requestTrackingByRequestId.put(item.Id, item);
            }

            List<NLP_Status_Code_Mapping__mdt> statusMetadata = [
                SELECT Id, DeveloperName, Error_Message__c, Object__c, Status_Code__c, Status__c, Description__c
                FROM NLP_Status_Code_Mapping__mdt
                ORDER BY Status__c
            ];
            Map<String, NLP_Status_Code_Mapping__mdt> statusMapByStatusCode
                = new Map<String, NLP_Status_Code_Mapping__mdt>();
            for(NLP_Status_Code_Mapping__mdt item : statusMetadata) {
                if(item.Status_Code__c == STATUS_CODE_200) {
                    if(item.Object__c == STATUS_OBJECT_CONTENT_VERSION) {
                        statusMapByStatusCode.put(STATUS_CODE_200_SUCCESS, item);
                    } else {
                        statusMapByStatusCode.put(STATUS_CODE_200_IN_PROGRESS, item);
                    }
                } else {
                    statusMapByStatusCode.put(item.Status_Code__c, item);
                }
            }

            for(ContentVersion item :contentVersions) {
                Request_Tracking__c requestTracking = null;
                if(requestTrackingByRequestId.containsKey(item.Request_Tracking_ID__c)) {
                    requestTracking = requestTrackingByRequestId.get(item.Request_Tracking_ID__c);
                }

                if(String.isBlank(item.Response_Status__c)) {
                    if(requestTracking != null && !String.isBlank(requestTracking.Status__c) &&
                        (statusMapByStatusCode.containsKey(requestTracking.Status__c) || requestTracking.Status__c == STATUS_CODE_200)) {
                        if (requestTracking.Status__c == STATUS_CODE_200) {
                            item.Response_Status__c = STATUS_CODE_200_IN_PROGRESS;
                        } else {
                            item.Response_Status__c = requestTracking.Status__c;
                        }
                    } else {
                        item.Response_Status__c = GENERIC_ERROR_STATUS_CODE;
                    }
                } else if (item.Response_Status__c != STATUS_CODE_200) {
                    if(!statusMapByStatusCode.containsKey(item.Response_Status__c)) {
                        item.Response_Status__c = GENERIC_ERROR_STATUS_CODE;
                    }
                } else {
                    item.Response_Status__c = STATUS_CODE_200_SUCCESS;
                }

                if(statusMapByStatusCode.get(item.Response_Status__c).Error_Message__c == null) {
                    item.Error_Message__c = '';
                } else {
                    item.Error_Message__c = statusMapByStatusCode.get(item.Response_Status__c).Error_Message__c;
                }

                item.Response_Status__c = statusMapByStatusCode.get(item.Response_Status__c).Status__c;
            }

            return contentVersions;
        } catch (Exception e) {
            throw new AuraHandledException('Something went wrong from the Controller: ' + e.getMessage());
        }
    }
}