objects/Contract_Reservation_Service_Call_Log__c.object
<CustomObject>
    <description>Stores the request and response messages of the Contract Code Reservation Service integration.</description>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <description>Tracks the contract code received as a response from the service.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Contract Reservation Service Call Log</label>
    <nameField>
        <displayFormat>CRSLog-{000000}</displayFormat>
        <label>CRS Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contract Reservation Service Call Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Funding__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Funding</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Performance_Indicator__c</fullName>
        <label>Performance Indicator</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Disability</fullName>
                </value>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Situs State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/LG_Riders__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <description>This field holds the date from which the Rider is effective.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>LG_Rider</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Riders Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LG_Riders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ProductSelectionDetail__c.object
<CustomObject>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Product Selection Detail</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Product Selection Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Selection Details</pluralLabel>
    <recordTypes>
        <fullName>LG_Rider_Plan_Assoc</fullName>
        <active>true</active>
        <label>LG_Rider_Plan_Assoc</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GroupSize__c</fullName>
        <formula>Text(Opportunity.Account.Group_Size__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GroupSize</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Non_Pooled__c</fullName>
        <formula>Text(Opportunity.Account.Pooled_Non_Pooled__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Non-Pooled</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <formula>TEXT(Opportunity.Account.Situs_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Situs State</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Actwise_Member_Provider_Pay_Indicator__c</fullName>
        <description>Act-Wise member / provider pay indicator directs EBA to know which code applies. This information must be provided to EBA by the submitter.</description>
        <label>Actwise Member / Provider Pay Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Member Pay</fullName>
                </value>
                <value>
                    <fullName>Provider Pay</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Anthem_Engage_Indicators__c</fullName>
        <description>Engage indicators must be populated by the submitter for EBA to know which indicator to code. It is a requirement.</description>
        <label>Anthem Engage Indicators</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>K2</fullName>
                    <label>K2- Anthem Engage Basic</label>
                </value>
                <value>
                    <fullName>9</fullName>
                    <label>9- Must be selected if you choose K2/K3 Value (BASIC/STANDARD)</label>
                </value>
                <value>
                    <fullName>No value coding</fullName>
                    <label>No value coding - Opting out of Anthem Engage Basic</label>
                </value>
                <value>
                    <fullName>K3</fullName>
                    <label>K3- Anthem Engage Standard Buy Up</label>
                </value>
                <value>
                    <fullName>K5</fullName>
                    <label>K5 - Anthem Engage Basic with Care and Cost Finder</label>
                </value>
                <value>
                    <fullName>K6</fullName>
                    <label>K6 - Anthem Engage Standard with Care and Cost Finder</label>
                </value>
                <value>
                    <fullName>AA</fullName>
                    <label>AA - MUST be selected if you are going to choose KK (Elite)</label>
                </value>
                <value>
                    <fullName>KK</fullName>
                    <label>KK - Anthem Engage Elite</label>
                </value>
                <value>
                    <fullName>BB</fullName>
                    <label>BB - Anthem Engage Elite Reference Based Benefits Buy-up</label>
                </value>
                <value>
                    <fullName>CC</fullName>
                    <label>CC - Anthem Engage Elite Pharmacy: Carve-in</label>
                </value>
                <value>
                    <fullName>C2</fullName>
                    <label>C2 - Anthem Engage Elite Pharmacy: Carve-out</label>
                </value>
                <value>
                    <fullName>DD</fullName>
                    <label>DD - Anthem Engage Elite Dental: Carve-in Administratively Integrated</label>
                </value>
                <value>
                    <fullName>D2</fullName>
                    <label>D2 - Anthem Engage Elite Dental: Carve-out</label>
                </value>
                <value>
                    <fullName>EE</fullName>
                    <label>EE - Anthem Engage Elite Elevate Buy-up: BH Carve-in and EAP Carve-in</label>
                </value>
                <value>
                    <fullName>E2</fullName>
                    <label>E2 - Anthem Engage Elite Elevate Buy-up: BH Carve-out and EAP Carve-out</label>
                </value>
                <value>
                    <fullName>E3</fullName>
                    <label>E3 - Anthem Engage Elite Elevate Buy-up: BH Carve-in and EAP Carve-out</label>
                </value>
                <value>
                    <fullName>E4</fullName>
                    <label>E4 - Anthem Engage Elite Elevate Buy-up: BH Carve-out and EAP Carve-in</label>
                </value>
                <value>
                    <fullName>FF</fullName>
                    <label>FF - Anthem Engage Elite Rewards Buy-up</label>
                </value>
                <value>
                    <fullName>JJ</fullName>
                    <label>JJ - Anthem Engage Elite Analytics Buy-up</label>
                </value>
                <value>
                    <fullName>GG</fullName>
                    <label>GG - Anthem Engage Specialty Rx Buy-up: Carve-in</label>
                </value>
                <value>
                    <fullName>G2</fullName>
                    <label>G2 - Anthem Engage Specialty Rx Buy-up: Carve-out</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CEP_Indicator__c</fullName>
        <label>CEP Indicator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                    <isActive>false</isActive>
                    <label>N/A</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Codes__c</fullName>
        <formula>Product2.Contract_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <formula>IF(ISBLANK(TermDate__c),IF(ISBLANK(Benefit_Year_Plan_Date__c), OpportunityEffectiveDate__c , Benefit_Year_Plan_Date__c) , TermDate__c)</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Quote.GroupNumber__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HPCC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HPCC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityEffectiveDate__c</fullName>
        <formula>Quote.Opportunity.CloseDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Opportunity Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Modified</fullName>
                </value>
                <value>
                    <fullName>Non-Pooled Standard</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Pooled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State_Abbrev__c</fullName>
        <formula>Quote.Opportunity.Account.Situs_State_Abbrev__c</formula>
        <label>Situs_State_Abbrev</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vlocity_ins__ContractCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContCodeReservServiceTest.cls
@isTest(SeeAllData=false)
public class ContCodeReservServiceTest {
    
    
    @isTest static void testContCodeReserve() {
        Test.startTest();
        ContCodeReservRequest rr = new ContCodeReservRequest();
        ContCodeReserveResponse res = new ContCodeReserveResponse();
        
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponseMockTest());
        
        res = ContCodeReservService.reserveContractCode(rr);
       
        system.debug('status********:' + res.Status.code);
        system.assertEquals('Contract codes(s) reserved successfully for the domain', res.Status.message);
        system.assertEquals('200', res.Status.code);
        system.assertEquals('4BMQ', res.contractCode);
        
        
        Test.stopTest();
    }
    
    @isTest 
    static void testContCodeReserveFailure() {
        Test.startTest();
        ContCodeReservRequest rr = new ContCodeReservRequest();
        ContCodeReserveResponse res = new ContCodeReserveResponse();
        
        ContCodeReservServiceUtility servUtility = new ContCodeReservServiceUtility();
        rr.baseContract = '';
      
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponsefailureMockTest());
        
        res = servUtility.reserveContractCode(rr);
        
        ContCodeReservServiceUtility.ContCodeAPITokenDetails tokendetails = new ContCodeReservServiceUtility.ContCodeAPITokenDetails();
        tokendetails = servUtility.getAuthToken();
       
        system.debug('status********:' + res.Status.code);
        //system.assertEquals('Invalid Input Parameter -  baseContract cannot be empty for processing the request', res.Status.message);
        system.assertEquals('400', res.Status.code);
        system.assertEquals('salesforce-large-gro', tokendetails.application_name);
        system.assertEquals('1557336486513', tokendetails.issued_at);
        system.assertEquals('899', tokendetails.expires_in);
        system.assertEquals('dv2JGaEOEl6p40WTKd17', tokendetails.client_id);
        system.assertEquals('approved', tokendetails.status);
        system.assertEquals(true, tokendetails.isNewToken); 
        system.assertEquals(null, tokendetails.currentTime); 
        Test.stopTest();
    } 
    
 /*   @isTest static void testContCodeRelease() {
        Test.startTest();
        ContCodeReleaseRequest rres = new ContCodeReleaseRequest();
        rres.callingSystem ='PMT';
        String[] conCodes = new String[]{'00GF'};
            rres.contractCodes = conCodes;
        rres.txnId='12345678';
          Test.setMock(HttpCalloutMock.class, new ContCodeReleaseResponseMockTest());
        ContCodeReservService.releaseContractCode(rres);
        
        Test.stopTest();
    } */
    
    static testMethod void testConCodeReservParse() {
        /*String json = '{"domain": {"lineOfBusiness": ["MED","PHARM" ],"businessEntity": "ABCBS","marketSegment": "LG","businessUnit": "LOCAL" }, "effectiveDate": "2019-04-22","expiryDate": "2019-12-31","comment": "RELEASE TESTING","contractCodeCount": 1,"callingSystem": "PMT","txnId": "1234567","txnTimestamp": ""}';*/
        String json = '{"callingSystem":"SFDCCOM2", "baseContract": "47KB", "planModifiedInd": "Y", "actwiseIndicator": "Member", "engageIndicators":"K2,9", "hpcc": "HM26", "fundingTypeCode": "ASO", "stateCode": "OH", "quoteLineItem": "NA", "effectiveDate": "2019-04-01", "groupSize": "100 - 249", "baseContractType": "Custom", "CEPIndicator": "N","performanceGuarantee": "Y", "caseID":"4701", "wgsgroupID": "15", "transactionId": "7aa6821b-aadd-41e8-8b34-83a3d8b5961e201906200513", "transactionTimestamp": "2018-05-16T08:05:15.222Z", "poolingStatus": "Y"}';
        ContCodeReservRequest.parse(json);
    }
    
  /*  static testMethod void testConCodeReleaseParse() {
        String json = '{"contractCodes": ["00EU"],"callingSystem": "PMT","txnId": "2345678","txnTimestamp": ""}';
        ContCodeReleaseRequest.parse(json);
    } */
    
     /*This method will create test data*/
    static QuoteLineItem createData()
    {
       Account acc=IntegrationTestDataUtilty.createAccount(true); 
       System.debug('Test Account ID :'+acc.id);
       
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        
        Quote qte=IntegrationTestDataUtilty.createQuote(oppty.Id, grp.id, true);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(true);
        prod.Contract_Code__c = '40QA';
        Database.update(prod);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        QuoteLineItem qlitest = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, true);
       
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.vlocity_ins__ContractCode__c = '40QA';
        System.debug(qli);         
        return qli;
        
    }
    
    @isTest
    static void testbuildRequest(){
        
        Order od = createImplCaseTestData();
        insert od;
        QuoteLineItem qli = [Select Id, Contract_Codes__c, vlocity_ins__ContractCode__c, Actwise_Member_Provider_Pay_Indicator__c, Anthem_Engage_Indicators__c, HPCC_Code__c, Product2.HPCC_code__c, Product_Type__c,
                                             Funding__c, Situs_State_Abbrev__c, Quote.Account.Situs_State__c, EffectiveDate__c, Quote.GroupNumber__r.Effective_Date__c, Quote.GroupSize__c, Plan_Type__c, Product2.Plan_Type__c,  
                                             CEP_Indicator__c, Group_Number__c, Quote.Non_Pooled__c, OpportunityEffectiveDate__c, Quote.GroupNumber__r.Performance_Indicator__c, P2AModified__c,  Quote.Account_Name__c,
                                             Quote.GroupNumber__r.Date_Migrated_to_WGS__c, HCR_Status__c
                                             FROM QuoteLineItem 
                                             WHERE quoteId =: od.QuoteId];
        
        ContCodeReservServiceUtility serviceUtility = new ContCodeReservServiceUtility();
        ContCodeReservRequest req = serviceUtility.buildRequest(qli.Id, od);
    }
    
    static Order createImplCaseTestData()
    {
       Account acc=IntegrationTestDataUtilty.createAccount(true); 
      
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        
        Quote qte=IntegrationTestDataUtilty.createQuote(oppty.Id, grp.id, true);
        
        Order ImplCaseTestCoverage =   IntegrationTestDataUtilty.createImplCase(Qte.Id, Acc.Id, true); 
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(false);
        prod.Category__c = 'Plan';
        prod.Product_Type__c = 'Medical';
        prod.Contract_Code__c = '40QA';
        Database.insert(prod);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.ProductStage__c = 'Sold';
        qli.vlocity_ins__ContractCode__c = '40QA';
        Database.insert(qli);
        
        Order ImplCase =   IntegrationTestDataUtilty.createImplCase(Qte.Id, Acc.Id, false); 
         
        return ImplCase;
    }
    @isTest
    static void testReservContCodeforImplCase(){
        
        Order Implcase = createImplCaseTestData();
        Database.insert(Implcase);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(false);
        prod.Category__c = 'Plan';
        prod.Product_Type__c = 'Medical';
        prod.Contract_Code__c = '40QA';
        Database.insert(prod);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(ImplCase.QuoteId, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.ProductStage__c = 'Sold';
        Database.insert(qli);
        
        LG_Riders__c rider = new LG_Riders__c(Name = 'Test Rider 001');
        Database.insert(rider);
        System.debug('Rider : '+ rider);
        
        String recTypeId = Schema.getGlobalDescribe().get('ProductSelectionDetail__c').getDescribe().getRecordTypeInfosByName().get('LG_Rider_Plan_Assoc').getRecordTypeId(); 
        ProductSelectionDetail__c prodSelectDetail = new ProductSelectionDetail__c(QuoteLineItem__c = qli.Id, Rider__c = rider.Id, RecordTypeId = recTypeId);
        Database.insert(prodSelectDetail);
        System.debug('Prod Select : '+ prodSelectDetail); 
       Contract_Reservation_Service_Call_Log__c servclog = new Contract_Reservation_Service_Call_Log__c();
       servclog.Implementation_Case_Id__c = Implcase.Id;
       servclog.Quote_Line_Item_Id__c = qli.Id;
       servclog.Status_Code__c = 'SUCCESS';
       Database.insert(servclog);
        
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponseMockTest());
        
        Test.startTest();  
        ContCodeReservService.contractCodeReserveServiceCallout(Implcase.Id);  
        Test.stopTest();
        
        List<Contract_Reservation_Service_Call_Log__c> servicelogs = [Select Id, Status_Code__c, Quote_Line_Item_ID__c, Implementation_Case_Id__c from Contract_Reservation_Service_Call_Log__c];
        System.assertEquals(2, servicelogs.size());
        
    }
    @isTest
    static void testFailureReservContCodeforImplCase(){
        
        Order Implcase = createImplCaseTestData();
        Database.insert(Implcase);
       
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponsefailureMockTest());
        
        Test.startTest();  
        ContCodeReservService.contractCodeReserveServiceCallout(Implcase.Id);  
        Test.stopTest();
        
        List<Contract_Reservation_Service_Call_Log__c> servicelogs = [Select Id, Status_Code__c, Quote_Line_Item_ID__c, Implementation_Case_Id__c from Contract_Reservation_Service_Call_Log__c];
        System.assertEquals(1, servicelogs.size());
        
    }
    
    
    @isTest
    static void testcontractCodeReserveServiceCalloutImpl(){
        
        Order Implcase = createImplCaseTestData();
        Database.insert(Implcase);
        
        List<QuoteLineItem> qlis = [Select Id, Contract_Codes__c, vlocity_ins__ContractCode__c, Actwise_Member_Provider_Pay_Indicator__c, Anthem_Engage_Indicators__c, HPCC_Code__c, Product2.HPCC_code__c, Product_Type__c,
                                             Funding__c, Situs_State_Abbrev__c, Quote.Account.Situs_State__c, EffectiveDate__c, Quote.GroupNumber__r.Effective_Date__c, Quote.GroupSize__c, Plan_Type__c, Product2.Plan_Type__c,  
                                             CEP_Indicator__c, Group_Number__c, Quote.Non_Pooled__c, OpportunityEffectiveDate__c, Quote.GroupNumber__r.Performance_Indicator__c, P2AModified__c,  Quote.Account_Name__c,
                                             Quote.GroupNumber__r.Date_Migrated_to_WGS__c, HCR_Status__c
                                             FROM QuoteLineItem 
                                             WHERE quoteId =: Implcase.QuoteId];
        
        LG_Riders__c rider = new LG_Riders__c(Name = 'Test Rider 001');
        Database.insert(rider);
        System.debug('Rider : '+ rider);
        
        String recTypeId = Schema.getGlobalDescribe().get('ProductSelectionDetail__c').getDescribe().getRecordTypeInfosByName().get('LG_Rider_Plan_Assoc').getRecordTypeId(); 
        ProductSelectionDetail__c prodSelectDetail = new ProductSelectionDetail__c(QuoteLineItem__c = qlis[0].Id, Rider__c = rider.Id, RecordTypeId = recTypeId);
        Database.insert(prodSelectDetail);
        System.debug('Prod Select : '+ prodSelectDetail); 
  
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponseMockTest());
        
        Test.startTest();  
        ContCodeReservService.contractCodeReserveServiceCalloutImpl(Implcase.Id);  
        Test.stopTest();
        
        List<Contract_Reservation_Service_Call_Log__c> servicelogs = [Select Id from Contract_Reservation_Service_Call_Log__c];
        System.assertEquals(1, servicelogs.size());
        
        Order ImplCaseUpdated = [Select Id, CC_Service_Invoked__c from Order where Id=: ImplCase.Id];
        System.assertEquals(true, ImplCaseUpdated.CC_Service_Invoked__c);
        
    }
    @isTest
    static void testFailurecontractCodeReserveServiceCalloutImpl(){
        
        Order Implcase = createImplCaseTestData();
        Database.insert(Implcase);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(false);
        prod.Category__c = 'Plan';
        prod.Product_Type__c = 'Medical';
        prod.Contract_Code__c = '40QA';
        Database.insert(prod);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(ImplCase.QuoteId, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.ProductStage__c = 'Sold';
        Database.insert(qli);
        
       Contract_Reservation_Service_Call_Log__c servclog = new Contract_Reservation_Service_Call_Log__c();
       servclog.Implementation_Case_Id__c = Implcase.Id;
       servclog.Quote_Line_Item_Id__c = qli.Id;
       servclog.Status_Code__c = 'SUCCESS';
       Database.insert(servclog);
  
        Test.setMock(HttpCalloutMock.class, new ContCodeReserveResponsefailureMockTest());
        
        Test.startTest();  
        ContCodeReservService.contractCodeReserveServiceCalloutImpl(Implcase.Id);  
        Test.stopTest();
        
        List<Contract_Reservation_Service_Call_Log__c> servicelogs = [Select Id from Contract_Reservation_Service_Call_Log__c];
        System.assertEquals(2, servicelogs.size());
        
    }
    
     @isTest
    static void testSendEmail(){
        
        Test.startTest();  
        ContCodeReservService.sendEmail('Test Attachment Body', 1, 0);  
        Integer invocations = Limits.getEmailInvocations();
        Test.stopTest();
       
        System.assertEquals(1, invocations);
        
    }
    
    @isTest
    static void IntegrationUtilCatchTest(){
    
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(null, true);
        
        Group__c grp=IntegrationTestDataUtilty.createGroup(null, true);
        
        Quote qte=IntegrationTestDataUtilty.createQuote(null, null, true);
        
        Order ImplCaseTestCoverage =   IntegrationTestDataUtilty.createImplCase(null, null, true); 
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(null, true);
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(null, null, true);
        
        Account acc=IntegrationTestDataUtilty.createAccount('Test Account','CO', null, 'Local/Large Group',true);
        Account accFailTest = IntegrationTestDataUtilty.createAccount('Test Account','CO', 'LG Customer', 'Local/Large Group',true);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct('32DQ',true);
        Product2 prodFail=IntegrationTestDataUtilty.createProduct(null,true);
    }
}