objects/CSLT_Integration_Process_Log__c.object
<CustomObject>
    <description>Tracks opportunities sent to Castlight.</description>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>OpportunityId</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Castlight Integration Process Logs</relationshipLabel>
        <relationshipName>Castlight_Integration_Process_Logs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_update__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send update</label>
        <type>Checkbox</type>
    </fields>
    <label>Castlight Integration Process Log</label>
    <nameField>
        <displayFormat>CSLTLog-{0000000}</displayFormat>
        <label>CSLT Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Castlight Integration Process Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CastLightProcessLogUpdate.cls
/* ***************************************************************************
Class Name   : CastLightProcessLogUpdate 
Date Created : 20-Feb-2019
Created By   : Legato
Description  : This gets called from the Process Builder "Reset CastLight Send Indicator for QLI update"
******************************************************************************* */
global class CastLightProcessLogUpdate { 
    
    @InvocableMethod
    public static void StatusUpdate(List<Id> oppList){
        Set<Id> oppSet = new Set<Id>(oppList);
        List<CSLT_Integration_Process_Log__c> csltProcessLogList = [SELECT Send_Update__c from CSLT_Integration_Process_Log__c where OpportunityId__c IN :oppSet];
        if(csltProcessLogList != null && !csltProcessLogList.isEmpty())
        {
            for(CSLT_Integration_Process_Log__c csltProcessLog : csltProcessLogList)
            {
                csltProcessLog.Send_update__c = true;
            }
            update csltProcessLogList;
        }
        
    }
}