objects/Defect__c.object
<CustomObject>
    <description>TOOLKIT - This object represents a failure to meet a requirement.</description>
    <fields>
        <fullName>Detailed_Description__c</fullName>
        <description>Detailed Description of the defect</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Detailed Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Retest_Status__c</fullName>
        <description>Status of retest of the defect</description>
        <label>Retest Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Retesting_Comments__c</fullName>
        <description>Comments on retesting of the defect</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Retesting Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the defect</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Approved By Business - Ready to Assign</fullName>
                </value>
                <value>
                    <fullName>Developer Assigned</fullName>
                </value>
                <value>
                    <fullName>Fix in Process</fullName>
                </value>
                <value>
                    <fullName>Fixed</fullName>
                </value>
                <value>
                    <fullName>Can Not Reproduce</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Open Salesforce.com Request</fullName>
                </value>
                <value>
                    <fullName>Future Enhancement Consideration</fullName>
                </value>
                <value>
                    <fullName>Expected Behavior</fullName>
                </value>
                <value>
                    <fullName>Resolved</fullName>
                </value>
                <value>
                    <fullName>Assigned to Business Analyst</fullName>
                </value>
                <value>
                    <fullName>Closed - Can Not Reproduce</fullName>
                </value>
                <value>
                    <fullName>Closed - Duplicate</fullName>
                </value>
                <value>
                    <fullName>Closed - Expected Behavior</fullName>
                </value>
                <value>
                    <fullName>Closed - Not a defect</fullName>
                </value>
                <value>
                    <fullName>Closed - Rejected</fullName>
                </value>
                <value>
                    <fullName>Closed - Resolved</fullName>
                </value>
                <value>
                    <fullName>Closed - Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Monitor</fullName>
                </value>
                <value>
                    <fullName>Need More Information</fullName>
                </value>
                <value>
                    <fullName>Ready to Retest</fullName>
                </value>
                <value>
                    <fullName>Re-Opened - Failed Retest</fullName>
                </value>
                <value>
                    <fullName>Re-opened</fullName>
                </value>
                <value>
                    <fullName>Set Default as True</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Subject of the defect</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Subject</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Times_Reopened__c</fullName>
        <description>Used to Store the number of time the defect has been reopened</description>
        <label>#of Times Reopened</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Defect</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Defect ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Defects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/UpdateReopenedCountTriggerTest.cls
@isTest
public class UpdateReopenedCountTriggerTest {
    
    static testmethod void UpdateReopenedCountTestMethod1(){
        Defect__c newDef = new Defect__c(Status__c = 'Failed Retest', Subject__c = 'efgh', Detailed_Description__c = 'New Test',Times_Reopened__c=0);
        insert(newDef);
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listNewDef= [SELECT Id FROM Defect__c WHERE id =: newDef.id]; 
        System.assertEquals(1, listNewDef.size(),'Record Not Present'); 
        System.assertNotEquals(0, listNewDef.size(),'Record Not Present'); 
        // End | Adding Assert Check PRDCRM-44931
        
        newDef.Status__c = 'Expected Behaviour';
        update newDef;
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listDefectsAfterUpdate = [SELECT Id, Status__c, Times_Reopened__c FROM Defect__c WHERE id =: newDef.id]; 
        Defect__c updatedDefect = listDefectsAfterUpdate[0];
        System.assertEquals(0, updatedDefect.Times_Reopened__c,'Times_Reopened__c increased by 1'); 
        System.assertNotEquals(1, updatedDefect.Times_Reopened__c,'Times_Reopened__c increased by 1'); 
        // End | Adding Assert Check PRDCRM-44931
    }
    
    static testmethod void UpdateReopenedCountTestMethod2(){
        Defect__c newDef2 = new Defect__c(Status__c = 'Closed', Subject__c = 'efgh', Detailed_Description__c = 'New Test');
        insert(newDef2);
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listNewDef2= [SELECT Id FROM Defect__c WHERE id=:newDef2.id]; 
        System.assertEquals(1, listNewDef2.size(),'Record Not Present'); 
        System.assertNotEquals(0, listNewDef2.size(),'Record Not Present');  
        // End | Adding Assert Check PRDCRM-44931        
        
        newDef2.Status__c = 'Resolved';
        update newDef2;
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listDefectsAfterUpdate = [SELECT Id, Status__c, Times_Reopened__c FROM Defect__c WHERE id =: newDef2.id]; 
        Defect__c updatedDefect = listDefectsAfterUpdate[0];
        System.assertEquals(null, updatedDefect.Times_Reopened__c,'Times_Reopened__c increased by 1'); 
        System.assertNotEquals(1, updatedDefect.Times_Reopened__c,'Times_Reopened__c increased by 1');  
        // End | Adding Assert Check PRDCRM-44931
    }
    
    static testmethod void updateReopenedCountTestMethod3(){
        Defect__c newDef2 = new Defect__c(Status__c = 'In Progress', Subject__c = 'efgh', Detailed_Description__c = 'New Test', Times_Reopened__c=11);
        insert(newDef2);
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listNewDef2= [SELECT Id FROM Defect__c WHERE id=:newDef2.id]; 
        System.assertEquals(1, listNewDef2.size(),'Record Not Present'); 
        System.assertNotEquals(0, listNewDef2.size(),'Record Not present'); 
        // End | Adding Assert Check PRDCRM-44931
        
        newDef2.Status__c = 'RE-OPENED';
        newDef2.Retest_Status__c='Open';
        newDef2.Retesting_Comments__c = 'XYZ';
        update newDef2;
        
        // Start | Adding Assert Check PRDCRM-44931
        List<Defect__c> listDefectsAfterUpdate = [SELECT Id, Status__c, Times_Reopened__c FROM Defect__c WHERE id =: newDef2.id]; 
        Defect__c updatedDefect = listDefectsAfterUpdate[0];
        System.assertEquals(12, updatedDefect.Times_Reopened__c,'Times_Reopened__c did not increase by 1'); 
        System.assertNotEquals(11, updatedDefect.Times_Reopened__c,'Times_Reopened__c did not increase by 1'); 
        // End | Adding Assert Check PRDCRM-44931
    }
}