objects/DNC_Preferences__c.object
<CustomObject>
    <fields>
        <fullName>AccountDNC__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DNC Preferences</relationshipLabel>
        <relationshipName>DNC_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment_Count__c</fullName>
        <label>Attachment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DNC_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DNC Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DNC_Reason__c</fullName>
        <label>DNC Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Preference</fullName>
                </value>
                <value>
                    <fullName>Employer Preference</fullName>
                </value>
                <value>
                    <fullName>Broker Preference</fullName>
                </value>
                <value>
                    <fullName>Sales Preference</fullName>
                </value>
                <value>
                    <fullName>Contractual</fullName>
                </value>
                <value>
                    <fullName>Review Communications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DNC__c</fullName>
        <label>DNC</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Member Marketing</fullName>
                </value>
                <value>
                    <fullName>Member Clinical</fullName>
                </value>
                <value>
                    <fullName>Pharmacy - Cost of Care</fullName>
                </value>
                <value>
                    <fullName>Pharmacy - Quality of Care</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Preference_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Preference Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <label>Requested By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager</fullName>
                    <default>true</default>
                    <label>Account Manager</label>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Pending Submission - Need Attachment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DNC Preferences</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>DNC Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DNC Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DNC_DNCPreferencesHandler_Test.cls
/****************************************************************
Class Name   : DNC_DNCPreferencesHandler_Test
Date Created : 24-Apr-2018
Created By   : Deloitte USI
Description  : Test class for DNC_DNCPreferencesHandler 
*****************************************************************/
@isTest
private class DNC_DNCPreferencesHandler_Test {
  
     // test before and after update
    @isTest
    static void test_update() {
        List<Account> accList = new List<Account>();
        Account acct = new Account(Name = staticVariableClass.DNCTstAcc);
         accList.add(acct);
        insert accList;
        
        List<DNC_Preferences__c> dncList = new List<DNC_Preferences__c>();
         DNC_Preferences__c dncPref = new DNC_Preferences__c(AccountDNC__c = acct.Id);
         dncPref.Status__c = staticVariableClass.DNCStatusNew;
         dncPref.Group_Preference_Comment__c = staticVariableClass.DNCStrGrpPref;
         dncPref.DNC_Effective_Date__c = Date.Today() + 1;
         dncPref.DNC__c = staticVariableClass.DNCStrGrp;
         dncPref.Requested_By__c = staticVariableClass.DNCStrAccManager;
         dncPref.DNC_Reason__c = staticVariableClass.DNCStrEmpPref;
         dncPref.Attachment_Count__c = 2;
         dncList.add(dncPref);
         insert dncList;
        
        accList[0].DNC_Preference_ID__c = dncList[0].Id;
        update accList[0];
        
        test.StartTest();
        
        DNC_DNCPreferencesHandler.onBeforeUpdateIsFirstRun = true;
        DNC_DNCPreferencesHandler.onAfterUpdateIsFirstRun = true;
        dncList[0].Status__c = staticVariableClass.DNCStatusApproved;
        update dncList;
        test.StopTest();
}
//test before delete
@isTest
    static void test_delete() {
        List<Account> accList = new List<Account>();
        Account acct = new Account(Name = staticVariableClass.DNCTstAcc);
         accList.add(acct);
        insert accList;
        
        List<DNC_Preferences__c> dncList = new List<DNC_Preferences__c>();
         DNC_Preferences__c dncPref = new DNC_Preferences__c(AccountDNC__c = acct.Id);
         dncPref.Status__c = staticVariableClass.DNCStatusPen;
         dncPref.Group_Preference_Comment__c = staticVariableClass.DNCStrGrpPref;
         dncPref.DNC_Effective_Date__c = Date.Today() + 1;
         dncPref.DNC__c = staticVariableClass.DNCStrGrp;
         dncPref.Requested_By__c = staticVariableClass.DNCStrAccManager;
         dncPref.DNC_Reason__c = staticVariableClass.DNCStrEmpPref;
         dncPref.Attachment_Count__c = 2;
         dncList.add(dncPref);
         insert dncList;
        
        test.StartTest();
        DNC_DNCPreferencesHandler.onBeforeDeleteIsFirstRun= true;
        delete dncList;
        test.StopTest();
}
}