objects/DNC_Preferences__c.object
<CustomObject>
    <fields>
        <fullName>AccountDNC__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>DNC Preferences</relationshipLabel>
        <relationshipName>DNC_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Attachment_Count__c</fullName>
        <label>Attachment Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DNC_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>DNC Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DNC_Reason__c</fullName>
        <label>DNC Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Preference</fullName>
                </value>
                <value>
                    <fullName>Employer Preference</fullName>
                </value>
                <value>
                    <fullName>Broker Preference</fullName>
                </value>
                <value>
                    <fullName>Sales Preference</fullName>
                </value>
                <value>
                    <fullName>Contractual</fullName>
                </value>
                <value>
                    <fullName>Review Communications</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DNC__c</fullName>
        <label>DNC</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Group</fullName>
                </value>
                <value>
                    <fullName>Member Marketing</fullName>
                </value>
                <value>
                    <fullName>Member Clinical</fullName>
                </value>
                <value>
                    <fullName>Pharmacy - Cost of Care</fullName>
                </value>
                <value>
                    <fullName>Pharmacy - Quality of Care</fullName>
                </value>
                <value>
                    <fullName>Survey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Preference_Comment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Preference Comment</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <label>Requested By</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account Manager</fullName>
                    <default>true</default>
                    <label>Account Manager</label>
                </value>
                <value>
                    <fullName>Employer</fullName>
                </value>
                <value>
                    <fullName>Account Executive</fullName>
                </value>
                <value>
                    <fullName>Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Pending Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Recalled</fullName>
                </value>
                <value>
                    <fullName>Pending Submission - Need Attachment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>DNC Preferences</label>
    <nameField>
        <displayFormat>A{0000}</displayFormat>
        <label>DNC Preferences Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DNC Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/DNC_DNCPreferencesHandler.cls
/****************************************************************
Class Name   : DNC_DNCPreferencesHandler
Date Created : 19-APR-2018
Created By   : Deloitte USI
Description  : DNC Handler class for DNCPreferenceTrigger
*****************************************************************/
public with sharing class DNC_DNCPreferencesHandler {

    public static boolean onAfterUpdateIsFirstRun = true;
    public static boolean onBeforeUpdateIsFirstRun = true;
    public static boolean onBeforeDeleteIsFirstRun = true;

    public static void onBeforeUpdate(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
        requireAttachmentIfApproved(dncList, oldMap);
    }

    public static void onAfterUpdate(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
        updateParentAccount(dncList, oldMap);
    }
    
    public static void onBeforeDelete(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
        updateParentAccountPref(dncList, oldMap);
    }

    /*
    Method Name : requireAttachmentIfApproved
    Parameter   : List<DNC_Preferences__c>, Map<Id, DNC_Preferences__c>
    Return type : none
    Description : This method is used validate that a DNC Approval record has attached documentation before every approval
   */
    public static void requireAttachmentIfApproved(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
        for(DNC_Preferences__c dnc : dncList) {
            //Check if status is updated
            if(dnc.Status__c != oldmap.get(dnc.Id).Status__c) {
                //Check if new status is 'Approved'
                if(('Approved').equalsIgnoreCase(dnc.Status__c)) {
                    if(dnc.Attachment_Count__c == null || dnc.Attachment_Count__c < 1) {
                        dnc.addError(staticVariableClass.DNCError);
                    }
                }
            }
        }
    }

   /*
    Method Name : updateParentAccount
    Parameter   : List<DNC_Preferences__c>, Map<Id, DNC_Preferences__c>
    Return type : none
    Description : This method is used to update DNC Preferences fields on the DNC Preferences records' parent Account records
    */
     public static void updateParentAccountPref(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
       try{
            //Set to hold all the accounts record IDs to be retrieved and updated
            Set<Id> acctIds = new Set<Id>();
            //Map of account IDs and their related DNC Preferences record
            Map<Id, DNC_Preferences__c> acctDNCMap = new Map<Id, DNC_Preferences__c>(); 
    
            for(DNC_Preferences__c dnc : dncList) {
                if(('Pending Approval').equalsIgnoreCase(dnc.Status__c) || ('Pending Submission - Need Attachment').equalsIgnoreCase(dnc.Status__c)) {
                    acctIds.add(dnc.AccountDNC__c);
                }
            }
            
            List<Account> accts = [SELECT Id, DNC_Preference_ID__c 
                                        FROM Account 
                                        WHERE Id in :acctIds];     
            
            for(Account a : accts) {
                //set DNC Preferences ID field to blank, to indicate that the record has already been processed
                a.put('DNC_Preference_ID__c','');// changed as part of Code Coverage fix
               // a.DNC_Preference_ID__c = ''; 
            }
    
            //update Account records
            if(!accts.isEmpty()) {
                update accts;
            }
        }
        catch(Exception e){
          System.debug('Exception'+e.getMessage());
        }
        
    }
  
    /*
    Method Name : updateParentAccount
    Parameter   : List<DNC_Preferences__c>, Map<Id, DNC_Preferences__c>
    Return type : none
    Description : This method is used to update DNC Preferences fields on the DNC Preferences records' parent Account records
    */
     public static void updateParentAccount(List<DNC_Preferences__c> dncList, Map<Id, DNC_Preferences__c> oldMap) {
       try{
            //Set to hold all the accounts record IDs to be retrieved and updated
            Set<Id> acctIds = new Set<Id>();
            //Map of account IDs and their related DNC Preferences record
            Map<Id, DNC_Preferences__c> acctDNCMap = new Map<Id, DNC_Preferences__c>(); 
            for(DNC_Preferences__c dnc : dncList) {
                //Check if status is updated
                if(dnc.Status__c != oldmap.get(dnc.Id).Status__c) {                    
                    //Check if new status is 'Approved' or 'Rejected' - indicates that the record is being approved/rejected
                    if(('Approved').equalsIgnoreCase(dnc.Status__c) || ('Rejected').equalsIgnoreCase(dnc.Status__c) || ('Recalled').equalsIgnoreCase(dnc.Status__c)) {
                      //add to account ID list
                        acctIds.add(dnc.AccountDNC__c);
                        //add to Account-DNC map
                        acctDNCMap.put(dnc.AccountDNC__c, dnc);
                    }
                }
            }
           
            List<Account> accts = [SELECT Id, DNC_Preference_ID__c 
                                        FROM Account 
                                        WHERE Id in :acctIds];                        
            DNC_Preferences__c dnc = null;
            
            for(Account a : accts) {
                //set DNC Preferences ID field to blank, to indicate that the record has already been processed
                //a.DNC_Preference_ID__c = ''; 
                a.put('DNC_Preference_ID__c',''); 
    
                //retrieve the related DNC record for the account
                dnc = acctDNCMap.get(a.Id);
                //if DNC Preferences status is 'Approved', copy all DNC fields to the Account
                if(('Approved').equalsIgnoreCase(dnc.Status__c)) {
                    a.DNC__c                        = dnc.DNC__c;
                    a.DNC_Effective_Date__c         = dnc.DNC_Effective_Date__c;
                    a.DNC_Reason__c                 = dnc.DNC_Reason__c;
                    a.Group_Preference_Comment__c   = dnc.Group_Preference_Comment__c;
                    a.Requested_By__c               = dnc.Requested_By__c;
                }
            }
    
            //update Account records
            if(!accts.isEmpty()) {
                update accts;
            }
        }
        catch(Exception e){
          System.debug('Exception'+e.getMessage());
        }
        
    }
}