objects/Enrollment_and_Billing__c.object
<CustomObject>
    <fields>
        <fullName>Case_Installation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Installation</label>
        <referenceTo>Issue_Control__c</referenceTo>
        <relationshipLabel>Membership</relationshipLabel>
        <relationshipName>Membership</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Case_Name__c</fullName>
        <formula>Implementation_Tracking_ID__r.Implementation_Case_Name1__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipName>Enrollment_and_Billing</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Membership</label>
    <nameField>
        <displayFormat>MEMBERSHIP-{000000}</displayFormat>
        <label>Membership Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Membership</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ID_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Implementer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned Implementer</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ID_Cards2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case_Installation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case Installation</label>
        <referenceTo>Issue_Control__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Case_Name__c</fullName>
        <formula>Implementation_Tracking_ID__r.Implementation_Case_Name1__c</formula>
        <label>Implementation Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <formula>HYPERLINK(    Implementation_Tracking_ID__r.Implementation_Record_ID__c  , Implementation_Tracking_ID__r.Implementation_Record_ID__r.OrderNumber )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Record ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership</label>
        <referenceTo>Enrollment_and_Billing__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ID Cards</label>
    <nameField>
        <displayFormat>IDCARD-{000000}</displayFormat>
        <label>ID Cards Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Cards</pluralLabel>
    <recordTypes>
        <fullName>Local</fullName>
        <active>true</active>
        <label>Local</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Implementation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Implementer__c</fullName>
        <formula>Implementation_Record_ID__r.Assigned_Implementer__r.FirstName + &apos; &apos; +  Implementation_Record_ID__r.Assigned_Implementer__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned Implementer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <formula>&quot;TRACK&quot; + &quot; &quot;  +   Implementation_Record_ID__r.OrderNumber</formula>
        <label>Implementation Tracking ID</label>
        <type>Text</type>
    </fields>
    <label>Implementation Tracking</label>
    <nameField>
        <displayFormat>TRACK-{000000}</displayFormat>
        <label>Implementation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Issue_Control__c.object
<CustomObject>
    <fields>
        <fullName>Implementation_Case_Name__c</fullName>
        <formula>Implementation_Tracking_ID__r.Implementation_Case_Name1__c</formula>
        <label>Implementation Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipName>Issue_Controls</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Membership__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Membership</label>
        <referenceTo>Enrollment_and_Billing__c</referenceTo>
        <relationshipLabel>Case Installation</relationshipLabel>
        <relationshipName>Case_Installation</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Case Installation</label>
    <nameField>
        <displayFormat>CASINS-{000000}</displayFormat>
        <label>Case Installation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Installation</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/IDCardActions.cls
/*
@Author : Rahul(Vikings)
@CreateDate : 08/20/2019
@description : Handles ID card Actions
@name :IDCardActions
*/
public with sharing class IDCardActions{
    /*
    @description :populates Assigned Implementer when stage is changed to Pending Card Review.Jira ID: 39701
    @name :populateIDcardAssignedImplementer
    @param :trigger.new
    */
    public Static Void populateIDcardAssignedImplementer(List<ID_Cards__c> listIDCardsNew){
        List<ID_Cards__c> idCardList = new List<ID_Cards__c>();
        Set<ID> implementationTrackingID = new Set<ID>();
        Map<ID,Implementation_Tracking__c> trackingMap;
        
            for(ID_Cards__c idcard:listIDCardsNew){
                if(idcard.Implementation_Case_Name__c!=null){
                    idCardList.add(idcard);
                    implementationTrackingID.add(idcard.Implementation_Tracking_ID__c);
                }
            }
            
            if(!implementationTrackingID.isEmpty()){
                trackingMap= new Map<ID,Implementation_Tracking__c>([SELECT Implementation_Record_ID__r.Assigned_Implementer__c  from Implementation_Tracking__c  where ID IN :implementationTrackingID]);
            }
            
            for(ID_Cards__c varIdCard:idCardList){
                if(trackingMap.containsKey(varIdCard.Implementation_Tracking_ID__c)){ 
                    varIdCard.Assigned_Implementer__c=trackingMap.get(varIdCard.Implementation_Tracking_ID__c).Implementation_Record_ID__r.Assigned_Implementer__c;
                }
            } 
       }
       
    /** Author       ::: Ranjith Kumar
    **  Purpose      ::: To tie up with Case Installation and membership in ID Cards.
    **  Created Date ::: 17th Feb 2020
    ** Execution     ::: Before Insert.
    **/
    public static void populateCaseInstMembership(List<ID_Cards__c> idCardsList){
        Set<Id> impltrackingId=new Set<Id>();
        List<ID_Cards__c> idCardsnewList=new List<ID_Cards__c>();
        Id localRecordTypeId = Schema.SObjectType.ID_Cards__c.getRecordTypeInfosByName().get('Local').getRecordTypeId();
        
        for(ID_Cards__c idcard : idCardsList){
            if(idcard.Implementation_Tracking_ID__c!=null && idcard.RecordTypeId==localRecordTypeId){
                impltrackingId.add(idcard.Implementation_Tracking_ID__c);
                idCardsnewList.add(idcard);
            }
        }
        
        Map<Id,Issue_Control__c> casInstMap=new Map<Id,Issue_Control__c>();
        Map<Id,Enrollment_and_Billing__c> membMap=new Map<Id,Enrollment_and_Billing__c>();
        if(impltrackingId.size()>0){
            for(Issue_Control__c csinst : [SELECT Id,Name,Implementation_Tracking_ID__c FROM Issue_Control__c WHERE Implementation_Tracking_ID__c=:impltrackingId]){
                casInstMap.put(csinst.Implementation_Tracking_ID__c,csinst);
            }
            
            for(Enrollment_and_Billing__c memb : [SELECT Id,Name,Implementation_Tracking_ID__c FROM Enrollment_and_Billing__c WHERE Implementation_Tracking_ID__c=:impltrackingId]){
                membMap.put(memb.Implementation_Tracking_ID__c,memb);
            }
        }
        
        if(idCardsnewList.size()>0){
            for(ID_Cards__c idcard : idCardsnewList){
                if(casInstMap.containsKey(idcard.Implementation_Tracking_ID__c)){
                    idcard.Case_Installation__c=casInstMap.get(idcard.Implementation_Tracking_ID__c).Id;
                }
                if(membMap.containsKey(idcard.Implementation_Tracking_ID__c)){
                    idcard.Membership__c=membMap.get(idcard.Implementation_Tracking_ID__c).id;
                }
            }
        }
        
    }
    
}