objects/Enrollment_user_notification__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of email addresses, which should be notified if consultant volunteers for event</description>
    <fields>
        <fullName>Email__c</fullName>
        <caseSensitive>true</caseSensitive>
        <encryptionScheme>None</encryptionScheme>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <label>Enrollment user notification</label>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup for the OE Coordinator so that email alerts can be sent when meetings are submitted or changed</description>
        <inlineHelpText>Please select your Open Enrollment Coordinator - For Central and South West - Colleen Douma, For North East - Colleen Jacobs, For West - Bethany Snee.</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <infoMessage>This field will be populated after save</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment (OE Coordinator)</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Participant__c.object
<CustomObject>
    <description>A junction object used for linking Volunteer Events to a participant</description>
    <fields>
        <fullName>Facilitator_Type__c</fullName>
        <formula>TEXT(OE_Ambassador_Volunteer__r.Facilitator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Facilitator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OE_Ambassador_Volunteer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>(LG20140424)- Please consult Dev Team before changing this field.  The OE Ambassador who volunteered for the parent meeting from the force.com site</description>
        <label>OE Ambassador Volunteer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.ContactAccountName__c</field>
                <operation>equals</operation>
                <value>Open Enrollment</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>Volunteer_Participants</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Volunteer_Event__c</fullName>
        <label>Meeting Name</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>R00N30000001WZmFEAW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OE Ambassador Volunteers</label>
    <nameField>
        <displayFormat>Volunteer_ID {0000}</displayFormat>
        <label>Volunteer Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OE Ambassador Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VolunteerParticipantEmailServiceImpl.cls
/***************************************************************
  * Purpose:  Service class for sending emails to event coordinators, if someone volunteers
  * Mod:     6 December 2016
  * Author:  Martin Kona
  * Mehaboob: Lifted and Shifted from COM1 - PRDCRM-39696
  ***************************************************************/

public class VolunteerParticipantEmailServiceImpl implements VolunteerParticipantEmailService {

  public static final String CONSULTANT_TYPE = 'Consultant';
  public static final String OE_AMBASSADOR_TYPE = 'OE Ambassador';
  public static final String OE_COORDINATOR_TYPE = 'OE Coordinator';
  
  public static final String EMAIL_FROM = 'donotreply@wellpoint.com';
  public static final String EMAIL_SUBJECT = 'Volunteer Submitted';
  public static final String SENDER_DISPLAY_NAME = 'Open Enrollment Ambassador Program';

  @TestVisible
  private List<String> notificationUsers {
    get {
      if (notificationUsers == NULL) {
        notificationUsers = new List<String>();
        List<Enrollment_user_notification__c> mcs = Enrollment_user_notification__c.getall().values();

        for (Enrollment_user_notification__c mc : mcs) {
          notificationUsers.add(mc.Email__c);
        }
      }

      return notificationUsers;
    }
    set;
  }


  public List<SFDC_Volunteer_Participant__c> getVolunteerInfo(Set<Id> volunteerParticipantIds) {

    List<SFDC_Volunteer_Participant__c> volunteers = [select id, 
        Volunteer_Event__r.Name, Volunteer_Event__r.OE_Coordinator_Contact__r.Email,
        Volunteer_Event__r.Date__c, OE_Ambassador_Volunteer__r.FirstName, 
        OE_Ambassador_Volunteer__r.LastName,OE_Ambassador_Volunteer__r.Facilitator_Type__c 
        from SFDC_Volunteer_Participant__c 
      where id IN :volunteerParticipantIds];

    // validation of records?

    return volunteers;
  }

  public List<Messaging.SingleEmailMessage> configureEmailMessages(List<SFDC_Volunteer_Participant__c> emailParameters) {

    List<Messaging.SingleEmailMessage> msgs = new List<Messaging.SingleEmailMessage>();

    for (SFDC_Volunteer_Participant__c emailParameter : emailParameters) {

      Messaging.SingleEmailMessage msg = new Messaging.SingleEmailMessage();

      // if consultant, then notify users from custom setting
      if (emailParameter.OE_Ambassador_Volunteer__r.Facilitator_Type__c == CONSULTANT_TYPE) {
        msg.setToAddresses(notificationUsers);
      } else {
        msg.setToAddresses(
          new List<String>{emailParameter.Volunteer_Event__r.OE_Coordinator_Contact__r.Email});
      }

      msg.setReplyTo(EMAIL_FROM);
      msg.setSubject(EMAIL_SUBJECT);
      msg.setSenderDisplayName(SENDER_DISPLAY_NAME);
      msg.setHtmlBody(initBodyHTML(emailParameter));

      msgs.add(msg);
    }

    return msgs;
  }

  public String initBodyHTML(SFDC_Volunteer_Participant__c bodyParameters) {

    String formattedDate=String.valueOf(bodyParameters.Volunteer_Event__r.Date__c);
    formattedDate=formattedDate.substring(0,10);

    String strBody = 'You have a new volunteer for one of your meetings. The details is listed below. <br/><br/>';
      strBody = strBody + '<table width=900px>';
      strBody = strBody + '<tr><td width=15% bgcolor=silver><b>Meeting</b></td><td width=85%>' 
      + bodyParameters.Volunteer_Event__r.Name + '</td></tr>';
      strBody = strBody + '<tr><td width=15% bgcolor=silver><b>Date</b></td><td width=85%>' 
      + formattedDate+'</td></tr>';
      strBody = strBody + '<tr><td width=15% bgcolor=silver><b>Volunteer</b></td><td width=85%>' 
      + bodyParameters.OE_Ambassador_Volunteer__r.FirstName + ' ' 
      + bodyParameters.OE_Ambassador_Volunteer__r.LastName + '</td></tr>';
      strBody = strBody + '</tr></table><br/>';
      strBody = strBody + 'Thank You<br/><br/>';
      strBody = strBody + 'The Open Enrollment Team';  

    return strBody;
  }

  public class MyException extends Exception {}
}