objects/Funding__c.object
<CustomObject>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <recordTypes>
        <fullName>Funding</fullName>
        <active>true</active>
        <label>Funding</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_Code_ASF__c</fullName>
        <formula>IF( ISBLANK(  vlocity_ins__ContractCode__c ) , Product2.Contract_Code__c  , vlocity_ins__ContractCode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Custom Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Codes__c</fullName>
        <formula>Product2.Contract_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Funding</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPCC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HPCC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IC_OpportunityId__c</fullName>
        <formula>CASESAFEID( Quote.OpportunityId )</formula>
        <label>IC OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Quote.OpportunityId</formula>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Modified</fullName>
                </value>
                <value>
                    <fullName>Non-Pooled Standard</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Pooled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductLOB__c</fullName>
        <formula>IF(
NOT(ISBLANK(TEXT(Product2.LOB__c))),
TEXT(Product2.LOB__c),
LEFT( TEXT(Product2.LOB_Org__c),LEN(TEXT(Product2.LOB_Org__c))-2 )
)</formula>
        <label>ProductLOB</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__ContractCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SBC_SOB_Request__c.object
<CustomObject>
    <fields>
        <fullName>Actual_SBC_Completion_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Actual SBC Completion Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Standard Contract Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Custom_Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Custom Contract Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Type</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HPCC_Code__c</fullName>
        <defaultValue>&apos; &apos;</defaultValue>
        <encryptionScheme>None</encryptionScheme>
        <label>HPCC Code</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>SBC_SOB_Request</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Type</label>
        <type>TextArea</type>
    </fields>
    <label>Custom SBC/SOB Request</label>
    <nameField>
        <displayFormat>SBC/SOB-{0000}</displayFormat>
        <label>Custom SBC/SOB Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom SBC/SOB Request</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QuoteLineItemActions.cls
/**************************************************************************************
Apex Class Name:  QuoteLineItemActions
Version     : 1.0 
Created Date    : 11 December 2019
* @Author: X-men Offshore(Smita)
@description: Class to update SBC/SOB Request fields(Hpcc,Contract Code,Custom Contract Code,Plan Type,Funding Type) whenever 
              Quotelineitem fields(Hpcc,Contract Code,Custom Contract Code,Plan Type,Funding Type) are edited.
US          : PRDCRM-45634
*************************************************************************************/
public with sharing class QuoteLineItemActions {

  /*@description :Method to get the quotelineitems*/  
    public static void updateSBC(Map<Id,QuoteLineItem> newQuoteMap,Map<Id,QuoteLineItem> oldQuoteMap){
        
        Set<ID> quoteId=new Set<ID>();
        Set<ID> opptyId=new Set<ID>();
        List<quotelineitem> quoteList=new List<quotelineitem>();
        List<SBC_SOB_Request__c> sbcList=new List<SBC_SOB_Request__c>();
        List<order> orderList=new List<order>();
        List<String> productStage=new List<String>();
        Quotelineitem quoteOld=new Quotelineitem();
        
        productStage.add('IGAP Sold');
        productStage.add('Renewed');
        productStage.add('Sold');
        productStage.add('In Progress');
        productStage.add('IGAP In Progress');
        productStage.add('Jeopardy');
        
        for(QuoteLineItem quo :newQuoteMap.values()){
            quoteOld=oldQuoteMap.get(quo.id);
            if(quo.Plan_Type__c!=quoteOld.Plan_Type__c||quo.Funding__c!=quoteOld.Funding__c||quo.Contract_Codes__c!=quoteOld.Contract_Codes__c||quo.vlocity_ins__ContractCode__c!=quoteOld.vlocity_ins__ContractCode__c||quo.HPCC_Code__c!=quoteOld.HPCC_Code__c){
                    
                    quoteId.add(quo.id);
                    opptyId.add(quo.IC_OpportunityId__c);       
            }
            }
        
        if(quoteId.size()>0){
            
        quoteList=[select id,ProductLOB__c,Funding__c,Contract_Code_ASF__c,HPCC_Code__c,Contract_Codes__c,
                       Plan_Type__c,opportunity__c,OpportunityId__c,vlocity_ins__ContractCode__c,
                       Product2.LOB__c,quote.OpportunityId,ProductStage__c from quotelineitem 
                       where quote.OpportunityId=:opptyId
                       AND ProductLOB__c='Medical' AND ProductStage__c =:productStage];
        
        sbcList=[select id,Opportunity__c,Funding_Type__c,Custom_Contract_Code__c,HPCC_Code__c,Contract_Code__c,
                 Plan_Type__c,Actual_SBC_Completion_Date__c from SBC_SOB_Request__c where Opportunity__c=:opptyId];
        
        updateSbcRequest(quoteList,sbcList);
        }    
    }
    
    /*@description : Method to update SBC/SOB object*/
    private static void updateSbcRequest(List<quotelineitem> quoteList,List<SBC_SOB_Request__c> sbcList){
        
        List<SBC_SOB_Request__c> sbcRecordListUpdate=new List<SBC_SOB_Request__c>();
        String sbcHpccString='';
        String sbcContractCodeString='';
        String sbcPlanTypeString='';
        String sbcFundingString='';
        String sbcCustomContractCodeString='';
        String sbcImplementationString='';
        
        Id profileId = UserInfo.getProfileId();
        String profileName =[Select Id, Name from Profile where Id=:profileId].Name;
        
        
        for(SBC_SOB_Request__c sbc :sbcList){
            
            if(sbc.Actual_SBC_Completion_Date__c==null || profileName==UtilConstants.Api_User || profileName ==UtilConstants.System_Admin || profileName ==UtilConstants.System_Administrator){
                 
                for(QuoteLineItem qli :quoteList){
                
                if(qli.OpportunityId__c==sbc.Opportunity__c){
                    
                    sbcHpccString=SBCSOBActions.concatHpcc(qli.HPCC_Code__c,sbcHpccString);
                    sbcContractCodeString=SBCSOBActions.concatContract(qli.Contract_Codes__c,sbcContractCodeString);
                    sbcPlanTypeString=SBCSOBActions.concatPlanType(qli.Plan_Type__c,sbcPlanTypeString);
                    sbcFundingString=SBCSOBActions.concatFunding(qli.Funding__c,sbcFundingString);
                    sbcCustomContractCodeString=SBCSOBActions.concatCustomContract(qli.vlocity_ins__ContractCode__c,sbcCustomContractCodeString);
                }
            }
            sbc.HPCC_Code__c=sbcHpccString;
            sbc.Contract_Code__c=sbcContractCodeString;
            sbc.Plan_Type__c=sbcPlanTypeString;
            sbc.Funding_Type__c=sbcFundingString;
            sbc.Custom_Contract_Code__c=sbcCustomContractCodeString;
            sbcRecordListUpdate.add(sbc); 
        }  
      }  
        
       if(sbcRecordListUpdate.size()>0){
           
             update sbcRecordListUpdate;
        } 
    }
    
}