objects/Funding__c.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipName>Funding</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>ClaimSystem__c</fullName>
        <label>Claim System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NASCO</fullName>
                </value>
                <value>
                    <fullName>WGS 2.0</fullName>
                </value>
                <value>
                    <fullName>ACES</fullName>
                </value>
                <value>
                    <fullName>ALICS</fullName>
                </value>
                <value>
                    <fullName>AniTa</fullName>
                </value>
                <value>
                    <fullName>CHIPS</fullName>
                </value>
                <value>
                    <fullName>COMPASS</fullName>
                </value>
                <value>
                    <fullName>CS90</fullName>
                </value>
                <value>
                    <fullName>DeCare Dental</fullName>
                </value>
                <value>
                    <fullName>FACETS</fullName>
                </value>
                <value>
                    <fullName>WDS</fullName>
                </value>
                <value>
                    <fullName>GBD FACETS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Line of Business (not the total Opportunity)</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>AHGProduct__c</fullName>
        <formula>OR(CONTAINS(Product2.Name, &quot;Anthem Health Guide&quot;),
    CONTAINS(Product2.Name, &quot;ANTHEM HEALTH GUIDE&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AHG Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ClinicalDeliveryModel__c</fullName>
        <label>Clinical Delivery Model</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Carved out (exception)</fullName>
                </value>
                <value>
                    <fullName>Custom Care Management Unit (CCMU)</fullName>
                </value>
                <value>
                    <fullName>Mercer Health Advantage (MHA)</fullName>
                </value>
                <value>
                    <fullName>IHM</fullName>
                </value>
                <value>
                    <fullName>Local</fullName>
                </value>
                <value>
                    <fullName>National CCM</fullName>
                </value>
                <value>
                    <fullName>Total Health Total You (THTY)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MedicalManagementPlatform__c</fullName>
        <label>Medical Management Platform</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ECC (exception)</fullName>
                </value>
                <value>
                    <fullName>HRS</fullName>
                </value>
                <value>
                    <fullName>HRS/WMDS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MembershipSplitBetweenAHGandNonAHG__c</fullName>
        <description>BW 2015 
New field which is required to submit an Opportunity for AHG approval</description>
        <inlineHelpText>Please explain split population in Background/Further Explanation field. HMO members cannot be supported.</inlineHelpText>
        <label>Membership split between AHG and non-AHG</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes (Please Explain)</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <label>Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Accident</fullName>
                </value>
                <value>
                    <fullName>ActWise Commuter</fullName>
                </value>
                <value>
                    <fullName>ActWise FSA</fullName>
                </value>
                <value>
                    <fullName>ActWise HRA</fullName>
                </value>
                <value>
                    <fullName>ActWise HSA</fullName>
                </value>
                <value>
                    <fullName>AIM</fullName>
                </value>
                <value>
                    <fullName>AIM: Integrated Imaging (RQI)</fullName>
                </value>
                <value>
                    <fullName>AIM: Integrated Imaging &amp; Sleep Management (RQI)</fullName>
                </value>
                <value>
                    <fullName>AIM: Integrated Imaging Full UM</fullName>
                </value>
                <value>
                    <fullName>AIM: Integrated Imaging with a Penalty (RQI+)</fullName>
                </value>
                <value>
                    <fullName>AIM: Integrated Imaging with a Penalty &amp; Sleep Management (RQI+)</fullName>
                </value>
                <value>
                    <fullName>Aligned Incentives</fullName>
                </value>
                <value>
                    <fullName>ANA Custom Networks</fullName>
                </value>
                <value>
                    <fullName>Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Solution</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin: ActWise FSA</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin: FSA</fullName>
                </value>
                <value>
                    <fullName>Benefits Admin: Identity Theft</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>C3 Concierge Cancer Care</fullName>
                </value>
                <value>
                    <fullName>Castlight</fullName>
                </value>
                <value>
                    <fullName>Castlight Core</fullName>
                </value>
                <value>
                    <fullName>CCMU/Maternity Solution</fullName>
                </value>
                <value>
                    <fullName>Cleveland Clinic Concierge</fullName>
                </value>
                <value>
                    <fullName>Critical Illness</fullName>
                </value>
                <value>
                    <fullName>Default</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Dependent Eligibility</fullName>
                </value>
                <value>
                    <fullName>Diabetes Prevention Program</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ServiceTier__c</fullName>
        <label>Service Tier</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>AHG</fullName>
                </value>
                <value>
                    <fullName>Mercer Health Advantage (MHA)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItemApproval__c.object
<CustomObject>
    <fields>
        <fullName>AHGProduct__c</fullName>
        <formula>QuoteLineItem__r.AHGProduct__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AHG Product?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecordType__c</fullName>
        <formula>TEXT(QuoteLineItem__r.RecordType__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Record Type</label>
        <type>Text</type>
    </fields>
    <label>Quote Line Item Approval</label>
    <nameField>
        <displayFormat>QLIA-{00000}</displayFormat>
        <label>Quote Line Item Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Item Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ANA_AP03_QuoteLineItemApproval_Test.cls
/**
@Author : Accenture Offshore Dev team
@name : ANA_AP03_QuoteLineItemApproval_Test
@CreateDate :05-05-2017
@Description : This class is test class for ANA_AP01_AccountContactList class. 
checks for positive and negative cases.
*/
@isTest
private class ANA_AP03_QuoteLineItemApproval_Test {
    private static final string NATIONALAMPROFILE='National Sales'; 
    private static final string CLAIMSYSTEM= 'CS90';
    /* @testSetup
static void setup() {       
Account acc=ANA_UTIL01_TestMethods.createAccount(false); 
Database.insert(acc);
Opportunity oppty=ANA_UTIL01_TestMethods.createOpportunity(acc.id, false);
Date dte=System.today();
oppty.CloseDate=Date.newInstance(dte.year(), dte.month()+1, 5);
Database.insert(oppty);
Group__c grp=ANA_UTIL01_TestMethods.createGroup(acc.id,false);
grp.ClaimSystem__c='CS90';
Database.insert(grp);
Quote qte=ANA_UTIL01_TestMethods.createQuote(oppty.Id, 1)[0];
qte.GroupNumber__c=grp.id;
Database.insert(qte);
QuoteLineItem QLI= ANA_UTIL01_TestMethods.createQuoteLineItem(qte.Id, 1)[0];
Database.insert(QLI);
QuoteLineItemApproval__c qlia=ANA_UTIL01_TestMethods.createQuoteLineItemApproval(QLI.id,1)[0];
Database.insert(qlia);     
}*/
    /*This method will create test data*/
    static QuoteLineItem createData()
    {
        Account acc=ANA_UTIL01_TestMethods.createAccount(false); 
        Database.insert(acc);
        Opportunity oppty=ANA_UTIL01_TestMethods.createOpportunity(false,acc.id);
        Database.insert(oppty);
        Group__c grp=ANA_UTIL01_TestMethods.createGroup(acc.id,false);
        grp.ClaimSystem__c=CLAIMSYSTEM;
        Database.insert(grp);
        Quote qte=ANA_UTIL01_TestMethods.createQuote(false,oppty.Id);
        qte.GroupNumber__c=grp.id;
        Database.insert(qte);
        Product2 prod=ANA_UTIL01_TestMethods.createProduct(false);
        prod.name='Anthem Health Guide';
        Database.insert(prod);
        PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false,prod.id);
        Database.insert(pbe);
        QuoteLineItem qli= ANA_UTIL01_TestMethods.createQuoteLineItem(false,qte.Id, pbe.id);
        return qli;
    }
    /*This method will test the functionality of submitApproval in positive scenario*/
     static testmethod void submitApprovalPositive(){
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1 ]; 
        User usr=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        usr.BypassValidation__c=True;
        usr.UserName='postest@anthem.com';
        system.runAs(usr){
            QuoteLineItem qli= createData();
            //qli.AHGProduct__c=true;
            qli.Funding__c='ASO';           
            qli.MedicalManagementPlatform__c='HRS/WMDS';
            qli.MembershipSplitBetweenAHGandNonAHG__c='No';
            qli.Members__c=52;
            qli.ClinicalDeliveryModel__c='IHM'; 
            qli.ServiceTier__c='AHG';
            qli.RecordType__c='AIM';            
            Database.insert(qli);
            QuoteLineItemApproval__c qlia=ANA_UTIL01_TestMethods.createQuoteLineItemApproval(QLI.id,1)[0];
            Database.insert(qlia);
            Map<String,Object> inputmap=new Map<String,Object>();
            Map<String,Object> outputmap=new Map<String,Object>();
            Map<String,Object> options=new Map<String,Object>();
            String methodName='submitApproval';           
            outputmap.put('error','OK');
            options.put('useQueueableApexRemoting',true); 
            inputmap.put('ContextId',qli.Id);
            inputmap.put('QLIid',QLI.Id);
            ANA_AP03_QuoteLineItemApproval actct=new ANA_AP03_QuoteLineItemApproval();
            Boolean approvalRes= actct.invokeMethod(methodName,inputmap,outputmap,options);  
            system.assertEquals(true,approvalRes);  
            methodName='recallApproval';
            Boolean recallRes= actct.invokeMethod(methodName,inputmap,outputmap,options);  
        }
    }
    /*This method will test the functionality of submitApproval in negative scenario*/
    static testmethod void submitApprovalNegative(){
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1 ]; 
        User usr=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        usr.UserName='negtest@anthem.com';
        usr.BypassValidation__c=True;
        system.runAs(usr){
            QuoteLineItem qli= createData();        
            Database.insert(qli);
            QuoteLineItemApproval__c qlia=ANA_UTIL01_TestMethods.createQuoteLineItemApproval(qli.id,1)[0];
            Database.insert(qlia);
            Map<String,Object> inputmap=new Map<String,Object>();
            Map<String,Object> outputmap=new Map<String,Object>();
            Map<String,Object> options=new Map<String,Object>();
            String methodName='submitApproval';           
            outputmap.put('error','OK');
            options.put('useQueueableApexRemoting',true); 
            inputmap.put('ContextId',QLI.Id);
            ANA_AP03_QuoteLineItemApproval actct=new ANA_AP03_QuoteLineItemApproval();
            Boolean actual= actct.invokeMethod(methodName,inputmap,outputmap,options);
            system.assertEquals(true,actual);
            methodName='recallApproval';           
            outputmap.put('error','OK');
            options.put('useQueueableApexRemoting',true); 
            inputmap.put('ContextId',QLI.Id);
            ANA_AP03_QuoteLineItemApproval recact=new ANA_AP03_QuoteLineItemApproval();
            Boolean recal= recact.invokeMethod(methodName,inputmap,outputmap,options);
            system.assertEquals(true,recal);
        }
    }
}