objects/Funding__c.object
<CustomObject>
    <label>Funding (WGS Only)</label>
    <nameField>
        <displayFormat>FUND-{000000}</displayFormat>
        <label>Funding Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding (WGS Only)</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupSize__c</fullName>
        <formula>Text(Opportunity.Account.Group_Size__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GroupSize</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GrpNumber__c</fullName>
        <formula>GroupNumber__r.Name</formula>
        <label>GrpNumber</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <formula>TEXT(Opportunity.Account.Situs_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Situs State</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Benefit Year</fullName>
                </value>
                <value>
                    <fullName>Plan Year</fullName>
                    <isActive>false</isActive>
                    <label>Plan Year</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ClientName__c</fullName>
        <formula>Quote.Opportunity.Account.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EffectiveDate__c</fullName>
        <formula>IF(ISBLANK(TermDate__c),IF(ISBLANK(Benefit_Year_Plan_Date__c), OpportunityEffectiveDate__c , Benefit_Year_Plan_Date__c) , TermDate__c)</formula>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HCR_Status__c</fullName>
        <label>HCR Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Grandfathered</fullName>
                </value>
                <value>
                    <fullName>Nongrandfathered</fullName>
                    <label>Non-Grandfathered</label>
                </value>
                <value>
                    <fullName>Prior to HCR Mandate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HPCC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HPCC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <formula>TEXT(Product2.Market__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Market</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentQuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to self.</description>
        <label>Parent Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plan Name</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <formula>TEXT(Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductName__c</fullName>
        <formula>Product2.Name</formula>
        <label>ProductName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State_Regular__c</fullName>
        <label>State Regulator</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>CDI-360C</fullName>
                </value>
                <value>
                    <fullName>DMHC-200C</fullName>
                </value>
                <value>
                    <fullName>NA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LGP2AIntegrationController.cls
/*
    Name               :    LGP2AIntegrationController 
    Description        :    Apex controller for Lightning Component - LGP2AHighRoadsCanvas to get the JSON and display values from the quote line object
    Created By         :    Arun Siddappa
*/
public class LGP2AIntegrationController {   
       public class ResponseWrapper {
        @AuraEnabled public String status;        
        @AuraEnabled public String statusMsg;
        @AuraEnabled public String attributeValue;        
        @AuraEnabled public String QuoteLineId;     
        @AuraEnabled public String GroupName;
        @AuraEnabled public String ProductName;     
        @AuraEnabled public String ProductStage;
        @AuraEnabled public String ProductContractCode;     
        @AuraEnabled public String GroupId;
        @AuraEnabled public String GroupSize;     
        @AuraEnabled public String AdministrativeType;
        @AuraEnabled public String FundingType;   
       }
    @AuraEnabled
    public static ResponseWrapper getQuoteDataForNavigation(Id quoteLineId, String sSource) {
        ResponseWrapper oResponseWrapper;
        LGP2AJSON oP2AJsonObj;
        String sEffectiveMonth;
        String sEffectiveDay;
        
        try {
            List<QuoteLineItem> listQtLineItem = [SELECT Quote.Opportunity.Name, ProductStage__c,Quote.Id, Id,ClientName__c,EffectiveDate__c,ProductName__c,
                                                Quote.GrpNumber__c,Product2.Contract_Code__c, Quote.GroupSize__c, Benefit_Period__c, Funding__c, Quote.AccountId,
                                                Quote.Opportunity.Account.TotalNumberofUnionWorkers__c, HPCC_Code__c, Product2.HPCC_Code__c,
                                                State_Regular__c,HCR_Status__c
                                                FROM QuoteLineItem WHERE Id=:quoteLineId];//PRDCRM-50634 - GLD - 201.2 - Added State_Regular__c,HCR_Status__c
            
            oResponseWrapper    = new ResponseWrapper(); 
            if(listQtLineItem.size()>0 && !listQtLineItem.isEmpty()){
                
                oP2AJsonObj         = populateP2AJSON(listQtLineItem[0].Quote.Id,sSource);
            
                for (QuoteLineItem oQtLineItem : listQtLineItem){
                    
                    sEffectiveMonth = getEffectiveMonth(oQtLineItem.EffectiveDate__c.month());
                    sEffectiveDay = getEffectiveDay(oQtLineItem.EffectiveDate__c.day());
                    
                    oResponseWrapper.QuoteLineId = oQtLineItem.Id;
                    oResponseWrapper.ProductName = oQtLineItem.ProductName__c;
                    oResponseWrapper.ProductStage = oQtLineItem.ProductStage__c;
                    oResponseWrapper.ProductContractCode = oQtLineItem.Product2.Contract_Code__c;
                    oResponseWrapper.AdministrativeType =  getAdminType(oQtLineItem.Benefit_Period__c);
                    oResponseWrapper.FundingType = (oQtLineItem.Funding__c == staticVariableClass.FI || oQtLineItem.Funding__c == staticVariableClass.ASO)?oQtLineItem.Funding__c:'';
                    oResponseWrapper.GroupName = oQtLineItem.Quote.Opportunity.Name +' - '+(oQtLineItem.EffectiveDate__c).year()+'-'+sEffectiveMonth+'-'+sEffectiveDay;
                    oResponseWrapper.GroupId = oQtLineItem.Quote.GrpNumber__c;
                    oResponseWrapper.GroupSize = oQtLineItem.Quote.GroupSize__c;
                    
                    oP2AJsonObj.QuoteLineItems = new List<LGP2AJSON.QuoteLineItems>();
                    
                    LGP2AJSON.QuoteLineItems oJSONqtLineItem = new LGP2AJSON.QuoteLineItems();
                    oJSONqtLineItem.SFDCQuoteLineItemId = oQtLineItem.Id;
                    oJSONqtLineItem.CyPyAdministrativeType = getAdminType(oQtLineItem.Benefit_Period__c);
                    oJSONqtLineItem.GroupIdentifier = oQtLineItem.Quote.GrpNumber__c;
                    oJSONqtLineItem.GroupSize = oQtLineItem.Quote.GroupSize__c;            
                    oJSONqtLineItem.OpportunityEffectiveDate = (oQtLineItem.EffectiveDate__c).year()+'-'+sEffectiveMonth+'-'+sEffectiveDay;
                    oJSONqtLineItem.ProductContractCode = oQtLineItem.Product2.Contract_Code__c;
                    oJSONqtLineItem.QuoteLineItemStage = oQtLineItem.ProductStage__c;
                    oJSONqtLineItem.ImplementationRecordStatus = oQtLineItem.ProductStage__c;
                    oJSONqtLineItem.FundingType   = (oQtLineItem.Funding__c == staticVariableClass.FI || oQtLineItem.Funding__c == staticVariableClass.ASO)? oQtLineItem.Funding__c:'';
                    oJSONqtLineItem.hpccCode = oQtLineItem.HPCC_Code__c !=null? oQtLineItem.HPCC_Code__c: oQtLineItem.Product2.HPCC_Code__c;
                   /* if(sSource == staticVariableClass.MODIFY){//PRDCRM-50634 - GLD - 201.2 - Added 2 new parameters for Modify Button
                        oJSONqtLineItem.sStateRegulator = oQtLineItem.State_Regular__c;
                        oJSONqtLineItem.sHcrStatus = oQtLineItem.HCR_Status__c; 
                    }*/
                    
                    oP2AJsonObj.QuoteLineItems.add (oJSONqtLineItem);
                }   
            }  
            oResponseWrapper = getFinalResponse(oP2AJsonObj,oResponseWrapper);
        } catch(Exception ex){ 
            oResponseWrapper.status = (staticVariableClass.FAILED).toUpperCase() + ex.getMessage();
        }
        return oResponseWrapper;
    }
     /*
      Story :PRDCRM-51890 -GLD- Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: Method to prepare Payload for Manage CEP Case Vlocity Action
    _________________________________________________________________________________________
    
    *@param: quoteId - Quote Id on which the button is clicked - Id
    *@param: sSource - Origin name either CEP button or Modify or view  - String
    _________________________________________________________________________________________
    
    *@return: ResponseWrapper
    _________________________________________________________________________________________
    */
    @AuraEnabled
    public static ResponseWrapper getQuoteDataForCEPNavigation(Id quoteId, String sSource){
    
        ResponseWrapper oResponseWrapper;
        LGP2AJSON oP2AJsonObj;
        LGP2AJSON.ParentQli oParentqtLineItem ;
        LGP2AJSON.QuoteLineItems oJSONqtLineItem;
        String sEffectiveMonth;
        String sEffectiveDay;
        
        if(quoteId !=null){
            List<QuoteLineItem> listQlis = new List<QuoteLineItem>(
                [Select Id, EffectiveDate__c, QuoteId,ClientName__c,Product2.Market__c,Product2.Name,Benefit_Period__c, Product2.Product_Type__c, Quote.Opportunity.Account.TotalNumberofUnionWorkers__c, Quote.Account.Situs_State__c,
                   Quote.AccountId, Quote.GrpNumber__c, Quote.GroupSize__c, Quote.Opportunity.Name,
                     (SELECT Id, ParentQuoteLineItem__c, ProductStage__c, HPCC_Code__c, Product2.Name, Funding__c, 
                         State_Regular__c, HCR_Status__c, Product2.Contract_Code__c, EffectiveDate__c,Benefit_Period__c
                                 FROM Quote_Line_Items__r 
                                 WHERE Product_Type__c = :staticVariableClass.Medical
                                 AND ProductCategory__c=:staticVariableClass.Plan 
                                 AND ParentQuoteLineItem__c != null ) 
                                     FROM QuoteLineItem  
                                     WHERE QuoteId =: quoteId
                                     AND Product_Type__c =:staticVariableClass.Medical
                                     AND ProductCategory__c=:staticVariableClass.Product 
                                     AND ParentQuoteLineItem__c = null]);
                                     
            oP2AJsonObj = populateP2AJSON(quoteId,sSource);

            if(listQlis.size()>0 && !listQlis.isEmpty()){
                
                oResponseWrapper    = new ResponseWrapper(); 
                oResponseWrapper.GroupId = listQlis[0].Quote.GrpNumber__c;
                oResponseWrapper.GroupSize = listQlis[0].Quote.GroupSize__c;
                
                oP2AJsonObj.listParentQli = new List<LGP2AJSON.ParentQli>();
                    
                for(QuoteLineItem oParentQli : listQlis){
                        oParentqtLineItem = new LGP2AJSON.ParentQli();
                        oParentqtLineItem.sParentQliId  = oParentQli.Id;
                        oParentqtLineItem.sProductName  =  oParentQli.Product2.Name;
                        oParentqtLineItem.sProductType  = oParentQli.Product2.Product_Type__c;
                        oParentqtLineItem.sProductState = oParentQli.Product2.Market__c;
                        oParentqtLineItem.listChildQuoteLineItems = new List<LGP2AJSON.QuoteLineItems>();
        
                        for(QuoteLineItem oChildQli : oParentQli.Quote_Line_Items__r ){
                            
                                sEffectiveMonth     = getEffectiveMonth(oChildQli.EffectiveDate__c.month());
                                sEffectiveDay       = getEffectiveDay(oChildQli.EffectiveDate__c.day());
                    
                                oJSONqtLineItem = new LGP2AJSON.QuoteLineItems();
                                oJSONqtLineItem.SFDCQuoteLineItemId = oChildQli.Id;
                                oJSONqtLineItem.QuoteLineItemStage  = oChildQli.ProductStage__c;
                                oJSONqtLineItem.ProductContractCode = oChildQli.Product2.Contract_Code__c;
                                oJSONqtLineItem.OpportunityEffectiveDate = (oParentQli.EffectiveDate__c).year()+'-'+sEffectiveMonth+'-'+sEffectiveDay;
                                oJSONqtLineItem.ImplementationRecordStatus = oChildQli.ProductStage__c;
                                oJSONqtLineItem.GroupIdentifier = oParentQli.Quote.GrpNumber__c;
                                oJSONqtLineItem.GroupSize = oParentQli.Quote.GroupSize__c;
                                oJSONqtLineItem.CyPyAdministrativeType = getAdminType(oChildQli.Benefit_Period__c);
                                oJSONqtLineItem.FundingType = (oChildQli.Funding__c == staticVariableClass.FI || oChildQli.Funding__c == staticVariableClass.ASO)? oChildQli.Funding__c:'';
                                oJSONqtLineItem.hpccCode = oChildQli.HPCC_Code__c;
                                oJSONqtLineItem.sStateRegulator = oChildQli.State_Regular__c;
                                oJSONqtLineItem.sHcrStatus = oChildQli.HCR_Status__c;
                                 
                                oParentqtLineItem.listChildQuoteLineItems.add(oJSONqtLineItem);
                          }
                      oP2AJsonObj.listParentQli.add(oParentqtLineItem);
                }

                oResponseWrapper = getFinalResponse(oP2AJsonObj,oResponseWrapper);
            }
        }
        return oResponseWrapper !=null ? oResponseWrapper : null; 
    }
   
    /*
      Story :PRDCRM-51890 --GLD- Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: Method to populate P2AJSON
    _________________________________________________________________________________________
    
    *@param: quoteId - Quote Id
    *@param: sSource - Source of Button click
    _________________________________________________________________________________________
    
    *@return: LGP2AJSON
    _________________________________________________________________________________________
    */
    private static LGP2AJSON populateP2AJSON( Id quoteId, String sSource ){
        LGP2AJSON oP2AJsonObj = new LGP2AJSON();
        
        List<Quote> listQte = new List<Quote>([SELECT Id, AccountId, Opportunity.Account.TotalNumberofUnionWorkers__c, GrpNumber__c, GroupSize__c, Opportunity.Account.Name
                                                        FROM Quote
                                                        WHERE Id= :quoteId]);
        
        if(listQte.size()>0 && !listQte.isEmpty()){
            oP2AJsonObj.sfdcAccountId = listQte[0].AccountId;
            oP2AJsonObj.GroupName = listQte[0].Opportunity.Account.Name;
            oP2AJsonObj.totalNoOfUnionWorkers = Integer.ValueOf(listQte[0].Opportunity.Account.TotalNumberofUnionWorkers__c);
            oP2AJsonObj.RequestedBy = UserInfo.getName();
            oP2AJsonObj.SFDCQuoteId =listQte[0].Id;
            oP2AJsonObj.ENVIRONMENT =  URL.getSalesforceBaseUrl().toExternalForm();
            
            if(sSource == staticVariableClass.CEP_CASE){
                oP2AJsonObj.GroupNumber = listQte[0].GrpNumber__c;
                oP2AJsonObj.GroupSize = listQte[0].GroupSize__c;
            }
            if(sSource == staticVariableClass.VIEW_STRING){
                    oP2AJsonObj.Action = staticVariableClass.VIEW_STRING;
            }
        }
        return oP2AJsonObj !=null ? oP2AJsonObj : null;
    }
    /*
      Story :PRDCRM-51890 --GLD- Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: gets Admin Type based on Benefit Period 
    _________________________________________________________________________________________
    
    *@param: sBenefitPeriod - Benefit Period from QLI - String
    _________________________________________________________________________________________
    
    *@return: String
    _________________________________________________________________________________________
    */
    private static String getAdminType(String sBenefitPeriod){
        if (sBenefitPeriod!= null && sBenefitPeriod.contains(staticVariableClass.BENEFIT)){
            return 'PY';
        }
        else if (sBenefitPeriod!= null && sBenefitPeriod.contains(staticVariableClass.CALENDAR)){
            return 'CY';
        }
        return null;
    }
    /*
      Story :PRDCRM-51890 --GLD- Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: getsEffectiveMonth with proper integer format
    _________________________________________________________________________________________
    
    *@param: iEffectiveMonth - Month - Integer
    _________________________________________________________________________________________
    
    *@return: String
    _________________________________________________________________________________________
    */
    private static String getEffectiveMonth(Integer iEffectiveMonth){
        return (iEffectiveMonth < 10 ? ('0'+ String.valueOf(iEffectiveMonth)) : String.valueOf(iEffectiveMonth));
    }
    /*
      Story :PRDCRM-51890 --GLD- Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: getsEffectiveDay with proper integer format
    _________________________________________________________________________________________
    
    *@param: iEffectiveDay - Day - Integer

    _________________________________________________________________________________________
    
    *@return: String
    _________________________________________________________________________________________
    */
    private static String getEffectiveDay(Integer iEffectiveDay){
        return (iEffectiveDay < 10 ? ('0'+ String.valueOf(iEffectiveDay)) : String.valueOf(iEffectiveDay));
    }
     /*
      Story :PRDCRM-51890 - Send parameters to P2A on Create CEP Case Button from QLI
      Team: Gladiators
    _________________________________________________________________________________________
    
    *@description: get Final Response
    _________________________________________________________________________________________
    
    *@param: oP2AJsonObj - P2A JSON values for Payload
    *@param: oResponseWrapper - response wrapper for lightning screen

    _________________________________________________________________________________________
    
    *@return: ResponseWrapper
    _________________________________________________________________________________________
    */
    
    private static ResponseWrapper getFinalResponse(LGP2AJSON oP2AJsonObj, ResponseWrapper oResponseWrapper){
        
         if(oP2AJsonObj != null){
                    String sJsonToHR = LGP2AJSON.parse(oP2AJsonObj);
                    oResponseWrapper.attributeValue = sJsonToHR;  
                    oResponseWrapper.status = (staticVariableClass.CreateGrpSUCCESS).toUpperCase();
        }
        return oResponseWrapper;
    }
}