objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account_legal_Name__c</fullName>
        <formula>Account__r.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account legal Name</label>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group_Plan_Design__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBP_Bill_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Populated via API response from Customer Master</inlineHelpText>
        <label>CBP Bill Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Suffix__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Four Byte Group Suffix</inlineHelpText>
        <label>Group Suffix</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Most Recent Usage On Implementation Case</inlineHelpText>
        <label>Implementation Case</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>Cobra</fullName>
                </value>
                <value>
                    <fullName>Cal Cobra</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Group Plan Design</label>
    <nameField>
        <displayFormat>GPD-{000000}</displayFormat>
        <label>GPD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Plan Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/ID_Cards__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <formula>IF( ISBLANK( Implementation_Tracking_ID__r.Account_Legal_Name__r.Id ), &apos;&apos;, HYPERLINK(Implementation_Tracking_ID__r.Account_Legal_Name__r.Id, Implementation_Tracking_ID__r.Account_Legal_Name__r.Name))</formula>
        <label>Account Legal Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ID_Cards_Triggered__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>ID Cards Triggered</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <formula>HYPERLINK(    Implementation_Tracking_ID__r.Implementation_Record_ID__c  , Implementation_Tracking_ID__r.Implementation_Record_ID__r.OrderNumber )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Record ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipLabel>ID Cards</relationshipLabel>
        <relationshipName>ID_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>ID Cards</label>
    <nameField>
        <displayFormat>IDCARD-{000000}</displayFormat>
        <label>ID Cards Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ID Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Implementation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <formula>&quot;TRACK&quot; + &quot; &quot;  +   Implementation_Record_ID__r.OrderNumber</formula>
        <label>Implementation Tracking ID</label>
        <type>Text</type>
    </fields>
    <label>Implementation Tracking</label>
    <nameField>
        <displayFormat>TRACK-{000000}</displayFormat>
        <label>Implementation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Integration_Error_Log__c.object
<CustomObject>
    <fields>
        <fullName>Implementation_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Case</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Integration Error Log</relationshipLabel>
        <relationshipName>Integration_Error_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Integration_Event_Log__c</fullName>
        <label>Integration Event Log</label>
        <referenceTo>Integration_Event_Log__c</referenceTo>
        <relationshipLabel>Integration Error Log</relationshipLabel>
        <relationshipName>Integration_Error_Log</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                    <default>true</default>
                    <label>Open</label>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>System_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Integration Error Log</label>
    <nameField>
        <displayFormat>Error-{0000000}</displayFormat>
        <label>Error ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Log</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Integration_Event_Log__c.object
<CustomObject>
    <fields>
        <fullName>Event_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Event Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Case</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Integration Event Log</relationshipLabel>
        <relationshipName>Integration_Event_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>System_Name__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>System Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking ID</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Integration Event Log</label>
    <nameField>
        <displayFormat>Event-{0000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Event Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Invoices_Local__c.object
<CustomObject>
    <fields>
        <fullName>Account_Legal_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices (Local)</relationshipLabel>
        <relationshipName>Invoices_Local</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CBP_Bill_Group_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Populated via API response from Customer Master</inlineHelpText>
        <label>CBP Bill Group ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Invoices (Local)</relationshipLabel>
        <relationshipName>Invoices_Local</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoices (Local)</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoices Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices (Local)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CMStatusUpdateServiceTest.cls
/*
* @author : Legato Health Technologies LLP
* @Date   : 27 - November - 2019
* @Description : Test Class for CMStatusUpdateService
* 
*/ 
@isTest
public class CMStatusUpdateServiceTest {
    
    static testmethod void cmAccountStructureUpdateTest(){
          
        //Msg with 1 WGS group, 1 compass group , each with 1 suffix
        String msg = '{"eventMetaData":{"userId":"ac04840","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"addCustomer"},'
					   +'"responseMsg":[{"globalCustomerId":"98981234","accountID":"<<AccountID>>","statusCode":"SUCCESS","statusMsg":"CustomerInstalled-PreviewReady-orMaintainceCompleted",'
					   +'"systemID":"CM","responseDetails":{"accountInfo":{"customerInfo":{"customers":[{"ids":[{"sourceSystem":"CM","name":"globalCustomerId","value":"CMGID123"},{"sourceSystem":"SFDCCOM2","name":"accountId","value":"<<AccountID>>"}],'
					   +'"subGroups":[{"TargetSystem":"WGS","TargetSystemId":"W22222","groupNumber":"W22222","sfgroupNumber":"<<WGSSuffixId1>>","groupSuffixId":"M001"},'
					   +'{"TargetSystem":"COMPASS","TargetSystemId":"C22222","groupNumber":"C22222","sfgroupNumber":"<<CompassSuffixId1>>","groupSuffixId":"C002"}]}]},'
					   +'"accountBillGroups":[{"ids":[{"sourceSystem":"CM","name":"billGroupId","value":"CMBG001"},{"sourceSystem":"CM","name":"globalCustomerId","value":"CMBG001"},{"sourceSystem":"SFDCCOM2","name":"sfdcBillGroupId","value":"<<SFDCBillGroupID1>>"}],'
					   +'"billConfig":{"billLevelParameters":[{"sourceSystem":"WGS","sequence":"1","billLevel1":"W22222","billLevel2":"M001","billLevel3":"Any","billLevel4":"Any","billGroupId":"Any","effectiveDate":"9999-12-31","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""},'
					   +'{"sourceSystem":"compass","sequence":"2","billLevel1":"C22222","billLevel2":"C002","billLevel3":"","billLevel4":"","billGroupId":"","effectiveDate":"2019-11-05","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""}],'
					   +'"billDates":{"paidToDate":"9999-12-31","billToDate":"9999-12-31"}}}]}}}]}';
        
        //CMResponse cmresponse = (CMResponse)JSON.deserialize(msg,CMResponse.class);
        
        
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,false);
        Grp1.Name = 'TBD';
        insert Grp1;
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        Implementation_Tracking__c itrac = IntegrationTestDataUtilty.createImplTracking(icr.id, acc1.Id,true);
        Group_plan_design__c gpd1 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Group_plan_design__c gpd2 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Invoices_Local__c il = IntegrationTestDataUtilty.createInvoice(acc1.Id,null, grp1.id, true);

        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
        
        //Insreting Integration Event Log
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'Add';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        
        //Invoices_Local__c il2 = new Invoices_Local__c();
        //il2.Account_Legal_Name__c =acc1.Id;
        //il2.Group__c = g1.Id;
        //insert il2;
        msg = msg.replace('<<AccountID>>', acc1.id);
        msg = msg.replace('<<WGSSuffixId1>>',gpd1.id);
        msg = msg.replace('<<CompassSuffixId1>>',gpd2.id);
        msg = msg.replace('<<SFDCBillGroupID1>>',il.id);
        System.debug('Implementation Record Id : '+ ord[0].Implementation_Record_ID__c);
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        System.debug(msg);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(200, res.statusCode);
        List<Group__c> g2list = [Select id,name from Group__c where name = 'C22222'];
        Grp1 = [Select id,name from Group__c where id = :Grp1.id];
        gpd1 = [Select id, group_suffix__c,CBP_Bill_Group_ID__c from group_plan_design__c where id = :gpd1.id];
        gpd2 = [Select id, group_suffix__c,CBP_Bill_Group_ID__c from group_plan_design__c where id = :gpd2.id];
        il =   [Select id, CBP_Bill_Group_ID__c from Invoices_Local__c where id = :il.id];
        List<Integration_Event_Log__c> ielList =  [Select id from Integration_Event_Log__c where System_Name__c ='CM'  ];
        System.assertEquals(ielList.Size(),1);
        System.assertEquals(g2list.Size(),1);
        System.assertEquals(Grp1.Name,'W22222');
        System.assertEquals(gpd1.Group_Suffix__c,'M001');
        System.assertEquals(gpd2.Group_Suffix__c,'C002');
        System.assertEquals(gpd1.CBP_Bill_Group_ID__c,'CMBG001');
        System.assertEquals(gpd2.CBP_Bill_Group_ID__c,'CMBG001');
        System.assertEquals(il.CBP_Bill_Group_ID__c,'CMBG001');
        //System.assertEquals(gpd2.CBP_Bill_Group_ID__c,'CMBG001');
    }
    static testmethod void cmMaintTransactionStatusUpdateTest(){
        
        
        //Msg with 1 WGS group, 1 compass group , each with 1 suffix
        String msg = '{"eventMetaData":{"userId":"ac04840","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"Maintenance"},'
					   +'"responseMsg":[{"globalCustomerId":"98981234","accountID":"<<AccountID>>","statusCode":"SUCCESS","statusMsg":"CustomerInstalled-PreviewReady-orMaintainceCompleted",'
					   +'"systemID":"CM","responseDetails":{"accountInfo":{"customerInfo":{"customers":[{"ids":[{"sourceSystem":"CM","name":"globalCustomerId","value":"CMGID123"},{"sourceSystem":"SFDCCOM2","name":"accountId","value":"<<AccountID>>"}],'
					   +'"subGroups":[{"TargetSystem":"WGS","TargetSystemId":"W22222","groupNumber":"W22222","sfgroupNumber":"<<WGSSuffixId1>>","groupSuffixId":"M001"},'
					   +'{"TargetSystem":"COMPASS","TargetSystemId":"C22222","groupNumber":"C22222","sfgroupNumber":"<<CompassSuffixId1>>","groupSuffixId":"C002"}]}]},'
					   +'"accountBillGroups":[{"ids":[{"sourceSystem":"CM","name":"billGroupId","value":"CMBG001"},{"sourceSystem":"CM","name":"globalCustomerId","value":"CMBG001"},{"sourceSystem":"SFDCCOM2","name":"sfdcBillGroupId","value":"<<SFDCBillGroupID1>>"}],'
					   +'"billConfig":{"billLevelParameters":[{"sourceSystem":"WGS","sequence":"1","billLevel1":"W22222","billLevel2":"M001","billLevel3":"Any","billLevel4":"Any","billGroupId":"Any","effectiveDate":"9999-12-31","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""},'
					   +'{"sourceSystem":"compass","sequence":"2","billLevel1":"C22222","billLevel2":"C002","billLevel3":"","billLevel4":"","billGroupId":"","effectiveDate":"2019-11-05","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""}],'
					   +'"billDates":{"paidToDate":"9999-12-31","billToDate":"9999-12-31"}}}]}}}]}';
        
        //CMResponse cmresponse = (CMResponse)JSON.deserialize(msg,CMResponse.class);
        
        
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,false);
        Grp1.Name = 'TBD';
        insert Grp1;
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,false);
        icr.Maintenance_Reason_Customer_Master__c = 'Add new Product (Medical/Specialty only)';
        insert icr;
        Implementation_Tracking__c itrac = IntegrationTestDataUtilty.createImplTracking(icr.id, acc1.Id,true);
        Group_plan_design__c gpd1 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Group_plan_design__c gpd2 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Invoices_Local__c il = IntegrationTestDataUtilty.createInvoice(acc1.Id,null, grp1.id, true);
     
        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
        
        //Insreting Integration Event Log
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'Maintenance';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        
        //Invoices_Local__c il2 = new Invoices_Local__c();
        //il2.Account_Legal_Name__c =acc1.Id;
        //il2.Group__c = g1.Id;
        //insert il2;
        msg = msg.replace('<<AccountID>>', acc1.id);
        msg = msg.replace('<<WGSSuffixId1>>',gpd1.id);
        msg = msg.replace('<<CompassSuffixId1>>',gpd2.id);
        msg = msg.replace('<<SFDCBillGroupID1>>',il.id);
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        System.debug(msg);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(200, res.statusCode);
        List<Group__c> g2list = [Select id,name from Group__c where name = 'C22222'];
        Grp1 = [Select id,name from Group__c where id = :Grp1.id];
        gpd1 = [Select id, group_suffix__c,CBP_Bill_Group_ID__c from group_plan_design__c where id = :gpd1.id];
        gpd2 = [Select id, group_suffix__c,CBP_Bill_Group_ID__c from group_plan_design__c where id = :gpd2.id];
        il =   [Select id, CBP_Bill_Group_ID__c from Invoices_Local__c where id = :il.id];
        List<Integration_Event_Log__c> ielList =  [Select id from Integration_Event_Log__c where System_Name__c ='CM'  ];
        System.assertEquals(ielList.Size(),1);
        System.assertEquals(g2list.Size(),1);
        System.assertEquals(Grp1.Name,'W22222');
        System.assertEquals(gpd1.Group_Suffix__c,'M001');
        System.assertEquals(gpd2.Group_Suffix__c,'C002');
        System.assertEquals(gpd1.CBP_Bill_Group_ID__c,'CMBG001');
        System.assertEquals(gpd2.CBP_Bill_Group_ID__c,'CMBG001');
        System.assertEquals(il.CBP_Bill_Group_ID__c,'CMBG001');
        //System.assertEquals(gpd2.CBP_Bill_Group_ID__c,'CMBG001');
    }
    static testmethod void cmGroupNumberUpdateErrorTest(){
        
        // Test if Group number already exist for group record in Salesforce
        //Msg with 1 WGS group, 1 compass group , each with 1 suffix
        String msg = '{"eventMetaData":{"userId":"ac04840","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"addCustomer"},'
					   +'"responseMsg":[{"globalCustomerId":"98981234","accountID":"<<AccountID>>","statusCode":"SUCCESS","statusMsg":"CustomerInstalled-PreviewReady-orMaintainceCompleted",'
					   +'"systemID":"CM","responseDetails":{"accountInfo":{"customerInfo":{"customers":[{"ids":[{"sourceSystem":"CM","name":"globalCustomerId","value":"CMGID123"},{"sourceSystem":"SFDCCOM2","name":"accountId","value":"<<AccountID>>"}],'
					   +'"subGroups":[{"TargetSystem":"WGS","TargetSystemId":"W22222","groupNumber":"W22222","sfgroupNumber":"<<WGSSuffixId1>>","groupSuffixId":"M001"},'
					   +'{"TargetSystem":"COMPASS","TargetSystemId":"C22222","groupNumber":"C22222","sfgroupNumber":"<<CompassSuffixId1>>","groupSuffixId":"C002"}]}]},'
					   +'"accountBillGroups":[{"ids":[{"sourceSystem":"CM","name":"billGroupId","value":"CMBG001"},{"sourceSystem":"CM","name":"globalCustomerId","value":"CMBG001"},{"sourceSystem":"SFDCCOM2","name":"sfdcBillGroupId","value":"<<SFDCBillGroupID1>>"}],'
					   +'"billConfig":{"billLevelParameters":[{"sourceSystem":"WGS","sequence":"1","billLevel1":"W22222","billLevel2":"M001","billLevel3":"Any","billLevel4":"Any","billGroupId":"Any","effectiveDate":"9999-12-31","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""},'
					   +'{"sourceSystem":"compass","sequence":"2","billLevel1":"C22222","billLevel2":"C002","billLevel3":"","billLevel4":"","billGroupId":"","effectiveDate":"2019-11-05","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""}],'
					   +'"billDates":{"paidToDate":"9999-12-31","billToDate":"9999-12-31"}}}]}}}]}';
        
        //CMResponse cmresponse = (CMResponse)JSON.deserialize(msg,CMResponse.class);
        
        
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,false);
        Grp1.Name = 'TestGroup';
        insert Grp1;
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        Implementation_Tracking__c itrac = IntegrationTestDataUtilty.createImplTracking(icr.id, acc1.Id,true);
        Group_plan_design__c gpd1 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Group_plan_design__c gpd2 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Invoices_Local__c il = IntegrationTestDataUtilty.createInvoice(acc1.Id,null, grp1.id, true);

       List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id]; 
       
        //Insreting Integration Event Log
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'Add';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        
        //Invoices_Local__c il2 = new Invoices_Local__c();
        //il2.Account_Legal_Name__c =acc1.Id;
        //il2.Group__c = g1.Id;
        //insert il2;
        msg = msg.replace('<<AccountID>>', acc1.id);
        msg = msg.replace('<<WGSSuffixId1>>',gpd1.id);
        msg = msg.replace('<<CompassSuffixId1>>',gpd2.id);
        msg = msg.replace('<<SFDCBillGroupID1>>',il.id);
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        
        System.debug(msg);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
    }
    static testmethod void cmGroupSuffixUpdateErrorTest(){
        
        // Test if Group number already exist for group record in Salesforce
        //Msg with 1 WGS group, 1 compass group , each with 1 suffix
        String msg = '{"eventMetaData":{"userId":"ac04840","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"addCustomer"},'
					   +'"responseMsg":[{"globalCustomerId":"98981234","accountID":"<<AccountID>>","statusCode":"SUCCESS","statusMsg":"CustomerInstalled-PreviewReady-orMaintainceCompleted",'
					   +'"systemID":"CM","responseDetails":{"accountInfo":{"customerInfo":{"customers":[{"ids":[{"sourceSystem":"CM","name":"globalCustomerId","value":"CMGID123"},{"sourceSystem":"SFDCCOM2","name":"accountId","value":"<<AccountID>>"}],'
					   +'"subGroups":[{"TargetSystem":"WGS","TargetSystemId":"W22222","groupNumber":"W22222","sfgroupNumber":"<<WGSSuffixId1>>","groupSuffixId":"M001"},'
					   +'{"TargetSystem":"COMPASS","TargetSystemId":"C22222","groupNumber":"C22222","sfgroupNumber":"<<CompassSuffixId1>>","groupSuffixId":"C002"}]}]},'
					   +'"accountBillGroups":[{"ids":[{"sourceSystem":"CM","name":"billGroupId","value":"CMBG001"},{"sourceSystem":"CM","name":"globalCustomerId","value":"CMBG001"},{"sourceSystem":"SFDCCOM2","name":"sfdcBillGroupId","value":"<<SFDCBillGroupID1>>"}],'
					   +'"billConfig":{"billLevelParameters":[{"sourceSystem":"WGS","sequence":"1","billLevel1":"W22222","billLevel2":"M001","billLevel3":"Any","billLevel4":"Any","billGroupId":"Any","effectiveDate":"9999-12-31","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""},'
					   +'{"sourceSystem":"compass","sequence":"2","billLevel1":"C22222","billLevel2":"C002","billLevel3":"","billLevel4":"","billGroupId":"","effectiveDate":"2019-11-05","expirationDate":"9999-12-31","contractCD":"","productName":"","productType":""}],'
					   +'"billDates":{"paidToDate":"9999-12-31","billToDate":"9999-12-31"}}}]}}}]}';
        
        //CMResponse cmresponse = (CMResponse)JSON.deserialize(msg,CMResponse.class);
        
        
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,false);
        Grp1.Name = 'TBD';
        insert Grp1;
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        Implementation_Tracking__c itrac = IntegrationTestDataUtilty.createImplTracking(icr.id, acc1.Id,true);
        Group_plan_design__c gpd1 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, false);
        gpd1.Group_Suffix__c = 'G001';
        insert gpd1;
        Group_plan_design__c gpd2 = IntegrationTestDataUtilty.createGrpPlanDesign(Grp1.id, null,null, true);
        Invoices_Local__c il = IntegrationTestDataUtilty.createInvoice(acc1.Id,null, grp1.id, true);

        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
               
        //Insreting Integration Event Log
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'Add';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        
        //Invoices_Local__c il2 = new Invoices_Local__c();
        //il2.Account_Legal_Name__c =acc1.Id;
        //il2.Group__c = g1.Id;
        //insert il2;
        msg = msg.replace('<<AccountID>>', acc1.id);
        msg = msg.replace('<<WGSSuffixId1>>',gpd1.id);
        msg = msg.replace('<<CompassSuffixId1>>',gpd2.id);
        msg = msg.replace('<<SFDCBillGroupID1>>',il.id);
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        
        System.debug(msg);
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
    }
    static testmethod void cmIDCardUpdateTest(){
        
        String msg = '{"eventMetaData":{"userId":"ac04840","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"IDCardRequest"},'
					  +'"responseMsg":[{"globalCustomerId":"98981234","accountID":"<<AccountID>>","statusCode":"SUCCESS","statusMsg":"CustomerInstalled-PreviewReady-orMaintainceCompleted","systemID":"CM",'
					  +'"responseDetails":{"accountInfo":{"customerInfo":{"customers":[{"ids":[{"sourceSystem":"CM","name":"globalCustomerId","value":"CMGID123"},'
					  +'{"sourceSystem":"SFDCCOM2","name":"accountId","value":"<<AccountID>>"}],"miscellaneousInfo":{"idcards":{"triggereddate":"2019-01-01"}}}]}}}}]}';
        
        //CMResponse cmresponse = (CMResponse)JSON.deserialize(msg,CMResponse.class);
      
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,true);
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        Implementation_Tracking__c itrac = IntegrationTestDataUtilty.createImplTracking(icr.id, acc1.Id,true);
        
        Id_cards__c idCard = IntegrationTestDataUtilty.createIdCards(itrac.id, true);
        System.debug('Id card record'+idCard.Implementation_Tracking_ID__r.Implementation_Record_ID__c);
        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
        
        //Insreting Integration Event Log
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'IDCardRequest';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        //Inserting Group Plan Design
        msg = msg.replace('<<AccountID>>', acc1.id);
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        //msg = msg.replace('<<WGSSuffixId1>>',gpd1.id);
        //msg = msg.replace('<<CompassSuffixId1>>',gpd2.id);
        //msg = msg.replace('<<SFDCBillGroupID1>>',il.id);
        System.debug(msg);
        Test.startTest();

        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(200, res.statusCode);
        List<ID_Cards__c> idCardList = [Select id,ID_Cards_Triggered__c from Id_cards__c where id  = :idCard.id];
        System.debug(idCardList.size());
        System.assertEquals(idCardList.Size(),1);
        System.debug(idCardList[0].ID_Cards_Triggered__c);
        System.assertEquals(idCardList[0].ID_Cards_Triggered__c,Date.valueOf('2019-01-01 00:00:00'));
    }
    static testmethod void cmStatusUpdateEventErrorLogTest(){
        String msg = '{"eventMetaData":{"userId":"af53352","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"addCustomer","masterId":"12345","subTrackingId":"12345"},'
					+'"responseMsg":[{"globalCustomerId":"","accountID":"123","statusCode":"FAILURE","statusMsg":"CustomerAddFailed","systemID":"CM","responseDetails":'
					+'{"listOfErrorCodes":[{"category":"Functional","errorCode":"409","bindingField":"globalCustomerId","entityName":"parentCustomer","errorMessage":"ParentCustomerAlreadyExistwithOrganizationName.Name[SASIone6],OrganizationName.dbaName[Richm22]WithCustomerId7571"},'
					+'{"category":"Functional","errorCode":"409","bindingField":"CustomerId","entityName":"Customer","errorMessage":"ChildCustomerAlreadyExistChildCustomerID[7572]withOrganizationName.Name[Cogz781],OrganizationName.dbaName[Coiz778]WithParentCustomerId7571"},'
					+'{"category":"Functional","errorCode":"409","bindingField":"billGroupId","entityName":"BillGroup","errorMessage":"AccountBillGroupAlreadyExistAccountBillGroupID[7188]withOrganizationName.Name[K11242],OrganizationName.dbaName[T112g4B]AssociatedwiththeparentCustomeridnum7571"},'
					+'{"category":"Functional","errorCode":"409","bindingField":"id","entityName":"product","errorMessage":"DuplicatProductwithcntractID[4TN3]"},'
					+'{"category":"Functional","errorCode":"800","bindingField":"groupSuffixBillAssignment","entityName":"customerInfo","errorMessage":"NoBillGroupAssigned.[arrayofthegroupsuffix]"}]}}]}';
        
        
        
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,true);
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
        
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'IDCardRequest';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(200, res.statusCode);
        List<Integration_Event_Log__c> ielList = [Select id from Integration_Event_Log__c where id != :iel.id] ;
        List<Integration_Error_Log__c> ieErrorLogList = [Select id from Integration_Error_Log__c where Integration_Event_Log__c = :ielList[0].id];
        System.assertEquals(ielList.Size(),1);
        System.assertEquals(ieErrorLogList.Size(),5);
         
    }
    static testmethod void invalidPayloadFormatTest(){
        
        String msg = '{"eventMetaData":{"userId":"af53352","sourceSystemId":"CM","trackingId":"1212","eventType":"addCustomer","masterId":"12345","subTrackingId":"12345"},"responseMsg":[]}';
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
        
    }
    static testmethod void invalidSystemNameTest(){
       
        String msg = '{"eventMetaData":{"userId":"af53352","sourceSystemId":"CM","trackingId":"<<TrackingId>>","eventType":"IDCardRequest","masterId":"12345","subTrackingId":"12345"},'
            +'"responseMsg":[{"globalCustomerId":"","accountID":"123","statusCode":"FAILURE","statusMsg":"CustomerAddFailed",'
            +'"systemID":"CMInvalidSystemName123123123123123123123123123123123123123123123"}]}';
       
        Account acc1 = IntegrationTestDataUtilty.createAccount(true);
        Opportunity opt1 = IntegrationTestDataUtilty.createOpportunity(acc1.Id,true);
        Group__c Grp1 = IntegrationTestDataUtilty.createGroup(acc1.Id,true);
        Quote qt = IntegrationTestDataUtilty.createQuote(opt1.Id, Grp1.Id, true);
        Order icr = IntegrationTestDataUtilty.createImplCase(qt.id, acc1.Id,true);
        List<Order> ord = [Select Id, Implementation_Record_ID__c from Order where id =: icr.Id];
        
        Integration_Event_Log__c iel = new Integration_Event_Log__c();
        iel.Tracking_ID__c = ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343';
        iel.System_Name__c = 'SFDCCOM2';
        iel.Event_type__c = 'IDCardRequest';
        iel.Implementation_Case__c =icr.id;
        iel.Status__c = 'SUCCESS';
        insert iel;
        msg = msg.replace('<<TrackingId>>', ord[0].Implementation_Record_ID__c.subString(5)+'_'+'12343');
        
        Test.startTest();
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
        
    }
    static testmethod void jSONParseExceptionTest(){
        
        String msg = '{test:test}';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
        
    }
    static testmethod void blankResponsePayloadTest(){
        
        String msg = '';
        RestRequest req = new RestRequest();
        RestResponse res = new RestResponse();
        req.requestURI = '/services/apexrest/CMStatusUpdateService/*';
        req.httpMethod = 'POST';
        //req.requestBody = Blob.valueof(msg);
        RestContext.request = req;
        RestContext.response= res;
        Test.startTest();
        CMStatusUpdateService.updateResponseFromCM();
        Test.stopTest();
        System.assertEquals(400, res.statusCode);
        
    }
   
}