objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Situs State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Next_Number_Utility__c.object
<CustomObject>
    <description>This custom object hold records that will be used with business logic to supply the next number in a series.  It is originally written for a user to get the next WGS case number, but hopefully it will be generic enough that if other sequential numbers are needed a record in this object can be used.</description>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <description>The entity for which the number is to be generated.</description>
        <label>Anthem Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO/NV</fullName>
                </value>
                <value>
                    <fullName>NY</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_State_Prefix__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Current State Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Number_Used__c</fullName>
        <description>This field will store the last number in use</description>
        <label>Last Number Used</label>
        <precision>10</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Value__c</fullName>
        <description>The is the max value for the number series.</description>
        <label>Max Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Next Number Utility</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Next Number Utility Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Next Number Utility</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateGroupNumber_Test.cls
/*
@author         Deloitte offshore
@date           29/03/2018
@name           CreateGroupNumber_Test
@description    Used in vlocity omniscript to Generate Group Number for Group record.
@LastModifiedDate 28Sept2018
*/
@isTest
private class CreateGroupNumber_Test
{
    
    private static final String GETGROUPNUMBER = staticVariableClass.CreateGrpGETGROUPNUMBER;
    private static final String UPDATENEXTNUMBERUTILITY =  staticVariableClass.CreateGrpUPDATENEXTNUMBERUTILITY;
    private static final string REQUESTGROUPNUMBERSTEP = staticVariableClass.CreateGrpREQUESTGROUPNUMBERSTEP;
    private static final string ACCTID = staticVariableClass.CreateGrpACCTID;
    
    /*Below method inserts sample data*/
    @testsetup
    static void createData()
    {
        Account A =new Account
        (
            RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('LG Prospect').getRecordTypeId(),
            Name= staticVariableClass.AccountName,
            Account_s_Suppress_Auto_Renewal__c = false,
            Anthem_Entity__c = staticVariableClass.Entity,
            Region__c= staticVariableClass.Region,
            Branding__c =staticVariableClass.UniCare,
            Group_Size__c =staticVariableClass.size,
            Total_Employees__c =staticVariableClass.emp,
            HQ_State__c =staticVariableClass.AK,
            Situs_State__c = staticVariableClass.California,
            Mailing_Address_Same_as_Physical_Address__c = true,
            BillingStreet = staticVariableClass.testAccBillingStreet,
            BillingPostalCode= staticVariableClass.testAccBillingPostalCode ,
            BillingCity = staticVariableClass.testAccBillingCity ,
            BillingCountry =  staticVariableClass.testAccBillingCountry ,
            BillingState = staticVariableClass.testAccBillingState ,
            Physical_County__c = staticVariableClass.testAccBillingCity
        );
        insert A;
        
        insert new list<Group__c>{  new Group__c(Name = staticVariableClass.TBD, Account__c = A.ID), 
                                    new Group__c(Name = staticVariableClass.GroupNum, Account__c = A.ID)};
        
        insert new Next_Number_Utility__c(Name = staticVariableClass.California, Last_Number_Used__c = 100, Max_Value__c = 500);
        insert new Next_Number_Utility__c(Name = staticVariableClass.Georgia, Last_Number_Used__c = 999, Max_Value__c = 999,Current_State_Prefix__c = 'GB');
    }
    
    /*Below method is to invoke the CreateGroupNumber with the data inserted*/
    public static testMethod void CreateGroupNumber_Test_1()
    {
        Account A = [select ID,Situs_State__c,RecordTypeId from Account where Name =:staticVariableClass.AccountName limit 1];
        list<Group__c> GroupList = [select ID,Name from Group__c where Name IN ('TBD', '123')];
        
        map<String,Object> inputMap = new map<String,Object>();
        inputMap.put(ACCTID, A.ID);
        inputMap.put(REQUESTGROUPNUMBERSTEP, new map<String, Object>());
        
        CreateGroupNumber C = new CreateGroupNumber();
        C.invokeMethod(GETGROUPNUMBER, inputMap, new map<String,Object>(), null);
        C.invokeMethod(UPDATENEXTNUMBERUTILITY, inputMap, new map<String,Object>(), null);
        
        A.Situs_State__c = staticVariableClass.Indiana;
        update A;
        
        C.invokeMethod(GETGROUPNUMBER, inputMap, new map<String,Object>(), null);
        C.invokeMethod(UPDATENEXTNUMBERUTILITY, inputMap, new map<String,Object>(), null);
        
         A.Situs_State__c = staticVariableClass.Georgia;
         update A;
        
        C.invokeMethod(GETGROUPNUMBER, inputMap, new map<String,Object>(), null);
        C.invokeMethod(UPDATENEXTNUMBERUTILITY, inputMap, new map<String,Object>(), null);
    }
}