objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ClaimSystem__c</fullName>
        <label>Claim System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NASCO</fullName>
                </value>
                <value>
                    <fullName>WGS 2.0</fullName>
                </value>
                <value>
                    <fullName>ACES</fullName>
                </value>
                <value>
                    <fullName>ALICS</fullName>
                </value>
                <value>
                    <fullName>AniTa</fullName>
                </value>
                <value>
                    <fullName>CHIPS</fullName>
                </value>
                <value>
                    <fullName>COMPASS</fullName>
                </value>
                <value>
                    <fullName>CS90</fullName>
                </value>
                <value>
                    <fullName>DeCare Dental</fullName>
                </value>
                <value>
                    <fullName>FACETS</fullName>
                </value>
                <value>
                    <fullName>WDS</fullName>
                </value>
                <value>
                    <fullName>GBD FACETS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <description>This field is used, in order for system to indicate if a group record is inactive or inactive.</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Line of Business (not the total Opportunity)</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GrpName__c</fullName>
        <formula>GroupNumber__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>GrpName</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Benefit Year</fullName>
                </value>
                <value>
                    <fullName>Plan Year</fullName>
                    <isActive>false</isActive>
                    <label>Plan Year</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contract_Codes__c</fullName>
        <formula>Product2.Contract_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <label>Financing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Services Only</fullName>
                </value>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Fee / % of Savings</fullName>
                </value>
                <value>
                    <fullName>JAA (Jointly Administered Arrangement)</fullName>
                </value>
                <value>
                    <fullName>Minimum Premium</fullName>
                </value>
                <value>
                    <fullName>Modified Cost Plus</fullName>
                </value>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>Percent of Savings</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Cost Plus Alternate Funded</fullName>
                </value>
                <value>
                    <fullName>FI - Deposit Premium</fullName>
                </value>
                <value>
                    <fullName>FI - Refund Agreement</fullName>
                </value>
                <value>
                    <fullName>Fully Insured</fullName>
                </value>
                <value>
                    <fullName>Non-Refunding</fullName>
                </value>
                <value>
                    <fullName>Refunding</fullName>
                </value>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>MCS Network Rental</fullName>
                </value>
                <value>
                    <fullName>Contingent Premium</fullName>
                </value>
                <value>
                    <fullName>JIA (Jointly Integrated Arrangement)</fullName>
                </value>
                <value>
                    <fullName>ABF (Anthem Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>EBF (Empire Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>ASC (Administrative Service Contract)</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
                <value>
                    <fullName>Level Funded/Fully Insured</fullName>
                </value>
                <value>
                    <fullName>JAA (Full Service) - ANA Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Funding</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WGS_Sold_Contract_Codes__c.object
<CustomObject>
    <description>Stores WGS Input Data with contract codes to automate QLI creation.</description>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Benefit Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Financing</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_count__c</fullName>
        <label>Member count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Message__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status Message</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Pending, Success , Error</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_count__c</fullName>
        <label>Subscriber count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upsell_Flag__c</fullName>
        <label>Upsell Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WGS_Group_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>WGS Group Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>WGS Sold Contract Codes</label>
    <nameField>
        <displayFormat>WGSCC-{0000000}</displayFormat>
        <label>WGS Sold Contract Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGS Sold Contract Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoadQLIFromWGSDataTest.cls
@isTest
public class LoadQLIFromWGSDataTest {
    
    static WGS_Sold_Contract_Codes__c createData()
    {
       Account acc=IntegrationTestDataUtilty.createAccount(true); 
       
        String renewalOppRecTypeId = Opportunity.sObjectType.getDescribe().getRecordTypeInfosbyName().get('Renewal Local').getRecordTypeId();
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        oppty.StageName = 'Submitted';
        oppty.RecordTypeId = renewalOppRecTypeId;
        update oppty;
        
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        grp.IsActive__c = True;
        grp.Name = 'W61305';
        update grp;
        
        Quote qte=IntegrationTestDataUtilty.createQuote(oppty.Id, grp.id, true);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(true);
        prod.Contract_Code__c = '40RA';
        prod.Category__c = 'Product';
        Database.update(prod);
        
        Product2 plan=IntegrationTestDataUtilty.createProduct(true);
        plan.Contract_Code__c = '40QA';
        plan.vlocity_ins__ProductSpecId__c = prod.Id;
        plan.ProductActive__c = True;
        Database.update(plan);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        PricebookEntry pbeplan=IntegrationTestDataUtilty.createPricebookEntry(plan.id, true);
        
        WGS_Sold_Contract_Codes__c wgsRec= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61305', Contract_Code__c ='40QA', Benefit_Period__c = 'Calendar Year',
                                                                Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Pending',
                                                                Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No');
		Database.insert(wgsRec);
        
        return wgsRec;
    }
	
    @isTest
    static void testQliInsertSuccess(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        System.assertEquals(2, [Select Count() from QuoteLineItem], 'Total No of QLis are not matching the expected count');
        QuoteLineItem childQLI = [Select Id, Members__c from QuoteLineItem where Contract_Codes__c = '40QA'];
        System.assertEquals(150, childQLI.Members__c, 'Member count is not correct');
    }
    
    @isTest
    static void testMandatoryfieldsnull(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        wgsTestRec.Contract_Code__c = '';
        update wgsTestRec;
        
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('Missing WGS Group Number and/or Contract Code in WGS input data', wgsRecresult.Status_Message__c, 'Required fields error message is not correct');
    }
    
    @isTest
    static void testWGSGroupNotExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        wgsTestRec.WGS_Group_Number__c = 'TestG';
        update wgsTestRec;
        
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('No active WGS Groups found with group number TestG', wgsRecresult.Status_Message__c, 'No active wgs group found error is not correct');    
        
    }
    
    @isTest
    static void testMultipleWGSgroupsExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Group__c grp = [Select Id, Account__c from Group__c where Name='W61305'];
        
       Group__c secondgrp = new Group__c(Name='W61305', IsActive__c = true, Account__c = grp.Account__c, ClaimSystem__c = 'WGS 2.0');
       insert secondgrp;
        
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('More than one active WGS Groups found with group number W61305', wgsRecresult.Status_Message__c, 'Multiple wgs groups exist error message is not correct');
    } 
    
    @isTest
    static void testNoOppExists(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Opportunity opp=[Select Id, StageName from Opportunity LIMIT 1];
        opp.StageName = 'Closed Won';
        update opp;
        
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        Group__c grp = [Select Id, Account__c From Group__c where Name ='W61305'];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('No Renewal Local Type Opportunity found for the related account '+grp.Account__c+' and group number W61305', wgsRecresult.Status_Message__c, 'No renewal Opp found error message is not correct');
    } 
    @isTest
    static void testMultipleOppsExists(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Opportunity opp=[Select Id, AccountId, StageName, RecordTypeId from Opportunity LIMIT 1];
        Opportunity opp2 = new Opportunity(Name = 'Test Opp2',AccountId = opp.AccountId, StageName='Initiated', CloseDate = Date.today(), RecordTypeId = opp.RecordTypeId);
        insert opp2;
        
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        Group__c grp = [Select Id, Account__c From Group__c where Name ='W61305'];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('More than one Renewal Local Type Opportunities found for the related account '+grp.Account__c+' and group number W61305', wgsRecresult.Status_Message__c, 'Multiple Opps found error message is not correct');
    }
    
    @isTest
    static void testNoQuoteExists(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
       /* Group__c grp = [Select Id, Account__c from Group__c where Name='W61305'];
        Group__c secondgrp = new Group__c(Name='W61307', IsActive__c = true, Account__c = grp.Account__c, ClaimSystem__c = 'WGS 2.0');
        insert secondgrp; */
        
        Quote quoteRec = [Select Id, GrpName__c from Quote where GrpName__c = 'W61305'];
       // quoteRec.GroupNumber__c = secondgrp.Id;
        delete quoteRec;
            
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        Group__c grp1 = [Select Id, Account__c From Group__c where Name ='W61305'];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('No quote found under Renewal Local Type Opportunity for the related account '+grp1.Account__c+' and group number W61305', wgsRecresult.Status_Message__c, 'No quote found error message is not correct');
    } 
    
    @isTest
    static void testMultipleQuotesExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        Group__c grp = [Select Id, Account__c from Group__c where Name='W61305'];
        Opportunity opp=[Select Id, AccountId, StageName, RecordTypeId from Opportunity LIMIT 1];
        
        Quote secondqte=IntegrationTestDataUtilty.createQuote(opp.Id, grp.id, true);     
            
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        Group__c grp1 = [Select Id, Account__c From Group__c where Name ='W61305'];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('More than one quotes found under Renewal Local Type Opportunity for the related account '+grp1.Account__c+' and group number W61305', wgsRecresult.Status_Message__c, 'Error message for multiple quotes scenario is wrong');
    } 
    
    @isTest
    static void testQLIExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Quote qte = [Select Id, GrpName__c from Quote where GrpName__c = 'W61305'];
        Product2 prod = [Select Id From Product2 where Contract_Code__c='40QA'];
        PriceBookEntry pbe = [Select Id from PriceBookEntry where Product2Id=: prod.Id];
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        Database.insert(qli); 
            
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('QLI already exists for the contract code 40QA and WGS group number W61305', wgsRecresult.Status_Message__c, 'Error message for QLI already exist scenario is not correct');
    } 
    
    @isTest
    static void testProductNotExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Product2 prod = [Select Id From Product2 where Contract_Code__c='40QA'];
        prod.Contract_Code__c = 'ABCD';
        update prod;
            
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        WGS_Sold_Contract_Codes__c wgsRecresult = [Select Id, Status__c, Status_Message__c from WGS_Sold_Contract_Codes__c LIMIT 1];
        System.assertEquals('Error', wgsRecresult.Status__c, 'Error occurred in the process');
        System.assertEquals('No matching Product found with the contract code 40QA', wgsRecresult.Status_Message__c, 'Product not found error message');
    }
     @isTest
    static void testParentQLIExist(){
        
        WGS_Sold_Contract_Codes__c wgsTestRec = createData();
        
        Quote qte = [Select Id, GrpName__c from Quote where GrpName__c = 'W61305'];
        Product2 prod = [Select Id From Product2 where Contract_Code__c='40RA'];
        PriceBookEntry pbe = [Select Id from PriceBookEntry where Product2Id=: prod.Id];
        
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        Database.insert(qli); 
            
        Test.startTest();
        Database.executeBatch(new LoadQLIFromWGSData(), 1);
        Test.stopTest();
        
        System.assertEquals(2, [Select Count() from QuoteLineItem], 'No of qlis not matching the expected count');
        QuoteLineItem childQLI = [Select Id, Members__c from QuoteLineItem where Contract_Codes__c = '40QA'];
        QuoteLineItem parentQLI = [Select Id, Members__c from QuoteLineItem where Contract_Codes__c = '40RA'];
        System.assertEquals(150, childQLI.Members__c, 'Member count not updated on child QLI');
        System.assertEquals(150, parentQLI.Members__c, 'Member count not updated on Parent QLI');
    } 
}