objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Group_Plan_Design__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Employee_Status__r.Location__r.Group__r.Name</formula>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Plan_Description__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is the requested name at the group suffix level. It is required if they don’t want to go with a default suffix. If blank then defaults will be applied.</inlineHelpText>
        <label>Group Plan Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Suffix_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Suffix Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Group_Suffix__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Four Byte Group Suffix</inlineHelpText>
        <label>Group Suffix</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_or_Product_Name__c</fullName>
        <formula>QuoteLineItem_Record_ID__r.Product2.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Plan or Product Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QLI_Funding__c</fullName>
        <formula>TEXT( QuoteLineItem_Record_ID__r.Funding__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QLI Funding</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QLI_Plan_Contract_Code__c</fullName>
        <formula>QuoteLineItem_Record_ID__r.Contract_Code_ASF__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>QLI Plan Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QuoteLineItem_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Group Plan Designs</relationshipLabel>
        <relationshipName>Group_Plan_Designs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Group Plan Design</label>
    <nameField>
        <displayFormat>GPD-{000000}</displayFormat>
        <label>GPD ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Group Plan Designs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Implementation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <formula>&quot;TRACK&quot; + &quot; &quot;  +   Implementation_Record_ID__r.OrderNumber</formula>
        <label>Implementation Tracking ID</label>
        <type>Text</type>
    </fields>
    <label>Implementation Tracking</label>
    <nameField>
        <displayFormat>TRACK-{000000}</displayFormat>
        <label>Implementation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_Code_ASF__c</fullName>
        <formula>IF( ISBLANK(  vlocity_ins__ContractCode__c ) , Product2.Contract_Code__c  , vlocity_ins__ContractCode__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Custom Contract Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>Quote.GroupNumber__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HPCC_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HPCC Code</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pharmacy_Benefit_Identifier__c</fullName>
        <description>This field is being added to support the Group Load functionality through Customer Master.
Formerly Proxy ID</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>This is also known as BPL (Benefit Code) and is provided by Rx vendor. This field is needed in WGS to create vendor segment which is key to send membership eligibility feed to the Rx vendor</inlineHelpText>
        <label>Pharmacy Benefit Identifier</label>
        <length>12</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <label>Plan Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Custom</fullName>
                </value>
                <value>
                    <fullName>Modified</fullName>
                </value>
                <value>
                    <fullName>Non-Pooled Standard</fullName>
                </value>
                <value>
                    <fullName>Standard</fullName>
                </value>
                <value>
                    <fullName>Pooled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProductCategory__c</fullName>
        <formula>TEXT(Product2.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ProductCategory</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLOB__c</fullName>
        <formula>IF(
NOT(ISBLANK(TEXT(Product2.LOB__c))),
TEXT(Product2.LOB__c),
LEFT( TEXT(Product2.LOB_Org__c),LEN(TEXT(Product2.LOB_Org__c))-2 )
)</formula>
        <label>ProductLOB</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Rx__c.object
<CustomObject>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>IF( ISBLANK( Implementation_Tracking_ID__r.Group_Number__r.Id ), &apos;&apos;, HYPERLINK(Implementation_Tracking_ID__r.Group_Number__r.Id, Implementation_Tracking_ID__r.Group_Number__r.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipLabel>Rxs</relationshipLabel>
        <relationshipName>Rxs</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Rx</label>
    <nameField>
        <displayFormat>RX-{000000}</displayFormat>
        <label>Rx Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rxs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LGA_GetPharmacyBenefitData.cls
/**
* @File Name          : LGA_GetPharmacyBenefitData.cls
* @Description        : 
* @Author             : Accenture OffShore 
* @Group              : Raptors
* @Modification Log   : 
* Ver       Date            Author      		        Modification
* 1.0    1/14/2020     Accenture OffShore              Initial Version
**/
public with sharing class LGA_GetPharmacyBenefitData {
    
    /**
    * @description : This metods returns the wrapperdata to be shown on the LWC component
    * @author Accenture Offshore | 1/24/2020 
    * @param qliID 
    * @return List<wrapPharmacyBenefitData> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<WrapPharmacyBenefitData> getPharmacyBenefitData(String recId){
        List<WrapPharmacyBenefitData> wrapPharmacyBenefitDataList = New List<WrapPharmacyBenefitData>();
        try {
            system.debug('@@@@@@@Inside The Apex Class' + recId );
            //String param = '%' + qliID + '%' ;
            String grpID;
            //String implCaseID;
            Implementation_Tracking__c impleTrack;
            impleTrack = [SELECT Id,Group_Number__c from Implementation_Tracking__c Where Id IN (Select Implementation_Tracking_ID__c From Rx__c where Id = :recId) LIMIT 50000 ];
            //system.debug('@@@@impleTrack : ' + impleTrack);
            //system.debug('@@@@impleTrack : ' + impleTrack.Group_Number__c);
            
            /*QuoteLineItem qliDetails= [Select Id,QuoteId, Quote.GroupNumber__c,Contract_Code_ASF__c,
                                    HPCC_Code__c,ProductStage__c FROM QuoteLineItem Where Id =: recId] ;
            
            system.debug('@@@@@@ Group Id: ' +qliDetails.Quote.GroupNumber__c );*/
            //grpID = qliDetails.Quote.GroupNumber__c;
            grpID = impleTrack.Group_Number__c;
            List<Group_Plan_Design__c> gpdDetailsList= [SELECT Id,Group__c,Group__r.Name,Group_Suffix__c,
                                                        QLI_Plan_Contract_Code__c,Plan_or_Product_Name__c,QLI_Funding__c,
                                                        Group_Plan_Description__c,Group_Suffix_Effective_Date__c,
                                                        QuoteLineItem_Record_ID__c,QuoteLineItem_Record_ID__r.Contract_Code_ASF__c,
                                                        QuoteLineItem_Record_ID__r.HPCC_Code__c, QuoteLineItem_Record_ID__r.ProductStage__c,
                                                        QuoteLineItem_Record_ID__r.ProductLOB__c, QuoteLineItem_Record_ID__r.ProductCategory__c,
                                                        QuoteLineItem_Record_ID__r.Pharmacy_Benefit_Identifier__c,
                                                    QuoteLineItem_Record_ID__r.Plan_Type__c
                                                        From Group_Plan_Design__c Where Group__c =:grpID 
                                                        AND QuoteLineItem_Record_ID__r.ProductLOB__c = :LGA_Constants.MEDICAL_LOB
                                                        AND QuoteLineItem_Record_ID__r.ProductCategory__c = :LGA_Constants.PLAN
                                                        AND (QuoteLineItem_Record_ID__r.ProductStage__c =: LGA_Constants.QLI_PRODUCT_STAGE_SOLD OR QuoteLineItem_Record_ID__r.ProductStage__c =: LGA_Constants.QLI_PRODUCT_STAGE_IGAPSOLD)
                                                        AND (QuoteLineItem_Record_ID__r.Plan_Type__c =:LGA_Constants.CUSTOM OR QuoteLineItem_Record_ID__r.Plan_Type__c =:LGA_Constants.MODIFIED ) LIMIT 50000 ];
            
            //system.debug('@@@@@gpdDetailsList: ' + gpdDetailsList);
            //system.debug('@@@@@gpdDetailsList: ' + gpdDetailsList.size());
            if(!gpdDetailsList.isEmpty()){
                for(Group_Plan_Design__c gpd : gpdDetailsList){
                    wrapPharmacyBenefitDataList.add(new WrapPharmacyBenefitData(gpd));
                }
                
            }
        } catch (Exception ex) {
            system.debug('****The following exception has occurred: ' + ex.getMessage());
        }
        
        //system.debug('@@@@@@wrapPharmacyBenefitDataList' + wrapPharmacyBenefitDataList);
        //system.debug('@@@@@@wrapPharmacyBenefitDataList' + wrapPharmacyBenefitDataList.Size());
        //system.debug('@@@@@@wrapPharmacyBenefitDataList' + wrapPharmacyBenefitDataList[0].gpdDetails);
        return wrapPharmacyBenefitDataList;
    }
    
    
    public with sharing class WrapPharmacyBenefitData {
        // This is the wrappaer class used populate the LWC Table.
        //@AuraEnabled public QuoteLineItem qliData {get;set;}
        @AuraEnabled public Group_Plan_Design__c gpdDetails {get;set;}
        @AuraEnabled public String grpName {get;set;}
        @AuraEnabled public String grpSuffix {get;set;}
        @AuraEnabled public String grpContractCode {get;set;}
        @AuraEnabled public String qliCustContractCode {get;set;}
        @AuraEnabled public String qliHPCC {get;set;}
        @AuraEnabled public String grpPlan {get;set;}
        @AuraEnabled public String grpPlanType {get;set;}
        @AuraEnabled public String grpFunding {get;set;}
        @AuraEnabled public String qliProdStage {get;set;}
        @AuraEnabled public String grpDescription {get;set;}
        @AuraEnabled public Date grpEffDate {get;set;}
        @AuraEnabled public String pharBenefit {get;set;}
        @AuraEnabled public String qliID {get;set;}
        @AuraEnabled public String gpdID {get;set;}
        
        public WrapPharmacyBenefitData(Group_Plan_Design__c gpdList){    
            grpName = gpdList.Group__r.Name;
            grpSuffix = gpdList.Group_Suffix__c;
            grpContractCode = gpdList.QLI_Plan_Contract_Code__c;
            qliCustContractCode = gpdList.QuoteLineItem_Record_ID__r.Contract_Code_ASF__c; //qli.Contract_Code_ASF__c;
            qliHPCC = gpdList.QuoteLineItem_Record_ID__r.HPCC_Code__c; //qli.HPCC_Code__c;
            grpPlan = gpdList.Plan_or_Product_Name__c;
            grpFunding = gpdList.QLI_Funding__c;
            qliProdStage = gpdList.QuoteLineItem_Record_ID__r.ProductStage__c; //qli.ProductStage__c;
            grpDescription = gpdList.Group_Plan_Description__c;
            
            /*if(gpdList.Group_Suffix_Effective_Date__c != null){
                system.debug('@@@@@@@@@gpdList.Group_Suffix_Effective_Date__c:    '+ string.valueOf(gpdList.Group_Suffix_Effective_Date__c).Split('T')[0]);
                grpEffDate = string.valueOf(gpdList.Group_Suffix_Effective_Date__c).Split('T')[0];
            }else{
                grpEffDate = gpdList.Group_Suffix_Effective_Date__c; //gpdList.Group_Suffix_Effective_Date__c date(
            } */
            grpEffDate = gpdList.Group_Suffix_Effective_Date__c;
            
            pharBenefit = gpdList.QuoteLineItem_Record_ID__r.Pharmacy_Benefit_Identifier__c;//Pharmacy_Benefit_Identifier__c
            qliID = gpdList.QuoteLineItem_Record_ID__c;
            grpPlanType = gpdList.QuoteLineItem_Record_ID__r.Plan_Type__c;
            gpdID = gpdList.Id;
        }
    }

   
    /**
    * @description : This method retunrs the current user's profile name.
    * @author Accenture Offshore | 1/31/2020 
    * @param userID 
    * @return List<UserProfileDetails> 
    **/
    @AuraEnabled(cacheable=true)
    public static List<UserProfileDetails> showLWCdata(String userID){ //String userID
        List<UserProfileDetails> usrPrfDetails = New List<UserProfileDetails>();
        try {
            system.debug('@@@Inside showLWCdata: ' + userID );
            
            String usrProfileName;
            for(Profile pf : [SELECT Id,Name FROM Profile Where Id in (Select ProfileId FROM User Where Id =:userID ) LIMIT 1]){
                //system.debug('@@@Inside For: ' + pf );
                //system.debug('@@@Inside For 2: ' + showData );
                usrProfileName = pf.Name;
            }
            //if(usrProfileName != Null && usrProfileName != '' ){
            if(String.isNotBlank(usrProfileName)){
                //system.debug('@@@@@@ Inside If: ' + usrProfileName);
                usrPrfDetails.add(new UserProfileDetails(usrProfileName));
            }
            
            //system.debug('@@@@@@usrPrfDetails: ' + usrPrfDetails);
            system.debug('@@@@@@usrPrfDetails: ' + usrPrfDetails.size());
        } catch (Exception ex) {
            system.debug('****The following exception has occurred: ' + ex.getMessage());
        }        

        return usrPrfDetails;
    }

    public with sharing class UserProfileDetails{
        
        //@AuraEnabled public String userId {get;set;}
        @AuraEnabled public Boolean userProfileName {get;set;}

        public UserProfileDetails(String profileName){    
            if (profileName == LGA_Constants.SME || profileName == LGA_Constants.SME_DUAL || profileName == LGA_Constants.SYSTEM_ADMINISTRATOR ){
                userProfileName = true;
            }
            else{
                userProfileName =false;
            }
            //userProfileName = profileName;
        }
    }


    /**
    * @description : This method updates Pharmacy Benefit Identifier data on QLI and passes the updated data to LWC Component.
    * @author Accenture Offshore | 2/4/2020 
    * @param saveData 
    * @param rxId   
    * @return List<WrapPharmacyBenefitData> 
    **/
    @AuraEnabled
    public static List<WrapPharmacyBenefitData> savePBIData(List<Map<String,String>> saveData,String rxId){ //List<WrapPharmacyBenefitData>

        try {
            system.debug('@@@@@@@@@Inside savePBIData: ' + saveData);
            //system.debug('@@@@@@@@@Inside savePBIData: ' + rxId);
            List<QuoteLineItem> qliList = New List<QuoteLineItem>();
            Map<String,QuoteLineItem> qliMap = New Map<String,QuoteLineItem>();
            QuoteLineItem qli;
            for(Map<String,String> obj : saveData ){
                //system.debug('@@@@@@@@@Inside savePBIData For: ' + obj);
                //system.debug('@@@@@@@@@Inside savePBIData For: ' + obj.get(LGA_Constants.ID));
                //QuoteLineItem qli = new QuoteLineItem();
                qli = new QuoteLineItem();
                qli.Id = obj.get(LGA_Constants.ID);
                qli.Pharmacy_Benefit_Identifier__c = obj.get(LGA_Constants.NAME);
                qliMap.put(obj.get(LGA_Constants.ID),qli );
                //system.debug('@@@@@@@@@Inside savePBIData For: ' + qliMap);
                //qliList.add(qli);
    
            }
            for(String qliIds:qliMap.keySet() ){
                //system.debug('@@@@@@@@@Inside savePBIData For 164: ' + qliMap);
                qliList.add(qliMap.get(qliIds));
            }
            if(!qliList.isEmpty()){
                //system.debug('@@@@@@@@@Inside savePBIData If 167: ' + qliList);
                database.update(qliList,false);
            }   
    
        } catch (Exception ex) {
            system.debug('****The following exception has occurred: ' + ex.getMessage());
        }
 
        return getPharmacyBenefitData(rxId);
        
    }


}