objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Benefit Year</fullName>
                </value>
                <value>
                    <fullName>Plan Year</fullName>
                    <isActive>false</isActive>
                    <label>Plan Year</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <label>Financing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Services Only</fullName>
                </value>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Fee / % of Savings</fullName>
                </value>
                <value>
                    <fullName>JAA (Jointly Administered Arrangement)</fullName>
                </value>
                <value>
                    <fullName>Minimum Premium</fullName>
                </value>
                <value>
                    <fullName>Modified Cost Plus</fullName>
                </value>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>Percent of Savings</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Cost Plus Alternate Funded</fullName>
                </value>
                <value>
                    <fullName>FI - Deposit Premium</fullName>
                </value>
                <value>
                    <fullName>FI - Refund Agreement</fullName>
                </value>
                <value>
                    <fullName>Fully Insured</fullName>
                </value>
                <value>
                    <fullName>Non-Refunding</fullName>
                </value>
                <value>
                    <fullName>Refunding</fullName>
                </value>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>MCS Network Rental</fullName>
                </value>
                <value>
                    <fullName>Contingent Premium</fullName>
                </value>
                <value>
                    <fullName>JIA (Jointly Integrated Arrangement)</fullName>
                </value>
                <value>
                    <fullName>ABF (Anthem Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>EBF (Empire Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>ASC (Administrative Service Contract)</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
                <value>
                    <fullName>Level Funded/Fully Insured</fullName>
                </value>
                <value>
                    <fullName>JAA (Full Service) - ANA Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Commercial Funding</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentQuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to self.</description>
        <label>Parent Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>In Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__ContractCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WGS_Sold_Contract_Codes__c.object
<CustomObject>
    <description>Stores WGS Input Data with contract codes to automate QLI creation.</description>
    <fields>
        <fullName>Benefit_Period__c</fullName>
        <label>Benefit Period</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Calendar Year</fullName>
                </value>
                <value>
                    <fullName>Benefit Year</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Financing</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Funding_Type__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Funding Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member_count__c</fullName>
        <label>Member count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QLI_ID_Created__c</fullName>
        <description>Stores the ID of new QLI created as a part of the automated batch process.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>QLI ID Created</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Pending, Success , Error</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subscriber_count__c</fullName>
        <label>Subscriber count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upsell_Flag__c</fullName>
        <label>Upsell Flag</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>WGS_Group_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>WGS Group Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>WGS Sold Contract Codes</label>
    <nameField>
        <displayFormat>WGSCC-{0000000}</displayFormat>
        <label>WGS Sold Contract Code Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>WGS Sold Contract Codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/WGSCCQLIDeleteReportTest.cls
@isTest
public class WGSCCQLIDeleteReportTest {
    
    @isTest
    static List<WGS_Sold_Contract_Codes__c> createWGSInputTestData(){
        
        Account acc=IntegrationTestDataUtilty.createAccount(true); 
        
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        
        Group__c allSuccessGrp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        allSuccessGrp.Name = 'W61305';
        update allSuccessGrp;
        
        Group__c errorGrp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        errorGrp.Name = 'W61307';
        update errorGrp;
        
        Group__c secondRunSuccessGrp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        secondRunSuccessGrp.Name = 'W61308';
        update secondRunSuccessGrp;
        
        Quote qte=IntegrationTestDataUtilty.createQuote(oppty.Id, allSuccessGrp.id, true);
        Quote qte1=IntegrationTestDataUtilty.createQuote(oppty.Id, errorGrp.id, true);
        Quote qte2=IntegrationTestDataUtilty.createQuote(oppty.Id, secondRunSuccessGrp.id, true);
        
        List<Product2> prodList = new List<Product2>();
        Product2 prod=IntegrationTestDataUtilty.createProduct('40QA', false);
        prod.Category__c = 'Plan';
        prod.Product_Type__c = 'Medical';
        prodList.add(prod);
        
        Product2 prod2 =IntegrationTestDataUtilty.createProduct('40PA', false);
        prod2.Category__c = 'Plan';
        prod2.Product_Type__c = 'Medical';
        prodList.add(prod2);
        
        Product2 prod3 =IntegrationTestDataUtilty.createProduct('40SA', false);
        prod3.Category__c = 'Plan';
        prod3.Product_Type__c = 'Medical';
        prodList.add(prod3);
        
        Product2 prod4 =IntegrationTestDataUtilty.createProduct('40TA', false);
        prod4.Category__c = 'Plan';
        prod4.Product_Type__c = 'Medical';
        prodList.add(prod4);
        
        Product2 prod5 =IntegrationTestDataUtilty.createProduct(null, false);
        prod5.Category__c = 'Plan';
        prod5.Product_Type__c = 'Medical';
        prodList.add(prod5);
        
        Product2 prod6 =IntegrationTestDataUtilty.createProduct(false);
        prod6.Category__c = 'Product';
        prod6.Product_Type__c = 'Medical';
        prodList.add(prod6);
        
        Product2 prod7 =IntegrationTestDataUtilty.createProduct('40AA', false);
        prod7.Category__c = 'Plan';
        prod7.Product_Type__c = 'Medical';
        prodList.add(prod7);
        
        Database.insert(prodList);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prodList[0].id, true);
        PricebookEntry pbe2=IntegrationTestDataUtilty.createPricebookEntry(prodList[1].id, true);
        PricebookEntry pbe3=IntegrationTestDataUtilty.createPricebookEntry(prodList[2].id, true);
        PricebookEntry pbe4=IntegrationTestDataUtilty.createPricebookEntry(prodList[3].id, true);
        PricebookEntry pbe5=IntegrationTestDataUtilty.createPricebookEntry(prodList[4].id, true);
        PricebookEntry pbe6=IntegrationTestDataUtilty.createPricebookEntry(prodList[5].id, true);
        PricebookEntry pbe7=IntegrationTestDataUtilty.createPricebookEntry(prodList[6].id, true);
        
        
        List<QuoteLineItem> qliList = new List<QuoteLineItem>();
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prodList[0].Id;
        qliList.add(qli); 
        
        QuoteLineItem qli2 = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe2.Id, false);
        qli2.Product2Id = prodList[1].Id;
        qliList.add(qli2);
        
        QuoteLineItem qli3 = IntegrationTestDataUtilty.createQuoteLineItem(qte1.Id, Pbe3.Id, false);
        qli3.Product2Id = prodList[2].Id;
        qliList.add(qli3);
        
        QuoteLineItem qli4 = IntegrationTestDataUtilty.createQuoteLineItem(qte2.Id, Pbe4.Id, false);
        qli4.Product2Id = prodList[3].Id;
        qliList.add(qli4);
        
        QuoteLineItem qli7 = IntegrationTestDataUtilty.createQuoteLineItem(qte2.Id, Pbe7.Id, false);
        qli7.Product2Id = prodList[6].Id;
        qliList.add(qli7);
        
        QuoteLineItem qli5 = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe5.Id, false);
        qli5.Product2Id = prodList[4].Id;
        qli5.vlocity_ins__ContractCode__c = null;
        qliList.add(qli5);
        
        QuoteLineItem qli9 = IntegrationTestDataUtilty.createQuoteLineItem(qte1.Id, Pbe5.Id, false);
        qli9.Product2Id = prodList[4].Id;
        qli9.vlocity_ins__ContractCode__c = null;
        qliList.add(qli9);
        
        QuoteLineItem qli6 = IntegrationTestDataUtilty.createQuoteLineItem(qte1.Id, Pbe6.Id, false);
        qli6.Product2Id = prodList[5].Id;
        qliList.add(qli6);
        
        QuoteLineItem qli8 = IntegrationTestDataUtilty.createQuoteLineItem(qte2.Id, Pbe6.Id, false);
        qli8.Product2Id = prodList[5].Id;
        insert qli8;
        
        QuoteLineItem childforParenDelQLI = IntegrationTestDataUtilty.createQuoteLineItem(qte2.Id, Pbe4.Id, false);
        childforParenDelQLI.Product2Id = prodList[3].Id;
        childforParenDelQLI.ParentQuoteLineItem__c = qli8.Id;
        insert childforParenDelQLI;
        
        QuoteLineItem qliParentError = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe6.Id, false);
        qliParentError.Product2Id = prodList[5].Id;
        qliList.add(qliParentError);
        
        Database.insert(qliList);
        
        List<WGS_Sold_Contract_Codes__c> wgsRecList = new List<WGS_Sold_Contract_Codes__c>();
        
        WGS_Sold_Contract_Codes__c allSuccessRec1= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61305', Contract_Code__c ='40QA', Benefit_Period__c = 'Calendar Year',
                                                                                  Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Success',
                                                                                  Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No', QLI_ID_Created__c = qliList[0].id);
        wgsRecList.add(allSuccessRec1);
        
        WGS_Sold_Contract_Codes__c allSuccessRec2= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61305', Contract_Code__c ='40PA', Benefit_Period__c = 'Calendar Year',
                                                                                  Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Success',
                                                                                  Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No', QLI_ID_Created__c = qliList[1].id);
        wgsRecList.add(allSuccessRec2);
        
        WGS_Sold_Contract_Codes__c partialSuccessRec1= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61307', Contract_Code__c ='40SA', Benefit_Period__c = 'Calendar Year',
                                                                                      Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Success',
                                                                                      Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No', QLI_ID_Created__c = qliList[2].id);
        wgsRecList.add(partialSuccessRec1);
        
        WGS_Sold_Contract_Codes__c partialSuccessRec2= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61307', Contract_Code__c ='40LA', Benefit_Period__c = 'Calendar Year',
                                                                                      Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Error',
                                                                                      Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No');
        wgsRecList.add(partialSuccessRec2);
        
        WGS_Sold_Contract_Codes__c partialSuccessRec3= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61307', Contract_Code__c ='40BA', Benefit_Period__c = 'Calendar Year',
                                                                                      Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Error',
                                                                                      Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No');
        wgsRecList.add(partialSuccessRec3);
        
        WGS_Sold_Contract_Codes__c secondRunSuccess1= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61308', Contract_Code__c ='40AA', Benefit_Period__c = 'Calendar Year',
                                                                                     Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Success',
                                                                                     Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No', QLI_ID_Created__c = qliList[4].id);
        wgsRecList.add(secondRunSuccess1);
        
        WGS_Sold_Contract_Codes__c secondRunSuccess2= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61308', Contract_Code__c ='40TA', Benefit_Period__c = 'Calendar Year',
                                                                                     Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Success',
                                                                                     Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No', QLI_ID_Created__c = qliList[3].id);
        wgsRecList.add(secondRunSuccess2);
        
        WGS_Sold_Contract_Codes__c secondRunSuccess3= new WGS_Sold_Contract_Codes__c(WGS_Group_Number__c = 'W61308', Contract_Code__c ='40TA', Benefit_Period__c = 'Calendar Year',
                                                                                     Effective_Date__c = Date.today(), Financing__c = 'Fully Insured', Funding_Type__c = 'FI', Status__c = 'Error',
                                                                                     Member_Count__c = 150, Subscriber_Count__c = 100, Upsell_Flag__c = 'No');
        wgsRecList.add(secondRunSuccess3);
        
        Database.insert(wgsRecList); 
        
        return wgsRecList;
    }
    
    @isTest
    static void testWGSCCDeeleteReport(){
        
        List<WGS_Sold_Contract_Codes__c> wgsRecList = createWGSInputTestData();
        
        System.debug('Test Data WGS Input data Records Size: '+ wgsRecList.size());
        
        String[] statuses= new String[]{'Success','Error'};
        String[] toEmails = new String[]{'sushmithachandra.venkata@anthem.com'}; 
        Date[] effectiveDatesToProcess = new Date[]{Date.today()};  
            
        WGSCCQLIDeleteReport.getdeleteQLIsReport( statuses,effectiveDatesToProcess, toEmails);
        System.assertEquals(1, Limits.getEmailInvocations(), 'An Email is sent with Attachments');
        
    } 
}