objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Anthem_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM-25346
PRDCRM - 26218</description>
        <inlineHelpText>Please select the Anthem Account Manager for this Client.</inlineHelpText>
        <label>Anthem Account Manager for the Client</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Early_Retiree_Population_Covered__c</fullName>
        <description>PRDCRM-20066
PRDCRM-26218</description>
        <inlineHelpText>Please indicate whether  the Client has an Early Retiree Population Covered Under the Anthem Medical Plan.</inlineHelpText>
        <label>Are early Retirees Covered?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Financing__c</fullName>
        <label>Financing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Funding__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Administrative Services Only</fullName>
                </value>
                <value>
                    <fullName>Cost Plus</fullName>
                </value>
                <value>
                    <fullName>Flat Fee / % of Savings</fullName>
                </value>
                <value>
                    <fullName>JAA (Jointly Administered Arrangement)</fullName>
                </value>
                <value>
                    <fullName>Minimum Premium</fullName>
                </value>
                <value>
                    <fullName>Modified Cost Plus</fullName>
                </value>
                <value>
                    <fullName>PEPM</fullName>
                </value>
                <value>
                    <fullName>Percent of Savings</fullName>
                </value>
                <value>
                    <fullName>PMPM</fullName>
                </value>
                <value>
                    <fullName>Cost Plus Alternate Funded</fullName>
                </value>
                <value>
                    <fullName>FI - Deposit Premium</fullName>
                </value>
                <value>
                    <fullName>FI - Refund Agreement</fullName>
                </value>
                <value>
                    <fullName>Fully Insured</fullName>
                </value>
                <value>
                    <fullName>Non-Refunding</fullName>
                </value>
                <value>
                    <fullName>Refunding</fullName>
                </value>
                <value>
                    <fullName>Flat Fee</fullName>
                </value>
                <value>
                    <fullName>Not Applicable</fullName>
                </value>
                <value>
                    <fullName>MCS Network Rental</fullName>
                </value>
                <value>
                    <fullName>Contingent Premium</fullName>
                </value>
                <value>
                    <fullName>JIA (Jointly Integrated Arrangement)</fullName>
                </value>
                <value>
                    <fullName>ABF (Anthem Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>EBF (Empire Balanced Funding)</fullName>
                </value>
                <value>
                    <fullName>ASC (Administrative Service Contract)</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
                <value>
                    <fullName>Level Funded/Fully Insured</fullName>
                </value>
                <value>
                    <fullName>JAA (Full Service) - ANA Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Geography_of_the_Population__c</fullName>
        <description>PRDCRM-20066
PRDCRM-26218</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Provide a breakdown where membership resides (i.e. state, % of membership population). List States and percentages in this manner: AL20%,MN54%,….</inlineHelpText>
        <label>Geography of Population per State</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_outreach__c</fullName>
        <description>PRDCRM-25346
PRDCRM-26218</description>
        <inlineHelpText>Select whether Anthem or Client provides the Marketing/Outreach File. As standard, Anthem provides. Account teams can request this at the Digital Marketing Operations SharePoint site. (https://share.antheminc.com/sites/edelivery/SitePages/welcome.aspx)</inlineHelpText>
        <label>Marketing / Outreach File Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Provided by client</fullName>
                </value>
                <value>
                    <fullName>Provided by Anthem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Members_Covered__c</fullName>
        <description>PRDCRM-20066
PRDCRM-26218</description>
        <inlineHelpText>Please indicate whether the Client has Members Covered Under a Commercial Medicare Plan</inlineHelpText>
        <label>Are Members Covered Under Medicare?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Other_Notes__c</fullName>
        <description>PRDCRM-25346 -  Text Area field for Notes</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Other/Notes Field</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Prefix_for_Client_Account__c</fullName>
        <description>PRDCRM-20066
        PRDCRM-26218 -updated help text</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>List all medical plan prefixes that the client wants Solera Health to manage.  List prefixes in this manner: ABC, EFG, HIJJ . . . .</inlineHelpText>
        <label>Prefix for Client Account</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Point_of_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Contact Information of Primary Point of Contact at Client Account  - PRDCRM - 25346</description>
        <inlineHelpText>Please select the Primary Point of Contact at the Client Account.</inlineHelpText>
        <label>Primary Point of Contact at the Client</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QLISoleraTemplateControllerTest.cls
/**************************************************************************************
@description          : Test Class for QLISoleraTemplateController
@Author                 : Mehaboob
US                        :  Modified Test class as part of PRDCRM-41975,43038
*************************************************************************************/
@isTest
private class QLISoleraTemplateControllerTest{

    static testMethod void testinsertOrUpdateQLI(){
        
        Id qliId;
        User testUser;
        Integer recordCount=1;
        Map<String,ID> profiles = new Map<String,ID>();
        User usr = [Select id from User where Id = :UserInfo.getUserId()];
         System.RunAs(usr){
          List<Profile> ps = [select id, name from Profile where name ='National Sales' or name = 'System Administrator'];
          for(Profile p : ps){
             profiles.put(p.name, p.id);
           }
          UserRole testRole = new UserRole(DeveloperName = 'TestRole', Name = 'Test Role');
          insert testRole;
          testUser = new User(alias = 'solera',email='testuser@testSolera.com',emailencodingkey='UTF-8',lastname='TestSolera', languagelocalekey='en_US',localesidkey='en_US',profileid = profiles.get('National Sales'),UserRoleId = testRole.Id,timezonesidkey='America/New_York',username='test121@testSolera.com');
          insert testUser;
         }
         
         //Insert account
         List<Account> accounts = new List<Account>();
         String accName='newaccount';
         String street='CA street';
         // String accRecordTypeName='Customer';
         //String situsState='ANA';
         String city='CA';
         String state='CA State';
         String zip='12345';
         String country='US';
         String stateCode='CAA';
         accounts =TestDataFactory.createAccountSICList(recordCount,accName,street,city,state,zip,country,stateCode);
         insert accounts; 
         
         //Insert Opportunity 
         List<Opportunity> opportunities = new List<Opportunity>();
         String optyName = 'test Opty';
         String optyRecordTypeName='New Business';
         String stageName='Prospecting';
         Date closeDate=System.Today();
         opportunities=TestDataFactory.createOpportunityList(recordCount,optyName,accounts[0]);
         insert opportunities; 
         
         //Insert Group
         Group__c groupRec=new Group__c();
         //String groupName='Test Group';
         Boolean doInsert=true;
         groupRec=TestDataFactory.createGroup(accounts[0].Id,doInsert);
         //insert groupRec;
       
         //Insert Product
         String prodName='Laptop X200';
         List<Product2> prodlist= new List<Product2>();
         prodlist=TestDataFactory.createProduct(prodName,recordCount);
         insert prodlist;
        
        //Insert PricebookEntry
        List<PricebookEntry> pricebookentrylist= new List<PricebookEntry>();
        pricebookentrylist=TestDataFactory.PricebookEntry(recordCount,prodlist[0]);
        insert pricebookentrylist;
        
        //Insert Quote
        List<Quote> quotelist= new List<Quote>();
        String quoteName='Test Quote';
        quotelist=TestDataFactory.Quote(quoteName,recordCount,opportunities[0]);
        insert quotelist;
        
        //Insert QuoteLineItem
        List<QuoteLineItem> quotelineitemlist= new List<QuoteLineItem>();
        String qliName='Test QLI';
        quotelineitemlist=TestDataFactory.QuoteLineItem(qliName,recordCount,quotelist[0],prodlist[0],pricebookentrylist[0]);
        insert quotelineitemlist;
      
        List<QuoteLineItem> qliFinalList=[SELECT Id,Description,Quote.AccountId,Quote.Account.Name,Prefix_for_Client_Account__c,Quote.Account.NASCO_Contracting_Situs_State__c,Quote.Account.WGS_Contracting_Situs_State__c,Financing__c,Primary_Point_of_Contact__r.Name,Primary_Point_of_Contact__r.Email,Primary_Point_of_Contact__r.Phone,Primary_Point_of_Contact__r.Title,Marketing_outreach__c,Anthem_Account_Manager__r.Name,Anthem_Account_Manager__r.Email,Anthem_Account_Manager__r.Phone,Anthem_Account_Manager__r.Title,Anthem_Account_Manager__r.UserRole.name,Quote.Opportunity.Closedate,Other_Notes__c,Geography_of_the_Population__c,Early_Retiree_Population_Covered__c,Members_Covered__c FROM QuoteLineItem WHERE id =:quotelineitemlist[0].Id Limit 1];

       Test.startTest();
        QuoteLineItem qliFinal=[SELECT Id,Description,Quote.AccountId,Quote.Account.Name,Prefix_for_Client_Account__c,Quote.Account.NASCO_Contracting_Situs_State__c,Quote.Account.WGS_Contracting_Situs_State__c,Financing__c,Primary_Point_of_Contact__r.Name,Primary_Point_of_Contact__r.Email,Primary_Point_of_Contact__r.Phone,Primary_Point_of_Contact__r.Title,Marketing_outreach__c,Anthem_Account_Manager__r.Name,Anthem_Account_Manager__r.Email,Anthem_Account_Manager__r.Phone,Anthem_Account_Manager__r.Title,Anthem_Account_Manager__r.UserRole.name,Quote.Opportunity.Closedate,Other_Notes__c,Geography_of_the_Population__c,Early_Retiree_Population_Covered__c,Members_Covered__c FROM QuoteLineItem WHERE id =:quotelineitemlist[0].Id Limit 1];
        QLISoleraTemplateController q=new QLISoleraTemplateController();
        q.QLIrec=qliFinalList;
        q.qliId=quotelineitemlist[0].Id;
        q.getQLIrec();
        
        System.assertEquals(accounts[0].Name,qliFinal.Quote.Account.Name,'Account returned from controller to template');
       Test.stopTest();       
   }
}