objects/Group__c.object
<CustomObject>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Contract_Code__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Should not be used by Sales</inlineHelpText>
        <label>Contract Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>P2AModified__c</fullName>
        <label>P2AModified</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>vlocity_ins__ContractCode__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Contract Code</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/P2AUpdateQliTest.cls
@isTest
public class P2AUpdateQliTest {
    
    static QuoteLineItem createData()
    {
       Account acc=IntegrationTestDataUtilty.createAccount(true); 
       
        Opportunity oppty=IntegrationTestDataUtilty.createOpportunity(acc.id, true);
        
        Group__c grp=IntegrationTestDataUtilty.createGroup(acc.id, true);
        
        Quote qte=IntegrationTestDataUtilty.createQuote(oppty.Id, grp.id, true);
        
        Product2 prod=IntegrationTestDataUtilty.createProduct(true);
        prod.Contract_Code__c = '40QA';
        Database.update(prod);
        
        PricebookEntry pbe=IntegrationTestDataUtilty.createPricebookEntry(prod.id, true);
        QuoteLineItem qlitest = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, true);
       
        QuoteLineItem qli = IntegrationTestDataUtilty.createQuoteLineItem(qte.Id, Pbe.Id, false);
        qli.Product2Id = prod.Id;
        qli.P2AModified__c = 'Yes';
        qli.vlocity_ins__ContractCode__c = '40QA';
        System.debug(qli);
        Database.insert(qli); 
        
        return qli;
    }
     @isTest 
     static void testUpdateNo(){
   
		QuoteLineItem qli = createData();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
         
        request.requestUri =System.URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/P2AUpdateQLI/'+ qli.Id;
        //request.httpMethod = 'PATCH';
        request.httpMethod = 'GET';
        request.params.put('modifiedFlag', 'N');
        request.params.put('qliId', qli.Id);
        request.addHeader('Content-Type', 'application/json');
        //request.requestBody = Blob.valueOf('{"modifiedFlag": "N"}');
        RestContext.request = request;
        RestContext.response = response;
         
        Test.startTest(); 
        P2AUpdateQli.UpdateQLI();
        Test.stopTest(); 
        
        System.assert(qli.Id != null);
        QuoteLineItem QliUpdated = [SELECT Id,P2AModified__c FROM QuoteLineItem WHERE Id=:qli.Id];
        System.debug(qliUpdated.P2AModified__c);
        System.assert(qliUpdated != null);
       System.assertEquals('No', qliUpdated.P2AModified__c);
    }  
	@isTest 
     static void testUpdateYes(){
   
		QuoteLineItem qli = createData();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
         
        request.requestUri =System.URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/P2AUpdateQLI/'+ qli.Id;
       // request.httpMethod = 'PATCH';
        request.httpMethod = 'GET';
        request.params.put('modifiedFlag', 'Y');
        request.params.put('qliId', qli.Id);
        request.addHeader('Content-Type', 'application/json');
      //  request.requestBody = Blob.valueOf('{"modifiedFlag": "N"}');
        RestContext.request = request;
        RestContext.response = response;
         
        Test.startTest(); 
        P2AUpdateQli.UpdateQLI();
        Test.stopTest(); 
        
        System.assert(qli.Id != null);
        QuoteLineItem QliUpdated = [SELECT Id,P2AModified__c FROM QuoteLineItem WHERE Id=:qli.Id];
        System.debug(qliUpdated.P2AModified__c);
        System.assert(qliUpdated != null);
        System.assertEquals('Yes', qliUpdated.P2AModified__c);
    }  
		@isTest 
     static void testUpdateError(){
   
		QuoteLineItem qli = createData();

        RestRequest request = new RestRequest();
        RestResponse response = new RestResponse();
         
        request.requestUri =System.URL.getSalesforceBaseUrl().toExternalForm()+'/services/apexrest/P2AUpdateQLI/'+ qli.Id+'?modifiedFlag=N';
        //request.httpMethod = 'PATCH';
         request.httpMethod = 'GET';
        //request.params.put('modifiedFlag', 'Y');
        //request.params.put('qliId', qliId);
        request.addHeader('Content-Type', 'application/json');
        RestContext.request = request;
        RestContext.response = response;
         
        Test.startTest(); 
        P2AUpdateQli.UpdateQLI();
        Test.stopTest(); 
        
        System.assert(qli.Id != null);
        QuoteLineItem QliUpdated = [SELECT Id,P2AModified__c FROM QuoteLineItem WHERE Id=:qli.Id];
        System.debug(qliUpdated.P2AModified__c);
        System.assert(qliUpdated != null);
       
    }  

}