objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Implementer__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assigned Implementer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClaimSystem__c</fullName>
        <label>Claim System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>NASCO</fullName>
                </value>
                <value>
                    <fullName>WGS 2.0</fullName>
                </value>
                <value>
                    <fullName>ACES</fullName>
                </value>
                <value>
                    <fullName>ALICS</fullName>
                </value>
                <value>
                    <fullName>AniTa</fullName>
                </value>
                <value>
                    <fullName>CHIPS</fullName>
                </value>
                <value>
                    <fullName>COMPASS</fullName>
                </value>
                <value>
                    <fullName>CS90</fullName>
                </value>
                <value>
                    <fullName>DeCare Dental</fullName>
                </value>
                <value>
                    <fullName>FACETS</fullName>
                </value>
                <value>
                    <fullName>WDS</fullName>
                </value>
                <value>
                    <fullName>GBD FACETS</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>This field is used for National Accounts when requesting a group number. It is referenced in both a flow and email template, which should be adjusted prior to modifying this field.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <recordTypes>
        <fullName>Group</fullName>
        <active>true</active>
        <label>Group</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Implementation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Assigned_Implementer__c</fullName>
        <formula>Implementation_Record_ID__r.Assigned_Implementer__r.FirstName + &apos; &apos; +  Implementation_Record_ID__r.Assigned_Implementer__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assigned Implementer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <formula>Implementation_Record_ID__r.Implementation_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Implementation Tracking</label>
    <nameField>
        <displayFormat>TRACK-{000000}</displayFormat>
        <label>Implementation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT( Opportunity.Account.Anthem_Entity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SME_Approvals__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Group_Number__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp;  Implementation_Record_ID__r.Quote.GroupNumber__c , Implementation_Record_ID__r.Quote.GroupNumber__r.Name ,&quot;_blank&quot;)</formula>
        <label>Group Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Impact_to_HPCC__c</fullName>
        <label>Impact To HPCC</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Cannot Determine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Implementation_Case_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Implementation_Record_ID__c, Implementation_Record_ID__r.Implementation_Case_Name__c ,&quot;_blank&quot;)</formula>
        <label>Implementation Case Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <formula>Implementation_Record_ID__r.Implementation_Effective_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipName>SME_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Status__c</fullName>
        <formula>text(Implementation_Record_ID__r.Implementation_Status__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Implementation Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SME_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The User Who Modified The Stage / Approved The Implementation Case Record For This Department</inlineHelpText>
        <label>SME Approver</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>1</booleanFilter>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>SME,SME Dual</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>SME_Approvals</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SME_Department__c</fullName>
        <label>SME Department</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>Act Wise CDH</fullName>
                </value>
                <value>
                    <fullName>Act Wise FSA</fullName>
                </value>
                <value>
                    <fullName>Anthem Flex Hour</fullName>
                </value>
                <value>
                    <fullName>Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>Benefit Booklets/Contracts</fullName>
                    <isActive>false</isActive>
                    <label>Benefit Booklets/Contracts</label>
                </value>
                <value>
                    <fullName>Blue Exchange (BX)</fullName>
                </value>
                <value>
                    <fullName>Bold</fullName>
                </value>
                <value>
                    <fullName>CCMU</fullName>
                </value>
                <value>
                    <fullName>Claims</fullName>
                </value>
                <value>
                    <fullName>Claims Retro</fullName>
                </value>
                <value>
                    <fullName>Contracts</fullName>
                </value>
                <value>
                    <fullName>Coordinated Care Model</fullName>
                </value>
                <value>
                    <fullName>Coordination of Benefits</fullName>
                </value>
                <value>
                    <fullName>Data Interface Team (DIT)</fullName>
                </value>
                <value>
                    <fullName>DeCare</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>EAP</fullName>
                </value>
                <value>
                    <fullName>EBA</fullName>
                    <isActive>false</isActive>
                    <label>EBA</label>
                </value>
                <value>
                    <fullName>Enrollment and Billing (E/B)</fullName>
                </value>
                <value>
                    <fullName>Group Services</fullName>
                </value>
                <value>
                    <fullName>Health and Wellness Solutions</fullName>
                </value>
                <value>
                    <fullName>HealthEquity/WageWorks/FSA/COBRA</fullName>
                </value>
                <value>
                    <fullName>ID Cards</fullName>
                </value>
                <value>
                    <fullName>IHM</fullName>
                </value>
                <value>
                    <fullName>Implementations</fullName>
                </value>
                <value>
                    <fullName>Interplan</fullName>
                </value>
                <value>
                    <fullName>IT</fullName>
                </value>
                <value>
                    <fullName>JAA/NTS</fullName>
                </value>
                <value>
                    <fullName>Life and Disability</fullName>
                </value>
                <value>
                    <fullName>LITES CDH</fullName>
                </value>
                <value>
                    <fullName>Medical Benefits</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Selections_Report_Required__c</fullName>
        <label>Selections Report Required</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Cannot Determine</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <defaultValue>&quot;Initiated&quot;</defaultValue>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Initiated</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Approved for Castlight (EBA Only)</fullName>
                </value>
                <value>
                    <fullName>Approved with Deviations</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Strings_Tables_Contract_Codes_Impacted__c</fullName>
        <label>Strings/Tables/Contract Codes Impacted</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>TBD</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>SME Approvals</label>
    <nameField>
        <displayFormat>SMEAPR-{000}</displayFormat>
        <label>SME Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SME Approvals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AP21_SMENotifyApproverEMail_Test.cls
/*
@author         Accenture offshore
@date           4/20/2018
@name           AP21_SMENotifyApproverEMail_Test
@description    This class is used to check the code coverage for AP21_SMENotifyApproverEMail .  
*/
@Istest
private class AP21_SMENotifyApproverEMail_Test {
    
static testMethod void SMENotifyApproverEMailTest() {
 
    test.startTest();
     Profile p = [SELECT Id FROM Profile WHERE Name='SME']; 
     User user = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fghdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test2314@testorg.com');

    insert user;
    
    
    Profile p1 = [SELECT Id FROM Profile WHERE Name='Local Implementations']; 
     User user2 = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fgasdhdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p1.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test23123we4@testorg.com');

    insert user2;
    


    Account acc = ANA_UTIL01_TestMethods.createAccount(false); 
    insert acc;
  
        //Creating Opportunity Records

        Opportunity opty = new opportunity(Name = 'test Opty',StageName = 'Engage',Closedate = Date.newInstance(2008,11,20),AccountId = acc.Id);
        insert opty; 
        Group__c grp1 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp1.ClaimSystem__c = 'NASCO';
            insert(grp1);
       Group__c grp2 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp2.ClaimSystem__c = 'WGS 2.0';
            insert(grp2);  
        //System.debug('Opty is created' );
        Quote quoteRec = new Quote(Name = 'Test Quote',OpportunityId = opty.Id,GroupNumber__c=grp1.id);
        insert quoteRec;
        System.debug('Quote is created' );
        
        //Creating Group
        
 Order ord = new Order(Group_Name__c=grp1.id,AccountId = acc.Id, EffectiveDate=System.today(), 
                       Status = 'Draft',Implementation_Case_Name__c = 'AIMTesting01', Discovery_Call_Desired__c ='Yes',
                       Implementation_Status__c = 'Initiated', Implementation_Effective_Date__c=System.today(),
                       Assigned_Implementer__c=user2.id,QuoteId=quoteRec.id
                      );      
 insert ord;
 
    
    
    
    List<SME_Approvals__c> smelist = new List<SME_Approvals__c>();
    SME_Approvals__c sme1= new SME_Approvals__c();
    sme1.SME_Approver__c=user.id;
    sme1.SME_Department__c='Group Services';
    sme1.Implementation_Record_ID__c = ord.Id;
    sme1.Selections_Report_Required__c ='Yes';
    sme1.Impact_to_HPCC__c ='Yes';
    sme1.Status__c ='Approved';
    smelist.add(sme1);              
    
    SME_Approvals__c sme2= new SME_Approvals__c();
    sme2.SME_Approver__c=user.id;
    sme2.SME_Department__c='Medical Benefits';
    sme2.Implementation_Record_ID__c = ord.Id;
    sme2.Selections_Report_Required__c ='Yes';
    sme2.Impact_to_HPCC__c ='Yes';
    sme2.Status__c ='Approved';
    sme2.Strings_Tables_Contract_Codes_Impacted__c ='Yes'; 
    smelist.add(sme2);
    
    SME_Approvals__c sme3= new SME_Approvals__c();
    sme3.SME_Approver__c=user.id;
    sme3.SME_Department__c='Health and Wellness Solutions';
    sme3.Implementation_Record_ID__c = ord.Id;
    sme3.Selections_Report_Required__c ='Yes';
    sme3.Comments__c='satya';   
    sme3.Impact_to_HPCC__c ='Yes';
    sme3.Status__c ='Approved';
    smelist.add(sme3);
 
    insert smelist;

    sme3.Selections_Report_Required__c='No';
    sme3.Impact_to_HPCC__c='No';
    update sme3; 
    
    sme1.Selections_Report_Required__c ='No';
    update sme1;
    
    sme1.Impact_to_HPCC__c ='No';
    update sme1;
    
    
    sme2.Strings_Tables_Contract_Codes_Impacted__c ='Yes'; 
    update sme2;
    
    
    
   List<String> strlist= new List<String>();
   String sendto1='test@gmail.com';
   strlist.add(sendto1);
    String subjectLine='Email test';
    String Salutation='Mr';
    String prirorValue ='Test';
    String newValue ='new test value';
    String hyperLink ='Emila testing Hyperlink';
    String mailBody='testing message suceesfully or not';
    AP21_SMENotifyApproverEMail.sendMailMethod(strlist, subjectLine, Salutation, prirorValue, newValue, hyperLink, mailBody);
    prirorValue =null;
    newValue=null;
    AP21_SMENotifyApproverEMail.sendMailMethod(strlist, subjectLine, Salutation, prirorValue, newValue, hyperLink, mailBody);    
  
test.stopTest();
}
    
    static testMethod void SMENotifyApproverEMailTest2(){
    
        
   test.startTest();       
     Profile p = [SELECT Id FROM Profile WHERE Name='SME']; 
     User user = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fghdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test2314@testorg.com');

    insert user;
    
    
    Profile p1 = [SELECT Id FROM Profile WHERE Name='Local Implementations']; 
     User user2 = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fgasdhdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p1.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test23123we4@testorg.com');

    insert user2;
 
 Account acc = ANA_UTIL01_TestMethods.createAccount(false); 
        acc.Anthem_Entity__c='National Accounts';
        insert acc ;
        
  Opportunity opty = new opportunity(Name = 'test Opty',StageName = 'Engage',Closedate = Date.newInstance(2008,11,20),AccountId = acc.Id);
        insert opty; 
        Group__c grp1 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp1.ClaimSystem__c = 'NASCO';
            insert(grp1);
       Group__c grp2 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp2.ClaimSystem__c = 'WGS 2.0';
            insert(grp2);  
        //System.debug('Opty is created' );
        Quote quoteRec = new Quote(Name = 'Test Quote',OpportunityId = opty.Id,GroupNumber__c=grp1.id);
        insert quoteRec;
        System.debug('Quote is created' );
                  
        
 Order ord = new Order(Group_Name__c=grp1.id,AccountId = acc.Id, EffectiveDate=System.today(), 
                       Status = 'Draft',Implementation_Case_Name__c = 'AIMTesting01', Discovery_Call_Desired__c ='Yes',
                       Implementation_Status__c = 'Initiated', Implementation_Effective_Date__c=System.today(),
                       Assigned_Implementer__c=user2.id 
                      );      
 insert ord;
      Id RecTypeId=Schema.SObjectType.Implementation_Tracking__c.getRecordTypeInfosByName().get('National NASCO and WGS').getRecordTypeId();  
      Implementation_Tracking__c trackRec = new Implementation_Tracking__c(
     
        Implementation_Record_ID__c =ord.id,
        Group_Number__c=grp1.id,  
        Account_Legal_Name__c=acc.id,
         RecordTypeId=RecTypeId
      );
       
   //  insert trackRec;
    
    List<SME_Approvals__c> smelist = new List<SME_Approvals__c>();
    SME_Approvals__c sme1= new SME_Approvals__c();
    sme1.SME_Approver__c=user.id;
    sme1.SME_Department__c='Group Services';
    sme1.Implementation_Record_ID__c = ord.Id;
    sme1.Selections_Report_Required__c ='Yes';
    sme1.Impact_to_HPCC__c ='Yes';
    sme1.Status__c ='Approved';
    smelist.add(sme1);              
    
    SME_Approvals__c sme2= new SME_Approvals__c();
    sme2.SME_Approver__c=user.id;
    sme2.SME_Department__c='Medical Benefits';
    sme2.Implementation_Record_ID__c = ord.Id;
    sme2.Selections_Report_Required__c ='Yes';
    sme2.Impact_to_HPCC__c ='Yes';
    sme2.Status__c ='Approved';
      
    sme2.Strings_Tables_Contract_Codes_Impacted__c ='Yes'; 
    smelist.add(sme2);
    
    SME_Approvals__c sme3= new SME_Approvals__c();
    sme3.SME_Approver__c=user.id;
    sme3.SME_Department__c='Health and Wellness Solutions';
    sme3.Implementation_Record_ID__c = ord.Id;
    sme3.Selections_Report_Required__c ='Yes';
    sme3.Comments__c='satya';   
    sme3.Impact_to_HPCC__c ='Yes';
    sme3.Status__c ='Approved';
    smelist.add(sme3);
        
    SME_Approvals__c sme4= new SME_Approvals__c();
    sme4.SME_Approver__c=user.id;
    sme4.SME_Department__c='ID Cards';
    sme4.Implementation_Record_ID__c = ord.Id;
    sme4.Selections_Report_Required__c ='Yes';
    sme4.Comments__c='satya';   
    sme4.Impact_to_HPCC__c ='Yes';
    sme4.Status__c ='Approved';
    smelist.add(sme4);   
  
    insert smelist;
           
    sme2.Strings_Tables_Contract_Codes_Impacted__c ='No'; 
    sme2.Status__c ='Approved with Deviations';
    sme2.Comments__c='satya';
    update sme2;
    
    sme4.Status__c ='Approved with Deviations';
    update sme4 ; 
    
     system.debug('%%%%%%%sme4'+sme4); 
   test.stopTest(); 
    }
        
    static testMethod void SMENotifyApproverEMailTest3() {
  test.startTest();  
     Profile p = [SELECT Id FROM Profile WHERE Name='SME']; 
     User user = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fghdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test2314@testorg.com');

    insert user;
    
    
    Profile p1 = [SELECT Id FROM Profile WHERE Name='Local Implementations']; 
     User user2 = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', 
                      EmailEncodingKey='UTF-8', LastName='fgasdhdfh', LanguageLocaleKey='en_US', 
                      LocaleSidKey='en_US', ProfileId = p1.Id, 
                      TimeZoneSidKey='America/Los_Angeles', UserName='test23123we4@testorg.com');

    insert user2;
    


    Account acc = ANA_UTIL01_TestMethods.createAccount(false); 
    insert acc;
  
        //Creating Opportunity Records

        Opportunity opty = new opportunity(Name = 'test Opty',StageName = 'Engage',Closedate = Date.newInstance(2008,11,20),AccountId = acc.Id);
        insert opty; 
        Group__c grp1 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp1.ClaimSystem__c = 'NASCO';
            insert(grp1);
       Group__c grp2 = ANA_UTIL01_TestMethods.createGroup(acc.id,false);
            grp2.ClaimSystem__c = 'WGS 2.0';
            insert(grp2);  
        //System.debug('Opty is created' );
        Quote quoteRec = new Quote(Name = 'Test Quote',OpportunityId = opty.Id,GroupNumber__c=grp2.id);
        insert quoteRec;
        System.debug('Quote is created' );
        
        //Creating Group
        
 Order ord = new Order(Group_Name__c=grp2.id,AccountId = acc.Id, EffectiveDate=System.today(), 
                       Status = 'Draft',Implementation_Case_Name__c = 'AIMTesting01', Discovery_Call_Desired__c ='Yes',
                       Implementation_Status__c = 'Initiated', Implementation_Effective_Date__c=System.today(),
                       Assigned_Implementer__c=user2.id,QuoteId=quoteRec.id
                      );      
 insert ord;
 
    
    
    
    List<SME_Approvals__c> smelist = new List<SME_Approvals__c>();
    SME_Approvals__c sme1= new SME_Approvals__c();
    sme1.SME_Approver__c=user.id;
    sme1.SME_Department__c='Group Services';
    sme1.Implementation_Record_ID__c = ord.Id;
    sme1.Selections_Report_Required__c ='Yes';
    sme1.Impact_to_HPCC__c ='Yes';
    sme1.Status__c ='Approved';
    smelist.add(sme1);              
    
    SME_Approvals__c sme2= new SME_Approvals__c();
    sme2.SME_Approver__c=user.id;
    sme2.SME_Department__c='Medical Benefits';
    sme2.Implementation_Record_ID__c = ord.Id;
    sme2.Selections_Report_Required__c ='Yes';
    sme2.Impact_to_HPCC__c ='Yes';
    sme2.Status__c ='Approved';
    sme2.Strings_Tables_Contract_Codes_Impacted__c ='Yes'; 
    smelist.add(sme2);
    
    SME_Approvals__c sme3= new SME_Approvals__c();
    sme3.SME_Approver__c=user.id;
    sme3.SME_Department__c='Health and Wellness Solutions';
    sme3.Implementation_Record_ID__c = ord.Id;
    sme3.Selections_Report_Required__c ='Yes';
    sme3.Comments__c='satya';   
    sme3.Impact_to_HPCC__c ='Yes';
    sme3.Status__c ='Approved';
    smelist.add(sme3);
 
    insert smelist;

    sme3.Selections_Report_Required__c='No';
    sme3.Impact_to_HPCC__c='No';
    update sme3; 
    
    sme2.Selections_Report_Required__c ='No';
    update sme2;
    
    sme2.Impact_to_HPCC__c ='No';
    update sme2;

    
   List<String> strlist= new List<String>();
   String sendto1='test@gmail.com';
   strlist.add(sendto1);
    String subjectLine='Email test';
    String Salutation='Mr';
    String prirorValue ='Test';
    String newValue ='new test value';
    String hyperLink ='Emila testing Hyperlink';
    String mailBody='testing message suceesfully or not';
    AP21_SMENotifyApproverEMail.sendMailMethod(strlist, subjectLine, Salutation, prirorValue, newValue, hyperLink, mailBody);
    prirorValue =null;
    newValue=null;
    AP21_SMENotifyApproverEMail.sendMailMethod(strlist, subjectLine, Salutation, prirorValue, newValue, hyperLink, mailBody);   
 test.stopTest(); 
  }
  
}