objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>Text(Account__r.Anthem_Entity__c)</formula>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_Implementer__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Assigned Implementer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Effective_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Implementation Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Situs State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT( Opportunity.Account.Anthem_Entity__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <formula>TEXT(Opportunity.Account.Situs_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Situs State</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Discount_sharing__c</fullName>
        <label>Discount sharing</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Accepted</fullName>
                </value>
                <value>
                    <fullName>Sold/Renewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EPHC_Enhanced_Personal_Health_Care__c</fullName>
        <label>EPHC (Enhanced Personal Health Care)</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Not Accepted</fullName>
                </value>
                <value>
                    <fullName>Sold/Renewed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group_Size__c</fullName>
        <label>Group Size</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>51 - 99</fullName>
                </value>
                <value>
                    <fullName>100 - 249</fullName>
                </value>
                <value>
                    <fullName>250 - 499</fullName>
                </value>
                <value>
                    <fullName>500 - 999</fullName>
                </value>
                <value>
                    <fullName>1000+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Status__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Status</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ParentQuoteLineItem__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to self.</description>
        <label>Parent Quote Line Item</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Term_Years_Left__c</fullName>
        <label>Product Term Years Left</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <formula>TEXT(Product2.Product_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Quote.Opportunity.Account.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Upsell__c</fullName>
        <label>Upsell</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SIC__c.object
<CustomObject>
    <label>SIC</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Industry</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SICs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LGOrderImpactedProducts_Test.cls
@isTest
public class LGOrderImpactedProducts_Test {
    
    @testSetup
    public static void testSetUpMethod(){
        SIC__c SIC = new SIC__c(Name = staticVariableClass.SIC);
        Insert SIC;
        
        Account acc =new Account(
            RecordTypeId = Schema.getGlobalDescribe().get('Account').getDescribe().getRecordTypeInfosByName().get('LG Prospect').getRecordTypeId(),
            Name = staticVariableClass.AccountName,Account_s_Suppress_Auto_Renewal__c = false,Anthem_Entity__c = staticVariableClass.Entity,
            Region__c= staticVariableClass.Region, Branding__c =staticVariableClass.UniCare,SIC__c = SIC.Id,Group_Size__c =staticVariableClass.size,
            Total_Employees__c =staticVariableClass.emp, HQ_State__c =staticVariableClass.AK, Situs_State__c = staticVariableClass.California,
            Mailing_Address_Same_as_Physical_Address__c = true, BillingStreet = 'Land Mark', BillingPostalCode = '636111',
            BillingCity = 'Banglore', BillingCountry = 'India', BillingState = 'Karnataka', Physical_County__c = '121');
        insert acc;
        
        List<Id> lstOpp= new List<Id>();
        
        Opportunity newOpp = new Opportunity(Name=  (String.valueOf(system.today().year() + 1) + ' New Business Local-' + acc.Name), 
                                             StageName = staticVariableClass.ClosedWon, AccountID = acc.id, CloseDate = ((system.TODAY())-95),                   
                                             RecordTypeId = Schema.getGlobalDescribe().get('Opportunity').getDescribe().getRecordTypeInfosByName().get('New Business Local').getRecordTypeId());
        
        INSERT newOpp;
        
        Group__c grp=ANA_UTIL01_TestMethods.createGroup(acc.id,false);
        insert grp;
        
        Quote qte=ANA_UTIL01_TestMethods.createQuote(false,newOpp.Id);
        qte.GroupNumber__c=grp.id;
        insert qte;
        
        Product2 DentalProd=ANA_UTIL01_TestMethods.createProduct(false);
        DentalProd.name='Anthem Dental';
        DentalProd.Product_Type__c = 'Dental';
        
        Product2 VisionProd = DentalProd.Clone();
        VisionProd.name='Anthem Vision';
        VisionProd.Product_Type__c = 'Vision';
        
        Product2 LifeProd = DentalProd.Clone();
        LifeProd.name='Anthem LifeProd';
        LifeProd.Product_Type__c = 'Life';
        
        Product2 MedicalProd = DentalProd.Clone();
        MedicalProd.Product_Type__c = 'Medical';
        
        Product2 MedicalProdLegacy = DentalProd.Clone();
        MedicalProd.Product_Type__c = 'Medical';
        
        insert new list<Product2>{DentalProd, VisionProd, LifeProd, MedicalProd,MedicalProdLegacy};
            
            PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false, DentalProd.id);
        PricebookEntry pbe2=ANA_UTIL01_TestMethods.createPricebookEntry(false, VisionProd.id);
        PricebookEntry pbe3=ANA_UTIL01_TestMethods.createPricebookEntry(false, LifeProd.id);
        PricebookEntry pbe4=ANA_UTIL01_TestMethods.createPricebookEntry(false, MedicalProd.id);
        insert new list<PricebookEntry>{pbe, pbe2, pbe3, pbe4};
            
            QuoteLineItem DentalQLI= ANA_UTIL01_TestMethods.createQuoteLineItem(false, qte.Id, pbe.id);
        DentalQLI.Quantity =  123.0;
        DentalQLI.UnitPrice =12.0;
        DentalQLI.Product_Term_Years_Left__c ='5';
        DentalQLI.Discount_sharing__c = staticVariableClass.SoldRenewed;
        DentalQLI.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        DentalQLI.ProductStage__c= staticVariableClass.Sold;
        DentalQLI.Product2ID = DentalProd.ID;
        DentalQLI.Upsell__c = '';
        
        
        QuoteLineItem VisionQLI = DentalQLI.clone();
        VisionQLI.Product2ID = VisionProd.ID;
        VisionQLI.Upsell__c = '';
        VisionQLI.Quantity = 1.0;
        VisionQLI.UnitPrice = 1.0;
        VisionQLI.Product_Term_Years_Left__c = '1';
        VisionQLI.Discount_sharing__c = staticVariableClass.SoldRenewed;
        VisionQLI.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        VisionQLI.ProductStage__c= staticVariableClass.Sold;
        
        
        
        QuoteLineItem LifeQLI = DentalQLI.clone();
        LifeQLI.Product2ID = LifeProd.ID;
        LifeQLI.Upsell__c = '';
        LifeQLI.Quantity = 1.0;
        LifeQLI.UnitPrice = 1.0;
        LifeQLI.Product_Term_Years_Left__c = '1';
        LifeQLI.Discount_sharing__c = staticVariableClass.SoldRenewed;
        LifeQLI.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        LifeQLI.ProductStage__c= staticVariableClass.Sold;
        
        
        QuoteLineItem MedicalQLI = DentalQLI.clone();
        MedicalQLI.Product2ID = MedicalProd.ID;
        MedicalQLI.Upsell__c = '';
        MedicalQLI.Quantity = 1.0;
        MedicalQLI.UnitPrice = 1.0;
        MedicalQLI.Product_Term_Years_Left__c = '1';
        MedicalQLI.Discount_sharing__c = staticVariableClass.SoldRenewed;
        MedicalQLI.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        MedicalQLI.ProductStage__c= staticVariableClass.Sold;
        
        
        QuoteLineItem MedicalQLILeg = DentalQLI.clone();
        MedicalQLILeg.Product2ID = MedicalProdLegacy.ID;
        MedicalQLILeg.Upsell__c = '';
        MedicalQLILeg.Quantity = 1.0;
        MedicalQLILeg.UnitPrice = 1.0;
        MedicalQLILeg.Product_Term_Years_Left__c = '1';
        MedicalQLILeg.Discount_sharing__c = staticVariableClass.SoldRenewed;
        MedicalQLILeg.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        MedicalQLILeg.ProductStage__c= staticVariableClass.Sold;
        
        QuoteLineItem MedicalQLI2 = DentalQLI.clone();
        MedicalQLI2.ParentQuoteLineItem__c = MedicalQLI.Id;
        MedicalQLI2.Upsell__c = 'No';
        MedicalQLI2.Quantity = 1.0;
        MedicalQLI2.UnitPrice = 1.0;
        MedicalQLI2.Product_Term_Years_Left__c = '1';
        MedicalQLI2.Discount_sharing__c = staticVariableClass.SoldRenewed;
        MedicalQLI2.EPHC_Enhanced_Personal_Health_Care__c = staticVariableClass.SoldRenewed;
        MedicalQLI2.ProductStage__c= staticVariableClass.Sold;
        
        test.startTest();
        insert new list<QuoteLineItem>  {   DentalQLI, VisionQLI, LifeQLI, MedicalQLI, 
            MedicalQLI2
            };
                
                Profile p1 = [SELECT Id FROM Profile WHERE Name='Local Implementations']; 
        User user2 = new User(Alias = 'asfsaf', Email='standarduser@testorg.com', EmailEncodingKey='UTF-8', LastName='fgasdhdfh', 
                              LanguageLocaleKey='en_US', LocaleSidKey='en_US', ProfileId = p1.Id, TimeZoneSidKey='America/Los_Angeles', 
                              UserName='test23123we4@testorg.com');
        
        insert user2;
        
        Order ord = new Order(Group_Name__c=grp.id,AccountId = acc.Id, EffectiveDate=System.today(), Status = 'Draft',
                              Implementation_Case_Name__c = 'AIMTesting01', Discovery_Call_Desired__c ='Yes', Implementation_Status__c = 'Ready for Imps', 
                              Implementation_Effective_Date__c=System.today(), Assigned_Implementer__c=user2.id,QuoteId=qte.id);
        
        
        insert new list<Order>{ord};
    }
    
    @isTest
    public static void testGetQliOfCase()
    {
        List<Order> ord = new List<Order>([select id,QuoteId from Order where Implementation_Case_Name__c='AIMTesting01']);
        test.startTest();
        if(ord.size()>0){
            LGOrderImpactedProducts_Ctrl.getQliOfCase(ord[0].Id,ord[0].QuoteId);
        }
        test.stopTest();
    }
    @isTest
    public static void testGetQliOfCaseWithIMP()
    {
        List<Order> ord = new List<Order>([select id,QuoteId from Order where Implementation_Case_Name__c='AIMTesting01']);
        List<QuoteLineItem> qli = new List<QuoteLineItem>([select id, Product2.Name from QuoteLineItem where Product2.Name='Anthem LifeProd']);
        ord[0].Impacted_Products_Id__c = qli[0].Id;
        test.startTest();
        update ord[0];
        if(ord.size()>0){
            LGOrderImpactedProducts_Ctrl.getQliOfCase(ord[0].Id,ord[0].QuoteId);
        }
        test.stopTest();
    }
    
    @isTest
    public static void testUpdateQli()
    {
        
        Map<String,QuoteLineItem> qliIds = new Map<String,QuoteLineItem>([select id from QuotelineItem where Upsell__c = 'yes' OR Upsell__c = 'No']);
        List<Order> ord = new List<Order>([select id,QuoteId from Order where Implementation_Case_Name__c='AIMTesting01']);
        List<String> qliIdList = new List<String>();
        qliIdList.addAll(qliIds.keySet());
        test.startTest();
        if(!qliIdList.isEmpty() && qliIdList!=null)
        {
            
            
            LGOrderImpactedProducts_Ctrl.updateQli(qliIdList,ord[0].Id);
        }
        else
        {
            System.debug('Not Updated');
            //LGOrderImpactedProducts_Ctrl.updateQli(qliIdList,ord[0].Id);
        }
        test.stopTest();
        
    }
    @isTest
    public static void testUpdateQliNull()
    {
        List<Order> ord = new List<Order>([select id,QuoteId from Order where Implementation_Case_Name__c='AIMTesting01']);
        List<String> qliIdList = new List<String>();
        test.startTest();
        LGOrderImpactedProducts_Ctrl.updateQli(qliIdList,ord[0].Id);
        test.stopTest();
    }
    
    @isTest
    public static void testGetQliOfCaseOrdIdNull()
    {
        
        List<String> qliIdList = new List<String>();
        test.startTest();
        LGOrderImpactedProducts_Ctrl.getQliOfCase(null,null);
        test.stopTest();
    }
}