objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Account_Manager__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Account Manager</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <description>It is the Account associated with the Group.</description>
        <inlineHelpText>It defines the Account associated with the Group.</inlineHelpText>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Groups</relationshipLabel>
        <relationshipName>Groups</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HRA_Administration__c.object
<CustomObject>
    <description>Child to QuoteLineItem for ANA / LG CDHP Admin</description>
    <fields>
        <fullName>AllocationEA__c</fullName>
        <label>AllocationEA</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AllocationEChildren__c</fullName>
        <label>AllocationEChildren</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AllocationEE__c</fullName>
        <label>AllocationEE</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>AllocationFamily__c</fullName>
        <label>AllocationFamily</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Allocation_EChild__c</fullName>
        <label>Allocation EChild</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Annual_Allocation_Tiers__c</fullName>
        <label>Annual Allocation Tiers</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2 Tier</fullName>
                </value>
                <value>
                    <fullName>3 Tier</fullName>
                </value>
                <value>
                    <fullName>4 Tier</fullName>
                </value>
                <value>
                    <fullName>5 Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CapEA__c</fullName>
        <label>CapEA</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapEChild__c</fullName>
        <label>CapEChild</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapEChildren__c</fullName>
        <label>CapEChildren</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapEE__c</fullName>
        <label>CapEE</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CapEFamily__c</fullName>
        <label>CapEFamily</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Claim_Run_Out_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Claim Run-Out Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Debit_Card_Services__c</fullName>
        <label>Debit Card Services</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Medical</fullName>
                </value>
                <value>
                    <fullName>Dental</fullName>
                </value>
                <value>
                    <fullName>Vision</fullName>
                </value>
                <value>
                    <fullName>Pharmacy</fullName>
                </value>
                <value>
                    <fullName>OTC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Employee_Funds_Rollover_Next_Plan_Year__c</fullName>
        <label>Employee Funds Rollover Next Plan Year</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>All (100%)</fullName>
                </value>
                <value>
                    <fullName>Percent</fullName>
                </value>
                <value>
                    <fullName>Cap Amount</fullName>
                </value>
                <value>
                    <fullName>Percent Up to Cap</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HRA1_Group_Suffix__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>HRA1: Group Suffix</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>HRA_Funds_Pro_Rate_on_Entry_Date__c</fullName>
        <label>HRA Funds Pro Rate on Entry Date</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Quarterly</fullName>
                </value>
                <value>
                    <fullName>Semi-Annually</fullName>
                </value>
                <value>
                    <fullName>Not Pro-Rated/Incentive Only HRA</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HRA_Funds_to_Employees_and_on_what_basis__c</fullName>
        <label>HRA Funds to Employees and on what basis</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No, Annually</fullName>
                </value>
                <value>
                    <fullName>No, Incentive Only HRA</fullName>
                </value>
                <value>
                    <fullName>Yes, Monthly</fullName>
                </value>
                <value>
                    <fullName>Yes, Quarterly</fullName>
                </value>
                <value>
                    <fullName>Yes, Semi-Annually</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HRA_Rollover__c</fullName>
        <label>HRA Rollover</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Activities_Incentives__c</fullName>
        <label>Health Activities Incentives</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Health_Incentive_Type__c</fullName>
        <label>Health Incentive Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Incentives Earned In Addition to the Employer HRA Allocation</fullName>
                </value>
                <value>
                    <fullName>Fully Insured Health Incentive Account Plus</fullName>
                </value>
                <value>
                    <fullName>Incentive HRA Only</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>If_Other_Please_Specify__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>If Other Please Specify</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Individual_Deductible_Amount__c</fullName>
        <label>Individual Deductible Amount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Member_Responsibility_by_Claim__c</fullName>
        <label>Member Responsibility by Claim</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>25%</fullName>
                </value>
                <value>
                    <fullName>50%</fullName>
                </value>
                <value>
                    <fullName>75%</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Minimum_Rollover_Amount__c</fullName>
        <label>Minimum Rollover Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Plan_End_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Plan_Start_Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Plan Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>QLI__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>QLI</label>
        <referenceTo>QuoteLineItem</referenceTo>
        <relationshipLabel>HRA Administrations</relationshipLabel>
        <relationshipName>HRA_Administrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rollover_Cap_Tiers__c</fullName>
        <label>Rollover Cap Tiers</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>2 Tier</fullName>
                </value>
                <value>
                    <fullName>3 Tier</fullName>
                </value>
                <value>
                    <fullName>4 Tier</fullName>
                </value>
                <value>
                    <fullName>5 Tier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Rollover_Different_Admin__c</fullName>
        <label>Rollover Different Admin</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Specialty__c</fullName>
        <label>Specialty</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Dental (Debit Card)</fullName>
                </value>
                <value>
                    <fullName>Vision (Debit Card)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type_of_HRA__c</fullName>
        <label>Type of HRA</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Member Pay (debit card) Only</fullName>
                </value>
                <value>
                    <fullName>Auto-Pay Provider Only</fullName>
                </value>
                <value>
                    <fullName>Provider Pay Medical with Optional Rx/Dental/Vision Debit Card</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UpFrontDedEA__c</fullName>
        <label>UpFrontDedEA</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UpFrontDedEEChildren__c</fullName>
        <label>UpFrontDedEEChildren</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UpFrontDedFamily__c</fullName>
        <label>UpFrontDedFamily</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UpfrontDedEChild__c</fullName>
        <label>UpfrontDedEChild</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UpfrontDedEE__c</fullName>
        <label>UpfrontDedEE</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>HRA Administration</label>
    <nameField>
        <displayFormat>HRAD-{0000}</displayFormat>
        <label>HRA Administration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HRA Administrations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>GroupNumber__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Group Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Group__c.IsActive__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Group__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>PRDCRM2-1707 - Raptors: Created as part of this user story</description>
        <label>Group</label>
        <referenceTo>Group__c</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Individual_Deductible_Amount__c</fullName>
        <label>Individual Deductible Amount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/CDHPServiceHandlerTest.cls
@isTest
public class CDHPServiceHandlerTest {
    static testMethod void testMethod1() {
        //System.debug('in testMethod1');
        List<RecordType> lstRcdType = [Select Id From RecordType Where Name =: 'Prospect' Limit 1];
        Account acc = new Account(Name = 'Test Account', RecordTypeId = lstRcdType[0].Id);
        Insert acc;
        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.id, StageName = 'Prospecting', CloseDate = system.today().toStartOfMonth());
        insert opp;
        Group__c grp=new Group__c(Account__c=acc.id,Account_Manager__c='Test');
        insert grp;
        Quote q=new quote(Name='Test', OpportunityId = opp.Id,GroupNumber__c=grp.Id);
        insert q; 
        
        CDHPService.CDHPFields cdhpSerFlds = new CDHPService.CDHPFields(); 
        CDHPService.StatusDetails StatusDetails1 =new CDHPService.StatusDetails();
        CDHPService.OpportunityDetails oppDetails1 = new CDHPService.OpportunityDetails();
        CDHPService.DocuSignDetails docsgn1 = new CDHPService.DocuSignDetails();
        CDHPService.GroupDetails grpDetails1 = new CDHPService.GroupDetails();
        
        
        StatusDetails1.Status = 'Test';
        StatusDetails1.StatusMessage = 'Test';
        StatusDetails1.QuoteId = q.id;
        //StatusDetails1.QuoteId = null;
        Test.startTest();
        oppDetails1.SFORGOpportunityId = opp.Id; 
        oppDetails1.OptyName = 'Test Opportunity';
        oppDetails1.OptyEffectiveDate = System.today().toStartOfWeek() ;
        oppDetails1.OptyRecordType = 'New Business';
        oppDetails1.StageName = 'Prospecting';
        
        docsgn1.dsfs_Envelope_Name = 'DSX-100002';
        docsgn1.dsfs_Envelope_Status = 'Test DocuSign';
        docsgn1.dsfs_Sent_Date_Time = datetime.now().addDays(-5);
        docsgn1.dsfs_Sent_Age = 5;
        
        grpDetails1.EmployerName = 'Test Employer';
        grpDetails1.EmployerIdCaseNumber = '12345' ;
        
        cdhpSerFlds.StatusDetails = StatusDetails1;
        cdhpSerFlds.oppDetails = oppDetails1;
        cdhpSerFlds.docSignDetails = docsgn1;
        cdhpSerFlds.grpDetails = grpDetails1;
        
        List<CDHPService.CDHPFields> cdhpSerFldsList = new List<CDHPService.CDHPFields>();
        CDHPService.CDHPFields cdhpSerFlds2 = new CDHPService.CDHPFields(); 
        CDHPService.StatusDetails StatusDetails2 =new CDHPService.StatusDetails();
        CDHPService.OpportunityDetails oppDetails2 = new CDHPService.OpportunityDetails();
        CDHPService.DocuSignDetails docsgn2 = new CDHPService.DocuSignDetails();
        CDHPService.GroupDetails grpDetails2 = new CDHPService.GroupDetails();      
        
        StatusDetails2.Status = 'Test';
        StatusDetails2.StatusMessage = 'Test';
        StatusDetails2.QuoteId =null;
        
        
        oppDetails2.SFORGOpportunityId = opp.Id; 
        oppDetails2.OptyName = 'Test Opportunity';
        oppDetails2.OptyEffectiveDate = System.today().toStartOfWeek() ;
        oppDetails2.OptyRecordType = 'New Business';
        oppDetails2.StageName = 'Prospecting';
        
        docsgn2.dsfs_Envelope_Name = 'DSX-100002';
        docsgn2.dsfs_Envelope_Status = 'Test DocuSign';
        docsgn2.dsfs_Sent_Date_Time = datetime.now().addDays(-5);
        docsgn2.dsfs_Sent_Age = 5;
        
        grpDetails2.EmployerName = 'Test Employer';
        grpDetails2.EmployerIdCaseNumber = '12345' ;
        
        cdhpSerFlds2.StatusDetails = StatusDetails2;
        cdhpSerFlds2.oppDetails = oppDetails2;
        cdhpSerFlds2.docSignDetails = docsgn2;
        cdhpSerFlds2.grpDetails = grpDetails2;
        cdhpSerFldsList.add(cdhpSerFlds);
        cdhpSerFldsList.add(cdhpSerFlds2);
        cdhpSerFlds = CDHPServiceHandler.ProcessRequest(cdhpSerFldsList);
        
        Test.stopTest(); 
    }
    static testMethod void testMethod2(){
        List<RecordType> lstRcdType = [Select Id From RecordType Where Name =: 'Prospect' Limit 1];
        Account acc = new Account(Name = 'Test Account', RecordTypeId = lstRcdType[0].Id);
        Insert acc;
        Opportunity opp = new Opportunity(Name = 'Test Opp', AccountId = acc.id, StageName = 'Prospecting', CloseDate = system.today().toStartOfMonth());
        insert opp;
        Contact con = new Contact(lastname = 'Test');
        insert con;
        
        Product2 prod = new Product2(Name = 'Laptop X200', 
                                     Family = 'Hardware');
        insert prod;
        
        Id pricebookId = Test.getStandardPricebookId();
        
        PricebookEntry standardPrice = new PricebookEntry(
            Pricebook2Id = pricebookId, Product2Id = prod.Id,
            UnitPrice = 10000, IsActive = true);
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2(Name='Custom Pricebook', isActive=true);
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry(
            Pricebook2Id = customPB.Id, Product2Id = prod.Id,
            UnitPrice = 12000, IsActive = true);
        insert customPrice;
        List<QuoteLineItem> qliListToInsert = new List<QuoteLineItem>();
        Quote q=new quote(Name='Test', OpportunityId = opp.Id, ContactId = con.id, Pricebook2Id = pricebookId);
        insert q;
        System.debug('method2 q.id--->>'+q.id);
        QuoteLineItem qli1 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli1);
        QuoteLineItem qli2 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli2);
        QuoteLineItem qli3 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli3);
        QuoteLineItem qli4 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli4);
        QuoteLineItem qli5 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli5);
        QuoteLineItem qli6 = new QuoteLineItem(QuoteId = q.Id, Product2Id = prod.id, Quantity =1, UnitPrice=2, PricebookEntryId= standardPrice.id);
        qliListToInsert.add(qli6);
        
        insert qliListToInsert;
        /* Required fields are missing: [PricebookEntryId, Quantity, UnitPrice, Product2Id]: [PricebookEntryId, Quantity, UnitPrice, Product2Id] */
        //33173 data
        List<HRA_Administration__c> lstHRA = new List<HRA_Administration__c>();
        HRA_Administration__c hra = new HRA_Administration__c(QLI__c=qliListToInsert[5].Id,Plan_Start_Date__c=System.today(),Plan_End_Date__c=System.today().addDays(3),HRA1_Group_Suffix__c='HRA',CapEE__c=12.00,CapEA__c=12.00,
                                                             CapEChild__c=12.00,CapEChildren__c=12.00,CapEFamily__c=12.00,AllocationEA__c=12.00,
                                                             Allocation_EChild__c=12.00,AllocationEChildren__c=12.00,AllocationEE__c=12.00,AllocationFamily__c=12.00,
                                                             Annual_Allocation_Tiers__c='2 Tier',Claim_Run_Out_Date__c=System.today().addDays(2),Debit_Card_Services__c='Medical;Dental',
                                                             Employee_Funds_Rollover_Next_Plan_Year__c='Percent',HRA_Funds_to_Employees_and_on_what_basis__c='No, Annually',
                                                             HRA_Funds_Pro_Rate_on_Entry_Date__c='Monthly',Health_Activities_Incentives__c='No',Health_Incentive_Type__c='Incentive HRA Only',Individual_Deductible_Amount__c=12.00,
                                                             If_Other_Please_Specify__c='123',Specialty__c='Dental (Debit Card);Vision (Debit Card)',Rollover_Cap_Tiers__c='2 Tier',Member_Responsibility_by_Claim__c='25%',Minimum_Rollover_Amount__c=12.00,Type_of_HRA__c='Auto-Pay Provider Only',HRA_Rollover__c='No',
                                                             Rollover_Different_Admin__c='Yes',UpfrontDedEE__c=12.00,UpFrontDedEA__c=12.00,UpfrontDedEChild__c=12.00,UpFrontDedEEChildren__c=12.00,
                                                             UpFrontDedFamily__c=12.00,Up_Front_Deductible_Tiers__c='2 Tier',HRA_Lites_Rollover__c='Yes');
        
        HRA_Administration__c hra1 = new HRA_Administration__c(QLI__c=qliListToInsert[1].Id,Plan_Start_Date__c=System.today(),Plan_End_Date__c=System.today().addDays(3),HRA1_Group_Suffix__c='HRA',CapEE__c=12.00,CapEA__c=12.00,
                                                             CapEChild__c=12.00,CapEChildren__c=12.00,CapEFamily__c=12.00,AllocationEA__c=12.00,
                                                             Allocation_EChild__c=12.00,AllocationEChildren__c=12.00,AllocationEE__c=12.00,AllocationFamily__c=12.00,
                                                             Annual_Allocation_Tiers__c='2 Tier',Claim_Run_Out_Date__c=System.today().addDays(2),Debit_Card_Services__c='Medical;Dental',
                                                             Employee_Funds_Rollover_Next_Plan_Year__c='Percent',HRA_Funds_to_Employees_and_on_what_basis__c='No, Annually',
                                                             HRA_Funds_Pro_Rate_on_Entry_Date__c='Monthly',Health_Activities_Incentives__c='No',Health_Incentive_Type__c='Incentive HRA Only',Individual_Deductible_Amount__c=12.00,
                                                             Rollover_Cap_Tiers__c='2 Tier',Member_Responsibility_by_Claim__c='25%',Minimum_Rollover_Amount__c=12.00,Type_of_HRA__c='Auto-Pay Provider Only',HRA_Rollover__c='No',
                                                             Covered_Services__c='Auto Pay Medical; In Network Medical Deductible',HRA_Upfront_Deductible__c='Yes',Medical__c='Provider Pay;Member Pay (Debit Card)');
   
        
        lstHRA.add(hra);
        lstHRA.add(hra1);
        insert lstHRA;
        //
        CDHPService.CDHPFields cdhpSerFlds = new CDHPService.CDHPFields();
        CDHPService.StatusDetails StatusDetails1 =new CDHPService.StatusDetails();
        StatusDetails1.Status = 'Alegeus Completed';
        StatusDetails1.StatusMessage = 'Test';
        StatusDetails1.QuoteId = q.id;
        cdhpSerFlds.StatusDetails = StatusDetails1;
        
        
        /*
public CDHParDetails CDHPar{ get; set; }
public List<CDHPCommuterAccount> CDHPCommuterList{ get; set; }
public List<CDHPHSAAccount> CDHPHSAList { get; set; }
public List<CDHPFSAAccount> CDHPFSAList{ get; set; }
public List<CDHPHRARepeatingAccount> CDHPHRAList{ get; set; }
*/
        List<CDHPService.CDHPHRARepeatingAccount> CDHPHraList1 = new List<CDHPService.CDHPHRARepeatingAccount>();
        CDHPService.CDHPHRARepeatingAccount CDHPHra = new CDHPService.CDHPHRARepeatingAccount();
        CDHPHra.SF_Quote_Item_Id = qli6.id;
        CDHPHra.HRA_Embedded_Ded = true;
        CDHPHra.HRA_Plan_Start_Date = date.newInstance(2098, 12, 1);
        CDHPHra.HRA_Plan_End_Date = date.newInstance(2099, 12, 1);
        CDHPHra.HRA_Debit_Card_Dental_Services = true;
        CDHPHra.HRA_Debit_Card_Medical_Services = true;
        CDHPHra.HRA_Debit_Card_OTC_Services = true;
        CDHPHra.HRA_Debit_Card_Rx_Services = true;
        CDHPHra.HRA_Debit_Card_Vision_Services = true;
        CDHPHra.HRA_Employee_Funds_Rollover_Amounts = '132';
        CDHPHra.HRA_Health_Activities = 'Yes';
        CDHPHra.HRA_Prov_Pay_Med_w_Opt_Rx_Den_Vis_Deb_Cd = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_Dental_Option = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_Vision_Option = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_INN_Med_Coins = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_INN_Med_Copay = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_INN_Med_Ded = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_ONN_Med_Coins = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_ONN_Med_Copay = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_ONN_Med_Ded = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_Rx_Option = true;
        CDHPHra.HRA_ProvPay_Opt_DebCd_Medical = true;
        CDHPHra.Member_Pay_HRA_with_Debit_Card = true;
        CDHPHra.HRA_Terminated_Employees_Other_Value = '21';
        CDHPHra.Provider_Pay_Split_HRA = true;
		CDHPHra.HRA_Rollover_Offer = 'Yes';
        CDHPHraList1.add(CDHPHra);
        cdhpSerFlds.CDHPHRAList=CDHPHraList1;
        CDHPService.CDHPFSAAccount CDHPFSA = new CDHPService.CDHPFSAAccount();
        CDHPFSA.SF_Quote_Item_Id = qli3.id;
        CDHPFSA.FSA_Section_213_d_Plan = true;
        CDHPFSA.Limited_Purpose_FSA_Plan = true;
        CDHPFSA.Dependent_Care_FSA_Plan = true;
        List<CDHPService.CDHPFSAAccount> CDHPfsalst = new List<CDHPService.CDHPFSAAccount>();
        
        CDHPService.CDHPFSAAccount CDHPFSA1 = new CDHPService.CDHPFSAAccount();
        CDHPFSA1.SF_Quote_Item_Id = qli4.id;
        CDHPFSA1.FSA_Section_213_d_Plan = false;
        CDHPFSA1.Limited_Purpose_FSA_Plan = true;
        CDHPFSA1.Dependent_Care_FSA_Plan = true;    
        //List<CDHPService.CDHPFSAAccount> CDHPfsalst = new List<CDHPService.CDHPFSAAccount>();
        
        CDHPService.CDHPFSAAccount CDHPFSA2 = new CDHPService.CDHPFSAAccount();
        CDHPFSA2.SF_Quote_Item_Id = qli5.id;
        CDHPFSA2.FSA_Section_213_d_Plan = false;
        CDHPFSA2.Limited_Purpose_FSA_Plan = false;
        CDHPFSA2.Dependent_Care_FSA_Plan = true;    
        //List<CDHPService.CDHPFSAAccount> CDHPfsalst = new List<CDHPService.CDHPFSAAccount>();
        
        
        CDHPfsalst.add(CDHPFSA);
        CDHPfsalst.add(CDHPFSA1);
        CDHPfsalst.add(CDHPFSA2);
        cdhpSerFlds.CDHPFSAList = CDHPfsalst;
        
            
        CDHPService.CDHParDetails CDHPar1 = new CDHPService.CDHParDetails();
        CDHPar1.EmployerName = 'Test';
        CDHPar1.TaxId = 'Te123';
        CDHPar1.Employer_Contact_Name_1='M D K';
        CDHPar1.Member_Pay_HRA_with_Debit_Card = true;
        CDHPar1.Provider_Pay_Split_HRA = true;
        CDHPar1.Effective_Date = date.newInstance(2099, 12, 1);
        CDHPar1.HRA_Provider_Pay = true;
        CDHPar1.Prov_Pay_HRA_w_Upfront_Ded_and_Auto_Pay = true;
        CDHPar1.HRA_Rollover = true;
        
        //cdhpSerFlds.CDHPar= CDHPar1;
         List<CDHPService.CDHParDetails> lstpar1 = new List<CDHPService.CDHParDetails>();
        lstpar1.add(CDHPar1);
        cdhpSerFlds.CDHPar= CDHPar1;
        
        
        CDHPService.CDHPCommuterAccount comm1 = new CDHPService.CDHPCommuterAccount();
        comm1.Transit_Plan_Option = true;
        comm1.Parking_Plan_Option = true;
        comm1.SF_Quote_Item_Id = qli1.id;
        List<CDHPService.CDHPCommuterAccount> commList = new List<CDHPService.CDHPCommuterAccount>();
        commList.add(comm1);
        cdhpSerFlds.CDHPCommuterList = commList;
        
        
        CDHPService.CDHPHSAAccount hsa = new CDHPService.CDHPHSAAccount();
        hsa.HSA_Custodian='Test';
        hsa.SF_Quote_Item_Id = qli2.Id;
        
        List<CDHPService.CDHPHSAAccount> hsaList= new List<CDHPService.CDHPHSAAccount>();
        hsaList.add(hsa);
        cdhpSerFlds.CDHPHSAList = hsaList;
        
        /*
        testDataFactoryCDHP.createAccount();
        testDataFactoryCDHP.createOpp();
        testDataFactoryCDHP.createQuote();
        testDataFactoryCDHP.createProducts();
        testDataFactoryCDHP.createQuoteLineItem();
        StatusDetails1.QuoteId = testDataFactoryCDHP.lstQLItem[0].id;
        cdhpSerFlds2.StatusDetails = StatusDetails1;       
        testDataFactoryCDHP.createHRA();
        */
        //
        CDHPService.OpportunityDetails oppDetails1 = new CDHPService.OpportunityDetails();
        oppDetails1.SFORGOpportunityId = opp.Id; 
        oppDetails1.OptyName = 'Test Opportunity';
        oppDetails1.OptyEffectiveDate = System.today().toStartOfWeek() ;
        oppDetails1.OptyRecordType = 'New Business';
        oppDetails1.StageName = 'Prospecting';
        cdhpSerFlds.oppDetails = oppDetails1;
        
        
        List<CDHPService.CDHPFields> cdhpSerFldsList = new List<CDHPService.CDHPFields>();
        cdhpSerFldsList.add(cdhpSerFlds);
        //cdhpSerFldsList.add(cdhpSerFlds2);
        
        CDHPServiceHandler.BackSynch(cdhpSerFldsList);
        
        
    }
}