objects/Group__c.object
<CustomObject>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Line of Business (not the total Opportunity)</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Group</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Group Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Groups</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Members__c</fullName>
        <description>These are temporal fields added for request 1260. These values will be used when creating a standalone IGAP opportunity and directly connect to the AddProduct OS.</description>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>AdditionalDetails__c</fullName>
        <description>Please describe any additional details, background or relevant history</description>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Please describe any additional details, background or relevant history</inlineHelpText>
        <label>Additional Details</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>AlternativesDiscussedWithClient__c</fullName>
        <label>Alternatives discussed with client</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Dont Know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>BackgroundFurtherExplanation__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Plz provide addt’l comments regarding client market relevance, background, relationship w/information helpful in determining if good fit w/AHG. Plz explain any deviations from standard indicating client is participating w/Exchange.</inlineHelpText>
        <label>Background/Further Explanation</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>CompetitorStatus__c</fullName>
        <description>JT(20140306) - picklist to note type of competitor</description>
        <inlineHelpText>Select the current status of this Competitor. If it is the Current Carrier (Incumbent), use the Incumbent selections otherwise use the Not Incumbent selections.</inlineHelpText>
        <label>Competitor Status1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unknown</fullName>
                </value>
                <value>
                    <fullName>Incumbent</fullName>
                </value>
                <value>
                    <fullName>Not Incumbent</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CustomSolutionBenefitToOtherAccts__c</fullName>
        <inlineHelpText>Would custom solution benefit other ANA accounts?</inlineHelpText>
        <label>Custom solution benefit to other accts?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DoesAnthemcurrentlyworkwithvendor__c</fullName>
        <inlineHelpText>Does Anthem currently work with this vendor?</inlineHelpText>
        <label>Does Anthem currently work with vendor?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EstimatedCostIfRequestApproved__c</fullName>
        <inlineHelpText>Estimated dollar cost to Anthem if request approved (If known)</inlineHelpText>
        <label>Estimated Cost If Request Approved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Funding__c</fullName>
        <description>(For West, Non-Pooled EOC field. iAve: MED_FUND_TYPE, FUND_TYP)</description>
        <label>Funding</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>ProductStage__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ASO</fullName>
                </value>
                <value>
                    <fullName>FI</fullName>
                </value>
                <value>
                    <fullName>N/A</fullName>
                </value>
                <value>
                    <fullName>ASO/FI</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IntegrationWith3rdPartyVendor__c</fullName>
        <inlineHelpText>Does request include integrating with a third party Vendor?</inlineHelpText>
        <label>Integration with 3rd party vendor?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MarketsAffectedByRequest__c</fullName>
        <inlineHelpText>check as many as you need to</inlineHelpText>
        <label>Markets affected by request</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>National</fullName>
                </value>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MedicalManagementPlatform__c</fullName>
        <label>Medical Management Platform</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>ECC (exception)</fullName>
                </value>
                <value>
                    <fullName>HRS</fullName>
                </value>
                <value>
                    <fullName>HRS/WMDS</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Members__c</fullName>
        <inlineHelpText>Enter the number of Members for this particular Product Line (not the total Opportunity).</inlineHelpText>
        <label>Members</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MembershipSplitBetweenAHGandNonAHG__c</fullName>
        <description>BW 2015 
New field which is required to submit an Opportunity for AHG approval</description>
        <inlineHelpText>Please explain split population in Background/Further Explanation field. HMO members cannot be supported.</inlineHelpText>
        <label>Membership split between AHG and non-AHG</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes (Please Explain)</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RFPorCriticalMeetingdaterequired__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>RFP or Critical Meeting date required</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RequestTypeComment__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Request Type Comment</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RequestType__c</fullName>
        <label>Request Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Narrow Network</fullName>
                </value>
                <value>
                    <fullName>High Performing Network</fullName>
                </value>
                <value>
                    <fullName>Custom ACO</fullName>
                </value>
                <value>
                    <fullName>Other (Please describe)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequiresITWorkToImplement__c</fullName>
        <inlineHelpText>Will request require IT work to implement?</inlineHelpText>
        <label>Requires IT work to implement?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SolutionRequiresLocalInvolvement__c</fullName>
        <inlineHelpText>Will this solution require local contracting team involvement?</inlineHelpText>
        <label>Solution requires local involvement?</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t know</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/QuoteLineItemApproval__c.object
<CustomObject>
    <fields>
        <fullName>BackgroundFurtherExplanation__c</fullName>
        <formula>QuoteLineItem__r.BackgroundFurtherExplanation__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Background_Further_Explanation</label>
        <type>Text</type>
    </fields>
    <label>Quote Line Item Approval</label>
    <nameField>
        <displayFormat>QLIA-{00000}</displayFormat>
        <label>Quote Line Item Approval Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Line Item Approval</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ANA_VFC02_CustomNetworksApprlReq_Test.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
/*******************************************************************************************
@class Name  : ANA_VFC02_CustomNetworksApprlReq_Test
@created By  : IDC Offshore
@description : This test class is for ANA_VFC02_CustomNetworksApprlReq
********************************************************************************************/
@isTest
private class ANA_VFC02_CustomNetworksApprlReq_Test {
    private static final string CLAIMSYSTEM= 'CS90';
    private static final string NATIONALAMPROFILE='National Sales';
    

/*******************************************************************************************
@ method Name  : custNetworkApprovalCall
@ description : This method is used to cretae QLI object records from Util class
********************************************************************************************/
    static testMethod void custNetworkApprovalCall() {
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1];
        User user1=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        system.runAs(user1){
            // TO DO: implement unit test
            QuoteLineItem qli= createData();
            qli.RequestType__c = 'Narrow Network';
            qli.RFPorCriticalMeetingdaterequired__c = system.today();
            qli.IntegrationWith3rdPartyVendor__c ='Yes';
            qli.MarketsAffectedByRequest__c ='AL';
            qli.CompetitorStatus__c = 'Incumbent';
            qli.DoesAnthemcurrentlyworkwithvendor__c = 'Yes';
            qli.CustomSolutionBenefitToOtherAccts__c = 'Yes';
            qli.SolutionRequiresLocalInvolvement__c = 'Yes';
            qli.BackgroundFurtherExplanation__c = 'test';
            qli.RequiresITWorkToImplement__c ='Yes';
            qli.AlternativesDiscussedWithClient__c='Yes';
            qli.Funding__c='ASO';           
            qli.MedicalManagementPlatform__c='HRS/WMDS';
            qli.MembershipSplitBetweenAHGandNonAHG__c='No';
            qli.Members__c=52;
            qli.AdditionalDetails__c = 'Test'; //New Line
            qli.EstimatedCostIfRequestApproved__c = 100; //New Line
            qli.RequestTypeComment__c = 'Test Request Comment'; //New Line
            qli.ClinicalDeliveryModel__c='IHM'; 
            qli.ServiceTier__c='AHG';
            qli.RecordType__c='AIM';            
            Database.insert(qli);
            QuoteLineItemApproval__c qlia=ANA_UTIL01_TestMethods.createQuoteLineItemApproval(QLI.id,1)[0];
            
            Database.insert(qlia);       
            ANA_VFC02_CustomNetworksApprovalRequest.quotelineitembean cbean=beanassignment();
            ANA_VFC02_CustomNetworksApprovalRequest cn_AppRequest= new ANA_VFC02_CustomNetworksApprovalRequest();
            cn_AppRequest.qlitemappNewId = qlia.id;
            cn_AppRequest.qlitemapp = qlia.Id;
            cn_AppRequest.qlibean = cbean;
            cn_AppRequest.getBeanAssignment();
            system.assertEquals(cbean.Vendorname,cbean.DurationofGuarantee,'Success');      
        }  
    }

/*******************************************************************************************
@ method Name  : beanassignment
@ description : class bean assignmen
********************************************************************************************/
    static ANA_VFC02_CustomNetworksApprovalRequest.quotelineitembean beanassignment(){
        
        ANA_VFC02_CustomNetworksApprovalRequest.quotelineitembean cbean= new ANA_VFC02_CustomNetworksApprovalRequest.quotelineitembean();    
        cbean.ANASalesorAccountrep = 'test';
        cbean.GROUPNAME = 'test';
        cbean.RVP = 'test';
        cbean.RequestType = 'test';
        cbean.RequestTypeComment = 'test';
        cbean.RFPORCriticalMeetingdaterequired = system.today();
        cbean.DoesrequestincludeintegratingwiththirdpartyVendor = 'test';
        cbean.Marketsaffectedbyrequest = 'test';
        cbean.NewSalesorCurrentAccount = 'test';
        cbean.NumberofEmployees = 'test';
        cbean.NumberofMembers = 'test';
        cbean.HQState = 'test';
        cbean.Consultant = 'test';
        cbean.CompetitorStatus = 'test';
        cbean.ClaimSystem = 'test';
        cbean.RenewalofBaseExpenseCovered = 'test';
        cbean.RenewalofTotalExpenseCovered = 'test';
        cbean.DurationofGuarantee = 'test';
        cbean.CurrentYearofGuarantee = 'test';
        cbean.WillrequestrequireITWImpl = 'test';
        cbean.Estimateddlrcost2AnthemreqApp = 'test';
        cbean.Alternativesdiscussedwithclient = 'test';
        cbean.Vendorname = 'test';
        cbean.DoesAnthemcurrentlyworkwiththisvendor = 'test';
        cbean.WouldcustomslBenfOthANAaccounts = 'test';
        cbean.Willthissolreqlocalcontrteaminv = 'test';
        cbean.Plzdescribeanyadddetbackghistory = 'test';
        return cbean;
    }
    
/*******************************************************************************************
@ method Name  : createData
@ description : This method is used to perform DML operations on object records
********************************************************************************************/
    static QuoteLineItem createData()
    {
        Account acc=ANA_UTIL01_TestMethods.createAccount(false);
        acc.HQ_State__c = 'CA';
        acc.Eligible_Employees__c = 100; //New Line
        acc.Total_Employees__c = 100; //New Line
        Database.insert(acc);
        Opportunity oppty=ANA_UTIL01_TestMethods.createOpportunity(false,acc.id);
        oppty.closedate = Date.newInstance(system.today().year()+1, 1, 1 );//system.today().adddays(10);
        Database.insert(oppty);
        Group__c grp=ANA_UTIL01_TestMethods.createGroup(acc.id,false);
        grp.ClaimSystem__c=CLAIMSYSTEM;
        Database.insert(grp);
        Quote qte=ANA_UTIL01_TestMethods.createQuote(false,oppty.Id);
        qte.GroupNumber__c=grp.id;
        Database.insert(qte);
        Product2 prod=ANA_UTIL01_TestMethods.createProduct(false);
        Database.insert(prod);
        PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false,prod.id);
        Database.insert(pbe);
        QuoteLineItem qli= ANA_UTIL01_TestMethods.createQuoteLineItem(false,qte.Id, pbe.id);
        return qli;
    }
}