objects/Implementation_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>Implementation_Record_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Record ID</label>
        <referenceTo>Order</referenceTo>
        <relationshipLabel>Implementations Tracking</relationshipLabel>
        <relationshipName>Implementations_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <formula>&quot;TRACK&quot; + &quot; &quot;  +   Implementation_Record_ID__r.OrderNumber</formula>
        <label>Implementation Tracking ID</label>
        <type>Text</type>
    </fields>
    <label>Implementation Tracking</label>
    <nameField>
        <displayFormat>TRACK-{000000}</displayFormat>
        <label>Implementation Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Implementations Tracking</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Underwriting__c.object
<CustomObject>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT(Implementation_Tracking_ID__r.Implementation_Record_ID__r.Account.Anthem_Entity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Implementation_Tracking_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Implementation Tracking ID</label>
        <referenceTo>Implementation_Tracking__c</referenceTo>
        <relationshipLabel>Underwriting</relationshipLabel>
        <relationshipName>Underwriting</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>01A Assign To UW</fullName>
                </value>
                <value>
                    <fullName>01 Not Started</fullName>
                    <default>true</default>
                    <label>01 Not Started</label>
                </value>
                <value>
                    <fullName>02 Work In Progress</fullName>
                </value>
                <value>
                    <fullName>03 Pending Correction</fullName>
                </value>
                <value>
                    <fullName>03 Pending Correction Returned</fullName>
                </value>
                <value>
                    <fullName>04 Approved</fullName>
                </value>
                <value>
                    <fullName>05 Declined</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Underwriting</label>
    <nameField>
        <displayFormat>UW-{000000}</displayFormat>
        <label>Underwriting Tracking ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Underwriting</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LG_OrderActions.cls
/**
@author Ravideep Singh (Vikings)
@createDate 02/04/2020
@description This is action class for implementation case(order).
@Modified : 1) Ravideep(Vikings) -02/04/2020 - PRDCRM-49125 - Prevent ICR status to change to withdrawn if underwriting record stage is approved 
*/
public with sharing class LG_OrderActions {  

public String local = staticVariableClass.Entity;

/*******************************************************************************************************
* @description Errors out ICR record if related Underwriting record has status 'Approved'-PRDCRM-49125 - Ravideep(Vikings)
* @param Accepts list of Order Ids to be processed and trigger.new
* @return Doesn't return anything
*/

    public void showErrorICRUpdate(Set<Id> orderIds,List<Order> newOrderList){
        Set<Id> errorOrderIds = new Set<Id>();
        List<Underwriting__c> underwritingList = new List<Underwriting__c>();
        
        /*
        getting all underwriting records that are grandchildren of ICR records being inserted
        */
        underwritingList = [SELECT id,Stage__c,Implementation_Tracking_ID__c,Implementation_Tracking_ID__r.Implementation_Record_ID__c FROM Underwriting__c WHERE Implementation_Tracking_ID__r.Implementation_Record_ID__c IN: orderIds and Implementation_Tracking_ID__r.Implementation_Record_ID__r.Account.Anthem_Entity__c =: local];
        
        if(!underwritingList.isEmpty()){
            system.debug('underwritingList-> ' + underwritingList);
            for(Underwriting__c uwr : underwritingList){
                if(uwr.stage__c != null && uwr.stage__c == staticVariableClass.APPROVED){
                    errorOrderIds.add(uwr.Implementation_Tracking_ID__r.Implementation_Record_ID__c);
                }
                
            }
        }
        /*
            setting error message for all ICR records that are associated to a UW record with stgage approved
        */
        
        if(!errorOrderIds.isEmpty()){
            
            system.debug('errorOrderIds-> ' + errorOrderIds);
            for(order thisOrder : newOrderList ){
                if(errorOrderIds.contains(thisOrder.id)){
                    thisOrder.addError(staticVariableClass.UNDERWRITING_ERROR);
                }
            }
        }
    }
}