objects/OE_Order__c.object
<CustomObject>
    <description>BW - June 2016 for Open Enrollment engagement</description>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OE Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Fulfillment__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Location</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tracking_Number__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tracking Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Order Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <scale>15</scale>
        <type>Location</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UPSUpdateStatusBatch_Test.cls
@isTest
private class UPSUpdateStatusBatch_Test {
    @istest static void testBatch() {
        Account a = UPS_TestDataFactory.createAccount(true);
        Open_Enrollment_Meetings__c oem = UPS_TestDataFactory.createOEMeetings(1, a, true)[0];
        SFDC_Volunteer_Event__c oe = UPS_TestDataFactory.createOpenEnrollments(1, oem, true)[0];
        OE_Order__c oeOrder = UPS_TestDataFactory.createOrders(1, oe, true)[0];
        List<Order_Fulfillment__c> ofList = UPS_TestDataFactory.createOrderFulfillments(100, oeOrder, false);
        for(Order_Fulfillment__c ofx : ofList) {
            ofx.Location__c = Label.UPS_Status_Update_Pending;
            ofx.Tracking_Number__c = '1Z6F814F0323777546';
        }
        insert ofList;

        MultiRequestMock multiRequestMock = new MultiRequestMock();
        multiRequestMock.addRequestMock(UPS_Constants.UPS_ENDPOINT_URL, new UPSMockResponseGenerator.UPSSinglePackageSuccessResponse());
        multiRequestMock.addRequestMock(TravelResponseService.BING_LOCATION_ENDPOINT, TravelResponseServiceTest.getDefaultBingGeocodeMock());
        Test.setMock(HttpCalloutMock.class, multiRequestMock);
        Test.startTest();
        Database.executeBatch(new UPSUpdateStatusBatch(), 100);
        Test.stopTest();
        
        List<Order_Fulfillment__c> updatedOf = [SELECT Id from Order_Fulfillment__c WHERE Id in :ofList AND Status__c = 'DELIVERED'];
        System.assertEquals(100, updatedOf.size());
    }
    
     @isTest static void testSchedBatch() {
        Test.startTest();
            UPSUpdateStatusBatch upsBatch = new UPSUpdateStatusBatch();
            Datetime dt = Datetime.now().addMinutes(1);
            String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
            System.schedule('test_schedule_run', CRON_EXP, upsBatch);   
        Test.stopTest();
    }
}