objects/OE_Order__c.object
<CustomObject>
    <description>BW - June 2016 for Open Enrollment engagement</description>
    <fields>
        <fullName>Open_Enrollment__c</fullName>
        <description>BW - June 2016 for Open Enrollment engagement</description>
        <label>Open Enrollment</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>Orders</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Order</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>OE Order #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the account for which the OE meetings will be recorded.</description>
        <inlineHelpText>Select an account if this set of meetings is related to an account in Salesforce.com.</inlineHelpText>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>The Plan Type for the meetings group.</description>
        <inlineHelpText>Select the Product offering for this group of meetings.</inlineHelpText>
        <label>Plan Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP- HIA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP - HRA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP -HSA</fullName>
                    <label>MED     CDHP - HSA</label>
                </value>
                <value>
                    <fullName>MED     POS</fullName>
                </value>
                <value>
                    <fullName>MED     PPO</fullName>
                </value>
                <value>
                    <fullName>MED     EPO</fullName>
                </value>
                <value>
                    <fullName>MED     HMO</fullName>
                </value>
                <value>
                    <fullName>MED     JAA</fullName>
                </value>
                <value>
                    <fullName>MED     LiveHealth Online</fullName>
                </value>
                <value>
                    <fullName>MED     Engage</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice EQ</fullName>
                </value>
                <value>
                    <fullName>CA      First Impressions</fullName>
                </value>
                <value>
                    <fullName>CA      SIMNSA</fullName>
                </value>
                <value>
                    <fullName>CA      Transition Assistance</fullName>
                </value>
                <value>
                    <fullName>CA      Vivity</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD-HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD- PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   PDP</fullName>
                </value>
                <value>
                    <fullName>HW – Group Retiree - Silver Sneakers</fullName>
                </value>
                <value>
                    <fullName>HW      24/7 Nurseline</fullName>
                </value>
                <value>
                    <fullName>HW      AIM</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Rewards</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Mobile Health</fullName>
                </value>
                <value>
                    <fullName>HW      Complex Care</fullName>
                </value>
                <value>
                    <fullName>HW      ConditionCare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Order_Fulfillment__c.object
<CustomObject>
    <fields>
        <fullName>Carrier__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Carrier</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <label>Order</label>
        <referenceTo>OE_Order__c</referenceTo>
        <relationshipLabel>Order Fulfillments</relationshipLabel>
        <relationshipName>Order_Fulfillments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Order Fulfillment</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Order Fulfillment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Fulfillments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <label>Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Fair</fullName>
                </value>
                <value>
                    <fullName>Conference Call</fullName>
                </value>
                <value>
                    <fullName>Health Fair</fullName>
                </value>
                <value>
                    <fullName>PowerPoint w/ VO  {PP with VO}</fullName>
                    <label>PowerPoint with Voiceover</label>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Q &amp; A</fullName>
                </value>
                <value>
                    <fullName>Supplies Only</fullName>
                </value>
                <value>
                    <fullName>Virtual (Webinar)</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OE_Grouping__c</fullName>
        <description>The parent link.</description>
        <inlineHelpText>This link will take you back to the Group Meeting record.</inlineHelpText>
        <label>Meetings Grouping</label>
        <referenceTo>Open_Enrollment_Meetings__c</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Open_Enrollment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Open Enrollment</label>
        <referenceTo>Open_Enrollment_Meetings__c</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Tax_ID__c.object
<CustomObject>
    <description>KF(20140507) table added to allow for more than one TaxID per account, per instruction from CIP and National SME&apos;s</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Tax IDs</relationshipLabel>
        <relationshipName>Tax_IDs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Tax_ID__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Tax ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Tax ID</label>
    <nameField>
        <displayFormat>TID-{000000}</displayFormat>
        <label>Tax ID Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tax IDs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UPS_TestDataFactory.cls
@isTest
public class UPS_TestDataFactory {
    
    public static Account createAccount(boolean isInsert) {
        Account acc= new Account(
        Name = 'TestAccount',
        TAX_ID__c = '12345',
        Phone = '(123) 456-7890' );
        
        if(isInsert) insert acc;
        return acc;
    }
    
    public static List<Open_Enrollment_Meetings__c> createOEMeetings (Integer num, Account acct, boolean isInsert) {
        List<Open_Enrollment_Meetings__c> meetingList = new List<Open_Enrollment_Meetings__c>();
        for(Integer i = 0; i < num; i++) {
            Open_Enrollment_Meetings__c oem = new Open_Enrollment_Meetings__c(
                Name = 'Test Open Enrollment Meeting ' + i,
                Plan_Type__c = 'ANC - AD&D',
                Account__c = acct.Id
            );
            meetingList.add(oem);
        }
        
        if(isInsert) {
            insert meetingList;
        }
        return meetingList;
    }    
    
    public static List<SFDC_Volunteer_Event__c> createOpenEnrollments(Integer num, Open_Enrollment_Meetings__c oe_meeting, boolean isInsert) {
        List<SFDC_Volunteer_Event__c> oeList = new List<SFDC_Volunteer_Event__c>();
        for(Integer i = 0; i < num; i++) {
            SFDC_Volunteer_Event__c oe = new SFDC_Volunteer_Event__c(
                Name = 'Test Open Enrollment ' + i,
                OE_Grouping__c = oe_meeting.Id,Date__c=System.Today(),Meeting_Type__c='Benefit Fair',Recruitment_of_Facilitator_Needed__c='Yes'
            );
            oeList.add(oe);
        }
        
        if(isInsert) {
            insert oeList;
        }
        return oeList;
    }
    
    public static List<OE_Order__c> createOrders(Integer num, SFDC_Volunteer_Event__c oe, boolean isInsert) {
        List<OE_Order__c> orderList = new List<OE_Order__c>();
        for(Integer i = 0; i < num; i++) {
            OE_Order__c oeOrder = new OE_Order__c(
                Open_Enrollment__c = oe.Id
            );
            orderList.add(oeOrder);
        }
        
        if(isInsert) {
            insert orderList;
        }
        return orderList;
    }
    
    public static List<Order_Fulfillment__c> createOrderFulfillments(Integer num, OE_Order__c ord, boolean isInsert) {
        List<Order_Fulfillment__c> ofList = new List<Order_Fulfillment__c>();
        for(Integer i = 0; i < num; i++) {
            Order_Fulfillment__c ordFul = new Order_Fulfillment__c(
                Carrier__c = 'UPS',
                Order__c = ord.Id
            );
            ofList.add(ordFul);
        }
        
        if(isInsert) {
            insert ofList;
        }
        return ofList;
    }
}