objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the account for which the OE meetings will be recorded.</description>
        <inlineHelpText>Select an account if this set of meetings is related to an account in Salesforce.com.</inlineHelpText>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Client_Arrangement__c</fullName>
        <description>Multi-select, visible to National, Local Sales and National Open Enrollment.</description>
        <label>Client Arrangement</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New Business</fullName>
                </value>
                <value>
                    <fullName>Renewal - Growth Opportunity</fullName>
                </value>
                <value>
                    <fullName>Renewal – Full Replacement</fullName>
                </value>
                <value>
                    <fullName>Renewal – Partial Replacement</fullName>
                </value>
                <value>
                    <fullName>Renewal – Minimal Changes</fullName>
                </value>
                <value>
                    <fullName>Renewal – Additional Plan Offerings</fullName>
                </value>
                <value>
                    <fullName>Renewal – No Changes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Client_Drivers_Issues_Risks__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <inlineHelpText>Use this space to list out any notable Client Drivers, Issues / Risks, Talking Points, and Division Names.</inlineHelpText>
        <label>Client Drivers, Issues / Risks</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cost_Center_Local__c</fullName>
        <description>Local Users Access Only</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Cost Center - Local</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cost_Center_National__c</fullName>
        <description>National Users Access Only</description>
        <label>Cost Center - National</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>National - Northeast - 5360500300</fullName>
                </value>
                <value>
                    <fullName>National - Central - 5100168000</fullName>
                </value>
                <value>
                    <fullName>National - Southeast - 5100167100</fullName>
                </value>
                <value>
                    <fullName>National - West - 5100167800</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dress_Code_for_Event__c</fullName>
        <label>Dress Code for Event</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Business Casual</fullName>
                </value>
                <value>
                    <fullName>Business Formal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Member_Customer_Service_Telephone__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Member Customer Service Telephone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Performance_Guarantees__c</fullName>
        <label>Performance Guarantees</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>The Plan Type for the meetings group.</description>
        <inlineHelpText>Select the Product offering for this group of meetings.</inlineHelpText>
        <label>Plan Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP- HIA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP - HRA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP -HSA</fullName>
                    <label>MED     CDHP - HSA</label>
                </value>
                <value>
                    <fullName>MED     POS</fullName>
                </value>
                <value>
                    <fullName>MED     PPO</fullName>
                </value>
                <value>
                    <fullName>MED     EPO</fullName>
                </value>
                <value>
                    <fullName>MED     HMO</fullName>
                </value>
                <value>
                    <fullName>MED     JAA</fullName>
                </value>
                <value>
                    <fullName>MED     LiveHealth Online</fullName>
                </value>
                <value>
                    <fullName>MED     Engage</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice EQ</fullName>
                </value>
                <value>
                    <fullName>CA      First Impressions</fullName>
                </value>
                <value>
                    <fullName>CA      SIMNSA</fullName>
                </value>
                <value>
                    <fullName>CA      Transition Assistance</fullName>
                </value>
                <value>
                    <fullName>CA      Vivity</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD-HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD- PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   PDP</fullName>
                </value>
                <value>
                    <fullName>HW – Group Retiree - Silver Sneakers</fullName>
                </value>
                <value>
                    <fullName>HW      24/7 Nurseline</fullName>
                </value>
                <value>
                    <fullName>HW      AIM</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Rewards</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Mobile Health</fullName>
                </value>
                <value>
                    <fullName>HW      Complex Care</fullName>
                </value>
                <value>
                    <fullName>HW      ConditionCare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Request_is_from__c</fullName>
        <label>Request is from</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Commercial Medical</fullName>
                    <default>true</default>
                    <label>Commercial Medical</label>
                </value>
                <value>
                    <fullName>Group Retiree Solutions</fullName>
                </value>
                <value>
                    <fullName>Voluntary Specialty</fullName>
                </value>
                <value>
                    <fullName>Specialty Only</fullName>
                </value>
                <value>
                    <fullName>Group Retiree Solution</fullName>
                    <isActive>false</isActive>
                    <label>Group Retiree Solution</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Sole_Carrier_or_Multi_Carriers__c</fullName>
        <inlineHelpText>If there are other Vendors please list here:</inlineHelpText>
        <label>Carrier Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sole Carrier</fullName>
                </value>
                <value>
                    <fullName>Multi Carrier</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Request_is_From__c</fullName>
        <formula>IF(INCLUDES( OE_Grouping__r.Request_is_from__c, &quot;Commercial Medical&quot;), &quot;Commercial Medical&quot;, NULL) + BR() + 
IF(INCLUDES( OE_Grouping__r.Request_is_from__c, &quot;Group Retiree Solutions&quot;), &quot;Group Retiree Solutions&quot;, NULL) + BR() + 
IF(INCLUDES( OE_Grouping__r.Request_is_from__c, &quot;Voluntary Specialty&quot;), &quot;Voluntary Specialty&quot;, NULL) + BR() + 
IF(INCLUDES( OE_Grouping__r.Request_is_from__c, &quot;Specialty Only&quot;), &quot;Specialty Only&quot;, NULL) + BR()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Request is From</label>
        <type>Text</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/UploadForOpenEnrollmentControllerTest.cls
/**********************************************************
@Author - Harish (X-Men)
@name - UploadForOpenEnrollmentControllerTest
@CreateDate - 06/03/2014
@Description - Test class to test the case scenarios for the class "UploadForOpenEnrollmentController".
@Version - 1.0
@reference - None
********************************************************/

@isTest 
private class UploadForOpenEnrollmentControllerTest {
    
    @testSetup static void setup() {
        Account acc = new Account();
        acc.Name = 'TestAccount';
        insert acc;
        
        Open_Enrollment_Meetings__c oem = new Open_Enrollment_Meetings__c();
        oem.Name = 'TestMeeting';
        oem.Account__c = acc.Id;
        oem.Request_is_from__c = 'Commercial Medical';
        oem.Performance_Guarantees__c = 'No';
        oem.Cost_Center_Local__c = 'testCostCenterlocal';
        oem.Cost_Center_National__c = 'National - West - 5100167800';
        oem.Plan_Type__c = 'ANC - AD&D';
        oem.Client_Arrangement__c ='New Business';
        oem.Sole_Carrier_or_Multi_Carriers__c = 'Sole Carrier';
        oem.Dress_Code_for_Event__c ='Business Casual';
        oem.Client_Drivers_Issues_Risks__c ='No Risk';
        oem.Member_Customer_Service_Telephone__c = '1234567890';
        
        insert oem;
    }
    
    //Covers Negative Scenario
    public static testmethod void uploadOETestMethod() {
        
        Open_Enrollment_Meetings__c meet = new Open_Enrollment_Meetings__c();
        
        list<Open_Enrollment_Meetings__c> oem = new list<Open_Enrollment_Meetings__c>();
        oem = [SELECT Id,name FROM Open_Enrollment_Meetings__c Limit 1];
        meet = oem[0];
        
        Test.startTest();
        
        PageReference pageRef = Page.UploadForOpenEnrollment;
        Test.setCurrentPage(pageRef);
        
        ApexPages.StandardController sc = new ApexPages.StandardController(meet); 
        UploadForOpenEnrollmentController uploadOE = new UploadForOpenEnrollmentController(sc);
        uploadOE.fileName = 'test.doc';
        uploadOE.fileBodyContents = String.valueOf(meet);
        uploadOE.fileRefreshPage();
        
        //Check for ApexPages.Message in Assert
        ApexPages.Message[] pageMessages = ApexPages.getMessages();
        System.assertNotEquals(0, pageMessages.size());
        
        // Check that the error message you are expecting is in pageMessages
        Boolean messageFound = false;

        for(ApexPages.Message message : pageMessages) {
            if(message.getSummary() == 'You can only upload csv files.'
                && message.getDetail() == 'You can only upload csv files.'
                && message.getSeverity() == ApexPages.Severity.ERROR) {
                messageFound = true;        
            }
        }
        
        System.assert(messageFound);
        
        Test.stopTest();
    }
    
    //Covers Positive Scenario
    public static testmethod void uploadOETestMethod1() {
        
        list<Open_Enrollment_Meetings__c> oem = new list<Open_Enrollment_Meetings__c>();
        oem = [SELECT Id,name FROM Open_Enrollment_Meetings__c Limit 1];
       
        
        Test.startTest();
        
        PageReference pageRef = Page.UploadForOpenEnrollment;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(oem[0]); 
        UploadForOpenEnrollmentController uploadOE = new UploadForOpenEnrollmentController(sc);
        //List<SFDC_Volunteer_Event__c> lstOe = uploadOE.openEnrollmentList;
        
        uploadOE.fileName = 'Upload.csv';
        uploadOE.fileBodyContents = String.valueOf('Upload.csv');
        uploadOE.fileRefreshPage();
        
        //List<OpenEnrollmentWrapper> enrollmentWrappers = new List<OpenEnrollmentWrapper>();
        List<String> testColumnRow = new List<String> {'Test','Data'};
        List<OpenEnrollmentCSVParserServices.ColumnNameWrapper> testColumnNames = OpenEnrollmentCSVParserServices.generateColumnNames(testColumnRow, 0);
        Integer expectedCSVRowNumber =  1;
        List<String> testData = new List<String>{'TestName','12345'};
        OpenEnrollmentCSVParserServices.OpenEnrollmentWrapper actualEnrollmentWrapper = OpenEnrollmentCSVParserServices.createOpenEnrollment(testData, testColumnNames, oem[0].Id, expectedCSVRowNumber);
        
        uploadOE.enrollmentWrappers = new List<OpenEnrollmentCSVParserServices.OpenEnrollmentWrapper>{actualEnrollmentWrapper};
        uploadOE.insertRecords();
        
        
        Test.stopTest();
    }
}