objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the account for which the OE meetings will be recorded.</description>
        <inlineHelpText>Select an account if this set of meetings is related to an account in Salesforce.com.</inlineHelpText>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT(Account__r.Anthem_Entity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is from the Facilitator account.  It will be populated by a workflow.  The OE Coordinator is now a Facilitator role on the facilitator account so they can manage who the facilitator will be should there be personnell changes</description>
        <inlineHelpText>This field will be populated when you save the record.  There is no need to enter the OE Coordinator..</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>The Plan Type for the meetings group.</description>
        <inlineHelpText>Select the Product offering for this group of meetings.</inlineHelpText>
        <label>Plan Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP- HIA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP - HRA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP -HSA</fullName>
                    <label>MED     CDHP - HSA</label>
                </value>
                <value>
                    <fullName>MED     POS</fullName>
                </value>
                <value>
                    <fullName>MED     PPO</fullName>
                </value>
                <value>
                    <fullName>MED     EPO</fullName>
                </value>
                <value>
                    <fullName>MED     HMO</fullName>
                </value>
                <value>
                    <fullName>MED     JAA</fullName>
                </value>
                <value>
                    <fullName>MED     LiveHealth Online</fullName>
                </value>
                <value>
                    <fullName>MED     Engage</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice EQ</fullName>
                </value>
                <value>
                    <fullName>CA      First Impressions</fullName>
                </value>
                <value>
                    <fullName>CA      SIMNSA</fullName>
                </value>
                <value>
                    <fullName>CA      Transition Assistance</fullName>
                </value>
                <value>
                    <fullName>CA      Vivity</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD-HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD- PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   PDP</fullName>
                </value>
                <value>
                    <fullName>HW – Group Retiree - Silver Sneakers</fullName>
                </value>
                <value>
                    <fullName>HW      24/7 Nurseline</fullName>
                </value>
                <value>
                    <fullName>HW      AIM</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Rewards</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Mobile Health</fullName>
                </value>
                <value>
                    <fullName>HW      Complex Care</fullName>
                </value>
                <value>
                    <fullName>HW      ConditionCare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Strategic Accounts</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Interplan</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Labor Accounts</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>Ohio</fullName>
                </value>
                <value>
                    <fullName>Virginia</fullName>
                </value>
                <value>
                    <fullName>Wisconsin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>OE_Grouping__r.Anthem_Entity__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bilingual__c</fullName>
        <description>Pick list to indicate if bilingual Facilitator is required.</description>
        <inlineHelpText>Select Yes if bilingual representation is required.  Indicate the language in the meeting comments.</inlineHelpText>
        <label>Bilingual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Tagalog</fullName>
                </value>
                <value>
                    <fullName>Tieng-Viet</fullName>
                </value>
                <value>
                    <fullName>Mandarin</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buddy_Program_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meeting is Eligible for the buddy program the field is maintained by OE Coordinators because not all fit into a formula.</description>
        <label>Buddy Program Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <label>Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Fair</fullName>
                </value>
                <value>
                    <fullName>Conference Call</fullName>
                </value>
                <value>
                    <fullName>Health Fair</fullName>
                </value>
                <value>
                    <fullName>PowerPoint w/ VO  {PP with VO}</fullName>
                    <label>PowerPoint with Voiceover</label>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Q &amp; A</fullName>
                </value>
                <value>
                    <fullName>Supplies Only</fullName>
                </value>
                <value>
                    <fullName>Virtual (Webinar)</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup for the OE Coordinator so that email alerts can be sent when meetings are submitted or changed</description>
        <inlineHelpText>Please select your Open Enrollment Coordinator - For Central and South West - Colleen Douma, For North East - Colleen Jacobs, For West - Bethany Snee.</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <infoMessage>This field will be populated after save</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment (OE Coordinator)</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OE_Grouping__c</fullName>
        <description>The parent link.</description>
        <inlineHelpText>This link will take you back to the Group Meeting record.</inlineHelpText>
        <label>Meetings Grouping</label>
        <referenceTo>Open_Enrollment_Meetings__c</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <formula>TEXT(OE_Grouping__r.Source__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Participant__c.object
<CustomObject>
    <description>A junction object used for linking Volunteer Events to a participant</description>
    <fields>
        <fullName>Facilitator_Type__c</fullName>
        <formula>TEXT(OE_Ambassador_Volunteer__r.Facilitator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Facilitator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Event__c</fullName>
        <label>Meeting Name</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>R00N30000001WZmFEAW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OE Ambassador Volunteers</label>
    <nameField>
        <displayFormat>Volunteer_ID {0000}</displayFormat>
        <label>Volunteer Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OE Ambassador Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OEAmbassadorVolunteerTriggerHandlerTest.cls
/**************************************************************************************
@description : Test Class for OEAmbassadorVolunteerActions
@Author               : X-men Offshore
US                    : PRDCRM-30730 . Modified Test class as part of PRDCRM-41975
*************************************************************************************/
/**************************************************************************
* Mod 				  : 10/24/2019
* @Author             : Poonam Goturi - xmen
* @description		  : As part of PRDCRM-43212, added TestDataFactory reference (Xmen)
*************************************************************************************/

@isTest
public class OEAmbassadorVolunteerTriggerHandlerTest {
    public static final String COORDINATOR_EMAIL = 'coordinator@test.com';
    
    @testSetup
    static void setupTestData(){
        Test.setMock(HttpCalloutMock.class, New MockBingTravelResponse());
        
        Id conrtID = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Facilitator Contact').getRecordTypeId();
        Id accrtID = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Prospect').getRecordTypeId();
        
		//Insert Account records
        List<Account> accRec = new List<Account>();
        Account accOeRec = new Account();
        accOeRec.Name = 'Open Enrollment';
        accOeRec.Anthem_Entity__c = 'National Accounts';
        accOeRec.Region__c = 'Central';
        accRec.add(accOeRec);
        insert accRec;
        
        Account acc = (Account)TestFactory.createSObject(new Account(name='Open Enrollment'), true);
        
        List<Contact> ambassadors = new List<Contact>();
        Contact ambassador = 
        (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id,Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_AMBASSADOR_TYPE));
        insert ambassador;
          
        Contact coordinator = (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, email = COORDINATOR_EMAIL,Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_COORDINATOR_TYPE), true); 
        
        //Insert contact records
		List<Contact> conRec = new List<Contact>();
        conRec = TestDataFactory.createContact(1,'Tony','Test1',accRec[0],conrtID,'OE Ambassador','Central','test22@test.com',true,-1,-1);
        insert conRec;
        
		List<Contact> conRec1 = new List<Contact>();
        conRec1 = TestDataFactory.createContact(1,'Tony','Test2',accRec[0],conrtID,'OE Ambassador','Central','test11@test.com',true,NULL,NULL);
        insert conRec1;
        
		List<Contact> conRec5 = new List<Contact>();
        conRec5 = TestDataFactory.createContact(1,'Tony','Test3',accRec[0],conrtID,'OE Ambassador','Central','test55@test.com',true,NULL,NULL);
        insert conRec5;
        
		List<Contact> conRec6=new List<Contact>();
        conRec6 = TestDataFactory.createContact(1,'test','Test4',accRec[0],conrtID,'OE Coordinator','Central','test@test.com',true,0,0);
        insert conRec6;
        
        //Insert OE meeting record
		List<Open_Enrollment_Meetings__c> oemeetingRec = new List<Open_Enrollment_Meetings__c>();
        oemeetingRec = TestDataFactory.createOpenEnrollmentMeeting(1,'Test123',accRec[0],'Georgia',conRec6[0],UtilConstants.Plan_Type,'Commercial Medical','Yes','Test Performance comment','Renewal - Growth Opportunity','Sole Carrier','Test tally fields','3534353453',UtilConstants.Dress_Code_for_Event);
        insert oemeetingRec;
        
        //Insert Open Enrollment record
		List<SFDC_Volunteer_Event__c> oeRec = new List<SFDC_Volunteer_Event__c>();
        oeRec = TestDataFactory.createOpenEnrollment(1,'Test123',oemeetingRec[0],'No',FALSE,'321 N Clark','Chicago','IL','60654','N/A','N/A',System.Today(),'No',UtilConstants.Meeting_Type,100,true,'DRAFT','Yes',41.8882434,-87.6328535,true,false,false,accRec[0],'New Request',conRec6[0]);
        insert oeRec;
        
        Open_Enrollment_Meetings__c meeting =(Open_Enrollment_Meetings__c)TestFactory.createSObject(new Open_Enrollment_Meetings__c(account__c = acc.Id, source__c = 'Central', Plan_Type__c='MED CDHP- HIA',OE_Coordinator_Contact__c = coordinator.Id), true);

        SFDC_Volunteer_Event__c event = (SFDC_Volunteer_Event__c)TestFactory.createSObject(new SFDC_Volunteer_Event__c(OE_Grouping__c = meeting.Id, name = 'Test Event', bilingual__c = 'No', Buddy_Program_Eligible__c = FALSE,Meeting_Type__c='Benefit Fair',Recruitment_of_Facilitator_Needed__c='Yes',meeting_city__c = 'Poway', meeting_state__c = 'CA', Date__c = system.today()), true);                
        
        List<SFDC_Volunteer_Participant__c> participants = new List<SFDC_Volunteer_Participant__c>();
        
        SFDC_Volunteer_Participant__c sp = (SFDC_Volunteer_Participant__c)TestFactory.createSObject(new SFDC_Volunteer_Participant__c(OE_Ambassador_Volunteer__c = ambassador.Id, Volunteer_Event__c = event.Id));
        insert sp;
       
		//Insert OE Ambassador Volunteer records
		List<SFDC_Volunteer_Participant__c> oeVolunteer2 = new List<SFDC_Volunteer_Participant__c>();
        oeVolunteer2 = TestDataFactory.createOEAmbassadorVolunteer(1,oeRec[0],conRec[0],true,true);
        insert oeVolunteer2;
        
		List<SFDC_Volunteer_Participant__c> oeAmbUpdateList1 = new List<SFDC_Volunteer_Participant__c>();
        oeAmbUpdateList1 = [select id,Selected_For_Facilitator__c,Thanks_but_No_Thanks__c from SFDC_Volunteer_Participant__c where OE_Ambassador_Volunteer__r.id =: conRec[0].id LIMIT 1];
        oeAmbUpdateList1 [0].Thanks_but_No_Thanks__c = false;
		Update oeAmbUpdateList1;
        
		List<SFDC_Volunteer_Participant__c> oeVolunteer10 = new List<SFDC_Volunteer_Participant__c>();
        oeVolunteer10 = TestDataFactory.createOEAmbassadorVolunteer(1,oeRec[0],conRec5[0],false,false);
        insert oeVolunteer10;
        
		List<SFDC_Volunteer_Participant__c> oeAmbUpdateList2 = new List<SFDC_Volunteer_Participant__c>();
        oeAmbUpdateList2 = [select id,Selected_For_Facilitator__c,Thanks_but_No_Thanks__c from SFDC_Volunteer_Participant__c where (OE_Ambassador_Volunteer__r.id =: conRec5[0].id and Selected_For_Facilitator__c = false and Thanks_but_No_Thanks__c = false) LIMIT 1];
        oeAmbUpdateList2[0].Selected_For_Facilitator__c = true;
        oeAmbUpdateList2[0].Thanks_but_No_Thanks__c = true;
        Update oeAmbUpdateList2;
        
		List<SFDC_Volunteer_Participant__c> oeVolunteer = new List<SFDC_Volunteer_Participant__c>();
        oeVolunteer = TestDataFactory.createOEAmbassadorVolunteer(1,oeRec[0],conRec1[0],false,false);
        insert oeVolunteer;
        
		List<SFDC_Volunteer_Participant__c> oeVolunteer7 = new List<SFDC_Volunteer_Participant__c>();
        oeVolunteer7 = TestDataFactory.createOEAmbassadorVolunteer(1,oeRec[0],conRec1[0],true,true);
        insert oeVolunteer7;
        
		List<Contact> contactUpdateList = new List<Contact>();
        contactUpdateList = [select id,OE_Amb_No_Thanks_Current_Year_Tally__c ,OE_Amb_Selected_Current_Year_Tally__c from Contact where id =: conRec5[0].id LIMIT 1];
        contactUpdateList[0].OE_Amb_No_Thanks_Current_Year_Tally__c = -2;
        contactUpdateList[0].OE_Amb_Selected_Current_Year_Tally__c = -2;
        update contactUpdateList;
        
        Test.startTest();
        List<SFDC_Volunteer_Participant__c> updateSVPlist=new List<SFDC_Volunteer_Participant__c>();
        List<SFDC_Volunteer_Participant__c> svpList=[select Id,Selected_For_Facilitator__c from SFDC_Volunteer_Participant__c where Selected_For_Facilitator__c=FALSE LIMIT 1 ];
        for(SFDC_Volunteer_Participant__c svp:svpList){
            svp.Selected_For_Facilitator__c=TRUE;
            updateSVPlist.add(svp);
        }
        
        List<SFDC_Volunteer_Participant__c> updateSVPlist2=new List<SFDC_Volunteer_Participant__c>();
        List<SFDC_Volunteer_Participant__c> svpListFalse=[select Id,Selected_For_Facilitator__c from SFDC_Volunteer_Participant__c where Selected_For_Facilitator__c=TRUE LIMIT 1 ];
        system.debug('svpListFalse are'+svpListFalse);
        for(SFDC_Volunteer_Participant__c svp:svpListFalse){
            svp.Selected_For_Facilitator__c=FALSE;
            updateSVPlist2.add(svp);
        }       
        
        Update updateSVPlist2;
        Update updateSVPlist ;
               
        List<SFDC_Volunteer_Participant__c> oeVolDelete10 = [select id from SFDC_Volunteer_Participant__c where id =: oeVolunteer10[0].id];
        delete oeVolDelete10;
        
        Test.StopTest();
        System.assertEquals(null,oeVolunteer10[0].Selected_for_Facilitator_Tally__c , 'selected fac tally should be null as we have initialised with NULL ,thus no modification from OE amb records ');
        System.assertEquals(-1,conRec[0].OE_Amb_Selected_Current_Year_Tally__c, 'selected current year tally should should get update after change in OE amb volunteer');
    }    
       static testMethod void testMethodAccExec(){
           Test.startTest();
           OEAmbassadorVolunteerActions obj = new OEAmbassadorVolunteerActions();
           List<SFDC_Volunteer_Participant__c> oeAmbVolList= [select id,Selected_For_Facilitator__c,Thanks_but_No_Thanks__c from SFDC_Volunteer_Participant__c limit 1];
           System.assertEquals(oeAmbVolList[0].Selected_For_Facilitator__c,true,'Selected for facilator expected true');
           System.assertEquals(oeAmbVolList[0].Thanks_but_No_Thanks__c ,false,'Thanks but no thanks expected false');
           Test.StopTest();
       }
}