objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account_Region__c</fullName>
        <formula>TEXT(Account__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Anthem_Entity__c</fullName>
        <formula>TEXT(Account__r.Anthem_Entity__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Anthem Entity</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is from the Facilitator account.  It will be populated by a workflow.  The OE Coordinator is now a Facilitator role on the facilitator account so they can manage who the facilitator will be should there be personnell changes</description>
        <inlineHelpText>This field will be populated when you save the record.  There is no need to enter the OE Coordinator..</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Situs_State__c</fullName>
        <formula>TEXT(Account__r.Situs_State__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Situs State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submarket__c</fullName>
        <formula>Text( Account__r.Submarket__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Submarket</label>
        <type>Text</type>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/OpenEnrollmentMeetingsHandler.cls
/***************************************************************
* Purpose:  Assign OE Coordinator based on Anthem Entity ,Region,Situs State
* Mod:      5 August 2019
* Author:   Mehaboob
* Story :   PRDCRM-37974
***************************************************************
Modifications 
@Author :Mehaboob
@description : added oem.Submarket__c!='Strategic' for Situs State California where Submarket as Strategic
@Story :   PRDCRM-43854
@comment : Modified as part of PRDCRM-43854
***************************************************************/

public with sharing class OpenEnrollmentMeetingsHandler{

    //@comment : method to assign the OE Coordinator based on Entity,Region ,Situs State.
    public static void assignOECoordinator(List<Open_Enrollment_Meetings__c> newOEMList, String openEnrollmentAccountID){
        
        Id facRecTypeID = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Facilitator Contact').getRecordTypeId();
        
        //returns list of OE Coordinators
        List<Contact> conList=[Select Id,Account.Id,Facilitator_Type__c,RecordType.Name, Region_Location__c from Contact where Account.Id=: openEnrollmentAccountID AND Facilitator_Type__c='OE Coordinator' AND Region_Location__c!=NULL AND RecordTypeID=:facRecTypeID];
        
        for(Open_Enrollment_Meetings__c oem:newOEMList){ 
            
            for(Contact con:conList){
                
                
                //National Accounts  : OE Coordinator for Anthem Entity National Accounts
                if( oem.Anthem_Entity__c==Label.National_Accounts_AE && (con.Region_Location__c!=NULL && con.Region_Location__c!='') && con.Region_Location__c.contains(oem.Account_Region__c) ){
                        oem.OE_Coordinator_Contact__c=con.Id;
                    }
                
                //Local/Large Group : : OE Coordinator for Anthem Entity Local/Large Group
                else if((oem.Anthem_Entity__c==Label.Local_Large_Group_AE) && (con.Region_Location__c!=NULL && con.Region_Location__c!='') && oem.Situs_State__c==Label.Situs_State_California && oem.Submarket__c==Label.Strategic_California && con.Region_Location__c.contains(Label.Strategic_Accounts)){
                        oem.OE_Coordinator_Contact__c=con.Id;
                    } 
                    
                //Local/Large Group : : OE Coordinator for Anthem Entity Local/Large Group for non Strategic    
                else if((oem.Anthem_Entity__c==Label.Local_Large_Group_AE) && (con.Region_Location__c!=NULL && con.Region_Location__c!='')  && con.Region_Location__c.contains(oem.Situs_State__c) && oem.Submarket__c!=Label.Strategic_California){
                        oem.OE_Coordinator_Contact__c=con.Id;
                    }
                
                //Labor and Trust : OE Coordinator for Anthem Entity Labor and Trust
                else if( (con.Region_Location__c!=NULL && con.Region_Location__c!='') && oem.Anthem_Entity__c==Label.Labor_and_Trust_AE && con.Region_Location__c.contains(Label.Labor_Accounts) ){
                        oem.OE_Coordinator_Contact__c=con.Id;
                }
            }
        }  
    }
}