objects/Open_Enrollment_Meetings__c.object
<CustomObject>
    <description>This object is a container for all individual OE Meetings.  An Account may be associated to 0 to many Open Enrollment Meeting (Groupings).</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>This is the account for which the OE meetings will be recorded.</description>
        <inlineHelpText>Select an account if this set of meetings is related to an account in Salesforce.com.</inlineHelpText>
        <label>Account Legal Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field is from the Facilitator account.  It will be populated by a workflow.  The OE Coordinator is now a Facilitator role on the facilitator account so they can manage who the facilitator will be should there be personnell changes</description>
        <inlineHelpText>This field will be populated when you save the record.  There is no need to enter the OE Coordinator..</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment Meetings</relationshipLabel>
        <relationshipName>Open_Enrollment_Meetings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Plan_Type__c</fullName>
        <description>The Plan Type for the meetings group.</description>
        <inlineHelpText>Select the Product offering for this group of meetings.</inlineHelpText>
        <label>Plan Type</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP- HIA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP - HRA</fullName>
                </value>
                <value>
                    <fullName>MED     CDHP -HSA</fullName>
                    <label>MED     CDHP - HSA</label>
                </value>
                <value>
                    <fullName>MED     POS</fullName>
                </value>
                <value>
                    <fullName>MED     PPO</fullName>
                </value>
                <value>
                    <fullName>MED     EPO</fullName>
                </value>
                <value>
                    <fullName>MED     HMO</fullName>
                </value>
                <value>
                    <fullName>MED     JAA</fullName>
                </value>
                <value>
                    <fullName>MED     LiveHealth Online</fullName>
                </value>
                <value>
                    <fullName>MED     Engage</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice</fullName>
                </value>
                <value>
                    <fullName>CA      Elements Choice EQ</fullName>
                </value>
                <value>
                    <fullName>CA      First Impressions</fullName>
                </value>
                <value>
                    <fullName>CA      SIMNSA</fullName>
                </value>
                <value>
                    <fullName>CA      Transition Assistance</fullName>
                </value>
                <value>
                    <fullName>CA      Vivity</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD-HMO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MAPD- PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   MA PPO</fullName>
                </value>
                <value>
                    <fullName>Group Retiree   PDP</fullName>
                </value>
                <value>
                    <fullName>HW – Group Retiree - Silver Sneakers</fullName>
                </value>
                <value>
                    <fullName>HW      24/7 Nurseline</fullName>
                </value>
                <value>
                    <fullName>HW      AIM</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Guide</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Health Rewards</fullName>
                </value>
                <value>
                    <fullName>HW      Anthem Mobile Health</fullName>
                </value>
                <value>
                    <fullName>HW      Complex Care</fullName>
                </value>
                <value>
                    <fullName>HW      ConditionCare</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>National Accounts</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Strategic Accounts</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Interplan</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Labor Accounts</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New York</fullName>
                </value>
                <value>
                    <fullName>Ohio</fullName>
                </value>
                <value>
                    <fullName>Virginia</fullName>
                </value>
                <value>
                    <fullName>Wisconsin</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment Meetings</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>OE Meeting Grouping Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment Meetings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Bilingual__c</fullName>
        <description>Pick list to indicate if bilingual Facilitator is required.</description>
        <inlineHelpText>Select Yes if bilingual representation is required.  Indicate the language in the meeting comments.</inlineHelpText>
        <label>Bilingual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                    <label>No</label>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Tagalog</fullName>
                </value>
                <value>
                    <fullName>Tieng-Viet</fullName>
                </value>
                <value>
                    <fullName>Mandarin</fullName>
                </value>
                <value>
                    <fullName>Japanese</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Buddy_Program_Eligible__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Meeting is Eligible for the buddy program the field is maintained by OE Coordinators because not all fit into a formula.</description>
        <label>Buddy Program Eligible</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Meeting_Type__c</fullName>
        <label>Meeting Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Benefit Fair</fullName>
                </value>
                <value>
                    <fullName>Conference Call</fullName>
                </value>
                <value>
                    <fullName>Health Fair</fullName>
                </value>
                <value>
                    <fullName>PowerPoint w/ VO  {PP with VO}</fullName>
                    <label>PowerPoint with Voiceover</label>
                </value>
                <value>
                    <fullName>Presentation</fullName>
                </value>
                <value>
                    <fullName>Q &amp; A</fullName>
                </value>
                <value>
                    <fullName>Supplies Only</fullName>
                </value>
                <value>
                    <fullName>Virtual (Webinar)</fullName>
                </value>
                <value>
                    <fullName>OE Kit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup for the OE Coordinator so that email alerts can be sent when meetings are submitted or changed</description>
        <inlineHelpText>Please select your Open Enrollment Coordinator - For Central and South West - Colleen Douma, For North East - Colleen Jacobs, For West - Bethany Snee.</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <infoMessage>This field will be populated after save</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment (OE Coordinator)</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OE_Grouping__c</fullName>
        <description>The parent link.</description>
        <inlineHelpText>This link will take you back to the Group Meeting record.</inlineHelpText>
        <label>Meetings Grouping</label>
        <referenceTo>Open_Enrollment_Meetings__c</referenceTo>
        <relationshipLabel>Open Enrollment</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Recruitment_of_Facilitator_Needed__c</fullName>
        <description>AM checks this if they will not be attending or if they don&apos;t already have a facilitator lined up.</description>
        <inlineHelpText>If Yes Open Enrollment Team will seek coverage.</inlineHelpText>
        <label>Facilitator Needs to be Recruited</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <formula>TEXT(OE_Grouping__r.Source__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Source</label>
        <type>Text</type>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Participant__c.object
<CustomObject>
    <description>A junction object used for linking Volunteer Events to a participant</description>
    <fields>
        <fullName>Facilitator_Type__c</fullName>
        <formula>TEXT(OE_Ambassador_Volunteer__r.Facilitator_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Facilitator Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Volunteer_Event__c</fullName>
        <label>Meeting Name</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>R00N30000001WZmFEAW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OE Ambassador Volunteers</label>
    <nameField>
        <displayFormat>Volunteer_ID {0000}</displayFormat>
        <label>Volunteer Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OE Ambassador Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/VolunteerParticipantEmailServiceImplTest.cls
/***************************************************************
    * Purpose:  Test class for VolunteerParticipantEmailServiceImpl
    * Mod:      6 December 2016
    * Author:   Martin Kona
    * Mehaboob: Lifted and Shifted from COM1 - PRDCRM-39696  
    ***************************************************************/

@isTest
public class VolunteerParticipantEmailServiceImplTest {

    public static final List<String> NOTIFICATION_USERS = new List<String>{'a@bluewolf.com','b@bluewolf.com','c@bluewolf.com'}; 
    public static final String COORDINATOR_EMAIL = 'mehaboobpasha.kallur@legatohealth.com';
    public static final String CONSULTANT_EMAIL = 'smita.ganiger@legatohealth.com';
    public static final String AMBASADDOR_EMAIL = 'rishav.kumar@legatohealth.com';

    @testSetup
    public static void initData() {

        initCustomSettings();
        Test.setMock(HttpCalloutMock.class, TravelResponseServiceTest.getDefaultBingGeocodeMock());

        Account acc = (Account)TestFactory.createSObject(new Account(name='Open Enrollment'), true);

        Contact consultant = 
            (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, email = CONSULTANT_EMAIL,
                Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.CONSULTANT_TYPE), true);

        Contact ambassador = 
            (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, email = AMBASADDOR_EMAIL,
                Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_AMBASSADOR_TYPE), true);

        Contact coordinator = 
            (Contact)TestFactory.createSObject(new Contact(accountId = acc.Id, email = COORDINATOR_EMAIL,
                Facilitator_Type__c = VolunteerParticipantEmailServiceImpl.OE_COORDINATOR_TYPE), true);         

        Open_Enrollment_Meetings__c meeting = 
            (Open_Enrollment_Meetings__c)TestFactory.createSObject(
                new Open_Enrollment_Meetings__c(account__c = acc.Id, source__c = 'Central',Plan_Type__c='MED CDHP- HIA',
                    OE_Coordinator_Contact__c = coordinator.Id), true);

        SFDC_Volunteer_Event__c event = 
            (SFDC_Volunteer_Event__c)TestFactory.createSObject(
                new SFDC_Volunteer_Event__c(OE_Grouping__c = meeting.Id, name = 'Test Event', bilingual__c = 'No', Buddy_Program_Eligible__c = FALSE, Meeting_Type__c='Benefit Fair',Recruitment_of_Facilitator_Needed__c='Yes',
                OE_Coordinator_Contact__c=coordinator.Id,OE_Consultant_Lead__c=coordinator.Id,meeting_city__c = 'Poway', meeting_state__c = 'CA', Date__c = system.today()), true);                
        
        SFDC_Volunteer_Participant__c sp1 = 
            (SFDC_Volunteer_Participant__c)TestFactory.createSObject(
                new SFDC_Volunteer_Participant__c(OE_Ambassador_Volunteer__c = consultant.Id, Volunteer_Event__c = event.Id), true);

        SFDC_Volunteer_Participant__c sp2 = 
            (SFDC_Volunteer_Participant__c)TestFactory.createSObject(
                new SFDC_Volunteer_Participant__c(OE_Ambassador_Volunteer__c = ambassador.Id, Volunteer_Event__c = event.Id), true);            
    }

    @isTest
    public static void testNotificationUsers() {        

        VolunteerParticipantEmailServiceImpl service = new VolunteerParticipantEmailServiceImpl();

        System.assertEquals(NOTIFICATION_USERS, service.notificationUsers);
    }

    @isTest
    public static void testGetVolunteerInfo() {

        Set<Id> ids = new Map<Id, sObject>([select Id from SFDC_Volunteer_Participant__c]).keySet();

        VolunteerParticipantEmailServiceImpl service = new VolunteerParticipantEmailServiceImpl();
        List<SFDC_Volunteer_Participant__c> participants = service.getVolunteerInfo(ids);

        system.assert(ids.size() > 1);
        system.assertEquals(ids.size(), participants.size());

        for (SFDC_Volunteer_Participant__c part : participants) {
            system.assertNotEquals(part.Volunteer_Event__r.Name, NULL);
            system.assertNotEquals(part.Volunteer_Event__r.OE_Coordinator_Contact__r.Email, NULL);
            system.assertNotEquals(part.Volunteer_Event__r.Date__c, NULL);
            system.assertNotEquals(part.OE_Ambassador_Volunteer__r.FirstName, NULL);
            system.assertNotEquals(part.OE_Ambassador_Volunteer__r.LastName, NULL);
            system.assertNotEquals(part.OE_Ambassador_Volunteer__r.Facilitator_Type__c, NULL);          
        }
    }

    @isTest
    public static void testGetVolunteerInfo_ValidationException() {

    }   

    @isTest
    public static void testConfigureEmailMessages_Ambassador() {

        Set<Id> ids = 
            new Map<Id, sObject>(getTestParticipants(
                VolunteerParticipantEmailServiceImpl.OE_AMBASSADOR_TYPE)).keySet();

        VolunteerParticipantEmailServiceImpl service = new VolunteerParticipantEmailServiceImpl();
        List<SFDC_Volunteer_Participant__c> participants = service.getVolunteerInfo(ids);

        List<Messaging.SingleEmailMessage> msgs = 
            service.configureEmailMessages(participants);

        system.assert(msgs.size() > 0);

        for (Messaging.SingleEmailMessage msg : msgs) {
            system.assert(msg.toAddresses.size() == 1);
            System.assertEquals(msg.toAddresses[0], COORDINATOR_EMAIL);
        }

    }

    @isTest
    public static void testConfigureEmailMessages_Consultant() {
        
        Set<Id> ids = 
            new Map<Id, sObject>(getTestParticipants(
                VolunteerParticipantEmailServiceImpl.CONSULTANT_TYPE)).keySet();

        VolunteerParticipantEmailServiceImpl service = new VolunteerParticipantEmailServiceImpl();
        List<SFDC_Volunteer_Participant__c> participants = service.getVolunteerInfo(ids);

        List<Messaging.SingleEmailMessage> msgs = 
            service.configureEmailMessages(participants);

        system.assert(msgs.size() > 0);

        for (Messaging.SingleEmailMessage msg : msgs) {
            system.assertEquals(NOTIFICATION_USERS.size(),msg.toAddresses.size());      
        }
    }

    @isTest
    public static void testInitBodyHTML() {

        Set<Id> ids = 
            new Map<Id, sObject>(getTestParticipants(
                VolunteerParticipantEmailServiceImpl.CONSULTANT_TYPE)).keySet();

        VolunteerParticipantEmailServiceImpl service = new VolunteerParticipantEmailServiceImpl();
        List<SFDC_Volunteer_Participant__c> participants = service.getVolunteerInfo(ids);

        system.assert(participants.size() > 0);

        for (SFDC_Volunteer_Participant__c part : participants) {
            String htmlBody = service.initBodyHTML(part);

            system.assertNotEquals(htmlBody, NULL);
        }       

    }   

    public static List<SFDC_Volunteer_Participant__c> getTestParticipants(String facilitatorType) {

        List<SFDC_Volunteer_Participant__c> volunteers = [select id, 
                Volunteer_Event__r.Name, Volunteer_Event__r.OE_Coordinator_Contact__r.Email,  
                Volunteer_Event__r.Date__c, OE_Ambassador_Volunteer__r.FirstName, 
                OE_Ambassador_Volunteer__r.LastName,OE_Ambassador_Volunteer__r.Facilitator_Type__c 
                from SFDC_Volunteer_Participant__c
                where OE_Ambassador_Volunteer__r.Facilitator_Type__c = :facilitatorType];

        return volunteers;      
    }   

    public static void initCustomSettings() {

        List<Enrollment_user_notification__c> settings = new List<Enrollment_user_notification__c>();

        for (String email : NOTIFICATION_USERS) {
            Enrollment_user_notification__c eun = new Enrollment_user_notification__c();
            eun.Name = 'Name: ' + email;
            eun.email__c = email;

            settings.add(eun);
        }
   
        insert settings;
    }   

}