objects/PaginationRecords__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>To determine number of records to be displayed on each page.</description>
    <fields>
        <fullName>NumberofRecords__c</fullName>
        <label>Number of Records</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Pagination Records</label>
</CustomObject>

classes/UTIL_ErrorHandling_TestMethods.cls
/**
  * @author        Urmi Chatterjee
  * @date          30/10/2013
  * @description   UTIL Class for creation of common Data used in Test Classes.
  */
public class UTIL_ErrorHandling_TestMethods {
    /**
      * @description       Method for defining User object record to be created for use in Test Class. 
      * @param             aliasId the Alias Id of the User record is to be created
      * @param             profileName the profile for which the User record is to be created
      * @return            User
      * @throws            NA
      */
    public static User runningUser(String aliasId, String profileName){
        Id profId = [SELECT Id FROM Profile WHERE Name=: profileName].Id;
        User userData = new User(FirstName=aliasId, LastName=aliasId, Alias=aliasId, IsActive=True, Email=aliasId+'@test.com',
                                 ProfileId=profId, Username=aliasId+'@test.com', EmailEncodingKey='UTF-8', CommunityNickname='Test',
                                 LanguageLocaleKey='en_US', LocaleSidKey='en_US', TimeZoneSidKey='GMT', state='Michigan',Country = 'United States');
                           
        return userData;
    }
    
    /**
      * @description       Method for setting the Custom Setting Value to display fixed records on a Visualforce page
                           for use in Test Class.
      * @param             custName the Custom Setting name
      * @param             num the number of records value
      * @return            void
      * @throws            NA
      */
    public static void createCustomSetting(String custName, Integer num){
        PaginationRecords__c noOfRecs = new PaginationRecords__c(Name=custName, NumberofRecords__c=num);
        insert noOfRecs;
    }
}