objects/Question_Log__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a question that a project team member has about a request.</description>
    <fields>
        <fullName>Domain__c</fullName>
        <label>Domain</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account Management</fullName>
                </value>
                <value>
                    <fullName>Assets/Install Base</fullName>
                </value>
                <value>
                    <fullName>Campaign Management</fullName>
                </value>
                <value>
                    <fullName>Case Management</fullName>
                </value>
                <value>
                    <fullName>Chatter</fullName>
                </value>
                <value>
                    <fullName>Communications Media and Technologies</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Currency Management</fullName>
                </value>
                <value>
                    <fullName>Financial Services</fullName>
                </value>
                <value>
                    <fullName>Forecasting</fullName>
                </value>
                <value>
                    <fullName>Lead Management</fullName>
                </value>
                <value>
                    <fullName>Life Sciences</fullName>
                </value>
                <value>
                    <fullName>Mobile</fullName>
                </value>
                <value>
                    <fullName>Opportunity Management</fullName>
                </value>
                <value>
                    <fullName>Outlook</fullName>
                </value>
                <value>
                    <fullName>Product Management</fullName>
                </value>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>Reports and Dashboards</fullName>
                </value>
                <value>
                    <fullName>Retail Marketing</fullName>
                </value>
                <value>
                    <fullName>Search Marketing</fullName>
                </value>
                <value>
                    <fullName>Tasks and Activities</fullName>
                </value>
                <value>
                    <fullName>User Management</fullName>
                </value>
                <value>
                    <fullName>Website Integration</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Question__c</fullName>
        <description>Detailed question.</description>
        <encryptionScheme>None</encryptionScheme>
        <label>Question</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Related request to the question log</description>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Question Log</relationshipLabel>
        <relationshipName>Question_Log</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Scope__c</fullName>
        <label>Phase</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Plan and Analyze</fullName>
                </value>
                <value>
                    <fullName>Scope</fullName>
                </value>
                <value>
                    <fullName>Design</fullName>
                </value>
                <value>
                    <fullName>Build</fullName>
                </value>
                <value>
                    <fullName>Test</fullName>
                </value>
                <value>
                    <fullName>Deploy</fullName>
                </value>
                <value>
                    <fullName>Initiate and Confirm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who submitted the Question Log</description>
        <label>Submitter</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Question_Logs1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Question Log</label>
    <nameField>
        <displayFormat>QL-{0000}</displayFormat>
        <label>Question Log ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Question Log</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Related_Request__c.object
<CustomObject>
    <fields>
        <fullName>Question_Log__c</fullName>
        <label>Question Log</label>
        <referenceTo>Question_Log__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Related_Requests</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Request__c</fullName>
        <label>Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Related Requests</relationshipLabel>
        <relationshipName>Related_Requests</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Related Request</label>
    <nameField>
        <displayFormat>RR-{000000}</displayFormat>
        <label>Related Request Numbers</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Related Requests</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <description>TOOLKIT - An object that represents a set of features that provides the ability to handle a capability.</description>
    <fields>
        <fullName>Related_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Related Request</label>
        <referenceTo>Request__c</referenceTo>
        <relationshipLabel>Requests (Related Request)</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Request</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SaaSLinkToQuestionCtrlTest.cls
/** 
 *  @Author : Accenture 
 *  @Description : Test Class for Controller class for SaaSQuestionLogListViewCtrl  
 *  @Created Date : 16\06\2015
 * 
 *  Version History :
 *  Date              Changes 
 *  16\06\2015        created 
 *	12\11\2019		  modified
 *
 */
@isTest 
public class SaaSLinkToQuestionCtrlTest
{
    //PRDCRM - 48684 : Tech Debt story(Test setup method to create test data) | 10th Dec, 2019 | Accenture - Panthers
    /**
    @description : Test setup method for test data creation
    */
	@testSetup static void dataSetup() {
        // Creating Question_Log__c record
		SaaSTestUtility.createSaaSQuestion();
        
        //Creating Request__c records
        SaaSTestUtility.createRequest();
        SaaSTestUtility.createRequest();  
    }
    
    //PRDCRM - 48684 | Few modification done to increase the code coverage | 10th Dec, 2019 | Accenture - Panthers
    /**
    @description : Test method to to cover the SaaSLinkToQuestionCtrl class
    */
    @isTest
    static void validateLinkToQuestionLog() 
    {
        Test.startTest(); 
        Boolean bool;
                
        Question_Log__c questionObj = [Select Id, Submitter__c, Question__c, Scope__c, Domain__c, recordTypeID from Question_Log__c LIMIT 1];
        SaaSLinkToQuestionCtrl ctrlObj = new SaaSLinkToQuestionCtrl(new ApexPages.StandardController(questionObj ));
        List<SaaSLinkToQuestionCtrl.RequestWrapper> wraplst = ctrlObj.getrequestWrapLst();
        ctrlObj.previous();
        ctrlObj.next();
        ctrlObj.first();
        ctrlObj.last();
        
        bool = ctrlObj.hasNext;
        bool = ctrlObj.hasPrevious;
        wraplst.get(0).checked = true ;
        wraplst.get(1).checked = true ;
        
        wraplst.get(1).checked = false;
        ctrlObj.updateSelectedRequest();
        List<SaaSLinkToQuestionCtrl.RequestWrapper> listSelectedElements = ctrlObj.getSelectedElement();
        System.assertEquals(1, listSelectedElements.size(), 'Selected element size is not matching');
        ctrlObj.linkToRequest();
        List<Related_Request__c> listRelatedReq = [Select Id from Related_Request__c where Question_Log__c=: questionObj.Id] ;
        System.assertEquals(1, listRelatedReq.size(), 'Selected element size is not matching');
        
        wraplst.get(0).checked = false;
        wraplst.get(1).checked = false;
        ctrlObj.updateSelectedRequest();
        List<SaaSLinkToQuestionCtrl.RequestWrapper> listSelectedElements1 = ctrlObj.getSelectedElement();
        System.assertEquals(0, listSelectedElements1.size(), 'Selected element size is not matching');        
        ctrlObj.linkToRequest();
        System.assertEquals(0, ctrlObj.selectedrequestWrapLst.size(), 'Selected element size is not matching');
        Test.stopTest();   
    }
    
}