objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Quote.OpportunityId</formula>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reason_Update__c</fullName>
        <formula>TEXT( Quote.Opportunity.Stage_Reason__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reason Update</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>RecordType__c</controllingField>
            <valueSetDefinition>
                <sorted>true</sorted>
                <value>
                    <fullName>3rd Party Advocacy</fullName>
                </value>
                <value>
                    <fullName>Account/Sales Team</fullName>
                </value>
                <value>
                    <fullName>B2B</fullName>
                </value>
                <value>
                    <fullName>Bankruptcy/Client Went Out of Business</fullName>
                </value>
                <value>
                    <fullName>Behavioral Health Product Options</fullName>
                </value>
                <value>
                    <fullName>Billing Issues</fullName>
                </value>
                <value>
                    <fullName>Brand</fullName>
                </value>
                <value>
                    <fullName>Broker of Record Change</fullName>
                </value>
                <value>
                    <fullName>Cede</fullName>
                </value>
                <value>
                    <fullName>Claim Issues</fullName>
                </value>
                <value>
                    <fullName>Client Withdrew/No Further Inquiry</fullName>
                </value>
                <value>
                    <fullName>Clinical Value</fullName>
                </value>
                <value>
                    <fullName>COVID19</fullName>
                </value>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Digital and Consumer Engagement</fullName>
                </value>
                <value>
                    <fullName>Discount Value</fullName>
                </value>
                <value>
                    <fullName>Does Not Meet Requirements</fullName>
                </value>
                <value>
                    <fullName>Employee Customer Service</fullName>
                </value>
                <value>
                    <fullName>Exchange – Moving To/From</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation</fullName>
                </value>
                <value>
                    <fullName>Exchange – No Participation/ New Participant</fullName>
                </value>
                <value>
                    <fullName>Fees</fullName>
                </value>
                <value>
                    <fullName>Financial/Discount Value</fullName>
                </value>
                <value>
                    <fullName>Funding Type Change</fullName>
                </value>
                <value>
                    <fullName>Group Number Change</fullName>
                </value>
                <value>
                    <fullName>Guarantees</fullName>
                </value>
                <value>
                    <fullName>Incomplete Data</fullName>
                </value>
                <value>
                    <fullName>Inconvenient to Change Carriers</fullName>
                </value>
                <value>
                    <fullName>IT Security</fullName>
                </value>
                <value>
                    <fullName>Medical Products - CDHP</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QLIUpdate.cls
/* ***************************************************************************
Class Name   : QLIUpdate 
Date Created : 09-MAY-2018
Created By   : Accenture
Description  : This gets called from the Process Builder "UpdateQLIReason"
******************************************************************************* */
global class QLIUpdate {

    @InvocableMethod
    public static void QLIUpdate(List<Id> lstOppId){
    try{
        List<QuoteLineItem> lstQliUpdate = new List<QuoteLineItem>();
        System.debug('@@@lstOppId'+lstOppId);
        List<String> lstOp = new List<String>();
        for(String opp:lstOppId){
          String s = String.valueOf(opp);
          lstOp.add(s.substring(0, 15));
        }
        
        System.debug('@@@@@lstOp'+lstOp);
        if(!lstOp.isEmpty()){
        List<QuoteLineItem> lstQLI =[SELECT id,Reason__c,Reason_Update__c,OpportunityId__c FROM QuoteLineItem WHERE OpportunityId__c IN: lstOp];
        if(!lstQLI.isEmpty()){
            for(QuoteLineItem qli : lstQLI ){
                //qli.ProductStage__c = 'Declined to Quote';
                qli.Reason__c= qli.Reason_Update__c;
                lstQliUpdate.add(qli);
            }
        }
        if(!lstQliUpdate.isEmpty()){
            UPDATE lstQliUpdate;
        }
        }
    }
    catch(Exception e){
        System.debug('Exception'+e);
    }
}
}