objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>OpportunityId__c</fullName>
        <formula>Quote.OpportunityId</formula>
        <label>OpportunityId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductLOB__c</fullName>
        <formula>IF(
NOT(ISBLANK(TEXT(Product2.LOB__c))),
TEXT(Product2.LOB__c),
LEFT( TEXT(Product2.LOB_Org__c),LEN(TEXT(Product2.LOB_Org__c))-2 )
)</formula>
        <label>ProductLOB</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TimeofStageOrEffectiveDateChange__c</fullName>
        <description>Time Stamp when Opportunity Stage or Effective Date are changed . PRDCRM-49042</description>
        <encryptionScheme>None</encryptionScheme>
        <label>TimeofOpptyStageOrEffectiveDateChange</label>
        <type>DateTime</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/QLIUpdateForAccountBatch.cls
/* ***************************************************************************
Class Name   : QLIUpdateForAccountBatch 
Date Created : 12-Feb-2020
Created By   : Partha Pratim Baruah (Vikings)
Description  : This gets called from the Process Builder "UpdateQLIProdStage"
******************************************************************************* */
global class QLIUpdateForAccountBatch {

    @InvocableMethod
    public static void QLIUpdate(List<Id> lstOppId){
    try{
        List<QuoteLineItem> lstQliUpdate = new List<QuoteLineItem>();
        System.debug('@@@lstOppId'+lstOppId);
        List<String> lstOp = new List<String>();
        for(String opp:lstOppId){
          String s = String.valueOf(opp);
          lstOp.add(s.substring(0, 15));
        }
        
        System.debug('@@@@@lstOp'+lstOp);
        if(!lstOp.isEmpty()){
        List<QuoteLineItem> lstQLI =[SELECT id,ProductStage__c ,OpportunityId__c,TimeofStageOrEffectiveDateChange__c  FROM QuoteLineItem WHERE OpportunityId__c IN: lstOp and ProductLOB__c='Medical' ];
        if(!lstQLI.isEmpty()){
            for(QuoteLineItem qli : lstQLI ){                
                qli.TimeofStageOrEffectiveDateChange__c = system.now();              
                lstQliUpdate.add(qli);
            }
        }
        if(!lstQliUpdate.isEmpty()){
            UPDATE lstQliUpdate;
        }
        }
    }
    catch(Exception e){
        System.debug('Exception'+e);
    }
    
}
}