objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>IsArea3__c</fullName>
        <formula>IF(OR( ISPICKVAL(ProductStage__c, &apos;Sold&apos;),ISPICKVAL(ProductStage__c, &apos;IGAP Sold&apos;)),True,False)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsArea3</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Existing_Product__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field will be set to true through the renewal batch job. It is set to true for products already on the quote of the opportunity that was renewed. It will be used to distinguish sold Act Wise products already existing on the quote vs sold act wise products added to the quote after the renewal opportunity was created.</description>
        <label>Is Existing Product</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_New_Business__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used with Act Wise products to indicate that the Quote Line Item is a new product. It is set through the NewBusiness_QuoteLineItem apex class (the trigger handler for trigger ANA_QuoteLineItemsAfterCreate).</description>
        <label>Is New Business</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NewBusiness_QuoteLineItem.cls
/*
@Author : Karthik Keshavan
@name : NewBusiness_QuoteLineItem
@CreatedDate : 11/21/2019 
@Description : This class is the handler for the ANA_QuoteLineItemsAfterCreate trigger for the QLI insert and update conditions  
*/
public with sharing class NewBusiness_QuoteLineItem {
    /*
	@method Name : updateQuote
	@param : the list of Quote Line Items in trigger.new
	@return type : void
	@method Description : This method sets the Is_New_Business__c field on the Quote Line Item.   
	@last Modified Date: 12/04/19
	*/
    public static void updateQuote(list<QuoteLineItem> qliList){
        set<Id> quoteIds = new set<Id>();
        list<Quote> quoteListToBeUpdate = new list<Quote>();
        for(QuoteLineItem qli : qliList){
    			boolean isNewBusiness = false;
            if (qli.IsArea3__c && !qli.Is_New_Business__c ) {
                isNewBusiness = true;
            }
            if (qli.IsArea3__c && !qli.Is_New_Business__c && qli.Is_Existing_Product__c ){
                isNewBusiness = false;
            }
            if (qli.IsArea3__c  && !qli.Is_Existing_Product__c){
                isNewBusiness = true;
            }
            if (qli.Is_Existing_Product__c ){
                isNewBusiness = false;
            }             
            qli.Is_New_Business__c = isNewBusiness;
        }
    }
}