objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Competitor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Competitor1</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <filterItems>
                <field>Account.Competitor__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Quote Line Items</relationshipLabel>
        <relationshipName>Quote_Line_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductStage__c</fullName>
        <inlineHelpText>Set the current Stage for the Product Line</inlineHelpText>
        <label>Product Stage</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>OppType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Dead</fullName>
                </value>
                <value>
                    <fullName>Declined to Quote</fullName>
                </value>
                <value>
                    <fullName>IGAP Dead</fullName>
                </value>
                <value>
                    <fullName>IGAP In Progress</fullName>
                </value>
                <value>
                    <fullName>IGAP Lost</fullName>
                </value>
                <value>
                    <fullName>IGAP Sold</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Jeopardy</fullName>
                </value>
                <value>
                    <fullName>Lost</fullName>
                </value>
                <value>
                    <fullName>Not renewing in Current Period</fullName>
                </value>
                <value>
                    <fullName>Renewed</fullName>
                </value>
                <value>
                    <fullName>Sold</fullName>
                </value>
                <value>
                    <fullName>Termed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Filter on Service Provider Relationships for that particular vendor.</description>
        <label>Vendor</label>
        <referenceTo>ServiceProviderRelationship__c</referenceTo>
        <relationshipLabel>Quote Line Items (Vendor)</relationshipLabel>
        <relationshipName>Quote_Line_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>associatedAccountId__c</fullName>
        <formula>Quote.Opportunity.Account.Id</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Associated Account Id</label>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/ServiceProviderRelationship__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Vendors</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Competitor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Competitor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Vendor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Select the Name of the Vendor</inlineHelpText>
        <label>Vendor</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Service Provider</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Service Provider Relationships (Vendor)</relationshipLabel>
        <relationshipName>Vendors2</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Service Provider Relationship</label>
    <nameField>
        <displayFormat>SPR-{0000}</displayFormat>
        <label>Service Provider Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Provider Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ANA_AP07_ServiceProviderRecord_Test.cls
/**
* This class contains unit tests for validating the behavior of Apex classes
* and triggers.
*
* Unit tests are class methods that verify whether a particular piece
* of code is working properly. Unit test methods take no arguments,
* commit no data to the database, and are flagged with the testMethod
* keyword in the method definition.
*
* All test methods in an organization are executed whenever Apex code is deployed
* to a production organization to confirm correctness, ensure code
* coverage, and prevent regressions. All Apex classes are
* required to have at least 75% code coverage in order to be deployed
* to a production organization. In addition, all triggers must have some code coverage.
* 
* The @isTest class annotation indicates this class only contains test
* methods. Classes defined with the @isTest annotation do not count against
* the organization size limit for all Apex scripts.
*
* See the Apex Language Reference for more information about Testing and Code Coverage.
*/
@isTest(SeeAllData=false)
private without sharing class ANA_AP07_ServiceProviderRecord_Test {
    private static List<Quote> qteList=new List<Quote>();
    private static List<QuoteLineItem> qliList = new List<QuoteLineItem>();
    private static final string NATIONALAMPROFILE='National Sales';
    /*This method is used to covers the SPR class using Account competitor true*/
     static testMethod void upsertsprecordAccComp(){
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1];
        User user1=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        system.runAs(user1){
            Test.StartTest();
            Account brAcc=ANA_UTIL01_TestMethods.createAccount(false);
            brAcc.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('Account','Service Provider');
            brAcc.Competitor__c=true;
            system.assertEquals(true, brAcc.Competitor__c);
            database.insert(brAcc);
            List<Opportunity> opties=ANA_UTIL01_TestMethods.createOpportunities(100,true,brAcc.Id);
            for(Opportunity opt:opties){
                qteList.add(ANA_UTIL01_TestMethods.createQuote(false,opt.id));
            }
            database.insert(qteList); 
            Product2 prd=ANA_UTIL01_TestMethods.createProduct(false);
            database.insert(prd);
            PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false,prd.id);
            database.insert(pbe);
            quotelineitem alite = ANA_UTIL01_TestMethods.createQuoteLineItem(false,qteList.get(0).id,pbe.id);
            alite.Competitor__c = brAcc.id;
            alite.ProductStage__c = 'Sold';
            database.insert(alite);
            ServiceProviderRelationship__c  sprec= ANA_UTIL01_TestMethods.createServiceProviderRelationshipRecord(false,brAcc.id);
            sprec.Account__c = brAcc.id;
            sprec.Vendor__c= brAcc.id;
            database.insert(sprec);
            system.debug('inserted sprec is '+sprec);
            list<ServiceProviderRelationship__c>  listsprec= new list<ServiceProviderRelationship__c>();
            listsprec.add(sprec);
            //Added the below lines to increase the test coverage of the class ANA_UTIL05_AccessSPRDataUtil-start  
            list<ServiceProviderRelationship__c>  listsprec2;
            List<QuotelineItem> listqlitems;
            //Added the lines to increase the test coverage of the class ANA_UTIL05_AccessSPRDataUtil-end
              
            ANA_UTIL05_AccessSPRDataUtil.upsertServiceProviderRecord(listsprec);
            //Added the below lines to increase the test coverage of the class ANA_UTIL05_AccessSPRDataUtil-start
            ANA_UTIL05_AccessSPRDataUtil.upsertServiceProviderRecord(listsprec2);
            ANA_UTIL05_AccessSPRDataUtil.updateQuotelineitem(listqlitems);
             //Added the lines to increase the test coverage of the class ANA_UTIL05_AccessSPRDataUtil-end
            map<Id,QuotelineItem> mapqlitem = new map<Id,QuotelineItem>([select ProductStage__c,associatedAccountId__c,Competitor__c from QuotelineItem where Id =: alite.Id limit 1]);
            ANA_AP07_ServiceProviderRecord.qlineitemids.addAll(mapqlitem.keyset());
            ANA_AP07_ServiceProviderRecord.serviceProviderRecordupsert(mapqlitem);
            Test.StopTest();
        }
    }
     static testMethod void upsertnonsprecordAccComp(){
        Profile profileNA = [select id from profile where name=:NATIONALAMPROFILE limit 1];
        User user1=ANA_UTIL01_TestMethods.runAsUser(profileNA.id);
        system.runAs(user1){
            Test.StartTest();
            Account brAcc=ANA_UTIL01_TestMethods.createAccount(false);
            brAcc.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('Account','Service Provider');
            brAcc.Competitor__c=true;
            database.insert(brAcc);
            
            Account venacc=ANA_UTIL01_TestMethods.createAccount(false);
            venacc.RecordTypeId=ANA_UTIL01_TestMethods.getRecordTypeId('Account','Service Provider');
            venacc.Competitor__c=false;
            database.insert(venacc);
            system.assertEquals(true, brAcc.Competitor__c);
            
            List<Opportunity> opties=ANA_UTIL01_TestMethods.createOpportunities(100,true,brAcc.Id);
            for(Opportunity opt:opties){
                qteList.add(ANA_UTIL01_TestMethods.createQuote(false,opt.id));
            }
            database.insert(qteList); 
            Product2 prd=ANA_UTIL01_TestMethods.createProduct(false);
            database.insert(prd);
            PricebookEntry pbe=ANA_UTIL01_TestMethods.createPricebookEntry(false,prd.id);
            database.insert(pbe);
            quotelineitem alite = ANA_UTIL01_TestMethods.createQuoteLineItem(false,qteList.get(0).id,pbe.id);
            alite.Competitor__c = brAcc.id;
            alite.ProductStage__c = 'Sold';
            database.insert(alite);
            ServiceProviderRelationship__c  sprec= ANA_UTIL01_TestMethods.createServiceProviderRelationshipRecord(false,brAcc.id);
            sprec.Account__c = brAcc.id;
            sprec.Vendor__c= venacc.id;
            database.insert(sprec);
            list<ServiceProviderRelationship__c> sprlist = new list<ServiceProviderRelationship__c>();
            sprlist.add(sprec);
            map<Id,QuotelineItem> mapqlitem = new map<Id,QuotelineItem>([select ProductStage__c,associatedAccountId__c,Competitor__c from QuotelineItem where Id =: alite.Id limit 1]);
            ANA_AP07_ServiceProviderRecord.serviceProviderRecordupsert(mapqlitem);
            ANA_AP07_ServiceProviderRecord.assignsprtoqlitem(sprlist,mapqlitem);
            Test.StopTest();
        }
    }
    
}