objects/SFDC_Volunteer_Event__c.object
<CustomObject>
    <description>Used to manage and track vounteer events</description>
    <fields>
        <fullName>AM_Phone__c</fullName>
        <formula>OE_Grouping__r.Account__r.Account_Manager__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AM Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Manager_Formula__c</fullName>
        <formula>OE_Grouping__r.Account__r.Account_Manager__r.FirstName + &quot; &quot; + OE_Grouping__r.Account__r.Account_Manager__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Manager</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>OE_Grouping__r.Account__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Consultant_SAR_Phone__c</fullName>
        <formula>OE_Grouping__r.Account__r.Client_Engagement_Consultant_SAR1__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Engagement Consultant SAR Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Client_Engagement_Consultant_SAR__c</fullName>
        <description>OE_Grouping__r.Account__r.Client_Engagement_Consultant_SAR1__r.FirstName + &apos; &apos; + OE_Grouping__r.Account__r.Client_Engagement_Consultant_SAR1__r.LastName</description>
        <formula>OE_Grouping__r.Account__r.Client_Engagement_Consultant_SAR1__r.FirstName+ &apos; &apos; + OE_Grouping__r.Account__r.Client_Engagement_Consultant_SAR1__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Client Engagement Consultant SAR</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_City__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Meeting_State__c</fullName>
        <label>Meeting State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>AL</fullName>
                </value>
                <value>
                    <fullName>AK</fullName>
                </value>
                <value>
                    <fullName>AZ</fullName>
                </value>
                <value>
                    <fullName>AR</fullName>
                </value>
                <value>
                    <fullName>CA</fullName>
                </value>
                <value>
                    <fullName>CO</fullName>
                </value>
                <value>
                    <fullName>CT</fullName>
                </value>
                <value>
                    <fullName>DC</fullName>
                </value>
                <value>
                    <fullName>DE</fullName>
                </value>
                <value>
                    <fullName>FL</fullName>
                </value>
                <value>
                    <fullName>GA</fullName>
                </value>
                <value>
                    <fullName>HI</fullName>
                </value>
                <value>
                    <fullName>ID</fullName>
                </value>
                <value>
                    <fullName>IL</fullName>
                </value>
                <value>
                    <fullName>IN</fullName>
                </value>
                <value>
                    <fullName>IA</fullName>
                </value>
                <value>
                    <fullName>KS</fullName>
                </value>
                <value>
                    <fullName>KY</fullName>
                </value>
                <value>
                    <fullName>LA</fullName>
                </value>
                <value>
                    <fullName>ME</fullName>
                </value>
                <value>
                    <fullName>MD</fullName>
                </value>
                <value>
                    <fullName>MA</fullName>
                </value>
                <value>
                    <fullName>MI</fullName>
                </value>
                <value>
                    <fullName>MN</fullName>
                </value>
                <value>
                    <fullName>MS</fullName>
                </value>
                <value>
                    <fullName>MO</fullName>
                </value>
                <value>
                    <fullName>MT</fullName>
                </value>
                <value>
                    <fullName>NE</fullName>
                </value>
                <value>
                    <fullName>NV</fullName>
                </value>
                <value>
                    <fullName>NH</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_Street__c</fullName>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lookup for the OE Coordinator so that email alerts can be sent when meetings are submitted or changed</description>
        <inlineHelpText>Please select your Open Enrollment Coordinator - For Central and South West - Colleen Douma, For North East - Colleen Jacobs, For West - Bethany Snee.</inlineHelpText>
        <label>OE Coordinator</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Facilitator_Type__c</field>
                <operation>equals</operation>
                <value>OE Coordinator</value>
            </filterItems>
            <infoMessage>This field will be populated after save</infoMessage>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Open Enrollment (OE Coordinator)</relationshipLabel>
        <relationshipName>Open_Enrollment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>OE_Coordinator_Phone__c</fullName>
        <formula>OE_Grouping__r.OE_Coordinator_Contact__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>OE Coordinator Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAR_AcctMgt__c</fullName>
        <formula>OE_Grouping__r.Account__r.SARAcctMgmt__r.FirstName + &apos; &apos; + OE_Grouping__r.Account__r.SARAcctMgmt__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAR - AcctMgt</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SAR_Phone__c</fullName>
        <formula>OE_Grouping__r.Account__r.SARAcctMgmt__r.Phone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>SAR Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Session_1_End_Time__c</fullName>
        <label>Session #1 End Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:15 AM</fullName>
                </value>
                <value>
                    <fullName>12:30 AM</fullName>
                </value>
                <value>
                    <fullName>12:45 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:15 AM</fullName>
                </value>
                <value>
                    <fullName>1:30 AM</fullName>
                </value>
                <value>
                    <fullName>1:45 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:15 AM</fullName>
                </value>
                <value>
                    <fullName>2:30 AM</fullName>
                </value>
                <value>
                    <fullName>2:45 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:15 AM</fullName>
                </value>
                <value>
                    <fullName>3:30 AM</fullName>
                </value>
                <value>
                    <fullName>3:45 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:15 AM</fullName>
                </value>
                <value>
                    <fullName>4:30 AM</fullName>
                </value>
                <value>
                    <fullName>4:45 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:15 AM</fullName>
                </value>
                <value>
                    <fullName>5:30 AM</fullName>
                </value>
                <value>
                    <fullName>5:45 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:15 AM</fullName>
                </value>
                <value>
                    <fullName>6:30 AM</fullName>
                </value>
                <value>
                    <fullName>6:45 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:15 AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Session_1_Start_Time__c</fullName>
        <label>Session #1 Start Time</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>12:00 AM</fullName>
                </value>
                <value>
                    <fullName>12:15 AM</fullName>
                </value>
                <value>
                    <fullName>12:30 AM</fullName>
                </value>
                <value>
                    <fullName>12:45 AM</fullName>
                </value>
                <value>
                    <fullName>1:00 AM</fullName>
                </value>
                <value>
                    <fullName>1:15 AM</fullName>
                </value>
                <value>
                    <fullName>1:30 AM</fullName>
                </value>
                <value>
                    <fullName>1:45 AM</fullName>
                </value>
                <value>
                    <fullName>2:00 AM</fullName>
                </value>
                <value>
                    <fullName>2:15 AM</fullName>
                </value>
                <value>
                    <fullName>2:30 AM</fullName>
                </value>
                <value>
                    <fullName>2:45 AM</fullName>
                </value>
                <value>
                    <fullName>3:00 AM</fullName>
                </value>
                <value>
                    <fullName>3:15 AM</fullName>
                </value>
                <value>
                    <fullName>3:30 AM</fullName>
                </value>
                <value>
                    <fullName>3:45 AM</fullName>
                </value>
                <value>
                    <fullName>4:00 AM</fullName>
                </value>
                <value>
                    <fullName>4:15 AM</fullName>
                </value>
                <value>
                    <fullName>4:30 AM</fullName>
                </value>
                <value>
                    <fullName>4:45 AM</fullName>
                </value>
                <value>
                    <fullName>5:00 AM</fullName>
                </value>
                <value>
                    <fullName>5:15 AM</fullName>
                </value>
                <value>
                    <fullName>5:30 AM</fullName>
                </value>
                <value>
                    <fullName>5:45 AM</fullName>
                </value>
                <value>
                    <fullName>6:00 AM</fullName>
                </value>
                <value>
                    <fullName>6:15 AM</fullName>
                </value>
                <value>
                    <fullName>6:30 AM</fullName>
                </value>
                <value>
                    <fullName>6:45 AM</fullName>
                </value>
                <value>
                    <fullName>7:00 AM</fullName>
                </value>
                <value>
                    <fullName>7:15 AM</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Open Enrollment</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Meeting Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Open Enrollment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/SFDC_Volunteer_Participant__c.object
<CustomObject>
    <description>A junction object used for linking Volunteer Events to a participant</description>
    <fields>
        <fullName>Volunteer_Event__c</fullName>
        <label>Meeting Name</label>
        <referenceTo>SFDC_Volunteer_Event__c</referenceTo>
        <relationshipLabel>OE Ambassador Volunteers</relationshipLabel>
        <relationshipName>R00N30000001WZmFEAW</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>OE Ambassador Volunteers</label>
    <nameField>
        <displayFormat>Volunteer_ID {0000}</displayFormat>
        <label>Volunteer Participant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OE Ambassador Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/MeetingConfirmed_Ctrl.cls
/*************************************************************************************
Version     : 1.0 
@Author: Rahmath
Function    : Meeting confirmed Tab for community
US          : PRDCRM-41984
@description : Meeting confirmed Tab for community Open Enrollment
*************************************************************************************/

public with sharing class MeetingConfirmed_Ctrl{    

    @AuraEnabled
    /**
    * @description fetchVolPart     
    */
    public static String fetchVolPart() {
        /**
        * @description fetchVolPart method
        * @return String
        */
        List<id> lstVolEvTemp = new List<id>();
        lstVolEvTemp = getVolunteerEvent(true);
        
        List<WrapperopenEnrollment> wrapperEnrollmentList = new list<WrapperopenEnrollment>();
        if(!Schema.sObjectType.SFDC_Volunteer_Event__c.fields.id.isAccessible()||Schema.sObjectType.SFDC_Volunteer_Event__c.fields.id.isAccessible()) {  
            List<SFDC_Volunteer_Event__c> lstVolEve = [SELECT Id, 
                                                       Account_Name__c,
                                                       Date__C,
                                                       Session_1_Start_Time__c,
                                                       Session_1_End_Time__c,
                                                       Meeting_Street__c,
                                                       Meeting_City__c,
                                                       Meeting_State__c,
                                                       OE_Coordinator_Contact__r.Name,OE_Coordinator_Phone__c,
                                                       Account_Manager_Formula__c,
                                                       AM_Phone__c,SAR_AcctMgt__c,
                                                       SAR_Phone__c,
                                                       Client_Engagement_Consultant_SAR__c,
                                                       Client_Engagement_Consultant_SAR_Phone__c 
                                                       FROM SFDC_Volunteer_Event__c 
                                                       WHERE id IN :lstVolEvTemp];
            for (SFDC_Volunteer_Event__c temp:lstVolEve){
                WrapperopenEnrollment newWrapperEnrollment = new WrapperopenEnrollment();
                newWrapperEnrollment.accountName = temp.Account_Name__c;
                newWrapperEnrollment.meetingDate = temp.Date__c;
                newWrapperEnrollment.sessionStartTime = temp.Session_1_Start_Time__c;
                newWrapperEnrollment.sessionEndTime = temp.Session_1_End_Time__c;
                newWrapperEnrollment.meetingStreet = temp.Meeting_Street__c;
                newWrapperEnrollment.meetingCity = temp.Meeting_City__c;
                newWrapperEnrollment.meetingState = temp.Meeting_State__c;
                newWrapperEnrollment.oeCoordinatorName = temp.OE_Coordinator_Contact__r.Name;
                newWrapperEnrollment.oeCoordinatorPhoneNumber = temp.OE_Coordinator_Phone__c;
                newWrapperEnrollment.accountManger = temp.Account_Manager_Formula__c;
                newWrapperEnrollment.amPhone = temp.AM_Phone__c;
                newWrapperEnrollment.sarAccMgt = temp.SAR_AcctMgt__c;
                newWrapperEnrollment.sarPhone = temp.SAR_Phone__c;
                newWrapperEnrollment.clientEngagementConsultantSAR = temp.Client_Engagement_Consultant_SAR__c;
                newWrapperEnrollment.clientEngagementConsultantSARPhone = temp.Client_Engagement_Consultant_SAR_Phone__c;
                wrapperEnrollmentList.add(newWrapperEnrollment);
            }
        }
        return JSON.serialize(wrapperEnrollmentList);
        
    }    
   
    @AuraEnabled
    /**
    * @description fetchVolParts method    
    */ 
    public static String fetchVolParts() {
        /**
        * @description fetchVolParts method
        * @param
        * @return String fetchVolParts
        */ 
        List<id> lstVolEvTemp1 = new List<id>();
        lstVolEvTemp1 = getVolunteerEvent(false);
        
        List<WrapperopenEnrollment> wrapperEnrollmentList = new list<WrapperopenEnrollment>();
        if(!Schema.sObjectType.SFDC_Volunteer_Event__c.fields.id.isAccessible() || Schema.sObjectType.SFDC_Volunteer_Event__c.fields.id.isAccessible()) { 
            List<SFDC_Volunteer_Event__c> lstVolEved = [SELECT Account_Name__c,
                                                        Date__c,
                                                        Meeting_City__c ,
                                                        Meeting_State__c,
                                                        OE_Coordinator_Contact__r.Name,OE_Coordinator_Phone__c
                                                        FROM SFDC_Volunteer_Event__c WHERE id IN : lstVolEvTemp1];
            system.debug('==============================' + lstVolEved);
            
            
            for (SFDC_Volunteer_Event__c temp:lstVolEved){
                WrapperopenEnrollment newWrapperEnrollment = new WrapperopenEnrollment();
                newWrapperEnrollment.accountName = temp.Account_Name__c;
                newWrapperEnrollment.meetingDate = temp.Date__c;
                newWrapperEnrollment.meetingCity = temp.Meeting_City__c;
                newWrapperEnrollment.meetingState = temp.Meeting_State__c;
                newWrapperEnrollment.oeCoordinatorName = temp.OE_Coordinator_Contact__r.Name;
                newWrapperEnrollment.oeCoordinatorPhoneNumber = temp.OE_Coordinator_Phone__c;
                wrapperEnrollmentList.add(newWrapperEnrollment);
            }
        }
        return JSON.serialize(wrapperEnrollmentList);
    }
    
         private static List<Id> getVolunteerEvent(boolean isFilteredContent){
        List<id> lstVolEvTemp1 = new List<id>();
        if(!Schema.sObjectType.SFDC_Volunteer_Participant__c.fields.id.isAccessible()||Schema.sObjectType.SFDC_Volunteer_Participant__c.fields.id.isAccessible()) { 
            if(isFilteredContent == false){
              for(SFDC_Volunteer_Participant__c objVP : [   SELECT Volunteer_Event__c
                                                       FROM SFDC_Volunteer_Participant__c
                                                       WHERE  OE_Ambassador_Volunteer__r.Email = :UserInfo.getUserEmail()]) {
                                                           lstVolEvTemp1.add(objVP.Volunteer_Event__c);
                                                       }  
            }else{
                for(SFDC_Volunteer_Participant__c objVP : [   SELECT Volunteer_Event__c
                                                       FROM SFDC_Volunteer_Participant__c
                                                       WHERE  OE_Ambassador_Volunteer__r.Email = :UserInfo.getUserEmail()
                                                       AND Selected_For_Facilitator__c = true]) {
                                                           lstVolEvTemp1.add(objVP.Volunteer_Event__c);
                                                       }
            }
           
        }
        return lstVolEvTemp1;
    }
    
    
    /**
    * @description WrapperopenEnrollment class
    */
    public class WrapperopenEnrollment {
        String accountName{get;set;}
        String meetingCity{get;set;}
        String meetingState{get;set;}
        String oeCoordinatorName{get;set;}
        String oeCoordinatorPhoneNumber{get;set;}
        String sessionStartTime{get;set;}
        String sessionEndTime{get;set;}
        String meetingStreet{get;set;}
        String amPhone{get;set;}
        String sarAccMgt{get;set;}
        String sarPhone{get;set;}
        String accountManger{get;set;}
        String clientEngagementConsultantSAR{get;set;} 
        String clientEngagementConsultantSARPhone{get;set;}
        Date meetingDate{get;set;}
    }
    
}